/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2022-11-10 01:41:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.intl.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ragic.s3.nui.RagicBundle;

public final class discountTable_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ragic.s3.nui.RagicBundle");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


    RagicBundle bundle = (RagicBundle) session.getAttribute("RAGIC_BUNDLE");

      out.write("<style>\r\n    #volumeDiscountTable {\r\n        border-collapse:separate;\r\n        text-align: center;\r\n        white-space: nowrap;\r\n        --themeColor: #F27079;\r\n    }\r\n    #volumeDiscountTable tr:nth-child(odd) {\r\n        color: #F70E0E;;\r\n    }\r\n    #volumeDiscountTable th {\r\n        padding: 0.1rem 1rem;\r\n        border: 1px solid #F27079; /* IE */\r\n        border: 1px solid var(--themeColor);\r\n        background-color: #F27079; /* IE */\r\n        background-color: var(--themeColor);\r\n        color: #fff;\r\n        font-size: 1rem;\r\n    }\r\n\r\n    #volumeDiscountTable td {\r\n        border: 1px solid #F27079; /* IE */\r\n        border: 1px solid var(--themeColor);\r\n        font-size: 0.9rem;\r\n    }\r\n</style>\r\n<table id=\"volumeDiscountTable\">\r\n    <tr>\r\n        <th>");
      out.print(bundle.getString("volumeDiscountTable_header1"));
      out.write("</th>\r\n        <th>");
      out.print(bundle.getString("volumeDiscountTable_header2"));
      out.write("</th>\r\n    </tr>\r\n    <tr>\r\n        <td>20-49</td>\r\n        <td>15%</td>\r\n    </tr>\r\n    <tr>\r\n        <td>50-99</td>\r\n        <td>25%</td>\r\n    </tr>\r\n    <tr>\r\n        <td>100-199</td>\r\n        <td>35%</td>\r\n    </tr>\r\n    <tr>\r\n        <td>200-300</td>\r\n        <td>40%</td>\r\n    </tr>\r\n    <tr>\r\n        <td>300-500</td>\r\n        <td>45%</td>\r\n    </tr>\r\n    <tr>\r\n        <td>500+</td>\r\n        <td>50%</td>\r\n    </tr>\r\n</table>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
