/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2022-11-10 01:41:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sims.report.templates.ragic.reservation;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ragic.s3.nui.RagicBundle;
import com.ragic.s3.nui.helper.Encoder;
import com.ragic.s3.service.api.APIEntry;
import com.ragic.s3.service.api.APIQuery;
import com.ragic.s3.nui.User;
import com.ragic.s3.service.workflow.ScriptResponse;
import com.ragic.s3.service.api.APIResultsFull;
import org.json.JSONArray;
import com.ragic.s3.nui.report.ReservationWhoType;
import org.json.JSONObject;
import org.json.JSONException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.time.Instant;
import com.ragic.s3.nui.Account;

public final class updateReserveStatus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


    private boolean detectTimeOverLap(DateTimeFormatter df, String startTime1, String endTime1, String startTime2, String endTime2) {
        LocalDateTime start1 = LocalDateTime.parse(startTime1, df);
        LocalDateTime end1 = LocalDateTime.parse(endTime1, df);
        LocalDateTime start2 = LocalDateTime.parse(startTime2, df);
        LocalDateTime end2 = LocalDateTime.parse(endTime2, df);

        return !(start1.isBefore(start2) && (end1.isEqual(start2) || end1.isBefore(start2)) ||
                start2.isBefore(start1) && (end2.isEqual(start1) || end2.isBefore(start1)));
    }

    public boolean isPastDate(Date date, long timezoneOffset) {
        return date.getTime()-timezoneOffset < Instant.now().toEpochMilli();
    }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.time.LocalDateTime");
    _jspx_imports_classes.add("com.ragic.s3.nui.User");
    _jspx_imports_classes.add("com.ragic.s3.service.api.APIEntry");
    _jspx_imports_classes.add("com.ragic.s3.service.api.APIResultsFull");
    _jspx_imports_classes.add("java.time.Instant");
    _jspx_imports_classes.add("com.ragic.s3.service.workflow.ScriptResponse");
    _jspx_imports_classes.add("com.ragic.s3.nui.report.ReservationWhoType");
    _jspx_imports_classes.add("com.ragic.s3.nui.Account");
    _jspx_imports_classes.add("com.ragic.s3.service.api.APIQuery");
    _jspx_imports_classes.add("org.json.JSONException");
    _jspx_imports_classes.add("org.json.JSONObject");
    _jspx_imports_classes.add("com.ragic.s3.nui.RagicBundle");
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.Encoder");
    _jspx_imports_classes.add("org.json.JSONArray");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


    Map<String, String[]> reserveData = request.getParameterMap();

    RagicBundle bundle = (RagicBundle) session.getAttribute("RAGIC_BUNDLE");
    ReservationWhoType whoType = (ReservationWhoType)session.getAttribute("whoType");

    User user = (User) session.getAttribute("USER");
    JSONObject msg = new JSONObject();

    //guest user should not use USER whoType, they should use ReservationWhoType.EMAIL_TEXT or ReservationWhoType.TEXT
    if(whoType == ReservationWhoType.USER && !user.isValid()) {
        msg.put("success", false);
        msg.put("msg", bundle.getString("reserve_guest_user_warning"));
        out.print(msg.toString());
        return ;
    }

    String apname = request.getParameter("apname");
    String path = request.getParameter("path");
    String sheetIndex = request.getParameter("sheetIndex");
    int nodeId = Encoder.parseInt(request.getParameter("nodeId"), -1);
    Account account = Account.getInstance(apname);
    long timezoneOffset = account.getTimeZoneOffset();
    APIQuery aq = new APIQuery(apname,path,sheetIndex);
    aq.setUpdateMode();
    aq.setIfNoSubtable(true); //不要抓子表格資料

    ScriptResponse sr = null;
    APIEntry ae = null;
    String errorMsg = "";

    //insert entry
    if(nodeId < 0) {
        String startDateTime = null, endDateTime = null,
                newStartDateTime = null, newEndDateTime = null,
                taget = null;
        String key, value;
        int startDateTimeDomain = -1, endDateTimeDomain = -1, targetDomain = -1;
        boolean hasConflictTime = false;

        for(Map.Entry<String, String[]> entry : reserveData.entrySet()) {
            key = entry.getKey();
            value = entry.getValue()[0];
            if (key.endsWith("_startTime")) {
                startDateTimeDomain = Encoder.parseInt(key.split("_")[0], -1);
                newStartDateTime = value;
            }
            else if (key.endsWith("_endTime")) {
                endDateTimeDomain = Encoder.parseInt(key.split("_")[0], -1);
                newEndDateTime = value;
            }
            else if (key.endsWith("_target")) {
                targetDomain = Encoder.parseInt(key.split("_")[0], -1);
                taget = value;
            }
        }

        int[] fetchDomains = {startDateTimeDomain, endDateTimeDomain, targetDomain};
        for(int domainId : fetchDomains){
            aq.addFetchDomains(domainId);
        }

        if (newStartDateTime != null && newEndDateTime != null && taget != null) {
            APIResultsFull ar = aq.getAPIResultsFull();
            DateTimeFormatter df = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");

            for (APIEntry e : ar) {
                if (e.getFieldValue(targetDomain).equals(taget)) {
                    startDateTime = e.getFieldValue(startDateTimeDomain);
                    endDateTime = e.getFieldValue(endDateTimeDomain);

                    try {
                        if (!isPastDate(new Date(startDateTime), timezoneOffset) && detectTimeOverLap(df, startDateTime, endDateTime, newStartDateTime, newEndDateTime)) {
                            hasConflictTime = true;
                            break;
                        }
                    }
                    catch (Exception ex) {}
                }
            }
        }

        // 已經有資料存在該時段，無法新增!
        if (hasConflictTime) {
            errorMsg = bundle.getString("reserve_new_conflict_time_error");
        }
        else {
            ae = aq.insertAPIEntry();

            for (Map.Entry<String, String[]> entry : reserveData.entrySet()) {
                int domainId = Encoder.parseInt(entry.getKey().split("_")[0], -1);
                if(domainId >= 0) {
                    ae.setFieldValue(domainId, entry.getValue()[0]);
                }
            }
        }
    }
    //update entry
    else {
        ae = aq.getAPIEntry(nodeId);
        // 該資料已經不存在，無法更新!
        if (ae == null) {
            errorMsg = bundle.getString("reserve_deleted_data_error");
        }
        else {
            for(Map.Entry<String, String[]> entry : reserveData.entrySet()){
                int domainId = Encoder.parseInt(entry.getKey().split("_")[0], -1);
                if(domainId >= 0) {
                    ae.setFieldValue(domainId, entry.getValue()[0]);
                }
            }
        }
    }


    //see http://wiki.ragic.com/doku.php/%E5%BE%8C%E7%AB%AF%E8%A7%B8%E7%99%BC%E9%A0%90%E8%A8%AD%E5%80%BC_%E5%85%AC%E5%BC%8F_%E9%80%A3%E7%B5%90%E8%88%87%E8%BC%89%E5%85%A5%E7%9A%84%E9%A0%86%E5%BA%8F
    if(ae != null) {
        ae.markUserAssigned();  //預設值公式欄位如果有給定值，不該重算
        ae.loadAllDefaultValues(user, bundle);
        ae.loadAllListenFields();
        ae.recalculateAllFormulas();
        ae.setExecuteWorkflow(true);
        sr = ae.save(user, bundle);
    }

    try {
        if (sr != null) {
            if (sr.ifExec()) {//儲存成功
                msg.put("success", true);
                msg.put("msg", nodeId >= 0 ? bundle.getString("reserve_update") : bundle.getString("reserve_new"));
            }
            else {//儲存失敗
                msg.put("success", false);
                msg.put("msg",bundle.getString("reserve_new_update_error") );
            }
        }
        else {
            msg.put("success", false);
            msg.put("msg",bundle.getString("reserve_new_update_error") + (!errorMsg.isEmpty() ? errorMsg : ""));
        }

        out.print(msg.toString());
    }
    catch (JSONException e) {
        e.printStackTrace();
    }

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
