/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2022-11-10 01:41:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.api.http;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ragic.s3.nui.*;
import com.ragic.s3.nui.helper.Encoder;
import com.ragic.s3.nui.rules.FormRules;
import com.ragic.s3.nui.rules.formagent.HideCellAgent;
import com.ragic.s3.nui.rules.formagent.StyleCellAgent;
import com.ragic.s3.service.api.APIEntry;
import com.ragic.s3.service.api.APIQuery;
import com.ragic.s3.service.workflow.ScriptResponse;
import org.json.JSONException;
import org.json.JSONObject;
import java.util.*;
import java.util.*;
import com.ragic.s3.nui.helper.ExceptionManager;
import java.util.stream.Collectors;
import com.ragic.s3.nui.rules.formagent.ActionButtonAgent;
import com.ragic.s3.nui.rules.formagent.ReadonlyCellAgent;
import com.ragic.s3.util.Log;
import java.io.Writer;
import org.opensaml.xmlsec.signature.J;
import com.ragic.s3.nui.helper.Util;

public final class mobilejson_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


private void outputError(JspWriter out, HttpServletResponse response, int statusCode, String message) {
    _outputError(out, response, statusCode, statusCode, message);
}
private void outputError(JspWriter out, HttpServletResponse response, int statusCode, int code, String message) {
    _outputError(out, response, statusCode, code, message);
}
private void _outputError(JspWriter out, HttpServletResponse response, int statusCode, int code, String message) {
    JSONObject err = new JSONObject();
    response.setStatus(statusCode);
    try {
        err.put("status", ScriptResponse.ERROR);
        err.put("msg", message);
        err.put("code", code);
        out.print(err.toString(2));
    }
    catch (Exception e) {
        e.printStackTrace();
    }
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.ragic.s3.nui");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ragic.s3.nui.rules.formagent.HideCellAgent");
    _jspx_imports_classes.add("com.ragic.s3.service.api.APIEntry");
    _jspx_imports_classes.add("com.ragic.s3.service.workflow.ScriptResponse");
    _jspx_imports_classes.add("java.util.stream.Collectors");
    _jspx_imports_classes.add("com.ragic.s3.util.Log");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.ExceptionManager");
    _jspx_imports_classes.add("com.ragic.s3.nui.rules.FormRules");
    _jspx_imports_classes.add("com.ragic.s3.nui.rules.formagent.ReadonlyCellAgent");
    _jspx_imports_classes.add("com.ragic.s3.service.api.APIQuery");
    _jspx_imports_classes.add("org.json.JSONException");
    _jspx_imports_classes.add("org.json.JSONObject");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.Util");
    _jspx_imports_classes.add("java.io.Writer");
    _jspx_imports_classes.add("org.opensaml.xmlsec.signature.J");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.Encoder");
    _jspx_imports_classes.add("com.ragic.s3.nui.rules.formagent.StyleCellAgent");
    _jspx_imports_classes.add("com.ragic.s3.nui.rules.formagent.ActionButtonAgent");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("application/json; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


    //System.out.println("qs: " + request.getQueryString());
    RequestParam rp = (RequestParam) request.getAttribute("REQ");
    RagicBundle bundle=(RagicBundle) session.getAttribute("RAGIC_BUNDLE");
    final Log logger = new Log().setIfDisplayLevel(true).setIfDisplayTime(true).setLevel(Log.ERROR); //debug 時請改成 Log.DEBUG
    String apname = rp.getApname();
    String path = rp.getPath();
    int sheetIndex = rp.getSheetIndex();
    User user;
    try {
      user = (User) session.getAttribute("USER");
    } catch (IllegalStateException e) {
      outputError(out, response, HttpServletResponse.SC_BAD_REQUEST, 301, "session timeout.");
      return;
    }

    String mobilejson = request.getParameter("mobilejson");
    boolean v2 = request.getParameter("v2") != null;
    boolean nodeIdAndValue = request.getParameter("nodeIdAndValue") != null;  //[Fix issue #12955]
    String rmlc = request.getParameter("rmlc");
    // nodeIdAndValue 是 app 新的處理預設值、預設值公式的行為，用來判斷 nodeId < 0 時要載入預設值、預設值公式
    if (mobilejson == null) return;
    JSONObject jo = new JSONObject();
    if (!mobilejson.trim().isEmpty()) {
        try {
            jo = new JSONObject(mobilejson);
        } catch (JSONException e) {
            ExceptionManager.getInstance().processException(e);
            return;
        }
    }

    APIQuery aq = new APIQuery(apname, path, sheetIndex);
    NUIForm form = aq.getForm();
    if(form==null){
      outputError(out, response, HttpServletResponse.SC_NOT_FOUND, "NUIForm not found.");
      return;
    }
    if (rp.getNodeId() >= 0 && Util.isRmlcExpiredOrInvalid(rmlc, form)) {
        outputError(out, response, HttpServletResponse.SC_NOT_FOUND, "Rmlc is expired or invalid.");
        return;
    }
    aq.setUpdateMode();
    aq.setIfNodeIdAndValue(nodeIdAndValue);
    aq.setRmlc(rmlc);

    if (rmlc != null && rp.getNodeId() >= 0) {
        APIEntry tempEntry = aq.getAPIEntry(rp.getNodeId());
        /*
        * 即使上方 rmlc 驗證是未過期而且合法的 (isRmlcExpiredOrInvalid)，也有可能 ENTRY_MAGIC_LINK_TOKEN 根本沒有存過這個 rmlc 字串，所以獲得的 tempEntry 為 null
        * (rmlc 字串必須是真實從「分享這筆資料」產生的，不能隨意竄改來延長時限)
        * */
        if (tempEntry == null) {
            outputError(out, response, HttpServletResponse.SC_FORBIDDEN, "Rmlc is expired or invalid.");
            return;
        }
    }

    APIEntry e = aq.insertAPIEntry();
    e.setV2(v2);
    e.setIfNodeIdAndValue(nodeIdAndValue);
    e.setJSON(jo);
    e.setMobilejson(true);

    FormulaExecInfoProvider provider = new FormulaExecInfoProvider(form);
    e.setFormulaExecInfoProvider(provider);
    if (request.getParameter("dv") != null) {
        e.loadExchangeRates();
        e.loadAllDefaultValues(user,bundle);
    }
    // Last modified default values
    if (request.getParameter("dvl") != null) {
        e.loadExchangeRates();
        e.loadAllLastModifiedDefaultValues(user,bundle);
    }
    // All default values in subtable fields
    if (request.getParameter("dvst") != null) {
        e.loadExchangeRates();
        e.loadAllSubtableDefaultValues(user,bundle);
    }

    //load auto gen guess [BugId:04943]
    for (CellInfo info:form.getAllFields(false)) {
        if(info.getAttribute("ag")!=null){
            form.setBundle(bundle); //for guess date format to use the session bundle
            String guessAG=form.guessNextAG(Encoder.unformatNUIAttr(info.getAttribute("ag")),info.getDomainId());
            String existingValue=e.getFieldValue(info.getDomainId());//check existing value [BugId:06325]
            if (guessAG != null && !guessAG.isEmpty() && (existingValue==null || existingValue.isEmpty())){
                e.setFieldValue(info.getDomainId(),guessAG);
            }
        }
    }

    Map<CellLocation, CellInfo> loadFields = form.getLocFieldsByAttribute("l", null);
    loadFields.putAll(form.getLocFieldsByAttribute("ln", null));

    Map<String, Integer> formulaCellNameDomainIds = provider.getOrderCellNameDomainIds(e.getRootNodeId() >= 0);
    Map<String, Integer> formula_DVFCellNameDomainIds = provider.getOrderCellNameDomainIds();


    String[] fidStrings = request.getParameterValues("flocid");  //x,y_domainId  or  x,y_subtableDomainId_subtableRootNodeId
    boolean useflocid = fidStrings != null;
    if(!useflocid) fidStrings = request.getParameterValues("fid");  //domainId  or  subtableDomainId_subtableRootNodeId
    int linkedRootNodeId = Encoder.parseInt(request.getParameter("linkedRootNodeId"), -1); //link field's source data's root node id

    /*
        [Bug issue #14524]
        lf: recalculate all the empty single cell's formula when edit this form first.
        lstf: recalculate all the empty subtable cell's formula when edit this subtable first.

        Maybe we could merge them into one to recalculate all the empty cell's formula when edit the form in some day.
     */
    if (request.getParameter("lf") != null || request.getParameter("lstf") != null) {
        Map<String, Set<Integer>> lfRecalculatedDomainIds = e.recalculateFormulasWhenLoad(request.getParameter("lf") != null, request.getParameter("lstf") != null);
        Set<Integer> recalculatedDomainIds = lfRecalculatedDomainIds.get("recalculatedDomainIds");
        Set<Integer> recalculatedSubtableRootNodeIds = lfRecalculatedDomainIds.get("recalculatedSubtableRootNodeIds");
        loadFields.entrySet().stream()
                .filter(entry -> recalculatedDomainIds.contains(Encoder.parseInt(entry.getValue().getListenTo())))
                .forEach(entry -> e.loadListenField(entry.getKey(), true, -1, recalculatedSubtableRootNodeIds));
    }

    if (fidStrings == null) {
        if (request.getParameter("lf") == null && request.getParameter("lstf") == null) {
            e.recalculateAllFormulas();
            e.setDoNotMapTempNodeId(true);

            loadFields.entrySet().stream()
                .filter(entry -> formulaCellNameDomainIds.containsValue(Encoder.parseInt(entry.getValue().getListenTo())))
                .forEach(entry -> e.loadListenField(entry.getKey(), true));
        }
    }
    else {
        List<String> fidList = new ArrayList<>();
        Collections.addAll(fidList, fidStrings);
        String fidString;
        int fid;
        logger.debug("fidList: " + fidList);

        //這裡不能改成 forEach loop，不然下方的 fidList.add(loadField.getDomainId()+""); 會發生 ConcurrentModificationException
        for (int fidIndex = 0; fidIndex < fidList.size(); fidIndex++) {
            fidString = fidList.get(fidIndex);
            logger.debug(String.format("============ fidString: %s ============", fidString));

            fid = Encoder.parseInt(fidString);
            boolean ifSubtable = false;
            int subtableNodeId = -1;
            int locX = -1, locY = -1;
            if (fid<=0) {
                if(fidString.contains("_")) {
                    String[] fidStrParts = fidString.split("_");
                    if(useflocid) {
                        String[] locParts = fidStrParts[0].split(",");
                        locX = Encoder.parseInt(locParts[0]);
                        locY = Encoder.parseInt(locParts[1]);
                        fid = Encoder.parseInt(fidStrParts[1]);
                        if(fidStrParts.length > 2){  //subtable
                            if(fid > 0) {
                                ifSubtable = true;
                                subtableNodeId = Encoder.parseInt(fidStrParts[2], -1);
                            } else {
                                continue;
                            }
                        }
                    }
                    else {
                        fid = Encoder.parseInt(fidStrParts[0]);
                        if(fid > 0) {
                            ifSubtable = true;
                            subtableNodeId = Encoder.parseInt(fidStrParts[1], -1);
                        } else {
                            continue;
                        }
                    }
                }
            }

            Queue<String> cellNames = new LinkedList<>();  //changed cellNames which would trigger other formula fields refer to them to recalculate
            CellLocation floc;
            if(useflocid) floc = new CellLocation(locX, locY);
            else floc = form.getCellLocation(fid);

             //If focus on link field, we do link & load
            for (Map.Entry<CellLocation,CellInfo> entry : loadFields.entrySet()) {
                CellLocation loadLoc = entry.getKey();
                CellInfo loadField = entry.getValue();
                int listenToId = Encoder.parseInt(loadField.getListenTo());
                if (listenToId == fid) {
                    e.setDoNotMapTempNodeId(true);
                    Set<Integer> subtableRootNodeIds = new HashSet<>();
                    int loadId = loadField.getDomainId();
                    logger.debug(String.format("Found fid 【%d】 listened by loadId 【%d】", fid, loadId));

                    if(ifSubtable) {
                        subtableRootNodeIds.add(subtableNodeId);
                    }
                    // we need `linkedRootNodeId` to classify "load the empty link field's load fields values" and "clear link field to clear the load fields values"
                    // if linkedRootNodeId > -1, means we load the empty link field's load fields values. linkedRootNodeId is the mvp root node id.
                    if(linkedRootNodeId > -1) {
                        e.loadListenField(loadLoc, true, linkedRootNodeId, subtableRootNodeIds);
                        logger.debug(String.format("Use linkedRootNodeId 【%d】 to do loadListenField", linkedRootNodeId));
                    }
                    else {
                        boolean isListenToFieldInSubtable = !form.isSingleCell(floc);
                        CellLocation firstCellLoc = form.getFirstTableCell(floc);
                        String listenToFieldValue;

                        //old app version ifSubtable is false even if fid is a subtable domainId because fid is `domainId` , not `domainId_subtableRootNodeId`.
                        if(isListenToFieldInSubtable && ifSubtable) {
                            int subtableRootDomainId = form.getSubtableKey(firstCellLoc);
                            listenToFieldValue = e.getSubtableFieldValueByRootNodeId(subtableRootDomainId, subtableNodeId,
                                    String.valueOf(listenToId), v2 ? firstCellLoc : null);
                        }
                        else {
                            listenToFieldValue = e.getFieldValue(listenToId);
                        }
                        logger.debug("listenToFieldValue: " + listenToFieldValue);

                        //link field is empty, need to clear the load field
                        if (listenToFieldValue != null && listenToFieldValue.isEmpty()) {
                            logger.debug("clearing the load field...");

                            boolean isLoadFieldInSubtable = !form.isSingleCell(loadLoc);

                            if (isListenToFieldInSubtable) {
                                //link field and load field are both subtable fields
                                if (isLoadFieldInSubtable) {
                                    logger.debug("ifSubtable: " + ifSubtable);
                                    if (ifSubtable) {
                                        e.setSubtableFieldValue(loadId, subtableNodeId, "", false, v2 ? firstCellLoc : null);
                                    }
                                    //fallback for old app version whose fid is `domainId` , not `domainId_subtableRootNodeId`.
                                    //subtableRootNodeIds is empty
                                    else {
                                        e.loadListenField(loadLoc, true);
                                    }
                                }
                            }
                            //link field and load field are both normal fields
                            else if (!isLoadFieldInSubtable) {
                                e.setFieldValue(loadId, "");
                            }
                        }
                        else {
                            logger.debug(String.format("do loadListenField ( linkId: 【%d】 / loadId: 【%d】)", listenToId, loadId));

                            //We load all subtable values but only take the subtable value we choose on app.
                            //For now, if we remove link field, it could not clear the load value like web.
                            //Because we don't know the subtable rootNodeId
                            //We could not do that in loadListenField because #08197
                            //so we should clear the load value by setFieldValue() and setSubtableFieldValue()
                            e.loadListenField(loadLoc, true, -1, subtableRootNodeIds);
                        }
                    }
                    //[BugId:07410] 2 levels link and load
                    // 如果這個載入欄位也是個連結欄位，那也要跟著載入他的載入欄位
                    List<ListenerAction> listeners=form.getListenerActions(loadId);
                    if (listeners != null) {
                        for (ListenerAction action:listeners){
                            int listenDomain = action.getListenerDomainId();
                            logger.debug(String.format("2 levels listener domainId: 【%d】", listenDomain));
                            // [Bug issue #14866] 準備 fid 格式給這個 listenDomain 來加入 fidList，為了讓後面階層的 load 欄位也能因為關聯的 link 欄位是空值而被清除
                            StringJoiner newFidStr = new StringJoiner("_");
                            if (useflocid) newFidStr.add(floc.toString());
                            newFidStr.add(String.valueOf(listenDomain));
                            if (subtableNodeId != -1) newFidStr.add(String.valueOf(subtableNodeId));

                            if(!fidList.contains(newFidStr.toString())) fidList.add(newFidStr.toString());
                            e.loadListenField(listenDomain,true);
                        }
                    }

                    cellNames.add(loadLoc.getCellName(form.getCellLocOffsetX(loadLoc)));
                }
            }
            // [Bug issue #14866]:
            linkedRootNodeId = -1;  //只用做第一層 link & load 就好，第二層之後都不用

            Map<String, Integer> involvedCellNameDomainIds = new HashMap<>();
            if (floc != null) {
                String fCellName = floc.getCellName(form.getCellLocOffsetX(floc));
                cellNames.add(fCellName);
                involvedCellNameDomainIds.put(fCellName, fid);
            }

            List<Integer> subtableFieldIds = new ArrayList<>();
            Integer subtableParentAlias = -1;
            int subtableKey = -1, subtableIndex = -1;
            CellLocation firstCellLoc = form.getFirstTableCell(floc);
            Set<Integer> recalculateSubtableIndexs = new HashSet<>();


            if(subtableNodeId > -1) {
                subtableKey = form.getSubtableKey(firstCellLoc);
                subtableParentAlias = form.getSubtableParentAlias(floc);
                if(subtableParentAlias == null) subtableParentAlias = -1;
                subtableFieldIds = form.getSubtableFields(subtableKey, subtableParentAlias).stream()
                                                                                            .map(CellInfo::getDomainId)
                                                                                            .collect(Collectors.toList());
                int subtableSize = e.getSubtableSize(subtableKey, firstCellLoc);
                for(int i = 0; i < subtableSize ;i++) {
                    if (Encoder.parseInt(e.getSubtableRootNodeId(subtableKey, i, firstCellLoc)) == subtableNodeId) {
                        subtableIndex = i;
                        recalculateSubtableIndexs.add(subtableIndex);
                        break;
                    }
                }
            }
            logger.debug("cellNames: " + cellNames);

            Set<String> added=new HashSet<>();
            Map<CellLocation, Integer> subtableKeys = form.getSubtableKey();
            Map<String, Set<Integer>> toRecalculateDVFSubtableIndexs = new HashMap<>(); //cellName : recaculateSubtableIndexs

            //Preparing all the formula fields which should be recalculated
            while (!cellNames.isEmpty()) {
                String cellName = cellNames.remove();
                if(cellName==null) continue;
                boolean dvfRecalAllSubtableNewEntries;

                for (Map.Entry<String, Integer> cellNameDomainId: formula_DVFCellNameDomainIds.entrySet()) {
                    String formulaCellName = cellNameDomainId.getKey();
                    int formulaDomainId = cellNameDomainId.getValue();
                    CellInfo formulaField = form.getField(formulaDomainId, formulaCellName);
                    String formula = formulaField.getFormula();
                    CellLocation formualLoc = form.getCellLocation(formulaCellName);
                    dvfRecalAllSubtableNewEntries = false;

                    if(formualLoc != null) {
                        if(!form.isSingleCell(formualLoc)) {  //subtable dv_f field
                            if (formulaField.getAttribute("dv_f") != null) {
                                formula = formulaField.getAttribute("dv_f");
                                dvfRecalAllSubtableNewEntries = !nodeIdAndValue;
                            }
                        }
                        else if(formulaField.getAttribute("dv_f") != null &&
                            (nodeIdAndValue && e.shouldLoadDefaultValueAndDVFormula(formulaDomainId) || !nodeIdAndValue && e.getRootNodeId() < 0)) {
                            formula = formulaField.getAttribute("dv_f");
                        }

                        if (formula!=null && Encoder.getFormulaRelatedCells(formula).contains(cellName)) {
                            if(involvedCellNameDomainIds.containsValue(formulaDomainId) && cellNames.contains(formulaCellName)) continue;
                            involvedCellNameDomainIds.put(formulaCellName, formulaDomainId);

                            // collect subtable index to recalulate dv_f subtable fields when subtable root node id < 0
                            if (dvfRecalAllSubtableNewEntries) {
                                 CellLocation firstFormulaCellLoc = form.getFirstTableCell(formualLoc);
                                int subtableRootDomain = subtableKeys.get(firstFormulaCellLoc);
                                int subtableSize = e.getSubtableSize(subtableRootDomain, firstFormulaCellLoc);

                                for(int i = 0; i < subtableSize ;i++) {
                                    if(Encoder.parseInt(e.getSubtableRootNodeId(subtableRootDomain, i, firstFormulaCellLoc)) < 0) {
                                        if(!toRecalculateDVFSubtableIndexs.containsKey(formulaCellName)) {
                                            toRecalculateDVFSubtableIndexs.put(formulaCellName, new HashSet<>());
                                        }
                                        Set<Integer> indexs = toRecalculateDVFSubtableIndexs.get(formulaCellName);
                                        indexs.add(i);
                                    }
                                }
                            }

                            if(!added.contains(formulaCellName)){
                                cellNames.add(formulaCellName);
                                added.add(formulaCellName);
                            }
                        }
                    }
                }
            }

            Map<String, Integer> orderCellNameDomainIds = new LinkedHashMap<>();
            HashMap<String, Set<String>> children = new HashMap<>();
            HashMap<String, Integer> referenceCount = new HashMap<>();
            HashMap<String, Boolean> visited = new HashMap<>();


            for (String cellName : involvedCellNameDomainIds.keySet()) {
                CellInfo info = form.getFieldByCellName(cellName);
                String formula = info.getFormula();
                boolean useDVF = e.getRootNodeId() < 0 && info.getAttribute("dv_f") != null &&
                        info.getAttribute("dv_f").length() > 0;
                if (useDVF) {
                    formula = info.getAttribute("dv_f");
                }
                Set<String> relatedCellNames = Encoder.getFormulaRelatedCells(formula);

                children.put(cellName, relatedCellNames);
                referenceCount.put(cellName, 0);
                visited.put(cellName, false);
            }
            for (Map.Entry<String, Integer> referenceEntry : referenceCount.entrySet()) {
                String cellName = referenceEntry.getKey();
                int count = referenceEntry.getValue();
                Set<String> relatedCellNames = children.get(cellName);

                for (String relatedCellName : relatedCellNames) {
                    // if its child is a formula cell
                    if (children.get(relatedCellName) != null) {
                        count++;
                    }
                }

                referenceCount.put(cellName, count);
            }

            //Ordering the formula fields which should be recalculated
            for (int index = 0, domainSize = involvedCellNameDomainIds.size(); index < domainSize; index++) {
                for (String cellName : children.keySet()) {
                    // if a not-visited cell has no reference to formula cells
                    if (!visited.get(cellName) && referenceCount.get(cellName) == 0) {
                        orderCellNameDomainIds.put(cellName, involvedCellNameDomainIds.get(cellName));

                        for (Map.Entry<String, Set<String>> childEntry : children.entrySet()) {
                            String parentCell = childEntry.getKey();
                            Set<String> relatedCellNames = childEntry.getValue();

                            // if cell is a child of the other formula cell
                            if (relatedCellNames.contains(cellName)) {
                                referenceCount.put(parentCell, referenceCount.get(parentCell) - 1);
                            }
                        }
                        visited.put(cellName, true);
                        break;
                    }
                }
            }
            logger.debug("To recalculate orderCellNameDomainIds: " + orderCellNameDomainIds);

            //Start recalculating
            for(Map.Entry<String, Integer> orderCellNameDomainId : orderCellNameDomainIds.entrySet()) {
                String orderCellName = orderCellNameDomainId.getKey();
                int orderDomainId = orderCellNameDomainId.getValue();
                if(fid == orderDomainId) {
                    continue;
                }
                //subtable f or dv_f domainds when subtableNodeId > 0
                if(subtableFieldIds.contains(orderDomainId)) {
                    if(subtableIndex > -1) e.recalculateSubtableFormula(orderDomainId, recalculateSubtableIndexs, orderCellName);
                }
                else if(toRecalculateDVFSubtableIndexs.containsKey(orderCellName)) {
                    e.recalculateSubtableFormula(orderDomainId, toRecalculateDVFSubtableIndexs.get(orderCellName), orderCellName);
                }
                else {
                    e.recalculateFormula(orderDomainId, orderCellName);
                }

                //because we have recalculated the link field, we should trigger link & load
                loadFields.entrySet().stream()
                    .filter(entry -> orderDomainId == Encoder.parseInt(entry.getValue().getListenTo()))
                    .forEach(entry -> {
                        CellLocation loadLoc = entry.getKey();
                        CellInfo loadField = entry.getValue();
                        String toBeFid = String.valueOf(loadField.getDomainId());
                        if(!fidList.contains(toBeFid)) fidList.add(toBeFid);
                        e.loadListenField(loadLoc, true);
                    });
            }
            e.setDoNotMapTempNodeId(true);
        }
    }

    // Form Rules
    if (!form.getInteractiveRules().isEmpty()) {
        FormRules formRules = e.getFormRules();

        JSONObject rulesJSON = new JSONObject();
        jo.put("_formrules", rulesJSON);

        JSONObject ruleResult = new JSONObject();
        ruleResult.put("messages", formRules.getMessages());
        ruleResult.put("style", formRules.getStyleCellAgents().stream().map(StyleCellAgent::generateJSONContent).toArray());
        ruleResult.put("hide", formRules.getHideCellAgents().stream().map(HideCellAgent::generateJSONContent).toArray());
        ruleResult.put("hideDescription", formRules.getHideDescriptions());
          ruleResult.put("actionButton", formRules.getActionButtonAgent().stream().map(ActionButtonAgent::generateJSONContent).toArray());
                        ruleResult.put("readonly", formRules.getReadonlyCellAgents().stream().map(ReadonlyCellAgent::generateJSONContent).toArray());


        String resultName = form.getType() == NUIForm.NUI_FORM ? "form" : "listing";
        rulesJSON.put(resultName, ruleResult);
    }

//    e.recalculateAllFormulas();
//    System.out.println("mobilejson: " + e.getJSON().toString());
    out.print(e.getJSON().toString());

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
