/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2022-11-10 01:41:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.api.http;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ragic.s3.nui.NUIForm;
import com.ragic.s3.nui.RagicBundle;
import com.ragic.s3.nui.RequestParam;
import com.ragic.s3.nui.helper.Encoder;
import com.ragic.s3.service.workflow.ScriptResponse;
import com.ragic.s3.util.License;
import org.json.JSONObject;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.Files;
import java.nio.charset.StandardCharsets;

public final class post_005fhtml_005fresponse_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.json.JSONObject");
    _jspx_imports_classes.add("com.ragic.s3.nui.RagicBundle");
    _jspx_imports_classes.add("java.nio.file.Paths");
    _jspx_imports_classes.add("java.nio.file.Files");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.Encoder");
    _jspx_imports_classes.add("com.ragic.s3.util.License");
    _jspx_imports_classes.add("com.ragic.s3.nui.NUIForm");
    _jspx_imports_classes.add("com.ragic.s3.service.workflow.ScriptResponse");
    _jspx_imports_classes.add("java.nio.file.Path");
    _jspx_imports_classes.add("com.ragic.s3.nui.RequestParam");
    _jspx_imports_classes.add("java.nio.charset.StandardCharsets");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


    RequestParam rp = (RequestParam) request.getAttribute("REQ");
    String ap = rp.getApname();
    String referrer = request.getHeader("Referer");
    String submitOnce = referrer != null && referrer.contains("submitOnce") ? "&submitOnce" : "";
    String hideSlogan = request.getParameter("hideSlogan") != null ? "&hideSlogan" : "";
    String callback = request.getParameter("callback");
    boolean isSaveClose = request.getParameter("saveClose") != null;
    JSONObject resultJo = (JSONObject) request.getAttribute("resultJo");
    RagicBundle bundle = (RagicBundle) session.getAttribute("RAGIC_BUNDLE");
    NUIForm form = (NUIForm) request.getAttribute("NUIFORM");
    String formName = form.getRealname();
    ScriptResponse sr = (ScriptResponse) request.getAttribute("SCRIPT_RESPONSE");
    String submitMessage;
    // issue[12099] 使用 HTMLLineBreak 參數換行。
    submitMessage = form.getWFMessageType() == 0 ? Encoder.encjs(form.getWFMessage(), true) : form.getWFMessage();
    if (submitMessage == null || submitMessage.isEmpty()) submitMessage = bundle.getString("submitThanks");
    //process external user registration pages
    String html = request.getParameter("html");

    //use the workflow message if available
    if (sr.getMessages().size() > 0) submitMessage = sr.getMessage();

    //script not successfully executed, change message
    if (!sr.ifExec()) html = "";

      out.write("<!DOCTYPE html>\r\n<html lang=\"");
      out.print(bundle.getString("lang"));
      out.write("\">\r\n<head>\r\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n    <title>");
      out.print(Encoder.encjs(formName));
      out.write("</title>\r\n    ");
if (License.isDev()) { 
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/sims/webview/mod/webform_rwd.css\"/>\r\n    ");
} else {
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/intl/common/webform_rwd.min.css\"/>\r\n    ");
} 

        Path customCSS = Paths.get("cust/def/app/" + ap + "/custom.css");
        if (Files.exists(customCSS)) {
            String customCSSText = new String(Files.readAllBytes(customCSS), StandardCharsets.UTF_8);
            customCSSText = customCSSText.replaceAll("<[^>]*>", "");
    
      out.write("<style id=\"customCSS\">");
      out.print(customCSSText);
      out.write("</style>\r\n    ");

        }
    
      out.write("</head>\r\n<body>\r\n<div class=\"responseContainer\">\r\n    <p id=\"formTitle\" class=\"messageWrapper\">");
      out.print(submitMessage);
      out.write("</p>\r\n    <div class=\"informationWrapper\">\r\n        ");
if ("".equals(submitOnce)) {
      out.write("<div class=\"linkWrapper flex-center\">\r\n            <a href=\"");
      out.print(referrer);
      out.write('"');
      out.write('>');
      out.print(bundle.getString("submitAnotherEntry"));
      out.write("</a>\r\n        </div>\r\n        ");
}
if ("".equals(hideSlogan)) {
      out.write("<footer class=\"footerWrapper flex-center\">\r\n            <address class=\"powerby\">Powered by<a href=\"https://www.ragic.com\" target=\"_blank\"> Ragic!</a></address>\r\n        </footer>\r\n        ");
}
      out.write("</div>\r\n</div>\r\n\r\n\r\n<script>\r\n    ");
 if(callback != null && resultJo != null) {
      out.print(callback);
      out.write('(');
      out.write('\'');
      out.print(resultJo.toString());
      out.write("');\r\n    ");
 } 
 if(isSaveClose) {
      out.write("\r\n    window.close();\r\n    ");
 } 
      out.write("\r\n\r\n    function postSize(e) {\r\n        var target = parent.postMessage ? parent : (parent.document.postMessage ? parent.document : undefined);\r\n        if (typeof target != \"undefined\" && document.body.scrollHeight && document.getElementById('responseDiv'))\r\n            target.postMessage(document.getElementById('responseDiv').scrollHeight + 100, \"*\");\r\n    }\r\n\r\n    window.addEventListener(\"load\", postSize, false);\r\n    ");
 if(html.length()>7){ 
      out.write("\r\n    window.setTimeout(\"location.href='");
      out.print(html);
      out.write("';\", 3000);\r\n    ");
 } 
      out.write("\r\n    //prevent user refresh page and resend data\r\n    if (window.self === window.top) window.history.replaceState(null, null, \"");
      out.print(referrer);
      out.write("\");\r\n</script>\r\n</body>\r\n</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
