apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ragic-standard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudflared
  name: deployment-cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: cloudflared
  template:
    metadata:
      labels:
        pod: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        command: ["cloudflared", "tunnel", "run"]
        env:
        - name: TUNNEL_TOKEN
          value: $TUNNEL_TOKEN
          
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-ragic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-ragic
  template:
    metadata:
      labels:
        app: pod-ragic
    spec:
      volumes:
      - name: pvc-ragic-vol
        persistentVolumeClaim:
          claimName: pvc-ragic-standard
      containers:
      - name: ragic
        image: modagovtw/ragic:20230420
        ports:
        - containerPort: 80
        - containerPort: 443
        env:
        - name: JAVA_OPTS
          value: "-Xms4g -Xmx4g"
        resources:
          requests:
            cpu: 1000m
            memory: 5Gi
          limits:
            cpu: 1000m
            memory: 5Gi
        readinessProbe:
          httpGet:
            path: /default/home
            port: 80
        volumeMounts:
        - mountPath: /srv/ragic/volumes
          name: pvc-ragic-vol

---
apiVersion: v1
kind: Service
metadata:
  name: service-ragic
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http
  - port: 443
    protocol: TCP
    targetPort: 443
    name: https
  selector:
    app: pod-ragic
