apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ragic-enterprise-multishare-rwx
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: enterprise-multishare-rwx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-ragic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-ragic
  template:
    metadata:
      labels:
        app: pod-ragic
    spec:
      volumes:
      - name: pvc-ragic-vol
        persistentVolumeClaim:
          claimName: pvc-ragic-enterprise-multishare-rwx
      containers:
      - name: ragic
        image: modagovtw/ragic:20230330
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 1250m
            memory: 8Gi
        readinessProbe:
          httpGet:
            path: /default/home
            port: 80
        volumeMounts:
        - mountPath: /srv/ragic/volumes
          name: pvc-ragic-vol

---
apiVersion: v1
kind: Service
metadata:
  name: service-ragic
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: pod-ragic

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-ragic
spec:
  tls:
  - secretName: cert-ragic
  rules:
  - host: $DOMAIN
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-ragic
            port:
              number: 80
