/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2022-11-10 01:41:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.api.internal;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.json.JSONObject;
import com.ragic.s3.nui.helper.Util;
import com.ragic.s3.nui.Account;
import com.ragic.s3.sdb.data.bdb.BDBWorker;
import com.ragic.s3.sdb.query.SDBQuery;
import com.ragic.s3.sdb.query.SDBQueryFull;
import com.ragic.s3.util.DConst;
import com.ragic.s3.sdb.query.SDBNode;
import java.util.Date;
import com.ragic.s3.nui.helper.Encoder;
import com.ragic.s3.nui.helper.RedirectManager;
import com.ragic.s3.nui.helper.URLCaller;
import com.ragic.s3.nui.RagicConfig;

public final class local_005faccountActivity_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("com.ragic.s3.sdb.query.SDBQuery");
    _jspx_imports_classes.add("com.ragic.s3.util.DConst");
    _jspx_imports_classes.add("com.ragic.s3.sdb.data.bdb.BDBWorker");
    _jspx_imports_classes.add("com.ragic.s3.nui.Account");
    _jspx_imports_classes.add("org.json.JSONObject");
    _jspx_imports_classes.add("com.ragic.s3.nui.RagicConfig");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.Util");
    _jspx_imports_classes.add("com.ragic.s3.sdb.query.SDBNode");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.Encoder");
    _jspx_imports_classes.add("com.ragic.s3.sdb.query.SDBQueryFull");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.URLCaller");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.RedirectManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;



    //if(License.isProd() && !com.ragic.s3.nui.helper.Util.ifInternalIp(request.getRemoteAddr())) return;

    String apname=request.getParameter("a");
    if(Util.apnameExistsLocally(apname)) {
        //sheets
        int customSheetCount=Account.getInstance(apname).getActiveSheetCount();
        int totalSheetCount=Account.getInstance(apname).getTotalSheetCount();

        //data
        Date firstDataDate=null,lastDataDate=null;

        BDBWorker worker = new BDBWorker(apname);
        try {
            SDBQuery q = new SDBQueryFull(worker);
            q.go(DConst.HISTORY_TIMESTAMP);
            SDBNode node=q.next();
            if(node!=null){
                String ts=node.getValue();
                firstDataDate=new Date(Long.parseLong(ts));
            }
        } finally {
            worker.commit();
        }

        worker = new BDBWorker(apname);
        try {
            SDBQuery q = new SDBQueryFull(worker);
            q.go(DConst.HISTORY_TIMESTAMP);
            q.setReverse(true);
            SDBNode node=q.next();
            if(node!=null){
                String ts=node.getValue();
                lastDataDate=new Date(Long.parseLong(ts));
            }
        } finally {
            worker.commit();
        }

        JSONObject jo=new JSONObject();
        jo.put("customSheets",customSheetCount);
        jo.put("totalSheets",totalSheetCount);
        jo.put("firstDataDate", Encoder.formatDate(firstDataDate,"yyyy/MM/dd"));
        jo.put("lastDataDate", Encoder.formatDate(lastDataDate,"yyyy/MM/dd"));
        out.println(jo.toString(2));
    }

    else if(RagicConfig.getInstance().ifWWWRagicServer()){
        String server=RedirectManager.getInstance().getServer(apname);
        if(!"www.ragic.com".equals(server)){
            JSONObject jo= URLCaller.get("https://"+server+"/api/internal/local_accountActivity.jsp?a="+apname);
            out.println(jo.toString(2));
        }
    }

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
