/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2022-11-10 01:41:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.api.internal;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ragic.s3.nui.RagicBundle;
import com.ragic.s3.zookeeper.Zookeeper;
import com.ragic.s3.util.Const;
import java.util.*;
import com.ragic.s3.nui.helper.Util;
import com.ragic.s3.nui.helper.UserManager;
import com.ragic.s3.nui.User;
import com.ragic.s3.zookeeper.Schedule;

public final class proxy_005fzookeeper_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ragic.s3.nui.RagicBundle");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.Util");
    _jspx_imports_classes.add("com.ragic.s3.zookeeper.Schedule");
    _jspx_imports_classes.add("com.ragic.s3.nui.User");
    _jspx_imports_classes.add("com.ragic.s3.util.Const");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.UserManager");
    _jspx_imports_classes.add("com.ragic.s3.zookeeper.Zookeeper");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


    User access=(User)session.getAttribute("USER");
    boolean ifRagicSupport=access!=null && UserManager.ifRagicSupport(access.getUserId());
    //boolean internalIP= Util.ifInternalIp(request.getRemoteAddr());
    if(!ifRagicSupport) {
        if(access!=null) out.println("No access for "+access.getUserId());
        else out.println("Not Logged In.");
        return;
    }

    RagicBundle bundle=(RagicBundle)session.getAttribute("RAGIC_BUNDLE");
    List<Schedule> schedules= Zookeeper.getInstance().getSchedules();
    String result="";
    for(Schedule schedule:schedules){
        result += schedule.toString() + "\n";
    }


      out.write("<html>\r\n<head>\r\n<title>Zoo Scheduler</title>\r\n<style>\r\n    button{\r\n        padding:8px 21px;\r\n        margin:0 2px;\r\n        font-size:15px;\r\n    }\r\n    select{\r\n        font-size:15px;\r\n        padding:3px 8px;\r\n    }\r\n</style>\r\n</head>\r\n<body>\r\n\r\n<script type=\"text/javascript\" src=\"/intl/common/sims.js\"></script>\r\n<textarea id=\"currentSchedule\" style=\"width:50%;height:20%;\">");
      out.print(result);
      out.write("</textarea>\r\n\r\n<div style=\"margin:12px 0;\">\r\n");

    GregorianCalendar cal=new GregorianCalendar();
    cal.setTimeZone(TimeZone.getTimeZone("GMT+8"));


    out.println("<select id='year'>");
    for(int i=2021;i<=2031;i++){
        out.println("<option"+(cal.get(Calendar.YEAR)==i?" selected":"")+">"+i+"</option>");
    }
    out.println("</select> /");

    out.println("<select id='month'>");
    for(int i=1;i<=12;i++){
        out.println("<option"+(cal.get(Calendar.MONTH)+1==i?" selected":"")+">"+i+"</option>");
    }
    out.println("</select> /");

    out.println("<select id='day'>");
    for(int i=1;i<=31;i++){
        out.println("<option"+(cal.get(Calendar.DAY_OF_MONTH)==i?" selected":"")+">"+i+"</option>");
    }
    out.println("</select>");

    out.println("<select id='hour' style='margin:0 0 0 50px;'>");
    for(int i=0;i<=23;i++){
        out.println("<option"+(cal.get(Calendar.HOUR_OF_DAY)==i?" selected":"")+">"+i+"</option>");
    }
    out.println("</select> :");

    out.println("<select id='minute'>");
    for(int i=0;i<=59;i++){
        out.println("<option"+(cal.get(Calendar.MINUTE)+3==i?" selected":"")+">"+i+"</option>");
    }
    out.println("</select>");

      out.write("</div>\r\n");


    String[] servers= Const.ZOOKEEPER_SERVER_LIST;

    out.println("<div>Update Restart:<br/>");
    for(String server:servers){
        out.print("<button onclick=\"schedule('"+server+"');\">"+server+"</button>");
    }
    out.println("</div><div style='margin:15px 0;'>Cancel Update Restart:<br/>");
    for(String server:servers){
        out.print("<button onclick=\"schedule('"+server+"',true);\">"+server+"</button>");
    }
    out.println("</div>");


    out.println("<div>Update No Restart:<br/>");
    for(String server:servers){
        out.print("<button onclick=\"scheduleNoRestart('"+server+"');\">"+server+"</button>");
    }
    out.println("</div><div style='margin:15px 0;'>Cancel Update No Restart:<br/>");
    for(String server:servers){
        out.print("<button onclick=\"scheduleNoRestart('"+server+"',true);\">"+server+"</button>");
    }
    out.println("</div>");

      out.write("<script>\r\n    function schedule(server,ifCancel){\r\n        let updateTime=\r\n            $('year').options[$('year').selectedIndex].value+'/'+\r\n            $('month').options[$('month').selectedIndex].value+'/'+\r\n            $('day').options[$('day').selectedIndex].value+' '+\r\n            $('hour').options[$('hour').selectedIndex].value+':'+\r\n            $('minute').options[$('minute').selectedIndex].value;\r\n\r\n        ajaxget('/api/internal/proxy_zookeeper_action.jsp',\r\n            {'server':server,\r\n                'action':ifCancel?'cancel':'update',\r\n                'updateTime':updateTime\r\n            },\r\n            zookeeperCallback);\r\n    }\r\n    function scheduleNoRestart(server,ifCancel){\r\n        let updateTime=\r\n            $('year').options[$('year').selectedIndex].value+'/'+\r\n            $('month').options[$('month').selectedIndex].value+'/'+\r\n            $('day').options[$('day').selectedIndex].value+' '+\r\n            $('hour').options[$('hour').selectedIndex].value+':'+\r\n            $('minute').options[$('minute').selectedIndex].value;\r\n");
      out.write("\r\n        ajaxget('/api/internal/proxy_zookeeper_action.jsp',\r\n            {'server':server,\r\n                'action':ifCancel?'cancelNoRestart':'updateNoRestart',\r\n                'updateTime':updateTime\r\n            },\r\n            zookeeperCallback);\r\n    }\r\n    function zookeeperCallback(txt){\r\n        $('currentSchedule').value=txt;\r\n    }\r\n</script>\r\n\r\n</body>\r\n</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
