/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2022-11-10 01:41:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.partners;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ragic.s3.nui.User;
import com.ragic.s3.nui.helper.UserManager;
import com.ragic.s3.sdb.data.bdb.BDBWorker;
import com.ragic.s3.sdb.query.SDBNode;
import com.ragic.s3.sdb.query.SDBQuery;
import com.ragic.s3.sdb.query.SDBQueryFull;
import com.ragic.s3.util.Const;
import com.ragic.s3.util.DConst;
import com.stripe.Stripe;
import com.ragic.s3.sdb.data.bdb.BDBSmartWorker;
import java.math.BigDecimal;
import java.util.*;
import com.ragic.s3.util.partnertools.PaymentBasket;
import com.ragic.s3.util.partnertools.PaymentBasketSet;
import com.ragic.s3.nui.helper.Encoder;
import org.opensaml.xmlsec.signature.P;
import com.ragic.s3.util.partnertools.PaymentBasketItem;
import com.ragic.s3.util.partnertools.PaymentRecord;
import com.ragic.s3.nui.helper.ExceptionManager;
import java.io.*;
import com.ragic.s3.nui.RagicBundle;

public final class manage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.opensaml.xmlsec.signature.P");
    _jspx_imports_classes.add("com.ragic.s3.sdb.query.SDBQuery");
    _jspx_imports_classes.add("com.ragic.s3.util.partnertools.PaymentRecord");
    _jspx_imports_classes.add("com.ragic.s3.util.DConst");
    _jspx_imports_classes.add("com.ragic.s3.sdb.data.bdb.BDBSmartWorker");
    _jspx_imports_classes.add("com.stripe.Stripe");
    _jspx_imports_classes.add("com.ragic.s3.nui.User");
    _jspx_imports_classes.add("com.ragic.s3.util.Const");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.ExceptionManager");
    _jspx_imports_classes.add("com.ragic.s3.sdb.data.bdb.BDBWorker");
    _jspx_imports_classes.add("java.math.BigDecimal");
    _jspx_imports_classes.add("com.ragic.s3.nui.RagicBundle");
    _jspx_imports_classes.add("com.ragic.s3.sdb.query.SDBNode");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.Encoder");
    _jspx_imports_classes.add("com.ragic.s3.sdb.query.SDBQueryFull");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.UserManager");
    _jspx_imports_classes.add("com.ragic.s3.util.partnertools.PaymentBasketSet");
    _jspx_imports_classes.add("com.ragic.s3.util.partnertools.PaymentBasketItem");
    _jspx_imports_classes.add("com.ragic.s3.util.partnertools.PaymentBasket");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/intl/common/sims.css\"/>\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"/intl/common/fa5/css/fontawesome-all.min.css\" />\r\n<style>\r\n  td{\r\n    text-align: right;\r\n    width:150px;\r\n  }\r\n</style>\r\n\r\n<a href=\"?showPaid\">Show paid</a>\r\n\r\n");


  User user=(User)session.getAttribute("USER");
  if(user==null || (!UserManager.ifRagicSupport(user.getUserId()) && !"alliel@gmail.com".equalsIgnoreCase(user.getUserId()))){
    return;
  }
  //api info
  Stripe.apiKey = Const.STRIPE_KEY;
  Stripe.apiVersion = Const.STRIPE_API;

  RagicBundle bundle=(RagicBundle) session.getAttribute("RAGIC_BUNDLE");

  boolean showPaid=request.getParameter("showPaid")!=null;
  Calendar now = new GregorianCalendar();
  int nowyear = now.get(Calendar.YEAR);
  int nowmonth = now.get(Calendar.MONTH);
  int nowquarter = (nowmonth / 3 + 1);
  int filterYear = Encoder.parseInt(request.getParameter("year"), nowyear);
  int filterQuarter = Encoder.parseInt(request.getParameter("q"), nowquarter - 1);
  if (filterQuarter == 0) {
    filterQuarter = 4;
    filterYear--;
  }


  BDBWorker worker=new BDBWorker(Const.AP_RAGIC);

  PaymentBasketSet pbs;

  String filterPartner=request.getParameter("partner");
  if(filterPartner!=null){
    pbs=new PaymentBasketSet(filterPartner);
  }
  else{
    pbs=new PaymentBasketSet(filterYear,filterQuarter);
  }

  request.setAttribute("PBS",pbs);
  try{
    SDBQuery q=new SDBQueryFull(worker);
    q.go(DConst.ROOT_APNAME);
    q.filterRegex(DConst.ROOT_USER_REFFERED_BY, ".+");
    SDBNode node;
    while((node=q.next())!=null){
      String apname=node.getValue();
      String partnerEmail=q.dip(DConst.ROOT_USER_REFFERED_BY);
      String stripeId=q.dip(DConst.ROOT_STRIPE_ID);
      if(stripeId==null || stripeId.isEmpty()) continue;
      if(apname.contains("_deleted_")) continue;
      if(partnerEmail!=null && partnerEmail.endsWith("@ragic.com")) continue;
      if(partnerEmail!=null && partnerEmail.equalsIgnoreCase("jeff.kuo@gmail.com")) continue;
      if(filterPartner!=null && !filterPartner.equalsIgnoreCase(partnerEmail)) continue;

      BDBSmartWorker bbs=new BDBSmartWorker(Const.AP_RAGIC);
      String bank=bbs.getFieldValue(DConst.ROOT_USER_EMAIL,partnerEmail,DConst.ROOT_USER_PARTNER_BANK);
      if(bank==null || bank.isEmpty()) bank=bbs.getFieldValue(DConst.ROOT_USER_EMAIL,"@"+partnerEmail,DConst.ROOT_USER_PARTNER_BANK);

      String paypal=bbs.getFieldValue(DConst.ROOT_USER_EMAIL,partnerEmail,DConst.ROOT_USER_PARTNER_PAYPAL_EMAIL);
      if(paypal==null || paypal.isEmpty()) paypal=bbs.getFieldValue(DConst.ROOT_USER_EMAIL,"@"+partnerEmail,DConst.ROOT_USER_PARTNER_PAYPAL_EMAIL);

      pbs.addPaymentBasket(new PaymentBasket(partnerEmail,paypal,bank));

      if("m".equals(stripeId)){//manual, look in wire-in

        
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "manage_wire.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("apname", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(apname), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("partnerEmail", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(partnerEmail), request.getCharacterEncoding()), out, false);

      }
      else{
        
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "manage_creditcard.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("apname", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(apname), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("partnerEmail", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(partnerEmail), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("stripeId", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(stripeId), request.getCharacterEncoding()), out, false);

      }
    }
  }
  finally{
    worker.commit();
  }

  //payment log info
  Map<String,PaymentRecord> paymentLog=new LinkedHashMap<>();
  String paymentLogFile="log/partnerPayment.log";
  String dateFormat="yyyy/MM/dd HH:mm:ss";

  try (BufferedReader br = new BufferedReader(new FileReader(new File(paymentLogFile)))) {
    String line;
    while((line=br.readLine())!=null){
      String[] sec=line.split(",");
      PaymentRecord pr=new PaymentRecord(
              Encoder.parseDate(sec[0],dateFormat),
              sec[1],//pay user
              sec[2],//basketId
              Encoder.parseDouble(sec[3])//pay amount
      );
      paymentLog.put(sec[2],pr);
    }
  } catch (FileNotFoundException e) {
    ExceptionManager.getInstance().processException(e);
  } catch (IOException e) {
    ExceptionManager.getInstance().processException(e);
  }


  /*
    Output the partner management report
   */
  for(PaymentBasket basket:pbs.getBaskets().values()){

    if(basket.getTwdCommissionTotal()==0) continue;
    if(basket.getPartnerEmail().endsWith("fujixerox.com")) continue;
    if(basket.getPartnerEmail().endsWith("fujifilm.com")) continue;

    boolean ifPaid=paymentLog.containsKey(basket.getBasketId(filterYear,filterQuarter));
    if(ifPaid && !showPaid) continue;

    out.println("<div style='margin:20px;padding:25px;background:#efefef;"+(ifPaid?"opacity:0.5;":"")+"'>" +
            "<div><input type='checkbox' "+(ifPaid?"checked='true'":"")+" onclick=\"setAsPaid('"+basket.getBasketId(filterYear,filterQuarter)+"','"+basket.getUsdCommissionTotal()+"');\" /></div>"+
            "<div style='font-weight:700;margin:12px 0;'>To: <a href='?showPaid&partner="+Encoder.encodeURIComponent(basket.getPartnerEmail())+"'>"+basket.getPartnerEmail()+"</a></div>");

    if(basket.ifTWBank()){
              out.println("<div style='font-weight:700;margin:12px 0;'>銀行匯款資訊: "+Encoder.contentEncode(basket.getPartnerBank())+"</div>" +
              "您好！<br/>" +
              "<br/>" +
              "您的 "+filterYear+" 第 "+filterQuarter+" 季佣金合計為 "+Encoder.formatNumber(basket.getTwdCommissionTotal(),"#,###")+" 元，款項已匯至指定帳戶，請開立發票過來。謝謝！<br/>" +
              "<br/>" +
              "佣金明細如下：<br/>");
      for(Map.Entry<String,List<PaymentBasketItem>> entry:basket.getPaymentItems().entrySet()){
        String apname=entry.getKey();

        double apTotal=0;
        double apCommissionTotal=0;
        out.println("<div style='font-size:20px;margin:20px 0;'>"+apname+"</div>" +
                "<table>");

        for(PaymentBasketItem basketItem:entry.getValue()){
          out.println("<tr><td>"+Encoder.formatDate(basketItem.getPaymentDate(),"MMM d, yyyy",bundle)+"</td><td>"+Encoder.formatNumber(basketItem.getTWDAmount(),"#,###")+"</td></tr>");
          apTotal+=basketItem.getTWDAmount();
          apCommissionTotal+=basketItem.getTWDCommissionAmount();
        }

        out.println("<tr style='border-top:1px solid #888;'><td>Total Paid</td><td>"+Encoder.formatNumber(apTotal,"#,###")+"</td><td style='text-align:left'>(TWD)</td></tr>" +
                "<tr><td>Commission</td><td>"+Encoder.formatNumber(apCommissionTotal,"#,###")+"</td><td style='text-align:left'>(TWD)</td></tr>" +
                "</table><br/><br/>");
      }

      out.println("電子發票請直接email回覆，紙本發票請郵寄至：<br/>" +
              "100台北市中正區南昌路二段81號9樓<br/>" +
              "郭家甫 先生收");
    }
    else if(basket.ifPaypal()){
      out.println("<div style='font-weight:700;margin:12px 0;'>Paypal: "+basket.getPartnerPaypal()+
              " <a href=\"javascript:void(0);\" onclick=\"partnerNotify('"+ basket.getPartnerEmail()+"',1,this);\" style=\"font-weight: 400;font-size: 10px;\">Notify Invalid Taiwan Paypal</a></div>" +
              "Hi,<br/>" +
              "<br/>" +
              "Your total commission for "+filterYear+" Q"+filterQuarter+" is "+Encoder.formatNumber(basket.getUsdCommissionTotal(),"#,###.00")+" USD.<br/>" +
              "<br/>" +
              "Detail below：<br/>");
      for(Map.Entry<String,List<PaymentBasketItem>> entry:basket.getPaymentItems().entrySet()){
        String apname=entry.getKey();

        double apTotal=0;
        double apCommissionTotal=0;
        out.println("<div style='font-size:20px;margin:20px 0;'>"+apname+"</div>" +
                "<table>");

        for(PaymentBasketItem basketItem:entry.getValue()){
          out.println("<tr><td>"+Encoder.formatDate(basketItem.getPaymentDate(),"MMM d, yyyy",bundle)+"</td><td>"+Encoder.formatNumber(basketItem.getUSDAmount(),"#,###.00")+"</td></tr>");
          apTotal+=basketItem.getUSDAmount();
          apCommissionTotal+=basketItem.getUSDCommissionAmount();
        }

        out.println("<tr style='border-top:1px solid #888;'><td>Total Paid</td><td>"+Encoder.formatNumber(apTotal,"#,###.00")+"</td><td style='text-align:left'>(USD)</td></tr>" +
                "<tr><td>Commission</td><td>"+Encoder.formatNumber(apCommissionTotal,"#,###.00")+"</td><td style='text-align:left'>(USD)</td></tr>" +
                "</table>");
      }
    }
    else{
      out.println("Partner e-mail <b>"+basket.getPartnerEmail()+"</b> not ready.<br/><br/>" +
              " <a href=\"javascript:void(0);\" onclick=\"partnerNotify('"+ basket.getPartnerEmail()+"',2,this);\">Notify Paypal config</a><br/>" +
              " <a href=\"javascript:void(0);\" onclick=\"partnerNotify('"+ basket.getPartnerEmail()+"',3,this);\">通知設定銀行帳號</a><br/>" +
              "Total commission:"+Encoder.formatNumber(basket.getTwdCommissionTotal(),"#,###")+" (TWD) / "+Encoder.formatNumber(basket.getUsdCommissionTotal(),"#,###.00")+" (USD) <br/>");

      for(Map.Entry<String,List<PaymentBasketItem>> entry:basket.getPaymentItems().entrySet()){
        String apname=entry.getKey();

        double apTotal=0;
        double apCommissionTotal=0;
        out.println("<div style='font-size:20px;margin:20px 0;'>"+apname+"</div>" +
                "<table>");

        for(PaymentBasketItem basketItem:entry.getValue()){
          out.println("<tr><td>"+Encoder.formatDate(basketItem.getPaymentDate(),"MMM d, yyyy",bundle)+"</td><td>"+Encoder.formatNumber(basketItem.getUSDAmount(),"#,###.00")+"</td></tr>");
          apTotal+=basketItem.getUSDAmount();
          apCommissionTotal+=basketItem.getUSDCommissionAmount();
        }

        out.println("<tr style='border-top:1px solid #888;'><td>Total Paid</td><td>"+Encoder.formatNumber(apTotal,"#,###.00")+"</td><td style='text-align:left'>(USD)</td></tr>" +
                "<tr><td>Commission</td><td>"+Encoder.formatNumber(apCommissionTotal,"#,###.00")+"</td><td style='text-align:left'>(USD)</td></tr>" +
                "</table>");
      }
    }
    out.println("</div><hr/>");
  }


      out.write("<script>\r\n  function ajaxget(url,obj,callback,sync){\r\n    var qs='?';\r\n    var first=true;\r\n    for(var key in obj){\r\n      if(!first) qs+='&';\r\n      else first=false;\r\n      qs+=encodeURIComponent(key)+'='+encodeURIComponent(obj[key]);\r\n    }\r\n\r\n    var _reader=new XMLHttpRequest();\r\n    _reader.open('GET',url+qs,!sync);\r\n    _reader.withCredentials=true;//[BugId:07568]\r\n    if(!sync){\r\n      _reader.onreadystatechange = function(){\r\n        if(_reader.readyState==4){\r\n          if(_reader.status!=200){\r\n            return false;\r\n          }\r\n          if(callback) callback(_reader.responseText);\r\n          return true;\r\n        }\r\n      }\r\n    }\r\n    _reader.send(null);\r\n    if(sync) {\r\n      if(_reader.status!=200){\r\n        return false;\r\n      }\r\n      if(callback) callback(_reader.responseText);\r\n    }\r\n    return true;\r\n  }\r\n  function setAsPaid(basketId,paymentAmount){\r\n    ajaxget('/partners/setAsPaid.jsp',{\r\n      'payUserEmail':'");
      out.print(user.getUserId());
      out.write("',\r\n      'basketId':basketId,\r\n      'paymentAmount':paymentAmount\r\n    });\r\n  }\r\n  function partnerNotify(toEmail,type,obj){\r\n    ajaxget('/partners/partnerNotify.jsp',{\r\n      'toEmail':toEmail,\r\n      'type':type\r\n    },function(){\r\n      obj.innerHTML='Notified';\r\n      obj.disabled=true;\r\n    });\r\n  }\r\n</script>\r\n\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
