/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2022-11-10 01:41:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.intl.zh_002dCN;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ragic.s3.nui.RagicConfig;

public final class homepub_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ragic.s3.nui.RagicConfig");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


  RagicConfig rc=RagicConfig.getInstance();
  String cdnurl=rc.getProperty("CDN_URL");

      out.write("<div style=\"width:882px;min-height:650px;height:100%;margin:50px auto 25px auto;position:relative;\">\r\n  <div style=\"position:absolute;right:0;top:120px;\">\r\n\r\n    <a href=\"/\" style=\"margin:0 0 0 3px;color:#e70e0e;font-size:18px;font-weight:bold;\">Ragic!</a>\r\n    <div style=\"font-size:36px;color:#333;line-height: 1.2em;letter-spacing: -1px;width:380px;\">最方便的云端数据库</div>\r\n    <div style=\"font-size:18px;line-height: 1.5em;color:#aaa;\">任何人都能快速做出想要的数据库网页！</div>\r\n    <div style=\"margin:12px 0 0 0;\">\r\n      <form id=\"frontSignupForm\" action=\"/intl/zh-TW/register\" method=\"POST\">\r\n        <div class=\"placeholding-input\">\r\n          <input type=\"text\" id=\"signup-email\" class=\"text-input\" autocomplete=\"off\" name=\"e\" onkeydown=\"$('emailLabel').style.display='none';\" onblur=\"if(this.value==''){$('emailLabel').style.display='';}\">\r\n          <label id=\"emailLabel\" for=\"signup-email\" class=\"placeholder\">输入电子邮件信箱</label>\r\n        </div>\r\n        <a href=\"javascript:void(0);\" class=\"thebutton\" onclick=\"$('frontSignupForm').submit();\" style=\"margin:25px 150px 0 0;\">免费注册</a>\r\n");
      out.write("      </form>\r\n      ");
      out.write("</div>\r\n\r\n  </div>\r\n  <img src=\"/intl/common/img/lbulb2.png\" style=\"margin-left:-110px;\" />\r\n</div>\r\n\r\n<div id=\"learn-more\" onclick=\"animateScrollTo($('pubDiv').offsetTop-75);\">\r\n  来看看大家用它做了些什么？\r\n  <img src=\"/intl/common/img/down.png\" />\r\n</div>\r\n\r\n<div style=\"width:980px;margin:25px auto;background:#dbdbdb;height:1px;\"></div>\r\n\r\n<div id=\"pubDiv\" style=\"width:980px;margin:50px auto 25px auto;\">\r\n  <ul>\r\n    <li class=\"clearfix\">\r\n      <img src=\"/intl/common/img/pub_exchange.png\" />\r\n      <h3>网路交易类</h3>\r\n    </li>\r\n    <li><a href=\"//www.ragic.com/20130721snsd/snsd/1\" target=\"_blank\">少女时代演唱会门票交换</a></li>\r\n    <li><a href=\"//www.ragic.com/eason/ticket/1\" target=\"_blank\">陈奕迅演唱会门票交换</a></li>\r\n    <li><a href=\"//www.ragic.com/ticket/mayday/3\" target=\"_blank\">五月天演唱会门票交换</a></li>\r\n    <li><a href=\"//www.ragic.com/platform/jacky/2\" target=\"_blank\">张学友演唱会门票交换</a></li>\r\n    <li><a href=\"//www.ragic.com/2012ss4/ss4exchange/1\" target=\"_blank\">Super Junior演唱会门票交换</a></li>\r\n  </ul>\r\n  <ul>\r\n    <li class=\"clearfix\">\r\n      <img src=\"/intl/common/img/pub_opendb.png\" />\r\n");
      out.write("      <h3>公开数据库类</h3>\r\n    </li>\r\n    <li><a href=\"//www.ragic.com/safefood/tw/2\" target=\"_blank\">塑化剂查询数据库</a></li>\r\n    <li><a href=\"//www.ragic.com/popo/popo/1\" target=\"_blank\">波兰医生一览表</a></li>\r\n    <li><a href=\"//www.ragic.com/food/taiwan/1\" target=\"_blank\">台湾美食数据库</a></li>\r\n    <li><a href=\"//www.ragic.com/startupList/startups/1\" target=\"_blank\">全球新创公司 Z to A</a></li>\r\n    <li><a href=\"//www.ragic.com/twstartups/companies/1\" target=\"_blank\">台湾新创公司列表</a></li>\r\n  </ul>\r\n  <ul>\r\n    <li class=\"clearfix\">\r\n      <img src=\"/intl/common/img/pub_share.png\" />\r\n      <h3>信息分享类</h3>\r\n    </li>\r\n    <li><a href=\"//www.ragic.com/twsalary/forms/1\" target=\"_blank\">台湾薪资匿名分享</a></li>\r\n    <li><a href=\"//www.ragic.com/bio/salary/6\" target=\"_blank\">生技产业薪资分享</a></li>\r\n    <li><a href=\"//www.ragic.com/AdvisoRating/forms/1\" target=\"_blank\">教授信息匿名分享</a></li>\r\n    <li><a href=\"//www.ragic.com/directory/prweb/1\" target=\"_blank\">免费发布新闻稿</a></li>\r\n  </ul>\r\n  <ul style=\"clear:left;\">\r\n    <li class=\"clearfix\">\r\n      <img src=\"/intl/common/img/pub_academic.png\" />\r\n");
      out.write("      <h3>学术研究类</h3>\r\n    </li>\r\n    <li><a href=\"//www.ragic.com/bronzeagesacrifice/c---glyptic/1\" target=\"_blank\">铜器时代爱琴海考古数据库</a></li>\r\n  </ul>\r\n  <ul>\r\n    <li class=\"clearfix\">\r\n      <img src=\"/intl/common/img/pub_community.png\" />\r\n      <h3>虚拟社群类</h3>\r\n    </li>\r\n    <li><a href=\"//www.ragic.com/ptt/wow/1\" target=\"_blank\">魔兽世界揪团平台</a></li>\r\n    <li><a href=\"//www.ragic.com/ptt/beauty/1\" target=\"_blank\">PTT正妹数据库</a></li>\r\n    <li><a href=\"//www.ragic.com/ptt/wow104/1\" target=\"_blank\">魔兽世界公会征才平台</a></li>\r\n  </ul>\r\n\r\n\r\n</div>\r\n\r\n<div id=\"pubNote\" style=\"width:980px;margin:50px auto 25px auto;\">\r\n\r\n  <div style=\"clear:left;margin:100px auto 25px auto;font-size:25px;\">\r\n    你也用Ragic做了有趣的公开应用想跟大家分享吗？<a href=\"//www.ragic.com/support/contact/5?webview&webaction=form\" target=\"_blank\" style=\"border-bottom:1px solid #06C;\">告诉我们</a>！\r\n  </div>\r\n  <div style=\"clear:left;margin:25px auto 250px 0;font-size:25px;\">\r\n    Ragic免费赞助公益目的云端数据库，快来<a href=\"//www.ragic.com/support/contact/6?webview&webaction=form\" target=\"_blank\" style=\"border-bottom:1px solid #06C;\">申请赞助帐号</a>！\r\n");
      out.write("  </div>\r\n\r\n</div>\r\n\r\n<script>\r\n  function animateScrollTo(pos){\r\n    if(document.documentElement.scrollTop<pos){\r\n      document.documentElement.scrollTop+=25;\r\n      setTimeout('animateScrollTo('+pos+')',10);\r\n    }\r\n  }\r\n</script>\r\n\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
