/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2022-11-10 01:41:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sims.report.templates.ragic.calendar;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ragic.s3.nui.*;
import com.ragic.s3.nui.helper.*;
import com.ragic.s3.nui.output.CellInfoDisplayInfoRetriever;
import com.ragic.s3.nui.output.CellValueDisplayHelper;
import com.ragic.s3.service.api.APIEntry;
import com.ragic.s3.service.api.APIFullIteration;
import com.ragic.s3.service.api.APIQuery;
import com.ragic.s3.service.report.Report;
import com.ragic.s3.util.Const;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import java.text.SimpleDateFormat;
import java.util.*;
import java.text.DateFormat;
import com.dropbox.core.v2.teamlog.SmartSyncOptOutType;
import com.ragic.s3.util.Log;

public final class report_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.ragic.s3.nui");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.ragic.s3.nui.helper");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ragic.s3.nui.output.CellValueDisplayHelper");
    _jspx_imports_classes.add("com.ragic.s3.nui.output.CellInfoDisplayInfoRetriever");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("com.ragic.s3.service.api.APIEntry");
    _jspx_imports_classes.add("com.ragic.s3.util.Const");
    _jspx_imports_classes.add("com.dropbox.core.v2.teamlog.SmartSyncOptOutType");
    _jspx_imports_classes.add("com.ragic.s3.util.Log");
    _jspx_imports_classes.add("com.ragic.s3.service.api.APIFullIteration");
    _jspx_imports_classes.add("com.ragic.s3.service.report.Report");
    _jspx_imports_classes.add("com.ragic.s3.service.api.APIQuery");
    _jspx_imports_classes.add("org.json.JSONException");
    _jspx_imports_classes.add("org.json.JSONObject");
    _jspx_imports_classes.add("org.json.JSONArray");
    _jspx_imports_classes.add("java.text.DateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<script src=\"/sims/js/ragicStorage.js\"></script>\r\n\r\n");

    final int limitSize = 10000;
    DateFormat df = new SimpleDateFormat("yyyy/MM/dd");
    APIQuery aq = (APIQuery) request.getAttribute("REPORT_APIQUERY");//query ready
    aq.setLimitSize(limitSize);//無效 APIFullIteration 還是會遍歷全部，因此在APIFullIteration中設停止條件

    Report report = (Report) session.getAttribute("UNSAVED_REPORT" + aq.getApname());
    RagicBundle bundle = (RagicBundle) session.getAttribute("RAGIC_BUNDLE");
    User user = (User) session.getAttribute("USER");
    boolean ifPDFDownload = request.getParameter("pjs") != null;
    boolean ifPrintFriendly = request.getParameter("pf") != null;
    String apname = aq.getApname();
    String defaultDateTimeFormat=Account.getInstance(apname).getAppSetting().getDefaultDateTimeFormat();
    String defaultDateFormat=defaultDateTimeFormat.split(" ")[0];


    if(defaultDateFormat.indexOf('H') != -1||defaultDateFormat.indexOf("M")==-1){
        defaultDateFormat="yyyy/MM/dd";
        new Log("log/report_calendar.log").setIfDisplayTime(true).info("[Error date time format]"+defaultDateTimeFormat+"|"+defaultDateFormat);
    }

    // init the calendar setting
    String viewType = report.getValue("calendarView");
    String timeSplit = report.getValue("timeSplit");
    if (timeSplit == null || timeSplit.isEmpty()) {
        timeSplit = "0.5";
    }
    String timeViewInitTime = report.getValue("timeViewInitTime");
    if (timeViewInitTime == null || timeViewInitTime.isEmpty()) {
        timeViewInitTime = "6";
    }
    String timeViewEndTime = report.getValue("timeViewEndTime");
    if (timeViewEndTime == null || timeViewEndTime.isEmpty()) {
        timeViewEndTime = "20";
    }
    //if Printfriendly focusDate get from request
    String today=Encoder.formattedNow(apname,bundle,"yyyy/MM/dd");//user timeZone
    String chosenFocusDate;
    if(ifPrintFriendly)chosenFocusDate=request.getParameter("focusDate");
    else chosenFocusDate = report.getValue("chosenFocusDate");

    if (chosenFocusDate == null || chosenFocusDate.isEmpty()) {
        chosenFocusDate = today;
    }

    try{
        new Date( chosenFocusDate);
    }catch (Exception e){
        new Log("log/report_calendar.log").setIfDisplayTime(true).info("[Error focus date]"+chosenFocusDate);
        chosenFocusDate = today;

    }

    HttpSession psSession = (HttpSession) request.getAttribute("psSession");
    if(psSession != null) {
        bundle =(RagicBundle) psSession.getAttribute("RAGIC_BUNDLE");
        if(psSession.getAttribute("UNSAVED_REPORT"+aq.getApname()) != null) {
            report = (Report)psSession.getAttribute("UNSAVED_REPORT"+aq.getApname());
        }
    }

    String fontFamily = request.getParameter("fontFamily");
    double fontSizeScale = Double.parseDouble(request.getParameter("fontSize"));
    String boundaryMargin = request.getParameter("boundaryMargin");
    boolean showTimelines = Boolean.parseBoolean(report.getValue("showTimelines"));

    NUIForm form = aq.getForm();

    List<CellInfo> timeCells = form.getTimeFields();
    ArrayList<CellInfo> filteredTimeCells = new ArrayList<>();
    for (CellInfo info : timeCells) {
        String dateFormat = info.getAttribute("fmt_d");
        if (info.getAttribute("repeat") == null &&
                (!dateFormat.contains("y") || !dateFormat.contains("M") || !dateFormat.contains("d"))) {
            continue;
        }
        filteredTimeCells.add(info);
    }
    if (filteredTimeCells.size() == 0) {
        
      out.write("<div style='margin:25px;'>");
      out.print(bundle.getString("report_noDataFields"));
      out.write("</div>");

        return;
    }

    final int dateField_1 = Encoder.parseInt(report.getValue("df1"), filteredTimeCells.get(0).getDomainId());
    final int dateField_2 = Encoder.parseInt(report.getValue("df2"), Const.NODOMAIN);
    final CellInfo dateCell_1 = form.getCellInfoByDomainId(dateField_1);
    CellInfo dateCell_2 = form.getCellInfoByDomainId(dateField_2);
    final int reportItemTitleField = Encoder.parseInt(report.getValue("tf"), form.getTitleField());
    final CellInfo reportItemTitleFieldCellInfo = form.getField(reportItemTitleField);

    aq.addFetchDomains(dateField_1);
    if(dateField_2!=Const.NODOMAIN)aq.addFetchDomains(dateField_2);
    aq.addFetchDomains(reportItemTitleField);

    // prepare events data
    final JSONArray ja = new JSONArray();
    if (dateField_1 != Const.NODOMAIN) {
        aq.addFilter(dateField_1,NUIFilter.OPERAND_SORT_DESC,"x");
        List<NUIFilter> filters = aq.getAllFilters();
        boolean addDateRange = true;
        for (NUIFilter filter : filters) {
            if (filter.getDomainId() == dateField_1) {
                addDateRange = false;
                break;
            }
        }
        if (addDateRange) {
            Calendar now = Calendar.getInstance(), operateTime = Calendar.getInstance();
            operateTime.set(Calendar.YEAR, now.get(Calendar.YEAR) - 1);
            String _front = Encoder.formatAsStandardDate(operateTime.getTime(), true);
            operateTime.set(Calendar.YEAR, now.get(Calendar.YEAR) + 2);
            String _end = Encoder.formatAsStandardDate(operateTime.getTime(), true);
            NUIFilter _rangeLimit = new NUIFilter(dateField_1, NUIFilter.OPERAND_RANGE, _end, _front);
            aq.addFilter(dateField_1, _rangeLimit);
        }

        final RagicBundle _bundle = bundle;
        final Account account = Account.getInstance(apname);

        Calendar calendar = Calendar.getInstance();
        calendar.setTime(new Date( chosenFocusDate));


        APIFullIteration iteration = new APIFullIteration(aq) {
            private Date dateFrom = null;
            private Date dateTo = null;
            private int eventEntryCount=0;

            @Override
            protected void prepareIteration() {
            	if(this.dateFrom != null && this.dateTo != null) return;
                NUIFilter dateFieldFilter = null;
                for(NUIFilter f: this.aq.getAllFilters()) {
                    if(f.getDomainId() == dateField_1) {
                        dateFieldFilter = f;
                        break;
                    }
                }
                Date date_low,date_hi;
                //沒有篩選期限的話就用指定日期(當日)前後一年為區間
                if(dateFieldFilter == null || dateFieldFilter.getLow() == null || dateFieldFilter.getHi() == null){
                    date_low = new Date((calendar.get(Calendar.YEAR)-1)+"/"+(calendar.get(Calendar.MONTH)+1)+"/"+(calendar.get(Calendar.DATE)));
                    date_hi = new Date((calendar.get(Calendar.YEAR)+1)+"/"+(calendar.get(Calendar.MONTH)+1)+"/"+(calendar.get(Calendar.DATE)));
                }else{
                    date_low =  Encoder.parseStandardDate(dateFieldFilter.getLow());
                    date_hi = Encoder.parseStandardDate(dateFieldFilter.getHi());
                }

                if(date_low == null || date_hi == null) return;

                Calendar cal = Calendar.getInstance();
                cal.setTime(date_low);
                cal.set(Calendar.HOUR_OF_DAY, cal.getActualMinimum(Calendar.HOUR_OF_DAY));
                cal.set(Calendar.MINUTE, cal.getActualMinimum(Calendar.MINUTE));
                cal.set(Calendar.SECOND, cal.getActualMinimum(Calendar.SECOND));
                this.dateFrom = cal.getTime();

                cal.setTime(date_hi);
                cal.set(Calendar.HOUR_OF_DAY, cal.getActualMaximum(Calendar.HOUR_OF_DAY));
                cal.set(Calendar.MINUTE, cal.getActualMaximum(Calendar.MINUTE));
                cal.set(Calendar.SECOND, cal.getActualMaximum(Calendar.SECOND));
                this.dateTo = cal.getTime();

            }


            @Override
            protected void entryCustomAction(APIEntry entry, int runningCount) {
                try {
                    entry.setIfTranslateEmailToUserName(true);//[BugId:11521]
                	String startDateString = entry.getFieldValue(dateField_1);
                    if(startDateString == null || startDateString.trim().isEmpty()) return;

                	String title = entry.getFieldValue(reportItemTitleField);
                    if (reportItemTitleFieldCellInfo != null) {
                        if (reportItemTitleFieldCellInfo.getAttribute("fmt_n") != null || reportItemTitleFieldCellInfo.getAttribute("fmt_d") != null) {
                            CellInfoDisplayInfoRetriever retriever = new CellInfoDisplayInfoRetriever(reportItemTitleFieldCellInfo, title);
                            title = CellValueDisplayHelper.formatDisplayValueAsPlainText(retriever, apname, -1, _bundle);
                        }
                    }

                    String repeatType = dateCell_1.getAttribute("repeat");
                    if(repeatType == null) {
                    	JSONObject eventJSON = new JSONObject();
                        eventJSON.put("content", Encoder.removeBBCode(title));
                        eventJSON.put("date_init", startDateString);
                        eventJSON.put("date_end", (dateField_2 != Const.NODOMAIN) ? entry.getFieldValue(dateField_2) : "");
                        eventJSON.put("path", this.getPath());
                        eventJSON.put("sheetIndex", this.getSheetIndex());
                        eventJSON.put("nodeId", entry.getRootNodeId());
                        ja.put(eventJSON);
                        eventEntryCount++;
                    } else {
                    	if(this.dateFrom == null || this.dateTo == null) return;
                    	String repeatIndexString = RepeatDateHelper.createRepeatDateIndexString(startDateString, repeatType);
                    	List<Date> repeatDateList = RepeatDateHelper.getRepeatDates(this.dateFrom, this.dateTo, repeatIndexString);
                        for(Date repeatDate: repeatDateList) {
                        	String repeatDateString = Encoder.formatAsStandardDate(repeatDate, false);
                        	JSONObject eventJSON = new JSONObject();
                        	eventJSON.put("content", Encoder.removeBBCode(title));
                            eventJSON.put("date_init", repeatDateString);
                            eventJSON.put("date_end", repeatDateString);
                            eventJSON.put("path", this.getPath());
                            eventJSON.put("sheetIndex", this.getSheetIndex());
                            eventJSON.put("nodeId", entry.getRootNodeId());
                            ja.put(eventJSON);
                        }
                        eventEntryCount++;
                    }
                } catch (JSONException ignored) {
                }
            }
            @Override
            protected boolean keepIterationCheck(){
                if(eventEntryCount<limitSize)return true;
                else return false;
            }
        };
        iteration.setReadOnly(true);
        iteration.setBundle(bundle);
        iteration.iterate();
    }



      out.write("<script>\r\n    //FocusDate from java\r\n    var chosenFocusDate =  new Date(\"");
      out.print(chosenFocusDate );
      out.write("\");\r\n    RagicStorage.localStorage.setItem(\"FocusDateTime\",\"");
      out.print(chosenFocusDate );
      out.write("\");\r\n    RagicStorage.localStorage.setItem(\"newWinFocusDateTime\", chosenFocusDate);\r\n</script>\r\n\r\n");
report.setParamValue("chosenFocusDate",null);
      out.write("<script src=\"/sims/report/templates/ragic/calendar/ragicEventCalendar.js\"></script>\r\n<script>\r\n    var config = {};\r\n    ");
      out.print((viewType != null && !viewType.isEmpty()) ? "config.defaultView = '" + viewType + "'" : "" );
      out.write("\r\n    config.timeSplit = '");
      out.print(timeSplit);
      out.write("';\r\n    config.timeViewInitTime = '");
      out.print(timeViewInitTime);
      out.write("';\r\n    config.timeViewEndTime = '");
      out.print(timeViewEndTime);
      out.write("';\r\n    config.fontSizeScale = '");
      out.print(fontSizeScale);
      out.write("';\r\n    config.showTimelines = ");
      out.print(showTimelines);
      out.write(";\r\n    config.calendarView = '");
      out.print(report.getValue("calendarView")!=null?report.getValue("calendarView"):"M");
      out.write("';\r\n    config.focusDateTime = new Date(RagicStorage.localStorage.getItem(\"newWinFocusDateTime\"));\r\n    config.enableTimeFormatChange=true;//12-24小時至切換，預設小時制\r\n    RagicEventCalendar.loadConfig(config);\r\n    //目前切換 月/周/天 時，chosenFocusDate沒連動未來要改\r\n    RagicEventCalendar.registerAction('EventCalendar_Btn_Month', 'click',\r\n        function () {\r\n            updateConfig('calendarView', 'M', false, true, false, null, 'M');\r\n        });\r\n    RagicEventCalendar.registerAction('EventCalendar_Btn_Week', 'click',\r\n        function () {\r\n            updateConfig('calendarView', 'W', false, true, false, null, 'M');\r\n        });\r\n    RagicEventCalendar.registerAction('EventCalendar_Btn_Day', 'click',\r\n        function () {\r\n            updateConfig('calendarView', 'D', false, true, false, null, 'M');\r\n        });\r\n\r\n    var regNewWinFocusDateTime = function () {\r\n        RagicStorage.localStorage.setItem(\"newWinFocusDateTime\", RagicEventCalendar.getFocusDateTime());\r\n        document.getElementById(\"calendarFocusDate\").value=\"\";\r\n");
      out.write("    };\r\n    RagicEventCalendar.registerAction('EventCalendar_Btn_Prev', 'click');\r\n    RagicEventCalendar.registerAction('EventCalendar_Btn_Today', 'click', regNewWinFocusDateTime);\r\n    RagicEventCalendar.registerAction('EventCalendar_Btn_Next', 'click');\r\n    RagicEventCalendar.registerAction('Change_FocusDate', 'click');\r\n\r\n    RagicEventCalendar.setEventRenderFunction(function (eventDiv, calendarEvent) {\r\n        eventDiv.dataset.url = calendarEvent.path + \"/\" + calendarEvent.sheetIndex;\r\n        eventDiv.dataset.nodeId = calendarEvent.nodeId;\r\n        eventDiv.addEventListener('click', function () {\r\n            showXHTMLMsg(ap + this.dataset.url, this.dataset.nodeId);\r\n        });\r\n    });\r\n\r\n    RagicEventCalendar.setEventMoreFunction(function (calendarEvents) {\r\n        var allEventDiv = document.createElement('DIV');\r\n        calendarEvents.forEach(function (calendarEvent) {\r\n            var contentDiv = calendarEvent.render();\r\n            contentDiv.classList.add(\"EventCalendar_Evt_Day\");\r\n            if (!contentDiv.style.backgroundColor) {\r\n");
      out.write("                contentDiv.style.backgroundColor = \"transparent\";\r\n            } else {\r\n                contentDiv.style.borderRadius = \"3px\";\r\n            }\r\n            contentDiv.appendChild(document.createTextNode(calendarEvent.content));\r\n            allEventDiv.appendChild(contentDiv);\r\n        });\r\n\r\n        floatWin(function () {\r\n            $('floatingWinContent').replaceChild(allEventDiv, $('floatingWinContent').firstChild);\r\n        }, '\\u00A0', '');\r\n    });\r\n\r\n    var lang = {\r\n        today: '");
      out.print(bundle.getString("today"));
      out.write("',\r\n        focus: '");
      out.print(bundle.getString("chosenDate"));
      out.write("',\r\n        month: '");
      out.print(bundle.getString("month"));
      out.write("',\r\n        week: '");
      out.print(bundle.getString("week"));
      out.write("',\r\n        day: '");
      out.print(bundle.getString("day"));
      out.write("',\r\n\r\n        all_day: '");
      out.print(bundle.getString("report_allDay"));
      out.write("',\r\n\r\n        m0: '");
      out.print(bundle.getString("month1"));
      out.write("',\r\n        m1: '");
      out.print(bundle.getString("month2"));
      out.write("',\r\n        m2: '");
      out.print(bundle.getString("month3"));
      out.write("',\r\n        m3: '");
      out.print(bundle.getString("month4"));
      out.write("',\r\n        m4: '");
      out.print(bundle.getString("month5"));
      out.write("',\r\n        m5: '");
      out.print(bundle.getString("month6"));
      out.write("',\r\n        m6: '");
      out.print(bundle.getString("month7"));
      out.write("',\r\n        m7: '");
      out.print(bundle.getString("month8"));
      out.write("',\r\n        m8: '");
      out.print(bundle.getString("month9"));
      out.write("',\r\n        m9: '");
      out.print(bundle.getString("month10"));
      out.write("',\r\n        m10: '");
      out.print(bundle.getString("month11"));
      out.write("',\r\n        m11: '");
      out.print(bundle.getString("month12"));
      out.write("',\r\n\r\n        d0: '");
      out.print(bundle.getString("weekdayShort0"));
      out.write("',\r\n        d1: '");
      out.print(bundle.getString("weekdayShort1"));
      out.write("',\r\n        d2: '");
      out.print(bundle.getString("weekdayShort2"));
      out.write("',\r\n        d3: '");
      out.print(bundle.getString("weekdayShort3"));
      out.write("',\r\n        d4: '");
      out.print(bundle.getString("weekdayShort4"));
      out.write("',\r\n        d5: '");
      out.print(bundle.getString("weekdayShort5"));
      out.write("',\r\n        d6: '");
      out.print(bundle.getString("weekdayShort6"));
      out.write("'\r\n    };\r\n\r\n    RagicEventCalendar.loadLanguage(lang);\r\n    window.addEventListener('DOMContentLoaded', function () {\r\n        RagicEventCalendar.requireEventData(");
      out.print(ja.toString());
      out.write(");\r\n        $('eventCalendar').appendChild(RagicEventCalendar.render());\r\n    }, {once: true});\r\n</script>\r\n");
 if(ifPDFDownload){
      out.write("<script>\r\n    function init() {\r\n        var config = {};\r\n        ");
      out.print((viewType != null && !viewType.isEmpty()) ? "config.defaultView = '" + viewType + "'" : "" );
      out.write("\r\n        config.timeSplit = '");
      out.print(timeSplit);
      out.write("';\r\n        config.timeViewInitTime = '");
      out.print(timeViewInitTime);
      out.write("';\r\n        config.timeViewEndTime = '");
      out.print(timeViewEndTime);
      out.write("';\r\n        config.fontSizeScale = '");
      out.print(fontSizeScale);
      out.write("';\r\n        config.showTimelines = ");
      out.print(showTimelines);
      out.write(";\r\n        if (location.search.indexOf(\"newwin\") !== -1 && RagicStorage.localStorage.getItem(\"newWinFocusDateTime\")) {\r\n            config.focusDateTime = new Date(RagicStorage.localStorage.getItem(\"newWinFocusDateTime\"));\r\n        }\r\n        RagicEventCalendar.loadConfig(config);\r\n        RagicEventCalendar.registerAction('EventCalendar_Btn_Month', 'click',\r\n            function () {\r\n                updateConfig('calendarView', 'M', false, true, false, null, 'M');\r\n            });\r\n        RagicEventCalendar.registerAction('EventCalendar_Btn_Week', 'click',\r\n            function () {\r\n                updateConfig('calendarView', 'W', false, true, false, null, 'M');\r\n            });\r\n        RagicEventCalendar.registerAction('EventCalendar_Btn_Day', 'click',\r\n            function () {\r\n                updateConfig('calendarView', 'D', false, true, false, null, 'M');\r\n            });\r\n\r\n        var regNewWinFocusDateTime = function () {\r\n            RagicStorage.localStorage.setItem(\"newWinFocusDateTime\", RagicEventCalendar.getFocusDateTime());\r\n");
      out.write("        };\r\n        RagicEventCalendar.registerAction('EventCalendar_Btn_Prev', 'click');\r\n        RagicEventCalendar.registerAction('EventCalendar_Btn_Today', 'click', regNewWinFocusDateTime);\r\n        RagicEventCalendar.registerAction('EventCalendar_Btn_Next', 'click');\r\n        RagicEventCalendar.registerAction('Change_FocusDate', 'click');\r\n\r\n        RagicEventCalendar.setEventRenderFunction(function (eventDiv, calendarEvent) {\r\n            eventDiv.dataset.url = calendarEvent.path + \"/\" + calendarEvent.sheetIndex;\r\n            eventDiv.dataset.nodeId = calendarEvent.nodeId;\r\n            eventDiv.addEventListener('click', function () {\r\n                showXHTMLMsg(ap + this.dataset.url, this.dataset.nodeId);\r\n            });\r\n        });\r\n\r\n        RagicEventCalendar.setEventMoreFunction(function (calendarEvents) {\r\n            var allEventDiv = document.createElement('DIV');\r\n            calendarEvents.forEach(function (calendarEvent) {\r\n                var contentDiv = calendarEvent.render();\r\n                contentDiv.classList.add(\"EventCalendar_Evt_Day\");\r\n");
      out.write("                if (!contentDiv.style.backgroundColor) {\r\n                    contentDiv.style.backgroundColor = \"transparent\";\r\n                } else {\r\n                    contentDiv.style.borderRadius = \"3px\";\r\n                }\r\n                contentDiv.appendChild(document.createTextNode(calendarEvent.content));\r\n                allEventDiv.appendChild(contentDiv);\r\n            });\r\n\r\n            floatWin(function () {\r\n                document.getElementById('floatingWinContent').replaceChild(allEventDiv,  document.getElementById('floatingWinContent').firstChild);\r\n            }, '\\u00A0', '');\r\n        });\r\n\r\n        var lang = {\r\n            today: '");
      out.print(bundle.getString("today"));
      out.write("',\r\n            focus: '");
      out.print(bundle.getString("chosenDate"));
      out.write("',\r\n            month: '");
      out.print(bundle.getString("month"));
      out.write("',\r\n            week: '");
      out.print(bundle.getString("week"));
      out.write("',\r\n            day: '");
      out.print(bundle.getString("day"));
      out.write("',\r\n\r\n            all_day: '");
      out.print(bundle.getString("report_allDay"));
      out.write("',\r\n\r\n            m0: '");
      out.print(bundle.getString("month1"));
      out.write("',\r\n            m1: '");
      out.print(bundle.getString("month2"));
      out.write("',\r\n            m2: '");
      out.print(bundle.getString("month3"));
      out.write("',\r\n            m3: '");
      out.print(bundle.getString("month4"));
      out.write("',\r\n            m4: '");
      out.print(bundle.getString("month5"));
      out.write("',\r\n            m5: '");
      out.print(bundle.getString("month6"));
      out.write("',\r\n            m6: '");
      out.print(bundle.getString("month7"));
      out.write("',\r\n            m7: '");
      out.print(bundle.getString("month8"));
      out.write("',\r\n            m8: '");
      out.print(bundle.getString("month9"));
      out.write("',\r\n            m9: '");
      out.print(bundle.getString("month10"));
      out.write("',\r\n            m10: '");
      out.print(bundle.getString("month11"));
      out.write("',\r\n            m11: '");
      out.print(bundle.getString("month12"));
      out.write("',\r\n\r\n            d0: '");
      out.print(bundle.getString("weekdayShort0"));
      out.write("',\r\n            d1: '");
      out.print(bundle.getString("weekdayShort1"));
      out.write("',\r\n            d2: '");
      out.print(bundle.getString("weekdayShort2"));
      out.write("',\r\n            d3: '");
      out.print(bundle.getString("weekdayShort3"));
      out.write("',\r\n            d4: '");
      out.print(bundle.getString("weekdayShort4"));
      out.write("',\r\n            d5: '");
      out.print(bundle.getString("weekdayShort5"));
      out.write("',\r\n            d6: '");
      out.print(bundle.getString("weekdayShort6"));
      out.write("'\r\n        };\r\n\r\n        RagicEventCalendar.loadLanguage(lang);\r\n\r\n        RagicEventCalendar.requireEventData(");
      out.print(ja.toString());
      out.write(");\r\n        document.getElementById('eventCalendar').appendChild(RagicEventCalendar.render());\r\n    }\r\n</script>\r\n");
} 
      out.write("<div class='printHide' style='padding:12px 25px;background:#efefef;font-size:12px;'>\r\n    <div style='padding-bottom:5px;'>\r\n        <select title=\"");
      out.print(bundle.getString("accessibility_startDate"));
      out.write("\" onchange=\"updateConfig('df1',this.options[this.selectedIndex].value,false,true,false,null,");
      out.print(filteredTimeCells.get(0).getDomainId());
      out.write(");\">\r\n            <option ");
      out.print((Const.NODOMAIN == dateField_1 ? "selected='selected'" : ""));
      out.write(" value='");
      out.print(Const.NODOMAIN);
      out.write('\'');
      out.write('>');
      out.print(bundle.getString("report_selectStartDate"));
      out.write("</option>\r\n");

    for (CellInfo info : filteredTimeCells) {
        int domainId = info.getDomainId();
        if (dateField_2 != Const.NODOMAIN && domainId == dateField_2) continue;

      out.write("<option ");
      out.print((domainId == dateField_1 ? "selected='selected'" : ""));
      out.write(" value='");
      out.print(domainId);
      out.write('\'');
      out.write('>');
      out.print(info.getValue());
      out.write("</option>\r\n");

    }

      out.write("</select>\r\n");

    if (filteredTimeCells.size() > 1 && (dateCell_1 != null && dateCell_1.getAttribute("repeat") == null)) {

      out.write("<select title=\"");
      out.print(bundle.getString("accessibility_endDate"));
      out.write("\" onchange=\"updateConfig('df2',this.options[this.selectedIndex].value,false,true,false,null,");
      out.print(Const.NODOMAIN);
      out.write(");\">\r\n            <option ");
      out.print((Const.NODOMAIN == dateField_2 ? "selected='selected'" : ""));
      out.write(" value='");
      out.print(Const.NODOMAIN);
      out.write('\'');
      out.write('>');
      out.print(bundle.getString("report_selectEndDate"));
      out.write("</option>\r\n");

        for (CellInfo info : filteredTimeCells) {
            int domainId = info.getDomainId();
            if (dateField_1 != Const.NODOMAIN && domainId == dateField_1) continue;
            if(form.getCellInfoByDomainId(domainId) == null || form.getCellInfoByDomainId(domainId).getAttribute("repeat") != null) continue;

      out.write("<option ");
      out.print((domainId == dateField_2 ? "selected='selected'" : ""));
      out.write(" value='");
      out.print(domainId);
      out.write('\'');
      out.write('>');
      out.print(info.getValue());
      out.write("</option>\r\n");

        }

      out.write("</select>\r\n");

    }

    if(dateCell_1 != null) {

      out.write("<label for=\"calTitleSelect\">");
      out.print(bundle.getString("calTitleSelect"));
      out.write(": </label>\r\n        <select id=\"calTitleSelect\" onchange=\"updateConfig('tf',this.options[this.selectedIndex].value,false,true,false,null,");
      out.print(form.getTitleField());
      out.write(");\">\r\n");

        for (CellInfo info : form.getAllFields(false)) {
            String fieldType = info.getType();
            if (Const.FILE.equals(fieldType) || Const.GRAPHIC.equals(fieldType)) continue;

            int domainId = info.getDomainId();

      out.write("<option ");
      out.print((domainId == reportItemTitleField ? "selected='selected'" : ""));
      out.write(" value='");
      out.print(domainId);
      out.write('\'');
      out.write('>');
      out.print(info.getValue());
      out.write("</option>\r\n");

        }

      out.write("</select>\r\n        ");

            }
        
      out.write("<div onClick='datePickerClick($(\"calendarFocusDate\"),\"yyyy/MM/dd\"); event.cancelBubble=true;'\r\n             style='width: 300px;  margin-top:10px;margin-bottom:10px; display: flex;  align-items: center'>\r\n\r\n            <input title=\"");
      out.print(bundle.getString("chosenDate"));
      out.write("\" autoComplete='off' type='text' onFocuws='ctrl.outOfNUI = true;' onBlur='ctrl.outOfNUI=false;'\r\n                   onInput='hideTaskDatePicker();' id='calendarFocusDate'\r\n                   placeholder='-- ");
      out.print(bundle.getString("chosenDate"));
      out.write(" --'\r\n                   onchange=\"checkChosenDateFormat()\"\r\n                   style=' width:260px; border-radius: 3px;border: 1px solid #CCC; margin-right: 10px'\r\n            >\r\n            <i class=\"fas fa-calendar-alt fa-fw \"></i>\r\n\r\n        </div>\r\n\r\n\r\n    </div>\r\n");


    if (viewType != null && !"M".equals(viewType)) {
        // choose time setting

      out.write("<div>\r\n        <select title=\"");
      out.print(bundle.getString("accessibility_timeUnit"));
      out.write("\" onchange=\"updateConfig('timeSplit',this.options[this.selectedIndex].value,false,true,false,null,'0.5');\">\r\n            <option ");
      out.print("1".equals(timeSplit) ? "selected='selected'" : "");
      out.write(" value='1'>");
      out.print(bundle.getString("report_oneHourUnit"));
      out.write("</option>\r\n            <option ");
      out.print("0.5".equals(timeSplit) ? "selected='selected'" : "");
      out.write(" value='0.5'>");
      out.print(bundle.getString("report_thirtyMinutesUnit"));
      out.write("</option>\r\n            <option ");
      out.print("0.25".equals(timeSplit) ? "selected='selected'" : "");
      out.write(" value='0.25'>");
      out.print(bundle.getString("report_fifteenMinutesUnit"));
      out.write("</option>\r\n        </select>\r\n");

        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");
        Calendar calendar = Calendar.getInstance();

        float _ts = Float.parseFloat(timeSplit), _init_time = Float.parseFloat(timeViewInitTime), _end_time = Float.parseFloat(timeViewEndTime);

      out.write("<select title=\"");
      out.print(bundle.getString("accessibility_startTime"));
      out.write("\" onchange=\"updateConfig('timeViewInitTime',this.options[this.selectedIndex].value,false,true,false,null,'6.0');\">\r\n");

        float count = 0, duration = (_end_time - 0f) / _ts, accumulatedVal = 0f;
        for (; count < duration; count++) {
            calendar.set(Calendar.HOUR_OF_DAY, Double.valueOf(Math.floor(accumulatedVal)).intValue());
            calendar.set(Calendar.MINUTE, Double.valueOf(60 * (accumulatedVal % 1f)).intValue());

      out.write("<option ");
      out.print(_init_time == accumulatedVal ? "selected='selected'" : "");
      out.write(" value='");
      out.print(accumulatedVal);
      out.write('\'');
      out.write('>');
      out.print(sdf.format(calendar.getTime()));
      out.write("</option>\r\n");

            accumulatedVal += _ts;
        }

      out.write("</select> ~\r\n        <select title=\"");
      out.print(bundle.getString("accessibility_endTime"));
      out.write("\" onchange=\"updateConfig('timeViewEndTime',this.options[this.selectedIndex].value,false,true,false,null,'20.0');\">\r\n");

        count = 0;
        duration = (24f - _init_time) / _ts;
        accumulatedVal = _init_time;
        for (; count < duration; count++) {
            accumulatedVal += _ts;
            calendar.set(Calendar.HOUR_OF_DAY, Double.valueOf(Math.floor(accumulatedVal)).intValue());
            calendar.set(Calendar.MINUTE, Double.valueOf(60 * (accumulatedVal % 1f)).intValue());

      out.write("<option ");
      out.print(_end_time == accumulatedVal ? "selected='selected'" : "");
      out.write(" value='");
      out.print(accumulatedVal);
      out.write('\'');
      out.write('>');
      out.print(sdf.format(calendar.getTime()));
      out.write("</option>\r\n");

        }

      out.write("</select>\r\n        ");
 if(!timeSplit.equals("1")){ 
      out.write("<input id=\"showTimelinesCheckBox\" style=\"margin-left: 20px;vertical-align: middle\" onclick=\"showTimeLines()\" type=\"checkbox\" ");
      out.print(showTimelines?"checked":"");
      out.write(">\r\n        <label for=\"showTimelinesCheckBox\">");
      out.print(bundle.getString("showCalendarTimeLine"));
      out.write("</label>\r\n        ");
 } 
      out.write("</div>\r\n");

    }

      out.write("</div>\r\n<div id=\"eventCalendar\" style=\"");
      out.print(!fontFamily.equals("")?"font-family: "+fontFamily+";":"");
      out.write(" margin: ");
      out.print(boundaryMargin);
      out.write(";\"></div>\r\n\r\n<script>\r\n    function showTimeLines() {\r\n        var showTimelinesCheckbox = document.getElementById(\"showTimelinesCheckBox\");\r\n        var checked = showTimelinesCheckbox.checked;\r\n        updateConfig(\"showTimelines\",checked?\"true\":\"false\", false, true, false, null, false);\r\n    }\r\n    function dateEqual(d1,d2){\r\n        if(d1.getFullYear()!=d2.getFullYear()||d1.getMonth()!=d2.getMonth()||d1.getDate()!=d2.getDate()){\r\n            return false;\r\n        }else{\r\n            return true;\r\n        }\r\n    }\r\n    function getDateText(d){\r\n        return d.getFullYear()+\"/\"+(d.getMonth()+1)+\"/\"+d.getDate();\r\n\r\n    }\r\n\r\n    function checkChosenDateFormat(){\r\n        var d=new Date(document.getElementById('calendarFocusDate').value);\r\n\r\n        if(d!= \"Invalid Date\" && !isNaN(d)){\r\n            updateConfig('chosenFocusDate',d,false,true,false,null);\r\n        }\r\n        //日期格式不對，用公司設定的日期格式試試\r\n        else {\r\n            getPromise('/sims/report/templates/ragic/calendar/calendar_helper.jsp',\r\n                {'a':'");
      out.print(apname);
      out.write("', 'action': \"dateFormat\", 'format':'");
      out.print(defaultDateFormat);
      out.write("','d':document.getElementById('calendarFocusDate').value }\r\n            ).then(function(response) {\r\n                if(response!=null ||response!==\"\"){\r\n                    d=new Date(response);\r\n                }\r\n                if(d!= \"Invalid Date\" && !isNaN(d)){\r\n                    updateConfig('chosenFocusDate',d,false,true,false,null);\r\n                }else {\r\n                    document.getElementById('calendarFocusDate').value = \"\";\r\n                    alert(lm[\"calendar_errorMsg_timeFormat\"]);\r\n                }\r\n            });\r\n\r\n        }\r\n        //updateConfig('chosenFocusDate',document.getElementById('calendarFocusDate').value,false,true,false,null);\r\n\r\n    }\r\n\r\n\r\n</script>\r\n\r\n<script>\r\n    //決定是否再\"選擇指定時間\"的欄位顯示時間，當天 ->不顯示\r\n    if(!dateEqual(new Date(\"");
      out.print(today);
      out.write("\"),chosenFocusDate)){\r\n        document.getElementById(\"calendarFocusDate\").value=getDateText(chosenFocusDate);\r\n    }else{\r\n        document.getElementById(\"calendarFocusDate\").value=\"\";\r\n    }\r\n</script>\r\n\r\n\r\n<style>\r\n    .EventCalendar_switch {\r\n        position: relative;\r\n        width: ");
      out.print(bundle.getLangv5().equals("en")?"140px":"120px");
      out.write(";\r\n        -webkit-user-select: none;\r\n        -moz-user-select: none;\r\n        -ms-user-select: none;\r\n        margin: 0 20px;\r\n    }\r\n    .EventCalendar_switch_switch {\r\n        display: block;\r\n        width: 18px;\r\n        margin: 6px;\r\n        background: #FFFFFF;\r\n        position: absolute;\r\n        top: 0;\r\n        bottom: 0;\r\n        right: ");
      out.print(bundle.getLangv5().equals("en")?"100px":"84px");
      out.write(";\r\n        border: 2px solid #999999;\r\n        border-radius: 20px;\r\n        transition: all 0.3s ease-in 0s;\r\n    }\r\n    .EventCalendar_switch_inner:before {\r\n        content: \"");
      out.print(bundle.getString("12HourClock"));
      out.write("\";\r\n        padding-left: 10px;\r\n        background-color: #2196f3 ;\r\n        color: #FFFFFF;\r\n    }\r\n    .EventCalendar_switch_inner:after {\r\n        content: \"");
      out.print(bundle.getString("24HourClock"));
      out.write("\";\r\n        padding-right: 10px;\r\n        background-color: #d50e0e;\r\n        color: #FFFFFF;\r\n        text-align: right;\r\n    }\r\n</style>\r\n\r\n\r\n\r\n\r\n\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
