/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2022-11-10 01:41:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sims.mmailer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ragic.s3.sdb.query.SDBNode;
import java.util.List;
import com.ragic.s3.sdb.data.bdb.BDBWorker;
import com.ragic.s3.util.*;

public final class unreg_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.ragic.s3.util");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ragic.s3.sdb.data.bdb.BDBWorker");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.ragic.s3.sdb.query.SDBNode");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;



String unregString_old = request.getParameter("u"); // Old unregString contains email of sender (should be receiver), so this is deprecated. 
if(unregString_old != null) {
    out.println("This unsubscribe link has expired.");
    return;
}
String unregString=request.getParameter("u2");
if(unregString==null) {
    out.println(1);
    return;
}
String unreg=new DES().decrypt(unregString);
if(unreg==null){
    //out.println(2);
    return;
}
String[] split=unreg.split("\\|");
if(split.length<2){
    //out.println(3);
    return;
}
String apname=split[0];
String email=split[1];
if(apname==null || apname.length()==0 || email==null || email.length()==0) {
    //out.println("5:"+unreg);
    return;
}

Log logger = Log.createStandardLog();
String action = request.getParameter("act");
boolean unregistered = false;
BDBWorker worker=new BDBWorker(apname);
logger.debug("========================");
logger.debug("action=" + action);
logger.debug("apname=" + apname);
logger.debug("email=" + email);
try{
	int nid_unregEmail = worker.getNodeId(DConst.NOTIFY_UNREGISTERED, email);
	logger.debug("nid_unregEmail=" + nid_unregEmail);
    
	if("subscribe".equals(action)) {
		if(nid_unregEmail >= 0) {
            worker.delNode(DConst.NOTIFY_UNREGISTERED, nid_unregEmail, email);
        }
	    unregistered = false;
	} else if("unsubscribe".equals(action)) {
        if(nid_unregEmail < 0) {
        	worker.addNode(DConst.NOTIFY_UNREGISTERED,email,true);
        }
		unregistered = true;
	} else {
		unregistered = nid_unregEmail >= 0;
	}
}catch(Exception e){
  out.println(6);
  return;
}
finally{
  worker.commit();    
}
logger.debug("unregistered=" + unregistered);

      out.write("<b> ");
      out.print(email);
      out.write("</b> is now ");
      out.print((unregistered?"unsubscribed":"subscribed") );
      out.write(".\r\n<a href='/sims/mmailer/unreg.jsp?u2=");
      out.print(unregString);
      out.write("&act=");
      out.print(unregistered?"subscribe":"unsubscribe");
      out.write('\'');
      out.write('>');
      out.print(unregistered?"Re-Subscribe":"Unsubscribe" );
      out.write("</a>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
