/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2022-11-10 01:41:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sims.task;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ragic.s3.nui.RagicBundle;
import com.ragic.s3.nui.User;
import com.ragic.s3.nui.helper.Encoder;
import com.ragic.s3.service.tasks.TaskList;
import com.ragic.s3.service.tasks.TaskManager;
import com.ragic.s3.nui.Account;
import java.util.List;
import java.util.Set;
import com.ragic.s3.util.Const;
import org.json.JSONObject;
import org.json.JSONArray;
import com.ragic.s3.nui.helper.Util;

public final class task_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ragic.s3.nui.Account");
    _jspx_imports_classes.add("com.ragic.s3.service.tasks.TaskManager");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("org.json.JSONObject");
    _jspx_imports_classes.add("com.ragic.s3.nui.RagicBundle");
    _jspx_imports_classes.add("com.ragic.s3.service.tasks.TaskList");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.Util");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.Encoder");
    _jspx_imports_classes.add("java.util.Set");
    _jspx_imports_classes.add("com.ragic.s3.nui.User");
    _jspx_imports_classes.add("com.ragic.s3.util.Const");
    _jspx_imports_classes.add("org.json.JSONArray");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/javascript; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;



  User user=(User)session.getAttribute("USER");
  RagicBundle bundle=(RagicBundle)session.getAttribute("RAGIC_BUNDLE");
  String apname=request.getParameter("a");
  int pageSize=Encoder.parseInt(request.getParameter("count"),20);
  int offset=Encoder.parseInt(request.getParameter("offset"),0);
  if(user==null || !user.isCanLogout() || Util.apnameArchived(apname)){
    out.println("[]");
    return;
  }
  if(user==null || !user.isValid()) return;
  if(apname!=null && apname.startsWith("Deliveree")) return;

  //todo priv check

  JSONObject result = new JSONObject();

  String assignedBy=request.getParameter("aby");
  String assignedTo=request.getParameter("ato");
  String statusFilter=request.getParameter("type");//null is fine, no filter
  boolean assignChange=assignedBy!=null || assignedTo!=null;
  if(assignChange){
    session.setAttribute("TASK_ASSIGNED_BY",assignedBy);
    session.setAttribute("TASK_ASSIGNED_TO",assignedTo);
  } else {
  	assignedBy = (String) session.getAttribute("TASK_ASSIGNED_BY");
  	assignedTo = (String) session.getAttribute("TASK_ASSIGNED_TO");
  }

  JSONObject taskFilter = new JSONObject();
  taskFilter.put("aby", session.getAttribute("TASK_ASSIGNED_BY"));
  taskFilter.put("ato", session.getAttribute("TASK_ASSIGNED_TO"));
  result.put("taskFilter", taskFilter);

  if(statusFilter!=null) {
    if("CLEAR".equals(statusFilter)) session.removeAttribute("TASK_STATUS_FILTER");
    else session.setAttribute("TASK_STATUS_FILTER",statusFilter);
  }

  String globalTaskApname=user.getGlobalTaskApname();




  TaskList list=null;

  if(assignedBy!=null){
    list=new TaskManager(apname).getTaskByAssignBy(assignedBy,bundle,statusFilter);
    if(globalTaskApname!=null && !globalTaskApname.equals(apname)) list.add(new TaskManager(globalTaskApname).getTaskByAssignBy(assignedBy,bundle,statusFilter));
  }
  else if("MyTeam".equals(assignedTo)){
    Set<String> teamEmail=Account.getInstance(apname).getTeamMemberEmail(user.getUserId());
    list=new TaskManager(apname).getTaskByAssignTo(teamEmail,bundle,statusFilter);
    if(globalTaskApname!=null && !globalTaskApname.equals(apname)) list.add(new TaskManager(globalTaskApname).getTaskByAssignTo(teamEmail,bundle,statusFilter));
  }
  else if(assignedTo!=null){
    list=new TaskManager(apname).getTaskByAssignTo(assignedTo,bundle,statusFilter);
    if(globalTaskApname!=null && !globalTaskApname.equals(apname)) list.add(new TaskManager(globalTaskApname).getTaskByAssignTo(assignedTo,bundle,statusFilter));
  }
  else{
    list=new TaskManager(apname).getTaskByAssignTo(user.getUserId(),bundle,statusFilter);
    if(globalTaskApname!=null && !globalTaskApname.equals(apname)) list.add(new TaskManager(globalTaskApname).getTaskByAssignTo(user.getUserId(),bundle,statusFilter));
  }

  if(list != null) {
  	result.put("tasks", list.getJSON(bundle,false,offset,pageSize));
  } else {
  	result.put("tasks", new JSONArray());
  }

    out.println(result.toString());


    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
