/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2022-11-10 01:41:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sims.report.templates;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ragic.s3.nui.*;
import com.ragic.s3.nui.helper.*;
import com.ragic.s3.sdb.data.bdb.BDBWorker;
import com.ragic.s3.sdb.query.SDBNode;
import com.ragic.s3.service.api.APIQuery;
import com.ragic.s3.service.report.Report;
import com.ragic.s3.service.report.grouping.*;
import com.ragic.s3.util.*;
import com.ragic.s3.util.Util;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.nio.file.Paths;
import java.time.Instant;
import java.util.*;
import org.json.JSONObject;
import org.json.JSONException;

public final class display_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


  private static final int CONFIG_MODE_LIMIT_SIZE = 10000;
  private static final List<String> NO_CONFIG_MODE_TYPES = Collections.unmodifiableList(Arrays.asList("todo","gantt","estactual","basic","kanban", "grouping"));
  private static final List<String> FIXED_AREA_TYPES = Collections.unmodifiableList(Arrays.asList("ragic/gantt","ragic/kanban","ragic/userStatus","ragic/grouping"));
  //will be removed after all type id fixed
  private boolean checkIfPDFDownloadSupported(Report report) {
    String type = report.getType();

    if("ragic/map".equals(type) || "ragic/calendar".equals(type)) {
      return false;
    }
    return true;
  }

  // 一個 AP 同一時間只能跑一張報表，預約報表例外
  private boolean isRunningRestrict(Report report) {
      String type = report.getType();
      if ("ragic/reservation".equals(type)) {
          return false;
      }
      return true;
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.ragic.s3.nui");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.ragic.s3.util");
    _jspx_imports_packages.add("com.ragic.s3.nui.helper");
    _jspx_imports_packages.add("com.ragic.s3.service.report.grouping");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ragic.s3.sdb.data.bdb.BDBWorker");
    _jspx_imports_classes.add("com.ragic.s3.service.report.Report");
    _jspx_imports_classes.add("com.ragic.s3.service.api.APIQuery");
    _jspx_imports_classes.add("org.json.JSONException");
    _jspx_imports_classes.add("com.ragic.s3.util.Util");
    _jspx_imports_classes.add("org.json.JSONObject");
    _jspx_imports_classes.add("java.nio.file.Paths");
    _jspx_imports_classes.add("com.ragic.s3.sdb.query.SDBNode");
    _jspx_imports_classes.add("java.io.BufferedReader");
    _jspx_imports_classes.add("java.io.FileInputStream");
    _jspx_imports_classes.add("java.time.Instant");
    _jspx_imports_classes.add("java.io.InputStreamReader");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


  RequestParam rp=(RequestParam) request.getAttribute("REQ");
  if(rp == null) {
      out.println("Error: request param not found.");
      return;
  }
  String apname = rp.getApname();
  String type = request.getParameter("type");
  if(type != null) {
      type = Encoder.sanitizeHTML(type);
      if(type.contains("..")) return;
  }
  String dataSource = request.getParameter("dataSource");
  User user = (User)session.getAttribute("USER");
  RagicBundle bundle = (RagicBundle) session.getAttribute("RAGIC_BUNDLE");
  LongTermTask ltt = null;
  boolean otherReportIsRunning = false;
  boolean isRunningRestrictedReport = true;
  try {
    int id = Encoder.parseInt(request.getParameter("id"), -1);
    boolean newReport = id == -1;
    boolean newWindow = request.getParameter("newwin") != null;//友善列印
    boolean reportWebview = request.getParameter("reportwv") != null;
    boolean isViewMode = request.getParameter("viewMode") != null;
    boolean isConfigMode = request.getParameter("configMode") != null;
    boolean setQueryString = request.getParameter("setQueryString") != null;
    boolean ifInline = request.getParameter("inline") != null;
    boolean ifPDFDownload = request.getParameter("pjs") != null;
    String lang = request.getParameter("lang");
    if(lang != null) {
        //used by mobile
        bundle = Util.getBundleByLang(lang);
        session.setAttribute("RAGIC_BUNDLE", bundle);
    }
    String tabPath = request.getParameter("tabPath");
    //used for pdf download
    HttpSession psSession = null;
    if (request.getParameter("pssid") != null) {
      psSession = SessionRegistry.getInstance().getSession(request.getParameter("pssid"));
      if (psSession != null) {
        request.setAttribute("psSession", psSession);
        bundle = (RagicBundle) psSession.getAttribute("RAGIC_BUNDLE");
        user = (User) psSession.getAttribute("USER");
      }
    }

    //retrieve the json for this report
    Report r;
    Report unsavedReport = null;

    if (psSession != null) {
      unsavedReport = (Report) psSession.getAttribute("UNSAVED_REPORT" + apname);
    } else {
      unsavedReport=(Report)session.getAttribute("UNSAVED_REPORT"+apname);
    }

    String reportNameTmp = "";
    if(!newReport){
        reportNameTmp = Account.getInstance(apname).getReportConfig().getReport(id).getName();
    }

    if (unsavedReport == null) {
      if (newReport) {
        unsavedReport = new Report("", type);
        unsavedReport.setDataSource(dataSource);
      } else {
        unsavedReport = Account.getInstance(apname).getReportConfig().getReport(id);
        if (unsavedReport == null) {
          out.println("No such report id:" + id);
          return;
        }
      }
    } else if (unsavedReport != null && !newReport) {
        String changedUnsaved = unsavedReport.getValue("changed");
        /*
        * 已經存過的報表
        *
        * unsavedReport.getId() != id :
        * 1) 打開另一個報表
        * 2) 同一張報表，使用 resetConfig 重整報表，unsavedReport.getId() 為 -1
        *
        * unsavedReport.getId() == id && (changedUnsaved == null || changedUnsaved.isEmpty) :
        * 1) 同一張報表，而且沒有尚未儲存的設定
        *
        * 符合上述任一條件，就要取用 singleton 的報表，因為可能別的使用者已經儲存過，這個報表有最新儲存的設定 [Bug id: #14365]
        * */
        if (unsavedReport.getId() != id || changedUnsaved == null || changedUnsaved.isEmpty()) {
            unsavedReport = Account.getInstance(apname).getReportConfig().getReport(id);
            if (unsavedReport == null) {
                out.println("No such report id:" + id);
                return;
            }
        }
    } else if (type != null && dataSource != null &&
            (!unsavedReport.getType().equals(type) || !unsavedReport.getDataSource().equals(dataSource) || (newReport && unsavedReport.getId() != -1))) {
      unsavedReport = new Report("", type);
      unsavedReport.setDataSource(dataSource);
    }

    isRunningRestrictedReport = (unsavedReport != null && isRunningRestrict(unsavedReport));

    // [Bug issue #15336] 將預約報表排除於同時執行的限制
    if (isRunningRestrictedReport) {
        //make sure only one executed for one AP
        long now = Instant.now().toEpochMilli();
        String startedTimeLong = SystemCache.getInstance().get("REPORT_START" + apname);

        if (startedTimeLong != null) {
            long startedTime = Encoder.parseLong(startedTimeLong);
            long diff = (now - startedTime) / (1000 * 60);
            out.println("<div style='padding:40px 0 0 40px;'>You already have a report running " + diff + " minutes ago, please wait for it to finish.<br><br>" +
                    "<a href='javascript:history.back()'>" + bundle.getString("goBack") + "</a></div>");
            otherReportIsRunning = true;
            return;
        } else {
            SystemCache.getInstance().put("REPORT_START" + apname, "" + now);
        }
    }

    session.setAttribute("UNSAVED_REPORT" + apname, unsavedReport);
    ltt= ThreadManager.getInstance().addTask(Thread.currentThread(),apname,unsavedReport.getType()+" Report on "+unsavedReport.getDataSource()+" by "+user.getUserId());
    unsavedReport.initChanged();

    boolean isChanged = false;
    boolean isShowTitle = true;
    boolean isShowDataSource = true;
    boolean isShowBorder = true;
    boolean isShowA4Block = false;
    boolean isOneLabelOnePage = false;
    boolean showResetDefaultMarginBtn = false;
    boolean showResetDefaultOutMarginBtn = false;
    boolean unifyFontFamily = false;

    //fontsize, fontfamily and boundary margin
    String nff="", nfs="24",nAlign="left",
          desff="", desfs="16", desAlign="left", desAlignFlex="",
          dsff="", dsfs="12", dsAlign="flex-start",
          cntff="",cntfs="1",
          boundaryType="in", bw="0.5,0,0.5,1", outbw="0.5,0.7,0.5,0.7",
              //for onlineReport
           margins = "ragic/userStatus".equals(unsavedReport.getType()) ? "0, 0, 0, 0" :"0.5,1,0.5,1"
           , outMargins= "0.5,0.7,0.5,0.7";


    String styleParams = unsavedReport.getValue("styleParams");
    String changed = unsavedReport.getValue("changed");
    String desc = unsavedReport.getValue("desc")!=null ? Encoder.encjs(unsavedReport.getValue("desc")) : "";
    String desc_width = unsavedReport.getValue("desc_width");

    if(changed != null) isChanged = !unsavedReport.getValue("changed").equals("");
    if(styleParams != null) {
      try {
          JSONObject styleParamsJSON = new JSONObject(styleParams);

          if (styleParamsJSON != null) {
              nff = styleParamsJSON.optString("name_reportFontFamily");
              nfs = styleParamsJSON.optString("name_reportFontSize");
              nAlign = styleParamsJSON.optString("name_align", "left");
              unifyFontFamily = Boolean.parseBoolean(styleParamsJSON.optString("unifyFontFamily"));

              desff = styleParamsJSON.optString("des_reportFontFamily");
              desfs = styleParamsJSON.optString("des_reportFontSize");
              desAlign = styleParamsJSON.optString("des_align", "left");

              dsff = styleParamsJSON.optString("ds_reportFontFamily");
              dsfs = styleParamsJSON.optString("ds_reportFontSize");
              dsAlign = styleParamsJSON.optString("ds_align", "flex-start");

              cntff = styleParamsJSON.optString("cnt_reportFontFamily");
              cntfs = styleParamsJSON.optString("cnt_reportFontSize", "1");

              boundaryType = styleParamsJSON.optString("boundaryType", "in");
              bw = styleParamsJSON.optString("boundaryWidth", "0.5,0,0.5,1");
              outbw = styleParamsJSON.optString("outBoundaryWidth", "0.5,0.7,0.5,0.7");
              margins = styleParamsJSON.optString("boundaryMargins", "0.5,1,0.5,1");
              outMargins = styleParamsJSON.optString("outBoundaryMargins", "0.5,0.7,0.5,0.7");

              showResetDefaultMarginBtn = Boolean.parseBoolean(styleParamsJSON.optString("showResetDefaultMarginBtn"));
              showResetDefaultOutMarginBtn = Boolean.parseBoolean(styleParamsJSON.optString("showResetDefaultOutMarginBtn"));

              isShowTitle = Boolean.parseBoolean(styleParamsJSON.optString("isShowTitle"));
              if(styleParamsJSON.optString("isShowDataSource").equals("")){
                  isShowDataSource = isShowTitle;
              }
              else{
                  isShowDataSource = Boolean.parseBoolean(styleParamsJSON.optString("isShowDataSource"));
              }
              isShowBorder = Boolean.parseBoolean(styleParamsJSON.optString("isShowBorder"));
              isShowA4Block = Boolean.parseBoolean(styleParamsJSON.optString("isShowA4Block"));
              isOneLabelOnePage = Boolean.parseBoolean(styleParamsJSON.optString("isOneLabelOnePage"));
          }
      }catch (JSONException e){
          ExceptionManager.getInstance().processException(e);
      }
    }else{
        //Compatability with old keys in report.json
        isShowTitle = !Boolean.parseBoolean(unsavedReport.getValue("hideTitle"));
        isShowDataSource = isShowTitle;
        isShowBorder = !Boolean.parseBoolean(unsavedReport.getValue("hideBorder"));
        isShowA4Block = Boolean.parseBoolean(unsavedReport.getValue("showA4Block"));
        isOneLabelOnePage = Boolean.parseBoolean(unsavedReport.getValue("isOneLabelOnePage"));
    }

    if(desAlign.equals("left")) desAlignFlex = "flex-start";
    else if(desAlign.equals("right")) desAlignFlex = "flex-end";
    else desAlignFlex = "center";

    String[] marginsArr = margins.split(",");
    String[] outMarginsArr = outMargins.split(",");
    String margin = marginsArr[0] + "cm " + marginsArr[1] + "cm " + marginsArr[2] + "cm " + marginsArr[3] + "cm";
    String outMargin = outMarginsArr[0] + "cm " + outMarginsArr[1] + "cm " + outMarginsArr[2] + "cm " + outMarginsArr[3] + "cm";

    String reportFilters = unsavedReport.getValue("filter");

    int appliedView = -1;
    int appliedView2 = -1;
    Map<Integer, NUIFilterSet> views = null;
    Map<Integer, NUIFilterSet> views2 = null;
    APIQuery aq = null;
    APIQuery aq2 = null;
    NUIForm form = null;
    NUIForm form2 = null;
    boolean getAllData = unsavedReport.getType().equals("ragic/reservation");
    boolean ifAccountingReport = false;
    if(!unsavedReport.isNoDataSource()) {
    	//prepare APIQuery to do the main query
        aq = new APIQuery(apname, unsavedReport.getDataSourcePath(), unsavedReport.getDataSourceSheetIndex());
        aq.setMaxRetrieveFieldSize(65535);
        aq.setIfEidNaming(true);
        aq.setIfIncludeInfo(true);
        aq.setUser(getAllData ? new UserSuper("") : user);
        aq.setBundle(bundle);
        form = aq.getForm();
        
        if (!unsavedReport.getDataSource2().equals("")) {
          String reportType = unsavedReport.getType();
          ifAccountingReport = "fixed/balanceSimple".equals(reportType) || "fixed/balance".equals(reportType) || "fixed/profitnlossSimple".equals(reportType) ||
                  "fixed/profitnloss".equals(reportType) || "fixed/cashflowSimple".equals(reportType) || "fixed/cashflow".equals(reportType);
          aq2 = new APIQuery(apname, unsavedReport.getDataSourcePath2(), unsavedReport.getDataSourceSheetIndex2());
          aq2.setMaxRetrieveFieldSize(65535);
          aq2.setIfEidNaming(true);
          aq2.setIfIncludeInfo(true);
          aq2.setUser(user);
          aq2.setBundle(bundle);
          form2 = aq2.getForm();
        }

        if (form == null) {
          out.println("The source data form has been deleted.");
          return;
        }

        boolean ifRagicReport = unsavedReport.getType().contains("ragic/");
//        if (ifRagicReport &&
//                form.getNumberOfEntries() > CONFIG_MODE_LIMIT_SIZE &&
//                !NO_CONFIG_MODE_TYPES.contains(unsavedReport.getType().substring(unsavedReport.getType().indexOf("ragic/") + 6))) {
//          isConfigMode = true;
//        }
//
//        if (isViewMode) {
//          isConfigMode = false;
//        }

//        if (isConfigMode) {
//          aq.setLimitSize(CONFIG_MODE_LIMIT_SIZE);
//        }

        if (form.checkRight(user) < Const.USER && reportWebview) {
            String qs = request.getQueryString();
            RagicConfig rc = RagicConfig.getInstance();
            String protocol = Util.getServerProtocol(rc);
            String serverName = Util.getServerNameWithPort(rc);
            StringJoiner urlQueryStr = new StringJoiner("&");
            if(qs != null) urlQueryStr.add(qs);
            if(reportWebview) urlQueryStr.add("embed");
            out.println("<script>location='" + protocol + "://" + serverName + "/sims/reg/login.jsp?" + (reportWebview ? "embed&" : "") +
                    "url=" + Encoder.utf8URL(protocol + "://" + serverName + "/" + apname + "/report/display" + (urlQueryStr.length() != 0 ? "?" : "") + urlQueryStr.toString()) + "'</script>");
            return;
        }
        boolean isManager = user.ifApManager(apname, form.getPath()) || (form2 != null && user.ifApManager(apname, form2.getPath()));
        UserFeatureAccessModule modules = UserFeatureAccessModule.configureUserAccessModule(session,apname,user);
        if (form.checkRight(user) < Const.USER && (form2 == null || form2.checkRight(user) < Const.USER) || (!isManager && !modules.ifAllow(Const.FUNC_VIEW_REPORT))) {
            out.println(bundle.getString("noAccessRight"));
            return;
        }

        NUIForm listingPage = AppManager.getListingPage(apname, form.getPath(), form.getFormName());
        NUIForm listingPage2 = null;
        if (form2 != null) listingPage2 = AppManager.getListingPage(apname, form2.getPath(), form2.getFormName());

        //help gather filter string
        Map<String, String[]> param = request.getParameterMap();

        if (newWindow || !(setQueryString || newReport)) {
          if(psSession != null && psSession.getAttribute("TEMP_PARAM") != null) {
            param = (Map<String, String[]>) psSession.getAttribute("TEMP_PARAM");
          } else if (session.getAttribute("TEMP_PARAM") != null) {
            param = (Map<String, String[]>) session.getAttribute("TEMP_PARAM");
          }
        } else {
          session.setAttribute("TEMP_PARAM", param);//for printer friendly mode and pdf download
        }

        List<String> filterv2 = new ArrayList<>();
        if (param != null) {
          for (Map.Entry<String, String[]> e : param.entrySet()) {
            String filterName = e.getKey();
            String[] values = e.getValue();
            if (!filterName.startsWith("f_")) continue;

            for (String value : values) {
              if (value.length() == 0) continue;
                String filterPrefix = filterName.substring(2);
                value = Encoder.decodeURIComponent(value);
                String filterValue = Encoder.encodeSpecialSymbolToUniCode(value);
                if(filterPrefix.charAt(filterPrefix.length()-2) == (NUIFilter.OPERAND_LK+"").charAt(0) )
                    filterValue = "\\Q" + filterValue + "\\E";
                filterv2.add(filterName.substring(2) + filterValue);
            }
          }
        }

        //view
        appliedView = Encoder.parseInt(unsavedReport.getValue("view"), -1);
        views = listingPage.getDesignerFilterSet();
        if (appliedView >= 0 && views.containsKey(appliedView)) {
          NUIFilterSet fs = views.get(appliedView);
          for (NUIFilter f : fs.getFilters()) {
            Collections.addAll(filterv2, f.getFilterV2String());
          }
        }
        
        appliedView2 = Encoder.parseInt(unsavedReport.getValue("view2"), -1);
        List<String> filterv2_2 = new ArrayList<>();
        if (listingPage2 != null) {
          views2 = listingPage2.getDesignerFilterSet();
        }
        if (appliedView2 >= 0 && views2 != null && views2.containsKey(appliedView2)) {
          NUIFilterSet fs = views2.get(appliedView2);
          for (NUIFilter f : fs.getFilters()) {
            Collections.addAll(filterv2_2, f.getFilterV2String());
          }
        }

        //filter
        String[] filterv2Array = filterv2.toArray(new String[filterv2.size()]);
        if (filterv2Array != null && filterv2Array.length > 0) aq.setFiltersStringV2(filterv2Array);
        String[] filterv2Array2 = filterv2_2.toArray(new String[filterv2_2.size()]);
        if (filterv2Array2 != null && filterv2Array2.length > 0) aq2.setFiltersStringV2(filterv2Array2);

        //get current form filter status if no other filter active
        if (aq.getFilters().size() == 0) {
          //apply filter
          NUIFormSet set;
          if(psSession != null) {
            set = NUIFormSetInfo.loadBrowsingFormSet(psSession, apname, aq.getPath(), aq.getForm().getFormName());
          } else {
            set = NUIFormSetInfo.loadBrowsingFormSet(session, apname, aq.getPath(), aq.getForm().getFormName());
          }

          List<NUIFilter> filters = set.getCurrentFilter();
          for (NUIFilter filter : filters) {
            if (!filter.isFixed()) aq.addFilter(filter.getDomainId(), filter);
          }

        }


        //add fetch domain for filters
    //  Set<Integer> filterDomains=aq.getFilters_old().keySet();
    //  for(Integer filterDomain:filterDomains){
//        if(filterDomain==null) continue;
//        aq.addFetchDomains(filterDomain.intValue());
    //  }


        request.setAttribute("REPORT_APIQUERY", aq);
        request.setAttribute("REPORT_APIQUERY2", aq2);
    }
    if (newWindow) {
      out.println("<style>#v5Header,.printHide,#reportConfig{display:none;}#v5Content{padding:0}.EventCalendar_Day_Today{border:none;}.EventCalendar_Time_Today{background-color:transparent;}.EventCalendar_Evt_Hide{display: block;}</style>");
    }
    if (reportWebview) {
      out.println("<style>.webViewHide{display:none;}#v5Header{display:none;}#v5Content{padding:0}.EventCalendar_Day_Today{border:none;}.EventCalendar_Time_Today{background-color:transparent;}.EventCalendar_Evt_Hide{display: block;}</style>");
    }
    if (ifInline) {
      out.println("<style>#ragicload{display:none !important;}#serviceLoadingAJAXTOP{display:none;}#stpDiv{display:none;}#hin{display:none;}");
      //read system.css and v5frame.css
      try (BufferedReader br = new BufferedReader(new InputStreamReader(new FileInputStream(Paths.get("web", "sims", "css", "system.css").toFile())))) {
        String line;
        while ((line = br.readLine()) != null) {
          out.println(line);
        }
      } catch (Exception e) {
          ExceptionManager.getInstance().processException(e);
      }

      try (BufferedReader br = new BufferedReader(new InputStreamReader(new FileInputStream(Paths.get("web", "sims", "css", "v5frame.css").toFile())))) {
        String line;
        while ((line = br.readLine()) != null) {
          out.println(line);
        }
      } catch (Exception e) {
          ExceptionManager.getInstance().processException(e);
      }

      out.println("</style>");
    }
    String datasource = "";
    if(form != null) datasource = Encoder.encodeURIComponent(form.getRealname() + (form2!=null?form2.getRealname():""));
    
    //[issue:10840, 12088] we have to adjust DOM and CSS styles so horizontal scrollbar of particular reports can always show in visible area
    boolean ifReportFixedArea = FIXED_AREA_TYPES.contains(unsavedReport.getType());

 if (ifReportFixedArea) { 
      out.write("<div id=\"reportOuterContainer\" class=\"reportOuterContainer reportFixedArea");
      out.print(ifPDFDownload?" pdfDownload":"");
      out.write("\">\r\n");
 } 
      out.write("<div class=\"reportIconHeaderContainer printHide\">\r\n    <div class=\"reportIconHeader\">\r\n        <a id=\"discardChanges\" class=\"printHide\" style=\"display: ");
      out.print(isChanged && !reportWebview?"flex":"none");
      out.write(";\" href=\"javascript:void(0)\" onclick=\"resetReportConfig();\" onmouseover=\"tooltipTiny(this,'");
      out.print(bundle.getString("discardChanges"));
      out.write("');\"\r\n           onmouseleave=\"hideTinyTooltip();\"><img style=\"width:20px; height: 20px;\" src=\"/sims/img/return-arrow.png\"></a>\r\n        ");
 if(views!=null && views.size()>0 && !ifAccountingReport){
                out.print("<select  title='"+bundle.getString("applyView")+"' style=\"font-size:13px;color:#333;border:1px solid #CCCCCC;margin:8px 10px;\" onchange=\"updateConfig('view',this.options[this.selectedIndex].value,false,true);\">");
                out.print("<option value=''> - "+bundle.getString("applyView")+" - </option>");
                for(Map.Entry<Integer,NUIFilterSet> e:views.entrySet()){
                    Integer viewId=e.getKey();
                    if(viewId==null) continue;
                    NUIFilterSet fs=e.getValue();
                    out.print("<option value='"+(viewId!=null?viewId.toString():"")+"' "+(viewId==appliedView?"selected":"")+">"+fs.getName()+"</option>");
                }
                out.print("</select>");
           }
           if(views2!=null && views2.size()>0 && ifAccountingReport){
                out.print("<select title='"+bundle.getString("applyView")+"' style=\"font-size:13px;color:#333;border:1px solid #CCCCCC;margin:8px 10px;\" onchange=\"updateConfig('view2',this.options[this.selectedIndex].value,false,true);\">");
                out.print("<option value=''> - "+bundle.getString("applyView")+" - </option>");
                for(Map.Entry<Integer,NUIFilterSet> e:views2.entrySet()){
                    Integer viewId=e.getKey();
                    if(viewId==null) continue;
                    NUIFilterSet fs=e.getValue();
                    out.print("<option value='"+(viewId!=null?viewId.toString():"")+"' "+(viewId==appliedView2?"selected":"")+">"+fs.getName()+"</option>");
                }
                out.print("</select>");
           }
           if(!reportWebview) {
               if(user.ifApManager(apname, unsavedReport.getDataSourcePath())) { 
      out.write("<a id=\"reportSave\" class=\"printHide\" href=\"javascript:void(0)\" onclick=\"saveReport()\" onmouseover=\"tooltipTiny(this,'");
      out.print(bundle.getString("save"));
      out.write("');\"\r\n           onmouseleave=\"hideTinyTooltip();\"><i class=\"fas fa-save\"></i></a>\r\n            ");
 } 
      out.write("<a href=\"javascript:void(0)\" onclick=\"dropWin(this,$('settings'), true);\"><i class=\"fa fa-ellipsis-v\"></i></a>\r\n        ");
 } 
      out.write("</div>\r\n</div>\r\n\r\n<div id=\"settings\" class=\"dropdownToolbar\" style=\"display: none\">\r\n    <div onclick=\"openStyleConfig()\">\r\n        <div class=\"settingIcons\">\r\n            <i class=\"fas fa-pen\"></i>\r\n        </div>\r\n        <span>");
      out.print(bundle.getString("styleConfig"));
      out.write("</span>\r\n    </div>\r\n    ");
if (!reportWebview) {
      out.write("<div style=\"color:#333;\" onclick=\"showFloatingMain('mfEmbed','/sims/webview/config/report_index.jsp?url=");
      out.print(Util.getServerNameWithPort()+"/"+apname+"/report/display");
      out.print((newReport?"":"&id="+id));
      out.print(isViewMode?"&viewMode":"");
      out.print(isConfigMode?"&configMode":"");
      out.write("','embedConfigIframe');\">\r\n        <div class=\"settingIcons\">\r\n            <i class=\"fa fa-code\"></i>\r\n        </div>\r\n        <span>");
      out.print(bundle.getString("embedReport"));
      out.write("</span>\r\n    </div>\r\n    ");
}
 if(unsavedReport!=null && checkIfPDFDownloadSupported(unsavedReport)) {
      out.write("<div style=\"color:#333;\" onclick=\"downloadPDF(true);\">\r\n        <div class=\"settingIcons\">\r\n            <i class=\"fas fa-file-pdf\"></i>\r\n        </div>\r\n        <span>");
      out.print(bundle.getString("downloadPDF"));
      out.write("</span>\r\n    </div>\r\n    ");
 } 
      out.write("<!-- if report is calendar when printFirendly need to get report focus time which may not save to reportConfig-->\r\n    ");
if(unsavedReport.getType().equals("ragic/calendar")){
      out.write("<div onclick=\"calendarReportPrintFriendly()\">\r\n        <div class=\"settingIcons\">\r\n            <i class=\"fa fa-print\"></i>\r\n        </div>\r\n        <span>");
      out.print(bundle.getString("printerFriendly"));
      out.write("</span>\r\n    </div>\r\n    ");
}else{
      out.write("<div onclick=\"window.open('/");
      out.print(apname);
      out.write("/report/display?newwin");
      out.print((newReport?"":"&id="+id));
      out.print(isViewMode?"&viewMode":"");
      out.print(isConfigMode?"&configMode":"");
      out.write("', '_blank')\">\r\n        <div class=\"settingIcons\">\r\n            <i class=\"fa fa-print\"></i>\r\n        </div>\r\n        <span>");
      out.print(bundle.getString("printerFriendly"));
      out.write("</span>\r\n    </div>\r\n    ");
}
 if(user.ifApManager(apname)){ 
      out.write("<div onclick=\"saveAsReport()\">\r\n        <div class=\"settingIcons\"></div>\r\n        <span>");
      out.print(bundle.getString("saveAsNew"));
      out.write(" ...</span>\r\n    </div>\r\n    ");
 } 
      out.write("</div>\r\n<div style=\"display: flex; clear: both;\">\r\n<div id=\"report\" style=\"");
      out.print(newWindow?"overflow-x: visible":"");
      out.write("\">\r\n    ");
      out.write("<div class=\"reportHeader ");
      out.print(!isShowTitle?"hideTitle ":"");
      out.print(!isShowDataSource?"hideDataSource":"");
      out.write("\">\r\n      <h2 style=\"text-align: ");
      out.print(nAlign);
      out.write("; font-weight:700;color:#333; clear: both;");
      out.print(!nff.equals("")?"font-family: "+nff+";":"");
      out.print(!nfs.equals("")?"font-size: "+nfs+"px;":"");
      out.write('"');
      out.write('>');
      out.print(Encoder.isEmptyOrWhitespaceOnly(reportNameTmp) ? unsavedReport.getName(): reportNameTmp);
      out.write("</h2>\r\n      <div style='display:none;' class='printHide' id=\"config_mode_block\">\r\n          <div id=\"config_mode\">");
      out.print(bundle.getString("config_mode"));
      out.write("</div>\r\n          <div id=\"config_mode_desc\">");
      out.print(bundle.getString("config_mode_desc"));
      out.write("</div>\r\n          <div id=\"config_mode_button\" onclick='leaveConfigMode()'>");
      out.print(bundle.getString("config_mode_button"));
      out.write("</div>\r\n      </div>\r\n      <div style=\"overflow:hidden;\">\r\n          <div style=\"display: flex; justify-content: ");
      out.print(desAlignFlex);
      out.write("\">\r\n              <div id=\"reportDesc\" style=\"");
      out.print(desc_width!=null?("width:"+desc_width+"px"):"");
      out.write(";text-align: ");
      out.print(desAlign);
      out.write(";display:none;min-width:500px;max-width:950px;margin-bottom:7px;overflow:hidden;");
      out.print(!newWindow?"resize:horizontal;":"");
      out.print(!desff.equals("")?"font-family: "+desff:"");
      out.write(';');
      out.write(' ');
      out.print(!desfs.equals("")?"font-size: "+desfs+"px":"");
      out.write("\" data-desc=\"");
      out.print(desc);
      out.write("\"></div>\r\n          </div>\r\n          <div id=\"moreDesc\" style=\"color:#0000EE;clear:left;cursor:pointer;display:none;\" onmousedown=\"moreDesc();\" onmouseover=\"this.style.textDecoration='underline';\" onmouseout=\"this.style.textDecoration='none';\">");
      out.print(bundle.getString("more"));
      out.write("</div>\r\n      </div>\r\n      <div style=\"display: flex; justify-content: ");
      out.print(dsAlign);
      out.write("\">\r\n  ");

    if(!unsavedReport.isNoDataSource()) {
        out.println("<table class='queryTable' style='font-size: "+ dsfs + "px;"+ (!dsff.equals("")?"font-family: "+dsff:"") + "'>");
        int userRight=form.checkRight(user);
        boolean surveyUser=userRight==Const.USER;
        int userRight2=form2!=null?form2.checkRight(user):Const.NORIGHT;
        boolean surveyUser2=userRight2==Const.USER;
        out.println("<tr id='periodRow' style='display:none;'><th>"+bundle.getString("period")+":</th><td id='period'></td></tr>");
        out.println("<tr><th>"+bundle.getString("dataSource")+":</th><td>"+form.getRealname()+(surveyUser?" ("+bundle.getString("partialDataReport")+")":"")
                +(form2!=null?" "+form2.getRealname()+(surveyUser2?" ("+bundle.getString("partialDataReport")+")":""):"")+"</td></tr>");
        if (!"fixed/receivable".equals(unsavedReport.getType()) && !"fixed/payable".equals(unsavedReport.getType())) {
        for(NUIFilter filter:aq.getFilters()){
          if( filter.isSorting() )continue;
          CellInfo info=form.getField(filter.getDomainId());
          if(info==null){
            CellInfo originalInfo = form.getFieldByAttribute("stf", ""+filter.getDomainId());
            // link field
            if(originalInfo!=null){
              out.println("<tr><th>"+originalInfo.getValue()+":</th><td>");
              out.println(filter.getOriginalValue());
              out.println("</td></tr>");
            }
          }
          else{
            out.print("<tr>");
            BDBWorker worker=new BDBWorker(form.getApname());
            try{
              if(info.isSelection() && info.getStf()==Const.NODOMAIN){
                out.println("<th>"+info.getValue()+":</th><td>");
                boolean first=true;
                if(filter.getOperand() != NUIFilter.OPERAND_EQN) {
                  String filterValue=filter.getOriginalValue();
                  filterValue=filterValue.replaceAll("(?<=^|\\|)\\^+\\\\Q","");
                  filterValue=filterValue.replaceAll("\\\\E\\$+(?=$|\\|)","");
                  filterValue=filterValue.replaceAll("\\|",", ");
                  out.println(filterValue);
                } else {
                  for(Integer nodeId:filter.getNodeId()){
                    Selection s= DataHelper.createOption(filter.getDomainId(),worker);
                    String optionValue=s.getValueByNodeId(nodeId);
                    if(optionValue==null) continue;
                    if(!first) out.print(", ");
                    out.println(optionValue);
                    first=false;
                  }
                }
                out.println("</td>");
              }
              else if(info.getAttribute("usrref")!=null){
                String result="";
                for(Integer nodeId:filter.getNodeId()){
                  if(nodeId==null) continue;
                  SDBNode emailNode=worker.getNode(DConst.USER_USERID_EMAIL,nodeId);
                  if(emailNode==null) continue;
                  String userName=Account.getInstance(aq.getApname()).getUserName(emailNode.getValue());
                  if(result.length()>0) result+=", ";
                  result+=userName;
                }
                out.println("<th>"+info.getValue()+":</th><td>"+result+"</td>");
              }
              else if(info.getAttribute("fmt_d")!=null){
                out.println("<th>"+info.getValue()+":</th><td>"+Encoder.noNull(filter.getLow())+" ~ "+Encoder.noNull(filter.getHi())+"</td>");
              }
              else if(info.getAttribute("fmt_n")!=null){
                out.println("<th>"+info.getValue()+":</th><td>"+Encoder.noNull(filter.getLow())+" ~ "+Encoder.noNull(filter.getHi())+"</td>");
              }
              else{
                String filterValue=Encoder.noNull(filter.getValue());
                if(filterValue.startsWith(".*") && filterValue.endsWith(".*")) filterValue=filterValue.substring(2,filterValue.length()-2);
                if(filterValue.startsWith("\\Q") && filterValue.endsWith("\\E")) filterValue=filterValue.substring(2,filterValue.length()-2);
                out.println("<th>"+info.getValue()+":</th><td>"+filterValue+"</td>");
              }
            }
            catch(Exception e){
              out.println(e.getMessage());
                ExceptionManager.getInstance().processException(e);
            }
            finally{
              worker.commit();
            }
            out.print("</tr>");
          }
        }
        }
        out.println("</table>");
    }

    String backUrl="/"+apname+"/report/query?id="+id;
    if(id==-1){
      backUrl="/"+apname+"/report?dataSource="+dataSource;
    }
    
      out.write("</div>\r\n\r\n    </div>\r\n\r\n    ");
      out.write("<div class=\"reportContent clearfix ");
      out.print(!isShowBorder?"hideBorder":"");
      out.write("\" style=\"margin: ");
      out.print(outMargin);
      out.write("\">\r\n      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, unsavedReport.getType()+"/report.jsp" + ((unsavedReport.getType()+"/report.jsp").indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("fontFamily", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(cntff), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("fontSize", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(cntfs), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("boundaryMargin", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(margin), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("isShowA4Block", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(isShowA4Block), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("isOneLabelOnePage", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(isOneLabelOnePage), request.getCharacterEncoding()), out, false);
if (!reportWebview) {
      out.write("<div class=\"printHide\">\r\n        <input type=\"button\" style=\"float:left;clear:left;margin:12px 0 25px 12px;\" onclick=\"location.href='");
      out.print(backUrl);
      out.write("';\" value=\"");
      out.print(bundle.getString("back"));
      out.write("\" />\r\n      </div>\r\n      ");
} 
      out.write("</div>\r\n</div>\r\n");
 if (ifReportFixedArea) { 
      out.write("</div>\r\n");
 } 
 if(!newWindow){ 
      out.write("<div id=\"styleSettings\">\r\n    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "reportStyleConfig.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("a", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(apname), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("id", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(id), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("ifApManager", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(user.ifApManager(apname, unsavedReport.getDataSourcePath())), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("datasource", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(datasource), request.getCharacterEncoding()), out, false);
      out.write("</div>\r\n");
 }
      out.write("</div>\r\n<script>\r\n  //default value for styleParams\r\n  let defaultStyleCache={\r\n      name_reportFontFamily: \"\",\r\n      name_reportFontSize: \"24\",\r\n      name_align: \"left\",\r\n      unifyFontFamily: \"false\",\r\n      des_reportFontFamily: \"\",\r\n      des_reportFontSize: \"16\",\r\n      des_align: \"left\",\r\n      ds_reportFontFamily: \"\",\r\n      ds_reportFontSize: \"12\",\r\n      ds_align: \"flex-start\",\r\n      cnt_reportFontFamily: \"\",\r\n      cnt_reportFontSize: \"1\",\r\n      boundaryType: \"in\",\r\n      boundaryWidth: \"0.5,0,0.5,1\",\r\n      outBoundaryWidth: \"0.5,0.7,0.5,0.7\",\r\n      boundaryMargins: \"0.5,1,0.5,1\",\r\n      outBoundaryMargins: \"0.5,0.7,0.5,0.7\",\r\n      showResetDefaultMarginBtn: \"false\",\r\n      showResetDefaultOutMarginBtn: \"false\",\r\n      isShowTitle: \"true\",\r\n      isShowDataSource: \"true\",\r\n      isShowBorder: \"true\",\r\n      isShowA4Block: \"false\",\r\n      isOneLabelOnePage: \"false\"\r\n  };\r\n  let styleCache= {\r\n    name_reportFontFamily: \"");
      out.print(nff);
      out.write("\",\r\n    name_reportFontSize: \"");
      out.print(nfs);
      out.write("\",\r\n    name_align: \"");
      out.print(nAlign);
      out.write("\",\r\n    unifyFontFamily: \"");
      out.print(unifyFontFamily);
      out.write("\",\r\n    des_reportFontFamily: \"");
      out.print(desff);
      out.write("\",\r\n    des_reportFontSize: \"");
      out.print(desfs);
      out.write("\",\r\n    des_align: \"");
      out.print(desAlign);
      out.write("\",\r\n    ds_reportFontFamily: \"");
      out.print(dsff);
      out.write("\",\r\n    ds_reportFontSize: \"");
      out.print(dsfs);
      out.write("\",\r\n    ds_align: \"");
      out.print(dsAlign);
      out.write("\",\r\n    cnt_reportFontFamily: \"");
      out.print(cntff);
      out.write("\",\r\n    cnt_reportFontSize: \"");
      out.print(cntfs);
      out.write("\",\r\n    boundaryType: \"");
      out.print(boundaryType);
      out.write("\",\r\n    boundaryWidth: \"");
      out.print(bw);
      out.write("\",\r\n    outBoundaryWidth: \"");
      out.print(outbw);
      out.write("\",\r\n    boundaryMargins: \"");
      out.print(margins);
      out.write("\",\r\n    outBoundaryMargins: \"");
      out.print(outMargins);
      out.write("\",\r\n    showResetDefaultMarginBtn: \"");
      out.print(showResetDefaultMarginBtn);
      out.write("\",\r\n    showResetDefaultOutMarginBtn: \"");
      out.print(showResetDefaultOutMarginBtn);
      out.write("\",\r\n    isShowTitle: \"");
      out.print(isShowTitle);
      out.write("\",\r\n    isShowDataSource: \"");
      out.print(isShowDataSource);
      out.write("\",\r\n    isShowBorder: \"");
      out.print(isShowBorder);
      out.write("\",\r\n    isShowA4Block: \"");
      out.print(isShowA4Block);
      out.write("\",\r\n    isOneLabelOnePage: \"");
      out.print(isOneLabelOnePage);
      out.write("\"\r\n  };\r\n  let type = '");
      out.print(unsavedReport.getType());
      out.write("'.split(\"/\")[1];\r\n  let reportFilters = \"");
      out.print(reportFilters);
      out.write("\".split(\",\");\r\n  let tableTypeMap = {}, styleConfigIsOpen = true;\r\n  const ifReportFixedArea = ");
      out.print(ifReportFixedArea);
      out.write(";\r\n\r\n  function leaveConfigMode() {\r\n      if(location.search.includes(\"&configMode\")) {\r\n          location.href = location.href.replace(/&configMode/,\"&viewMode\");\r\n      } else if(location.search.includes(\"&viewMode\")) {\r\n          location.reload();\r\n      } else {\r\n          location.href = location.href + \"&viewMode\";\r\n      }\r\n  }\r\n\r\n  function enterConfigMode() {\r\n      if(location.search.includes(\"&viewMode\")) {\r\n          location.href = location.href.replace(/&configMode/,\"&configMode\");\r\n      } else if(location.search.includes(\"&configMode\")) {\r\n          location.reload();\r\n      } else {\r\n          location.href = location.href + \"&configMode\";\r\n      }\r\n  }\r\n\r\n  function ifChangeFilter(oldFilters) {\r\n    let multiComboFormElementDiv = document.querySelector(\"#reportFilter .multiComboFormElementDiv\");\r\n    let newFilters = [\"\"];\r\n    if(multiComboFormElementDiv) {\r\n        newFilters.length = 0;\r\n        let filterCheckboxs = $$(\"input[type=checkbox]\",multiComboFormElementDiv);\r\n        filterCheckboxs.forEach(function(e) {\r\n");
      out.write("            newFilters.push(e.value);\r\n        });\r\n    }\r\n\r\n    const difference = function(arr1, arr2) {\r\n        if (arr1.length !== arr2.length) return true;\r\n\r\n        let set1, set2;\r\n        if(ctrl.isIE11) {\r\n          set1 = new Set();\r\n          set2 = new Set();\r\n          for (let i = 0, len = arr1.length; i < len; i++) {\r\n              set1.add(arr1[i]);\r\n          }\r\n          for (let i = 0, len = arr2.length; i < len; i++) {\r\n              set2.add(arr2[i]);\r\n          }\r\n        }\r\n        else{\r\n          set1 = new Set(arr1);\r\n          set2 = new Set(arr2);\r\n        }\r\n\r\n        set2.forEach(function(elem){ set1.delete(elem)});\r\n        return set1.size !== 0;\r\n    };\r\n\r\n    return difference(oldFilters, newFilters);\r\n  }\r\n\r\n  function resetReportConfig() {\r\n    getPromise('/sims/report/templates/resetConfig.jsp', {a: ap})\r\n      .then(function (resp) {\r\n        ");
if(!newWindow){
      out.write("\r\n        location.href = location.href.replace(/&configMode/,\"\").replace(/&viewMode/,\"\");\r\n        ");
} else {
      out.write("\r\n        location.reload();\r\n        ");
}
      out.write("\r\n      });\r\n  }\r\n  function saveReport() {\r\n      let nameInput = $('reportName');\r\n      if (!nameInput) {\r\n          alert(\"Cannot save because you are not SysAdmin of this account or data source's path!\");\r\n          return;\r\n      }\r\n      if(nameInput.value === \"\") {\r\n          openStyleConfig();\r\n          nameInput.style.borderColor=\"red\";\r\n          nameInput.style.outline=\"none\";\r\n          nameInput.parentNode.children[1].style.display = \"none\";\r\n          nameInput.parentNode.children[2].style.display = \"\";\r\n          $('reportName').select();\r\n          return;\r\n      }\r\n      $('desc').dataset.desc = $('reportDesc').dataset.desc = $('reportDesc').textContent;\r\n      $('des_reportFontFamily').disabled =false;\r\n      $('ds_reportFontFamily').disabled =false;\r\n\r\n      //filters are changed or saving a new report will refresh the page after saving\r\n      if(ifChangeFilter(reportFilters) || ");
      out.print(newReport);
      out.write(") {\r\n          $('createReport').submit();\r\n      }else{\r\n          let reportName = textToHTML(encHTML($('reportName').value));\r\n          let header = document.querySelector(\".reportHeader > h2:first-child\");\r\n          nameInput.nextElementSibling.style.display = \"none\";\r\n          nameInput.style.borderColor=\"#CCCCCC\";\r\n          header.innerHTML = reportName;\r\n          ajaxget('/sims/report/templates/saveConfig.jsp',\r\n              {'a':'");
      out.print(apname);
      out.write("',\r\n                  'id':");
      out.print(id);
      out.write(",\r\n                  'quickSave':'',\r\n                  'msi':'");
      out.print(rp.getMenuSetIndex());
      out.write("',\r\n                  'reportName':reportName,\r\n                  'tabPath': '");
      out.print(tabPath);
      out.write("'\r\n              },\r\n              function(){\r\n                floatWin(null,\"");
      out.print(bundle.getString("exportReport_saveSuccess"));
      out.write("\");\r\n                setTimeout(function () {\r\n                    $('floatingWin').style.display = 'none';\r\n                }, 1000);\r\n                $('discardChanges').style.display = \"none\";\r\n              },\r\n              true\r\n          );\r\n      }\r\n  }\r\n  function saveAsReport() {\r\n      $('saveReportId').value=\"\";\r\n      $('createReport').submit();\r\n  }\r\n  function updateConfig(name,value,ifAppend,ifReload,ifRemove,func,defaultVal,valueIsArray,valueIsJSON,updateMultipleValues){\r\n    //t param to avoid server behavior that it puts the same request on hold before the last same request is finished\r\n    //same request before last request was finished should be blocked, if on hold, all of them will run and take unnecessary server resources\r\n    /*\r\n    To let discardChange works successfully, `defaultVal` is required.\r\n    when ifReload is false, func needs to be displayDiscardChanges\r\n    */\r\n    if(!ifReload) {\r\n        if(func !== displayDiscardChanges) {\r\n          console.warn('`func` needs to be displayDiscardChanges.');\r\n");
      out.write("        }\r\n        else if(defaultVal == undefined) {\r\n          console.warn('To let discardChange works successfully, `defaultVal` is required.');\r\n        }\r\n    }\r\n    ajaxget('/sims/report/templates/updateConfig.jsp',\r\n            {'a':'");
      out.print(apname);
      out.write("',\r\n                'name':name,\r\n                'p':'");
      out.print(unsavedReport.getDataSourcePath());
      out.write("',\r\n                'si':");
      out.print(unsavedReport.getDataSourceSheetIndex());
      out.write(",\r\n                'p2':'");
      out.print(unsavedReport.getDataSourcePath2());
      out.write("',\r\n                'si2':");
      out.print(unsavedReport.getDataSourceSheetIndex2());
      out.write(",\r\n                'value':value,\r\n                'append':ifAppend?1:0,\r\n                'remove':ifRemove?1:0,\r\n                't':new Date().getTime(),\r\n                'valueIsArray':valueIsArray?1:0,\r\n                'valueIsJSON':valueIsJSON?1:0,\r\n                'updateMultipleValues':updateMultipleValues?1:0\r\n            },\r\n            checkReportChange.bind(null,'");
      out.print(apname);
      out.write("',name,defaultVal+\"\",func),\r\n            true\r\n    );\r\n    if(ifReload) {\r\n        ");
if(!newWindow){
      out.write("\r\n        location.href = location.href.replace(/&configMode/,\"\").replace(/&viewMode/,\"\");\r\n        ");
} else {
      out.write("\r\n        location.reload();\r\n        ");
}
      out.write("\r\n    }\r\n  }\r\n  //remove certain value in JSONArray\r\n  function removeConfig(name,value,ifReload,defaultVal) {\r\n    updateConfig(name,value,false,ifReload,true,null,defaultVal);\r\n  }\r\n  //remove name-value pair\r\n  function removeConfigName(name,ifReload) {\r\n    ajaxget('/sims/report/templates/removeConfig.jsp',\r\n        {'a':'");
      out.print(apname);
      out.write("','name':name,'t':new Date().getTime()},\r\n        function(){\r\n            checkReportChange('");
      out.print(apname);
      out.write("',name,null,null);\r\n        },\r\n        true\r\n    );\r\n    if(ifReload) {\r\n        ");
if(!newWindow){
      out.write("\r\n        location.href = location.href.replace(/&configMode/,\"\").replace(/&viewMode/,\"\");\r\n        ");
} else {
      out.write("\r\n        location.reload();\r\n        ");
}
      out.write("\r\n    }\r\n  }\r\n  function checkReportChange(ap,name,defaultVal,func){\r\n      ajaxget('/sims/report/templates/checkReportChange.jsp',\r\n          {'a':ap, 'name':name, 'defaultVal':defaultVal},func,true);\r\n  }\r\n  function postSize(e) {\r\n    var target = parent.postMessage ? parent : (parent.document.postMessage ? parent.document : undefined);\r\n    var isMSIE = /*@cc_on!@*/0;\r\n    var isFF= navigator.userAgent.toLowerCase().indexOf('firefox') > -1;\r\n    document.body.style.height = 'auto';\r\n    if (typeof target != \"undefined\" && document.body.scrollHeight){\r\n      //add 20 more pixels to prevent that width overflow generate scroll and influence the height displayed\r\n      if(isMSIE) target.postMessage((document.documentElement ? Math.max(document.body.scrollHeight, document.documentElement.scrollHeight) : document.body.scrollHeight)+20, \"*\");\r\n      else if(isFF) target.postMessage(Math.max(document.body.scrollHeight, document.documentElement.scrollHeight)+70, \"*\");\r\n      else target.postMessage(Math.max(document.body.scrollHeight, document.documentElement.scrollHeight)+50, \"*\");\r\n");
      out.write("    }\r\n  }\r\n  function showReportDescription() {\r\n    var reportDesc = document.getElementById('reportDesc');\r\n    var desc = '");
      out.print(desc);
      out.write("';\r\n    if (window['ctrl']) window['ctrl'].reportDesc = '';\r\n    var ifApManager = ");
      out.print(apname!=null && user!=null && user.ifApManager(apname));
      out.write(";\r\n    var newWindow = ");
      out.print(newWindow);
      out.write(";\r\n    \r\n    if (desc) {\r\n      desc.replace(/<br\\/>/g, '\\n').replace(/<br>/g, '\\n');\r\n      reportDesc.innerHTML = desc;\r\n    }\r\n    else {\r\n      reportDesc.innerHTML = '");
      out.print(bundle.getString("reportDescHint"));
      out.write("';\r\n      reportDesc.style.color = '#aaa';\r\n    }\r\n    if (newWindow && !desc) return;\r\n    if (ifApManager || !ifApManager && desc) reportDesc.style.display = '';\r\n    if (ifApManager && !newWindow) {\r\n      reportDesc.setAttribute('contentEditable', true);\r\n      reportDesc.onmouseover = function() {this.style.border='1px solid #cccccc';};\r\n      reportDesc.onmouseout = function() {this.style.border='1px solid #f8f8f8';};\r\n      reportDesc.onfocus = function() {\r\n        if (!desc && !ctrl.reportDesc) {\r\n          this.innerHTML = '';\r\n          this.style.color = '#000';\r\n        }\r\n      };\r\n      reportDesc.onblur = function(){\r\n        if(!this.textContent){\r\n          this.innerHTML = '");
      out.print(bundle.getString("reportDescHint"));
      out.write("';\r\n          this.style.color = '#aaa';\r\n        }\r\n      };\r\n      reportDesc.onkeyup = function(){\r\n        if (ctrl) ctrl.reportDesc = this.textContent;\r\n        document.getElementById('desc').value = this.textContent;\r\n        updateReportDescription();\r\n      };\r\n    }\r\n    else {\r\n      reportDesc.style.overflowWrap = \"break-word\";\r\n      if (reportDesc.offsetHeight > 80) {\r\n        document.getElementById('moreDesc').style.display = 'inline-block';\r\n      }\r\n      reportDesc.style.maxHeight = '80px';\r\n    }\r\n  }\r\n  function updateReportDescription() {\r\n    var desc = document.getElementById('reportDesc').innerText;\r\n    desc = encHTML(desc);\r\n    desc = textToHTML(desc);\r\n    updateConfig(\"desc\",desc,false,false,false,displayDiscardChanges,\"\");\r\n  }\r\n  function moreDesc() {\r\n    $('reportDesc').style.maxHeight = '';\r\n    $('moreDesc').style.display = 'none';\r\n  }\r\n  function openStyleConfig(){\r\n      $('styleSettings').attr({width: \"480px\", padding: \"20px 30px\"});\r\n      $('reportStyleConfig').style.display = \"\";\r\n");
      out.write("      $('showStyleSettingIcon').style.display = \"\";\r\n      $('showStyleSettingIcon').children[0].style.left = \"-10px\";\r\n      if(!styleConfigIsOpen) {\r\n          $('showStyleSettingIcon').querySelector(\"i\").classList.toggle(\"rotate\");\r\n          styleConfigIsOpen = true;\r\n      }\r\n      $('showStyleSettingIcon').children[0].onclick = function() {\r\n          $('showStyleSettingIcon').querySelector(\"i\").classList.toggle(\"rotate\");\r\n          hideStyleConfig();\r\n      }\r\n      if (ifReportFixedArea) {\r\n          const headerHeight = $('v5Header') ? $('v5Header').offsetHeight : 0;\r\n          $('styleSettings').attr({top: headerHeight + 'px', height: 'calc(100vh - ' + headerHeight + 'px)'});\r\n          $('reportOuterContainer').style.width = (window.innerWidth - 480) + 'px';\r\n      }\r\n      ");
 if(newReport) { 
      out.write("\r\n      updateStyles();\r\n      ");
 } 
if(user.ifApManager(apname)){ 
      out.write("\r\n      enableMultiSelectCombo($('reportFilter'));\r\n      $('reportName').oninput = function() {\r\n          let warnNotSave = this.nextElementSibling;\r\n          let warnNotEmpty = this.parentNode.children[2];\r\n\r\n          if(this.value == \"\") {\r\n              warnNotSave.style.display = \"none\";\r\n              warnNotEmpty.style.display = \"\";\r\n          }else{\r\n              warnNotSave.style.display = (this.value !== this.dataset.name)?\"\":\"none\";\r\n              warnNotEmpty.style.display = \"none\";\r\n          }\r\n\r\n          if(warnNotSave.style.display == \"\" || warnNotEmpty.style.display == \"\") {\r\n              this.style.borderColor = \"red\";\r\n              this.style.outline = \"none\";\r\n          }else{\r\n              this.style.borderColor = \"#CCCCCC\";\r\n              this.style.outline = \"\";\r\n          }\r\n      }\r\n      $('desc').oninput = function() {\r\n          $('reportDesc').innerText = this.value;\r\n          updateReportDescription();\r\n      }\r\n      if($('reportDesc').innerText === '");
      out.print(bundle.getString("reportDescHint"));
      out.write("') {\r\n          $('desc').value = \"\";\r\n      }\r\n      ");
 } 
      out.write("\r\n\r\n      tableTypeMap = {\r\n          dashboard: $('reportMain'),\r\n          ranking: $(\"rankingChart\"),\r\n          pivot: $(\"pivotChart\"),\r\n          label: $('labelTable'),\r\n          map: $('map_canvas'),\r\n          trend: $('chartdiv'),\r\n          calendar: $('eventCalendar'),\r\n          kanban: $('board'),\r\n          pie: $(\"pieChart\"),\r\n          todo: document.querySelector('.todoTable'),\r\n          grouping: document.querySelector('.reportTable'),\r\n          gantt: document.querySelector('#ganttBody table'),\r\n          userStatus: [$('reportTable'), $('onlineReportContainer')],\r\n          approval:$('approvalTable'),\r\n          balance: $('balanceReport'),\r\n          balanceSimple: $('balanceReport'),\r\n          payable: $('overdueBillTable'),\r\n          receivable: $('overdueInvoiceTable'),\r\n          profitnloss: $('profitnlossReport'),\r\n          profitnlossSimple: $('profitnlossReport'),\r\n          cashflow: $('cashflowReport'),\r\n          cashflowSimple: $('cashflowReport'),\r\n          reservation: $('reservationChart'),\r\n");
      out.write("      };\r\n      previewStyleConfigOnChange();\r\n  }\r\n  function hideStyleConfig() {\r\n      styleConfigIsOpen = false;\r\n      $('showStyleSettingIcon').children[0].onclick = openStyleConfig;\r\n      $('showStyleSettingIcon').children[0].style.left = \"-60px\";\r\n      $('styleSettings').attr({width: 0, padding: \"20px 0\"});\r\n      $('reportStyleConfig').style.display = \"none\";\r\n      \r\n      if (ifReportFixedArea) {\r\n          $('reportOuterContainer').style.width = '';\r\n      }\r\n  }\r\n  function setStyleDefaultVal() {\r\n      $('showStyleSettingIcon').style.display = \"none\";\r\n      $('reportStyleConfig').style.display = \"none\";\r\n      let elem, selectedOption, customInputs, margins, value;\r\n      for(let tagId in styleCache){\r\n          elem = $(tagId);\r\n          value = styleCache[tagId];\r\n          if(tagId.includes(\"ResetDefault\")){\r\n              elem = tagId.search(/out/i)!==-1?$('out_backToDefault'):$('in_backToDefault');\r\n              elem.style.visibility = (value ==\"false\")?\"hidden\":\"\";\r\n          }\r\n\r\n          if(!elem) continue;\r\n");
      out.write("          if(elem.tagName === \"SELECT\"){\r\n            selectedOption = elem.querySelector(\"option[value='\"+ value +\"']\");\r\n            if(selectedOption) selectedOption.setAttribute(\"selected\", \"\");\r\n          } else if(elem.tagName === \"INPUT\" && elem.type === \"checkbox\"){ //unifyFontFamily, isShowTitle, isShowDataSource, isShowBorder, isShowA4Block,isOnePageOneLabel\r\n              value = (value == \"true\");\r\n              if(tagId === \"unifyFontFamily\") {\r\n                  $(\"des_reportFontFamily\").disabled = $(\"ds_reportFontFamily\").disabled = elem.checked = value;\r\n                  if($(\"cnt_reportFontFamily\")) $(\"cnt_reportFontFamily\").disabled = value;\r\n              }else {\r\n                  elem.checked = value;\r\n              }\r\n          }else if(tagId.search(/boundaryMargins/i)!==-1){\r\n              elem = tagId.search(/out/i)!== -1?$('outCustomBoundary'):$('customBoundary');\r\n              customInputs = $$('.orient',elem); //top, left, right, bottom\r\n              customInputs.push(customInputs.splice(1, 1)[0]); //top, right, bottom, left\r\n");
      out.write("\r\n              margins = value.split(\",\");\r\n              customInputs.forEach(function (input, i) {\r\n                  input.value = margins[i];\r\n              })\r\n          }\r\n      }\r\n  }\r\n  function setTableBoundaryMargin(tables, margin) {\r\n      if(!margin) return;\r\n\r\n      if(Array.isArray(tables)){\r\n          tables.forEach(function(table){\r\n              table.style.margin = margin.map(function(e) { return e+\"cm\";}).join(\" \");\r\n          });\r\n      }else{\r\n          tables.style.margin = margin.map(function(e) { return e+\"cm\";}).join(\" \");\r\n      }\r\n\r\n  }\r\n  function hideReportHeader(){\r\n      if(type === \"label\") return; //[related Bug id: 9125]\r\n      ");
 if((desc.equals("")) && !isShowTitle){
      out.write("\r\n          document.querySelector('.reportHeader').style.display=\"none\";\r\n      ");
 } 
      out.write("\r\n  }\r\n  function previewStyleConfigOnChange(){\r\n      let header = document.querySelector(\".reportHeader > h2:first-child\"),\r\n          desc = $('reportDesc'),\r\n          datasource = document.querySelector('.queryTable');\r\n      let tables = tableTypeMap[type];\r\n      /*Font*/\r\n      /*Report Name*/\r\n      $('name_reportFontFamily').onchange = function () {\r\n          let val = this.value;\r\n          header.style.fontFamily = styleCache[\"name_reportFontFamily\"] = val;\r\n\r\n          if($(\"unifyFontFamily\").checked){\r\n              $('des_reportFontFamily').value = desc.style.fontFamily = styleCache[\"des_reportFontFamily\"] = val;\r\n              $('ds_reportFontFamily').value = datasource.style.fontFamily = styleCache[\"ds_reportFontFamily\"] = val;\r\n              if(Array.isArray(tables)){\r\n                  tables.forEach(function(table){\r\n                      let tableChilds = table.querySelectorAll('.onlineReport');\r\n                      if(tableChilds && tableChilds.length > 0){\r\n                          for(let tableChild of tableChilds){\r\n");
      out.write("                              $('cnt_reportFontFamily').value = tableChild.style.fontFamily = styleCache[\"cnt_reportFontFamily\"] = val;\r\n                          }\r\n                      }\r\n                  });\r\n              }else{\r\n                  $('cnt_reportFontFamily').value = tables.style.fontFamily = styleCache[\"cnt_reportFontFamily\"] = val;\r\n              }\r\n\r\n          }\r\n          updateStyles();\r\n      };\r\n      $('name_reportFontSize').onchange = function () {\r\n          header.style.fontSize = styleCache[\"name_reportFontSize\"] = this.value;\r\n          updateStyles();\r\n      };\r\n      $('name_align').onchange = function () {\r\n          header.style.textAlign = styleCache[\"name_align\"] = this.value;\r\n          updateStyles();\r\n      };\r\n\r\n      /*Report Description*/\r\n      $('des_reportFontFamily').onchange = function () {\r\n          desc.style.fontFamily = styleCache[\"des_reportFontFamily\"] = this.value;\r\n          updateStyles();\r\n      };\r\n      $('des_reportFontSize').onchange = function () {\r\n");
      out.write("          desc.style.fontSize = styleCache[\"des_reportFontSize\"] = this.value;\r\n          updateStyles();\r\n      };\r\n      $('des_align').onchange = function () {\r\n          let val = (this.value === \"center\") && \"center\" ||\r\n              (this.value === \"left\") && \"flex-start\" ||\r\n              (this.value === \"right\") && \"flex-end\";\r\n          desc.style.textAlign = styleCache[\"des_align\"] = this.value;\r\n          desc.parentNode.style.justifyContent = val;\r\n          updateStyles();\r\n      };\r\n\r\n      /*Report Datasource*/\r\n      $('ds_reportFontFamily').onchange = function () {\r\n          datasource.style.fontFamily = styleCache[\"ds_reportFontFamily\"] = this.value;\r\n          updateStyles();\r\n      };\r\n      $('ds_reportFontSize').onchange = function () {\r\n          datasource.style.fontSize = styleCache[\"ds_reportFontSize\"] = this.value;\r\n          updateStyles();\r\n      };\r\n      $('ds_align').onchange = function () {\r\n          datasource.parentNode.style.justifyContent = styleCache[\"ds_align\"] = this.value;\r\n");
      out.write("          updateStyles();\r\n      };\r\n\r\n      /*Unify font family*/\r\n      $(\"unifyFontFamily\").onclick = function (){\r\n          let checked = this.checked, nameFontFamily = $('name_reportFontFamily').value;\r\n          let desff = checked?nameFontFamily:'");
      out.print(desff);
      out.write("',\r\n              dsff = checked?nameFontFamily:'");
      out.print(dsff);
      out.write("',\r\n              cntff = checked?nameFontFamily:'");
      out.print(cntff);
      out.write("';\r\n\r\n          $('des_reportFontFamily').value = desc.style.fontFamily = styleCache[\"des_reportFontFamily\"] = desff;\r\n          $('ds_reportFontFamily').value = datasource.style.fontFamily = styleCache[\"ds_reportFontFamily\"] = dsff;\r\n          if($('cnt_reportFontFamily')) {\r\n              $('cnt_reportFontFamily').disabled = checked;\r\n              if(Array.isArray(tables)){\r\n                  tables.forEach(function(table){\r\n                      let tableChilds = ele.querySelectorAll('.onlineReport');\r\n                      if(tableChilds && tableChilds.length > 0){\r\n                          for(let tableChild of tableChilds){\r\n                              $('cnt_reportFontFamily').value = tableChild.style.fontFamily = styleCache[\"cnt_reportFontFamily\"] = cntff;\r\n                          }\r\n                      }\r\n                  });\r\n              }else{\r\n                  $('cnt_reportFontFamily').value = tables.style.fontFamily = styleCache[\"cnt_reportFontFamily\"] = cntff;\r\n              }\r\n          }\r\n");
      out.write("\r\n          $('des_reportFontFamily').disabled = $('ds_reportFontFamily').disabled = checked;\r\n          styleCache[\"unifyFontFamily\"] = checked + \"\";\r\n          updateStyles();\r\n      };\r\n\r\n      /*Report content*/\r\n      if($('cnt_reportFontFamily') && $('cnt_reportFontSize')) {\r\n          //Map and label don't have cnt_reportFontFamily and cnt_reportFontSize\r\n          $('cnt_reportFontFamily').onchange = function () {\r\n              let _value = this.value;\r\n              if(Array.isArray(tables)){\r\n                  tables.forEach(function(table){\r\n                      let tableChilds = table.querySelectorAll('.onlineReport');\r\n                      if(tableChilds && tableChilds.length > 0){\r\n                          for(let tableChild of tableChilds){\r\n                              tableChild.style.fontFamily = styleCache[\"cnt_reportFontFamily\"] = _value\r\n                          }\r\n                      }\r\n                  });\r\n              }else{\r\n                  tables.style.fontFamily = styleCache[\"cnt_reportFontFamily\"] = _value;\r\n");
      out.write("              }\r\n\r\n              updateStyles();\r\n          };\r\n          $('cnt_reportFontSize').onchange = function () {\r\n              let val = styleCache[\"cnt_reportFontSize\"] = this.value;\r\n              if(Array.isArray(tables)){\r\n                  tables.forEach(function(table){\r\n                      let tableChilds = table.querySelectorAll('.onlineReport');\r\n                      if(tableChilds && tableChilds.length > 0){\r\n                          for(let tableChild of tableChilds){\r\n                              changeContentFontSize(tableChild, val);\r\n                          }\r\n                      }\r\n                  });\r\n              }else{\r\n                  changeContentFontSize(tables, val);\r\n              }\r\n\r\n              updateStyles();\r\n          }\r\n      }\r\n\r\n      /*Report boundary*/\r\n      let innerBoundary= $$(\".boundaryDiv\",$('boundaryChoose'))[0],\r\n          outerBoundary = $$(\".boundaryDiv\",$('boundaryChoose'))[1];\r\n      let margins=\"");
      out.print(margins);
      out.write("\".split(\",\"),\r\n          outMargins = \"");
      out.print(outMargins);
      out.write("\".split(\",\");\r\n\r\n      $('boundaryType').onchange = function(){\r\n          innerBoundary.classList.toggle(\"hideBoundary\");\r\n          outerBoundary.classList.toggle(\"hideBoundary\");\r\n          styleCache[\"boundaryType\"] =  this.value;\r\n          updateStyles();\r\n      };\r\n\r\n      /*Inner and Outer Boundary onchange*/\r\n      let container = document.querySelector(\".reportContent\");\r\n      let obj = {\r\n          in: [tables, innerBoundary],\r\n          out: [container, outerBoundary],\r\n      };\r\n      for(let i in obj){\r\n          boundaryOnChange(i, obj[i][0], obj[i][1]); //Due to IE, we cannot use spread operator\r\n      }\r\n\r\n      let hideBound = (styleCache[\"boundaryType\"]===\"in\")?outerBoundary:innerBoundary;\r\n      hideBound.classList.add(\"hideBoundary\");\r\n\r\n      /*Other*/\r\n      $(\"isShowTitle\").onclick = function(){\r\n          if(this.checked)\r\n              document.querySelector('.reportHeader').classList.remove(\"hideTitle\");\r\n          else\r\n              document.querySelector('.reportHeader').classList.add(\"hideTitle\");\r\n");
      out.write("          styleCache['isShowTitle'] = this.checked + \"\";\r\n          updateStyles();\r\n      };\r\n      $(\"isShowDataSource\").onclick = function(){\r\n          if(this.checked)\r\n              document.querySelector('.reportHeader').classList.remove(\"hideDataSource\");\r\n          else\r\n              document.querySelector('.reportHeader').classList.add(\"hideDataSource\");\r\n          styleCache['isShowDataSource'] = this.checked + \"\";\r\n          updateStyles();\r\n      };\r\n      $('isShowBorder').onclick = function(){\r\n          if(this.checked)\r\n            document.querySelector('.reportContent').classList.remove(\"hideBorder\");\r\n          else\r\n            document.querySelector('.reportContent').classList.add(\"hideBorder\");\r\n          styleCache['isShowBorder'] = this.checked + \"\";\r\n          updateStyles();\r\n      };\r\n      if(type === \"label\") {\r\n          $('isShowA4Block').onclick = function(){\r\n              let checked = this.checked;\r\n              styleCache['isShowA4Block'] =  checked + \"\";\r\n              updateStyles();\r\n");
      out.write("\r\n              if(checked) {\r\n                  let labels = Array.from($('labelTable').children);\r\n                  let labelsContentCount = Math.ceil(Math.max(labels.length / 1000, 1));\r\n                  $('labelTable').innerHTML = \"\";\r\n\r\n                  for (let i = 1; i <= labelsContentCount; i++) {\r\n                      let labelContent = node(\"DIV\");\r\n                      labelContent.className = \"labelContent\";\r\n                      for (let j = (i - 1) * 1000; j < i * 1000; j++) {\r\n                          if (!labels[j]) break;\r\n                          labelContent.appendChild(labels[j]);\r\n                      }\r\n                      $('labelTable').appendChild(labelContent);\r\n                  }\r\n              }else{\r\n                  let labels = [];\r\n                  $$('.labelContent', $('labelTable')).forEach(function(e) {\r\n                      labels = labels.concat(Array.from(e.children));\r\n                  });\r\n\r\n                  $('labelTable').innerHTML = \"\";\r\n                  labels.forEach(function (label) {\r\n");
      out.write("                      $('labelTable').appendChild(label);\r\n                  });\r\n              }\r\n          };\r\n\r\n          $('isOneLabelOnePage').onclick = function() {\r\n              if(this.checked) {\r\n                  $('labelTable').classList.add('onePageOneLabel');\r\n              } else {\r\n                  $('labelTable').classList.remove('onePageOneLabel');\r\n              }\r\n              styleCache['isOneLabelOnePage'] = this.checked + \"\";\r\n              updateStyles();\r\n          }\r\n      }\r\n      \r\n      if(type === 'grouping') {\r\n          $('groupPageBreak').onclick = function() {\r\n        \t  let groupPageBreak = this.checked;\r\n        \t  \r\n        \t  \r\n        \t  if(groupPageBreak) {\r\n        \t\t  $('groupingReportPrintStyle').innerHTML = '");
      out.print(GroupingReport.STYLE_GROUP_BREAKING);
      out.write("'\r\n        \t  } else {\r\n        \t\t  $('groupingReportPrintStyle').innerHTML = '';\r\n        \t  }\r\n        \t  \r\n        \t  styleCache['groupPageBreak'] = groupPageBreak;\r\n              updateStyles();\r\n          }\r\n      }\r\n  }\r\n  function updateStyles() {\r\n      updateConfig(\"styleParams\", JSON.stringify(styleCache), false, false, false, displayDiscardChanges, JSON.stringify(defaultStyleCache));\r\n  }\r\n  function displayDiscardChanges(res) {\r\n      //For updateConfig() which won't reload the page\r\n      $('discardChanges').style.display = res.trim() === \"true\"?\"flex\":\"none\";\r\n  }\r\n  function boundaryOnChange(boundaryType, tables, boundaryDiv){\r\n      let customDiv = boundaryDiv.querySelector(\".customBoundary\"),\r\n        select = boundaryDiv.querySelector(\".boundaryWidth\"),\r\n        resetDefault = boundaryDiv.querySelector(\".backToDefault\");\r\n      let customInputs = $$('.orient',customDiv); //top, left, right, bottom\r\n      customInputs.push(customInputs.splice(1, 1)[0]); //top, right, bottom, left\r\n      let resetDefaultMargin = boundaryType == \"in\"?\"showResetDefaultMarginBtn\":\"showResetDefaultOutMarginBtn\";\r\n");
      out.write("      let boundaryMargins = boundaryType == \"in\"?\"boundaryMargins\":\"outBoundaryMargins\";\r\n      let margins;\r\n\r\n      select.onchange = function () {\r\n          styleCache[select.id] = styleCache[boundaryMargins] = this.value;\r\n          margins = this.value.split(\",\");\r\n          setTableBoundaryMargin(tables, margins);\r\n\r\n          customInputs.forEach(function (input, i) {\r\n              input.value = margins[i];\r\n          });\r\n          resetDefault.style.visibility = \"hidden\";\r\n          styleCache[resetDefaultMargin] = \"false\";\r\n          updateStyles();\r\n      };\r\n      customInputs.forEach(function (input, index) {\r\n          margins = styleCache[boundaryMargins].split(\",\");\r\n          input.value = margins[index];\r\n          input.oninput = function () {\r\n              margins.splice(index, 1, this.value);\r\n              styleCache[boundaryMargins] = margins.join(\",\");\r\n              setTableBoundaryMargin(tables, margins);\r\n\r\n              let valIsChanged = styleCache[boundaryMargins] !== select.value;\r\n");
      out.write("              resetDefault.style.visibility = valIsChanged?\"\":\"hidden\";\r\n              styleCache[resetDefaultMargin] = valIsChanged + \"\";\r\n              updateStyles();\r\n          };\r\n      });\r\n      resetDefault.children[0].onclick = function () {\r\n          styleCache[boundaryMargins] = select.value;\r\n          margins = select.value.split(\",\");\r\n          setTableBoundaryMargin(tables, margins);\r\n          customInputs.forEach(function (input, i) {\r\n              input.value = margins[i];\r\n          });\r\n\r\n          resetDefault.style.visibility = \"hidden\";\r\n          styleCache[resetDefaultMargin] = \"false\";\r\n          updateStyles();\r\n      };\r\n  }\r\n  function changeContentFontSize(table,val){\r\n      switch (type) {\r\n          case \"dashboard\":\r\n              table.style.fontSize = Math.round(16*val) + \"px\";\r\n              document.querySelector(\".quickFactName + div\").style.fontSize = Math.round(25*val) + \"px\";\r\n              $$(\".quicktable\").forEach(function(e) { e.style.fontSize = Math.round(16*val) + \"px\"; });\r\n");
      out.write("              break;\r\n          case \"todo\":\r\n              table.rows[1].style.fontSize = Math.round(12*val) + \"px\";\r\n              document.querySelector(\".todoCount\").style.fontSize = Math.round(12*val) + \"px\";\r\n              $$(\".todorow\").forEach(function(e) { e.style.fontSize = Math.round(12*val) + \"px\"; });\r\n          case \"trend\":\r\n              table.style.fontSize = Math.round(9*val) + \"pt\";\r\n              break;\r\n          case \"grouping\":\r\n              table.style.fontSize = Math.round(13*val) + \"px\";\r\n              $$(\".grGroubLabel\").forEach(function(e) { e.style.fontSize = Math.round(16*val) + \"px\"; });\r\n              break;\r\n          case \"calendar\":\r\n              let fontSizeMap = {\r\n                  title_txt: 20,\r\n                  Header: 16,\r\n                  Corner_Cell: 16,\r\n                  Evt_Day: 12,\r\n                  Day_Top_Bar: 12,\r\n                  Evt_Filler: 12,\r\n                  Evt_Time_All_Day: 14,\r\n                  Evt_Time: 14,\r\n                  DayTime_Indicator: 16\r\n");
      out.write("              };\r\n\r\n              for(let key in fontSizeMap){\r\n                  let elem = $$(\".EventCalendar_\"+key);\r\n                  if(!elem) continue;\r\n                  elem.forEach(function(e) {\r\n                      e.style.fontSize = Math.round(fontSizeMap[key] * val) + \"px\";\r\n                  })\r\n              }\r\n              break;\r\n          case \"pie\":\r\n              $(\"reportTable\").style.fontSize = Math.round(16*val) + \"px\";\r\n              break;\r\n          case \"pivot\":\r\n              $(\"pivotTable\").style.fontSize = Math.round(16*val) + \"px\";\r\n              $(\"floatingHeader\").style.fontSize = Math.round(16*val) + \"px\";\r\n              break;\r\n          case \"ranking\":\r\n              document.querySelector(\".reportTable\").style.fontSize = Math.round(16*val) + \"px\";\r\n              break;\r\n          case \"approval\":\r\n              $$(\".approvalReportDispDiv\").forEach(function(div) {\r\n                  div.children[0].style.fontSize = Math.round(16*val) + \"px\";\r\n                  div.children[1].style.fontSize = Math.round(13*val) + \"px\";\r\n");
      out.write("              });\r\n              break;\r\n          case \"userStatus\":\r\n              table.style.fontSize = Math.round(14*val) + \"px\";\r\n              break;\r\n          default:  //gantt, kanban, balance, balanceSimple, cashflow, cashflowSimple, payable, profitnloss, profitnlossSimple, receivable\r\n              table.style.fontSize = Math.round(16*val) + \"px\";\r\n              break;\r\n      }\r\n  }\r\n  function showStylePanel(t){\r\n    let ulNavbar = t.parentNode;\r\n    $$(\"li\",ulNavbar).forEach(function(li) {\r\n        li.classList.remove(\"styleActive\");\r\n        $(li.dataset.target).classList.add(\"hideReportStyle\");\r\n    });\r\n    t.classList.add('styleActive');\r\n    $(t.dataset.target).classList.remove(\"hideReportStyle\");\r\n  }\r\n\r\n  afterInitHooks.push(function(){\r\n    ");
 if(!newWindow){ 
      out.write("\r\n    initChineseFontOption();\r\n    setStyleDefaultVal();\r\n    descDOMResizeObserve();\r\n    enableMultiSelectComboInReports();\r\n    document.getElementById('v5BodyTable').style.tableLayout = 'fixed';\r\n    ");
 } 
 if(!newReport){ 
      out.write("\r\n    showReportDescription();\r\n    ");
 } 
      out.write("\r\n  });\r\n  window.addEventListener(\"load\", function() {\r\n      postSize();\r\n      ");
 if(newWindow){ 
      out.write("\r\n      hideReportHeader();\r\n      ");
 } 
      out.write("\r\n      \r\n      if (ifReportFixedArea) {\r\n          document.body.style.overflowY = 'hidden';\r\n          resizeReport();\r\n      }\r\n  }, false);\r\n  window.addEventListener(\"resize\", debouncedFn(500, resizeReport));\r\n\r\n  function setPreviewLimit(limit) {\r\n      let configModeBlock = document.getElementById(\"config_mode_block\");\r\n      configModeBlock.style.display = '';\r\n      let configModeDesc = document.getElementById(\"config_mode_desc\");\r\n      configModeDesc.textContent = configModeDesc.textContent.replace(\"{0}\", limit);\r\n  }\r\n\r\n  function addChineseFontOption(select){\r\n      if(!select) return;\r\n      let commonFonts = select.querySelector(\"optgroup[label='Common Fonts']\");\r\n      let commonFontsInnerHTML = langv5 !== 'zh-TW' ? '' : ctrl.isMac\r\n          ? '<option value=\"PingFang\">蘋方</option>' +\r\n            '<option value=\"STHeiti\">黑體</option>' +\r\n            '<option value=\"STKaiti\">楷體</option>' +\r\n            '<option value=\"LiHei Pro\">儷黑 Pro</option>' +\r\n            '<option value=\"LiSong Pro\">儷宋 Pro</option>'\r\n");
      out.write("          : '<option value=\"PMingLiU\">新細明體</option>' +\r\n            '<option value=\"DFKai-SB\">標楷體</option>' +\r\n            '<option value=\"Microsoft JhengHei\">微軟正黑體</option>' +\r\n            '<option value=\"Microsoft YaHei\">微軟雅黑體</option>';\r\n      commonFonts.innerHTML += commonFontsInnerHTML;\r\n  }\r\n\r\n  function initChineseFontOption() {\r\n        let fontSelects = [$('name_reportFontFamily'), $('des_reportFontFamily'), $('ds_reportFontFamily'), $('cnt_reportFontFamily')];\r\n        fontSelects.forEach(function (s) {\r\n            addChineseFontOption(s);\r\n        });\r\n  }\r\n  function debouncedFn(delay, fn) {\r\n      var timerId = null;\r\n      return function () {\r\n          var context = this, args = arguments;\r\n\r\n          if (timerId) {\r\n              clearTimeout(timerId);\r\n          }\r\n          timerId = setTimeout(function () {\r\n              fn.apply(context, args);\r\n              timerId = null;\r\n          }, delay);\r\n      };\r\n  }\r\n function descDOMResizeObserve() {\r\n     let caller = 0;\r\n     if (ctrl.isIE) {\r\n");
      out.write("         //IE doesn't support ResizeObserver\r\n         const observer = new MutationObserver(debouncedFn(200, function (mutations) {\r\n             if (mutations.length) {\r\n                 let width = mutations[0].target.offsetWidth;\r\n                 updateConfig(\"desc_width\", width , false, false, false, displayDiscardChanges, \"\");\r\n             }\r\n             // observer.disconnect();\r\n         }));\r\n         observer.observe($('reportDesc'), {attributes: true, attributeFilter: [\"style\"]});\r\n    }\r\n    else if(ResizeObserver){\r\n         const resizeObserver = new ResizeObserver(debouncedFn(200, function(entries) {\r\n             if((caller++) == 0) return;  //ResizeObserver will call the resize callback once when the page is loaded.\r\n\r\n             let width;\r\n             for(let i = 0, entry; i < entries.length; i++) {\r\n                 entry = entries[i];\r\n                 if (entry.contentBoxSize) {\r\n                     let resizeObserverSize = entry.contentBoxSize[0];\r\n                     if (resizeObserverSize) {\r\n");
      out.write("                         width = resizeObserverSize.inlineSize;\r\n                         break;\r\n                     } else {\r\n                         resizeObserverSize = entry.contentBoxSize;\r\n                         width = resizeObserverSize.inlineSize;\r\n                         break;\r\n                     }\r\n                 } else {\r\n                     width = entry.contentRect.width;\r\n                     break;\r\n                 }\r\n             }\r\n\r\n             updateConfig(\"desc_width\", width, false, false, false, displayDiscardChanges, \"\");\r\n         }));\r\n\r\n         resizeObserver.observe($('reportDesc'));\r\n     }\r\n  }\r\n \r\n  function resizeReport() {\r\n      if (!ifReportFixedArea) return;\r\n      const newWindow = ");
      out.print(newWindow);
      out.write(";\r\n      if (newWindow) return;\r\n      const headerHeight = $('v5Header') ? $('v5Header').offsetHeight : 0;\r\n      const reportOuterContainer = $('reportOuterContainer');\r\n      if (reportOuterContainer) {\r\n          reportOuterContainer.style.height = 'calc(100vh - ' + headerHeight + 'px)';\r\n      }\r\n  }\r\n\r\n  function enableMultiSelectComboInReports() {\r\n      /* Reservation Report */\r\n      if('");
      out.print(unsavedReport.getType());
      out.write("'.includes(\"reservation\")) {\r\n          enableMultiSelectCombo($(\"reserve_availableDays\"));\r\n      }\r\n  }\r\n\r\n  function calendarReportPrintFriendly(){\r\n      const focusDate=RagicStorage.localStorage.getItem(\"FocusDateTime\", new Date());\r\n      window.open('/");
      out.print(apname);
      out.write("/report/display?newwin");
      out.print((newReport?"":"&id="+id));
      out.print(isViewMode?"&viewMode":"");
      out.print(isConfigMode?"&configMode":"");
      out.write("&pf&focusDate='+focusDate, '_blank');\r\n  }\r\n</script>\r\n\r\n");

  }
  finally{
    if (!otherReportIsRunning) {
        if (isRunningRestrictedReport) SystemCache.getInstance().remove("REPORT_START"+apname);
        if(ltt != null)ThreadManager.getInstance().removeTask(ltt);
    }
  }

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
