var __doc=document;function $(a){return __doc.getElementById(a)}function node(a){return __doc.createElement(a)}function evalJS(a){eval(a.responseText)}function rm(a){for(;a&&a.hasChildNodes();)a.removeChild(a.firstChild)}function toggle(a){a.style.display="none"!==a.style.display?"none":""}
function read(a,b,c){var d=new XMLHttpRequest;try{d.open("GET",b,!c);c||(d.onreadystatechange=function(){if(4==d.readyState){if(200!=d.status)return!1;a&&a(d)}});d.send(null);if(c){if(200!=d.status)return!1;a&&a(d)}return!0}catch(e){return floatWin(null,b+","+c+","+e.message),!1}}
function ajaxget(a,b,c,d){var e="?",k=!0,h;for(h in b)k?k=!1:e+="&",e+=encodeURIComponent(h)+"="+encodeURIComponent(b[h]);var f=new XMLHttpRequest;f.open("GET",a+e,!d);d||(f.onreadystatechange=function(){if(4==f.readyState){if(200!=f.status)return!1;c&&c(f.responseText);return!0}});f.send(null);if(d){if(200!=f.status)return!1;c&&c(f.responseText)}return!0}function dge(a){return __doc.getElementById(a)}
function getCookie(a){for(var b=document.cookie.split("; "),c=0;c<b.length;c++){var d=b[c].split("=");if(a==d[0])return decodeURIComponent(d[1])}return null}function removeCookie(a){document.cookie=a+"=;path=/;domain=.ragic.com; expires=Sat, 01-Jan-2000 00:00:00 GMT";document.cookie=a+"=;path=/;domain=www.ragic.com; expires=Sat, 01-Jan-2000 00:00:00 GMT";document.cookie=a+"=;path=/; expires=Sat, 01-Jan-2000 00:00:00 GMT"}
function setCookie(a,b,c){var d=-1!=location.hostname.indexOf(".ragic.com");d&&getCookie(a)&&removeCookie(a);c=c?new Date((new Date).getTime()+c):new Date((new Date).getTime()+31536E7);document.cookie=a+"="+encodeURIComponent(b)+"; path=/ ; expires="+c.toGMTString()+";"+(d?"domain=.ragic.com;":"")}
function changeHomeLang(a){a=a.options[a.selectedIndex].value;setCookie("lang",a);var b=location.toString().substr(0,location.toString().length-location.hash.length);b=b.split("/");4>=b.length?location.reload():("en-us"==a?b[4]="en":"zh-tw"==a?b[4]="zh-TW":"zh-cn"==a&&(b[4]="zh-CN"),b=b.join("/"),window.location=b)}function findPos(a){for(var b=a.offsetLeft,c=a.offsetTop;a=a.offsetParent;)b+=a.offsetLeft,c+=a.offsetTop;return[b,c]}
var dropWinTimer,timedDropper,currentDrop,timedOpenDropper,timedOpenAnchor,dropWinOpenTimer;
function mDropWin(a,b,c,d,e){a&&b&&(e||(e=100),c?(timedDropper=b,dropWinTimer=setTimeout(function(){timedDropper.style.display="none"},e),clearTimeout(dropWinOpenTimer)):timedDropper&&timedDropper.id==b.id&&clearTimeout(dropWinTimer),c||"none"!=b.style.display||(clearTimeout(dropWinTimer),timedDropper&&(timedDropper.style.display="none"),timedOpenDropper=b,timedOpenAnchor=a,dropWinOpenTimer=setTimeout("mDropWin_display("+d+");",e)))}
function mDropWin_display(a){timedOpenDropper.style.display="";var b=findPos(timedOpenAnchor),c=document.body.offsetWidth;timedOpenDropper.style.top=b[1]+timedOpenAnchor.offsetHeight+5+"px";b[0]+timedOpenDropper.offsetWidth>c?timedOpenDropper.style.right="25px":timedOpenDropper.style.left=a?b[0]-timedOpenDropper.offsetWidth+timedOpenAnchor.offsetWidth+"px":b[0]+"px"}var TimeToFade=500,currentId=1,skip=0,timer;
function fade(a){if(a)currentId=a,clearInterval(timer),timer=setInterval(fade,8E3);else{if(0<skip){skip--;return}currentId++;if(5<currentId||1>currentId)currentId=1}a="banner"+currentId;var b=$(a);b&&(b.style.opacity=0,b.style.filter="alpha(opacity = 0)",b.parentNode.appendChild(b),b.FadeState=1,b.FadeTimeLeft=TimeToFade,setTimeout("animateFade("+(new Date).getTime()+",'"+a+"')",33),$("fadeSwitch1").innerHTML="\u25cb",$("fadeSwitch2").innerHTML="\u25cb",$("fadeSwitch3").innerHTML="\u25cb",$("fadeSwitch4").innerHTML=
"\u25cb",$("fadeSwitch5").innerHTML="\u25cb",$("fadeSwitch"+currentId).innerHTML="\u25cf")}function animateFade(a,b){var c=(new Date).getTime(),d=c-a;a=$(b);a.FadeTimeLeft<=d?(a.style.opacity=1==a.FadeState?"1":"0",a.style.filter="alpha(opacity = "+(1==a.FadeState?"100":"0")+")",a.FadeState=1==a.FadeState?2:-2):(a.FadeTimeLeft-=d,d=a.FadeTimeLeft/TimeToFade,1==a.FadeState&&(d=1-d),a.style.opacity=d,a.style.filter="alpha(opacity = "+100*d+")",setTimeout("animateFade("+c+",'"+b+"')",33))}
function showTab(a,b){var c;for(c=0;c<a.childNodes.length;c++){var d=a.childNodes[c];1==d.nodeType&&(d.style.display="none")}b.style.display=""}
function showTour(a){var b=$("tourNavList"),c;for(c=0;c<b.childNodes.length;c++){var d=b.childNodes[c].firstChild;d&&1==d.nodeType&&(d.className="tourLeftNav")}$("a"+a).className="tourLeftNavSelected";b=$("tourRight");a=$("a"+a).href.split("#");for(c=0;c<b.childNodes.length;c++)(d=b.childNodes[c])&&1==d.nodeType&&(d.style.display="none");$("t"+a[1]).style.display=""}
function installApp(a,b,c){read(evalJS,"/sims/appInstall.jsp?appId="+a+(b?"&a="+b:"")+(c?"&update":""));$("floatingWin")&&floatWinClose();parent.$("floatingWin")&&(parent.$("floatingWin").style.display="none")}
function animate2012(){if(0<pauseCount)pauseCount--;else{var a=$("flick").scrollTop,b=a%50,c=1;3>=b?c=1:7>=b?c=2:15>=b?c=4:39>=b?c=8:47>=b?c=4:49>=b?c=2:50>b&&(c=1);50<=b+c&&(c=50-b,pauseCount=30);$("flick").scrollTop+=c;lastPos==a?(clearInterval(timer),timer=setInterval(showSubs,20)):lastPos=a}}
function showSubs(){if(0<pauseCount)pauseCount--;else{var a=$("sub1"),b=$("sub2");1>a.style.opacity?(a.style.opacity=parseFloat(a.style.opacity)+.05,a.style.filter="alpha(opacity = "+100*(parseFloat(a.style.opacity)+.05)+")"):0==b.style.opacity?(pauseCount=30,b.style.opacity=1E-4):1>b.style.opacity?(b.style.opacity=parseFloat(b.style.opacity)+.05,b.style.filter="alpha(opacity = "+100*(parseFloat(b.style.opacity)+.05)+")"):1<=b.style.opacity&&(clearInterval(timer),timer=-1)}}
function restartAnimate(){-1==timer&&($("flick").scrollTop=0,$("sub1").style.opacity=0,$("sub2").style.opacity=0,$("sub1").style.filter="alpha(opacity=0);",$("sub2").style.filter="alpha(opacity=0);",pauseCount=30,timer=setInterval(animate2012,20))}window.ctrl||(window.ctrl={});document.onmousedown=function(a){a||(a=window.event);dragFloatingWinStart(a)};document.onmousemove=function(a){a||(a=window.event);ctrl.dragWin&&dragFloatingWin(a)};document.onmouseup=function(a){ctrl.dragWin&&dragFloatWinEnd()};
function dragFloatingWinStart(a){if(a.target)var b=a.target;else a.srcElement&&(b=a.srcElement);3==b.nodeType&&(b=b.parentNode);if("floatingWinHeader"==b.className)b=b.parentNode;else if("floatingWin"!=b.className)return;ctrl.dragWin=b;ctrl.dragStartX=a.clientX;ctrl.dragStartY=a.clientY;b.style.left=b.offsetLeft+"px";b.style.top=b.offsetTop+"px";ctrl.winStartX=parseInt(b.offsetLeft);ctrl.winStartY=parseInt(b.offsetTop);disableSelection(document.body)}
function dragFloatingWin(a){var b=ctrl.dragWin,c=a.clientY-ctrl.dragStartY;b.style.left=ctrl.winStartX+(a.clientX-ctrl.dragStartX)+"px";b.style.top=ctrl.winStartY+c+"px"}function dragFloatWinEnd(){ctrl.dragWin=null;ctrl.dragStartX=null;ctrl.dragStartY=null;enableSelection(document.body)}"function"!=typeof outNUI&&(window.outNUI=function(){ctrl.outOfNUI=!0});
if("function"!=typeof getBodyScrolltop)var getBodyScrolltop=function(){return window.pageYOffset||document.documentElement.scrollTop||document.body.scrollTop||0};
function floatWinV6(a,b,c,d,e,k){var h=$("floatingWinOK"),f=$("floatingWin"),l=$("floatingWinHeader"),g=$("floatingWinContent"),m=$("floatingWinOuterContent");outNUI();c||(c="&nbsp;");d?h.style.display="none":(h.style.display="",e&&($("floatingOKButton").textContent=e));a||b||(b="&nbsp;");rm(l);b?(f.style.display="",f.style.top=getBodyScrolltop()+200+"px",b instanceof Element?(rm(g),g.appendChild(b)):g.innerHTML=b,l.innerHTML=c,a&&a()):(m.style.padding=k?"0":"15px 11px 10px 11px",a&&(floatingWinUrlFunc=
a),g.innerHTML=lm.prop_loading,f.style.display="",f.style.top=getBodyScrolltop()+200+"px",l.innerHTML=c,read(function(a){g.innerHTML=a.responseText;a=.6*document.body.offsetHeight;g.offsetHeight>a&&(g.style.height=a+"px");(a=$("email"))&&a.focus();"function"===typeof ctrl.floatWinCallback&&(ctrl.floatWinCallback(),ctrl.floatWinCallback=null)},floatingWinUrlFunc()))}
function disableSelection(a){a&&("undefined"!=typeof a.onselectstart&&(a.onselectstart=function(a){a||(a=window.event);if(a.target)var b=a.target;else a.srcElement&&(b=a.srcElement);3==b.nodeType&&(b=b.parentNode);return"hin"==b.id?!0:!1}),"undefined"!=typeof a.style.MozUserSelect&&(a.style.MozUserSelect="none"),a.style.cursor="default")}
function enableSelection(a){a&&("undefined"!=typeof a.onselectstart?a.onselectstart=null:"undefined"!=typeof a.style.MozUserSelect?a.style.MozUserSelect=null:a.onmousedown=null,a.style.cursor="")}function openid_login(a){read(function(a){location.href=a.responseText},"/sims/reg/openidDiscovery.jsp?type="+a)}var tooltipDiv;
function showTooltip(a,b){var c=node("div");c.innerHTML=b;b=findPos(a);c.className="tooltip";c.style.top=b[1]+a.offsetHeight+"px";c.style.left=b[0]+a.offsetWidth-100+"px";tooltipDiv=c;document.body.appendChild(c)}function hideTooltip(){tooltipDiv&&document.body.removeChild(tooltipDiv);tooltipDiv=null}function bodyScrollTo(a){document.documentElement.scrollTop&&(document.documentElement.scrollTop=a);document.body.scrollTop=a}
function calculate_time_zone(){return-1*(new Date).getTimezoneOffset()/60}setCookie("tz",calculate_time_zone(),null);
