var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,a,c){b!=Array.prototype&&b!=Object.prototype&&(b[a]=c.value)};
$jscomp.getGlobal=function(b){b=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,b];for(var a=0;a<b.length;++a){var c=b[a];if(c&&c.Math==Math)return c}return globalThis};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(b,a,c,d){if(a){c=$jscomp.global;b=b.split(".");for(d=0;d<b.length-1;d++){var f=b[d];f in c||(c[f]={});c=c[f]}b=b[b.length-1];d=c[b];a=a(d);a!=d&&null!=a&&$jscomp.defineProperty(c,b,{configurable:!0,writable:!0,value:a})}};
$jscomp.polyfill("Array.from",function(b){return b?b:function(a,b,d){b=null!=b?b:function(a){return a};var c=[],e="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if("function"==typeof e){a=e.call(a);for(var g=0;!(e=a.next()).done;)c.push(b.call(d,e.value,g++))}else for(e=a.length,g=0;g<e;g++)c.push(b.call(d,a[g],g));return c}},"es6","es3");var ragic_url_sec=ragic_url.split("/"),ap=ragic_url_sec[1],path="/"+ragic_url_sec[2],sheetIndex=ragic_url_sec[3];
function isIE(){var b=navigator.userAgent,a=/WebKit/.test(b),c=window.opera&&opera.buildNumber;return!a&&!c&&(/MSIE/gi.test(b)||/Trident/gi.test(b))}
function urlProcess(b){var a="?webview&webaction="+ragic_feature;b&&(a+="&fromWp");window.embedAPIKey&&(a+="&embedAPIKey="+encodeURIComponent(window.embedAPIKey));window.hideSlogan&&(a+="&hideSlogan");window.webFormVersionIsNew&&(a+="&ver=new");window.submitOnce&&(a+="&submitOnce");window.pfv&&Array.from(window.pfv).forEach(function(b){b.hasOwnProperty("fieldId")&&b.hasOwnProperty("fieldValue")&&(a+="&pfv"+b.fieldId+"="+encodeURIComponent(b.fieldValue))});window.version&&(a+="&version="+window.version);
window.dfCheckbox&&(a+="&dfCheckbox");window.listData&&(a+="&fv2");window.autoSearch&&(a+="&search");window.noSearchBar&&(a+="&noSearchBar");window.fieldSummary&&(a+="&fieldSummary");window.applyDefaultView&&(a+="&defaultView");window.ragic_webconfig&&(a+="&webconfig");window.ragic_filterv3&&(a+="&fv3="+window.ragic_filterv3);return a}
function ragic_iframe_load(){for(var b=document.getElementById("ragic_webview"),a=document.getElementsByTagName("script"),c=document.getElementById("ragic-link"),d=!1,f=a.length;f--;){var e=a[f].src;if(-1!==e.indexOf("/common/load")){d=-1!==e.replace(/^[^\?]+\??/,"").indexOf("wp");break}}if(!d&&(c.style.display="none",!c||-1==c.innerHTML.indexOf("Ragic")||-1==c.href.indexOf("ragic"))){alert("config error");return}a=("http:"===window.location.protocol?"http://":"https://")+ragic_url;d=urlProcess(d);
window.ragic_embedtype&&"report"==window.ragic_embedtype?b.innerHTML='<iframe id="ragic_iframe" title="ragic_iframe" src="'+a+'" style="border:none;width:100%;height:365px;" sandbox="allow-modals allow-forms allow-popups allow-scripts allow-same-origin allow-top-navigation"></iframe>':isIE()?b.innerHTML='<iframe id="ragic_iframe" title="ragic_iframe" src="'+a+d+'" style="border:none;width:100%;"></iframe>':b.innerHTML='<iframe id="ragic_iframe" title="ragic_iframe" src="'+a+d+'" style="border:none;width:100%;max-height: 100vh;" sandbox="allow-modals allow-forms allow-popups allow-scripts allow-same-origin allow-top-navigation"></iframe>'}
function receiveSize(b){if(isNaN(b.data))console.error("No data");else{var a=document.getElementById("ragic_iframe");a&&-1!==b.data&&(a.style.height=b.data+"px")}}window.addEventListener("message",receiveSize,!1);window.addEventListener("load",ragic_iframe_load,!1);
