var ragic_server=ragic_url.split("/")[0],fromWp=!1;function readForFPS(a){var c=document.createElement("script");c.setAttribute("src",a);head?head.appendChild(c):document.body.appendChild(c)}var __doc=document;function node(a){return __doc.createElement(a)}function findPos(a){for(var c=a.offsetLeft,d=a.offsetTop;a=a.offsetParent;)c+=a.offsetLeft,d+=a.offsetTop;return[c,d]}
var ragic_url_sec=ragic_url.split("/"),ap=ragic_url_sec[1],path="/"+ragic_url_sec[2],sheetIndex=ragic_url_sec[3],searchDropSelector={qt:"",selectedIndex:-1,keywords:null,options:null,loadOptions:function(){if(this.qt&&this.qt===document.getElementById("ragic_searchbox").value)searchDropSelector.renderOptions();else if((this.qt=document.getElementById("ragic_searchbox").value)&&0!==this.qt.length)readForFPS(("https:"===window.location.protocol?"https://":"http://")+ragic_server+"/sims/searchPrefix.jsp?a="+
ap+"&q="+encodeURIComponent(this.qt)+"&p="+(path?encodeURIComponent(path):"")+"&si="+sheetIndex+"&t="+(new Date).getTime()+"&webview"+(fromWp?"&fromWp":""));else{var a=document.getElementById("searchDropSelector");a&&(a.style.display="none")}},openOption:function(){var a=searchDropSelector.selectedIndex,c=searchDropSelector.keywords.length;0===searchDropSelector.options.length||0>a||(a<c?(document.getElementById("ragic_searchbox").value=searchDropSelector.keywords[a].w,document.getElementById("ragic_searchbutton").onclick()):
(document.getElementById("searchDropSelector")&&(document.getElementById("searchDropSelector").style.display="none"),a=searchDropSelector.options[a-c].url.split("/")[3],document.getElementById("ragic_fts").innerHTML='<iframe id="ragic_iframe" sandbox="allow-modals allow-forms allow-popups allow-scripts allow-same-origin allow-top-navigation" src="'+("https:"==window.location.protocol?"https://":"http://")+ragic_server+"/"+ap+path+"/"+sheetIndex+"/"+a+".xhtml?wv=fts"+(fromWp?"&fromWp":"")+(hideSlogan?
"&hideSlogan":"")+'" style="border:none;width:100%;"></iframe>'))},move:function(a){this.selectedIndex+=a;a=Math.max(1,this.options.length+this.keywords.length);0>this.selectedIndex?this.selectedIndex=-1:this.selectedIndex>=a&&(this.selectedIndex=a-1);this.renderOptions()},renderOptions:function(){var a=document.getElementById("searchDropSelector");a?(a.style.display="",a.innerHTML=""):(a=node("div"),a.className="searchDropSelector",a.id="searchDropSelector");var c=document.getElementById("ragic_searchbox"),
d=findPos(c);a.style.minWidth=c.offsetWidth+"px";a.style.top=d[1]+c.offsetHeight+"px";a.style.left=d[0]+"px";document.body.appendChild(a);d=0;var e;for(e=0;e<this.keywords.length;e++){var b=node("div");b.className="searchDropdiv";b.setAttribute("index",d);b.onmouseover=focusOnFTSOption;b.onclick=searchDropSelector.openOption;var f=node("span");b.appendChild(f);d===this.selectedIndex&&(searchDropSelector.selectedOption=b,b.className="searchDropdivSelected");f.innerHTML=this.keywords[e].d;a.appendChild(b);
d++}for(e=0;e<this.options.length;e++){b=node("div");b.className="searchDropdiv";b.setAttribute("index",d);b.onmouseover=focusOnFTSOption;f=node("span");b.appendChild(f);var g=node("span");b.appendChild(g);g.className="sheetNameSpan";var h=node("span");b.appendChild(h);d===this.selectedIndex&&(searchDropSelector.selectedOption=b,b.className="searchDropdivSelected");f.innerHTML=this.options[e].name||"&nbsp;";h.innerHTML=" - "+(this.options[e].term+"..."||"&nbsp;");g.innerHTML=" - "+this.options[e].fn;
b.json=this.options[e];b.onclick=searchDropSelector.openOption;a.appendChild(b);d++}0===d&&(b=node("div"),b.className="searchDropdiv",b.innerHTML=c.value+" - Search",b.setAttribute("index",d),b.onmouseover=focusOnFTSOption,b.onclick=searchDropSelector.openOption,d===this.selectedIndex&&(searchDropSelector.selectedOption=b,b.className="searchDropdivSelected"),a.appendChild(b))}};
function focusOnFTSOption(){searchDropSelector.selectedIndex=parseInt(this.getAttribute("index"));searchDropSelector.selectedOption&&(searchDropSelector.selectedOption.className="searchDropdiv")}
if(!document.getElementById("ragic_webview_css")){var head=document.getElementsByTagName("head")[0],style=document.createElement("style");style.innerHTML=".searchDropSelector{position:absolute;background:#fff;font-size:14px;line-height:22px;border:1px solid #aaa;z-index:200}\n.searchDropSelector div{cursor:pointer;padding:3px 15px}\n.searchDropdiv2{background:#f6f6f6}\n.searchDropdiv:hover,.searchDropdiv2:hover,.searchDropdivSelected{background:#efefef}\n.ftsMatch{color:#DD4B39!important}\n.thebutton3:visited,.thebutton3:hover,.thebutton3:active,.thebutton3:link{text-decoration:none;cursor:pointer}\n.thebutton3{box-shadow:inset 0 1px 0 0 #fff;background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ededed), color-stop(1, #dfdfdf) );background:-moz-linear-gradient( center top, #ededed 5%, #dfdfdf 100% );filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ededed',endColorstr='#dfdfdf');background-color:#ededed;-moz-border-radius:6px;-webkit-border-radius:6px;border-radius:6px;border:1px solid #bbb;display:inline-block;color:#777;font-family:arial;font-size:15px;font-weight:700;text-decoration:none;text-shadow:1px 1px 0 #fff;padding:6px 24px}\n.thebutton3:hover{background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #dfdfdf), color-stop(1, #ededed) );background:-moz-linear-gradient( center top, #dfdfdf 5%, #ededed 100% );filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#dfdfdf',endColorstr='#ededed');background-color:#dfdfdf}\n.thebutton3:active{position:relative;top:1px}\n#ragic_iframe{transition:all .5s;-moz-transition:all .5s;-webkit-transition:all .5s;-o-transition:all .5s}\n#ragic_searchbox,#ragic_searchbutton{font-size: 100%;margin: 0;vertical-align: baseline;line-height: normal;}\n#ragic_searchbutton{-webkit-appearance: button;cursor: pointer;}";head.appendChild(style)}
window.addEventListener("load",ragic_iframe_load,!1);
function ragic_iframe_load(){for(var a=document.getElementsByTagName("script"),c=document.getElementById("ragic-link"),d=a.length;d--;){var e=a[d].src;if(-1!==e.indexOf("/common/load")){fromWp=-1!==e.replace(/^[^\?]+\??/,"").indexOf("wp");break}}fromWp||c&&-1!=c.innerHTML.indexOf("Ragic")&&-1!=c.href.indexOf("https://www.ragic.com")?(a="https:"==window.location.protocol?"https://"+ragic_url:"http://"+ragic_url,d="&webaction=fts",fromWp&&(d+="&fromWp"),window.embedAPIKey&&(d+="&embedAPIKey="+encodeURIComponent(window.embedAPIKey)),
readForFPS(a+"?webview"+d+(window.ragic_webconfig?"&webconfig":"")),fromWp||(c.style.display="none")):alert("config error")}function receiveSize(a){var c=document.getElementById("ragic_iframe");c&&(c.style.height=a.data+"px")}window.addEventListener("message",receiveSize,!1);document.addEventListener("click",documentClick,!1);function documentClick(){var a=document.getElementById("searchDropSelector");a&&(a.style.display="none")};
