/*
 @copyright Copyright ? 2011-2015 by Neil Jenkins.
 @license   MIT Licensed.
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.getGlobal=function(l){l=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,l];for(var p=0;p<l.length;++p){var r=l[p];if(r&&r.Math==Math)return r}return globalThis};$jscomp.global=$jscomp.getGlobal(this);$jscomp.checkEs6ConformanceViaProxy=function(){try{var l={},p=Object.create(new $jscomp.global.Proxy(l,{get:function(r,w,E){return r==l&&"q"==w&&E==p}}));return!0===p.q}catch(r){return!1}};
$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();$jscomp.arrayIteratorImpl=function(l){var p=0;return function(){return p<l.length?{done:!1,value:l[p++]}:{done:!0}}};$jscomp.arrayIterator=function(l){return{next:$jscomp.arrayIteratorImpl(l)}};$jscomp.makeIterator=function(l){var p="undefined"!=typeof Symbol&&Symbol.iterator&&l[Symbol.iterator];return p?p.call(l):$jscomp.arrayIterator(l)};
$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(l,p,r){l!=Array.prototype&&l!=Object.prototype&&(l[p]=r.value)};$jscomp.owns=function(l,p){return Object.prototype.hasOwnProperty.call(l,p)};
$jscomp.polyfill=function(l,p,r,w){if(p){r=$jscomp.global;l=l.split(".");for(w=0;w<l.length-1;w++){var E=l[w];E in r||(r[E]={});r=r[E]}l=l[l.length-1];w=r[l];p=p(w);p!=w&&null!=p&&$jscomp.defineProperty(r,l,{configurable:!0,writable:!0,value:p})}};
$jscomp.polyfill("WeakMap",function(l){function p(){if(!l||!Object.seal)return!1;try{var t=Object.seal({}),r=Object.seal({}),p=new l([[t,2],[r,3]]);if(2!=p.get(t)||3!=p.get(r))return!1;p.delete(t);p.set(r,4);return!p.has(t)&&4==p.get(r)}catch(x){return!1}}function r(){}function w(t){var l=typeof t;return"object"===l&&null!==t||"function"===l}function E(t){if(!$jscomp.owns(t,u)){var l=new r;$jscomp.defineProperty(t,u,{value:l})}}function v(l){var t=Object[l];t&&(Object[l]=function(l){if(l instanceof
r)return l;E(l);return t(l)})}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(l&&$jscomp.ES6_CONFORMANCE)return l}else if(p())return l;var u="$jscomp_hidden_"+Math.random();v("freeze");v("preventExtensions");v("seal");var ba=0,I=function(l){this.id_=(ba+=Math.random()+1).toString();if(l){l=$jscomp.makeIterator(l);for(var t;!(t=l.next()).done;)t=t.value,this.set(t[0],t[1])}};I.prototype.set=function(l,p){if(!w(l))throw Error("Invalid WeakMap key");E(l);if(!$jscomp.owns(l,u))throw Error("WeakMap key fail: "+
l);l[u][this.id_]=p;return this};I.prototype.get=function(l){return w(l)&&$jscomp.owns(l,u)?l[u][this.id_]:void 0};I.prototype.has=function(l){return w(l)&&$jscomp.owns(l,u)&&$jscomp.owns(l[u],this.id_)};I.prototype.delete=function(l){return w(l)&&$jscomp.owns(l,u)&&$jscomp.owns(l[u],this.id_)?delete l[u][this.id_]:!1};return I},"es6","es3");
(function(l,p){function r(d,f,a){this.root=this.currentNode=d;this.nodeType=f;this.filter=a||$a}function w(d){return 1===d.nodeType&&!!ta[d.nodeName]}function E(d){switch(d.nodeType){case 3:return 1;case 1:case 11:if(ma&&na.has(d))return na.get(d);break;default:return 0}a:{var f=d.childNodes;for(var a=v,b=f.length;b--;)if(!a(f[b])){f=!1;break a}f=!0}f=f?ab.test(d.nodeName)?1:2:3;ma&&na.set(d,f);return f}function v(d){return 1===E(d)}function u(d){return 2===E(d)}function ba(d,f){f=new r(f,1,u);f.currentNode=
d;return f}function I(d,f){d=ba(d,f).previousNode();return d!==f?d:null}function t(d,f){d=ba(d,f).nextNode();return d!==f?d:null}function Ca(d,f){return!w(d)&&d.nodeType===f.nodeType&&d.nodeName===f.nodeName&&"A"!==d.nodeName&&d.className===f.className&&(!d.style&&!f.style||d.style.cssText===f.style.cssText)}function sa(d,f,a){if(d.nodeName!==f)return!1;for(var b in a)if(d.getAttribute(b)!==a[b])return!1;return!0}function x(d,f,a,b){for(;d&&d!==f;){if(sa(d,a,b))return d;d=d.parentNode}return null}
function oa(d,f){for(;f;){if(f===d)return!0;f=f.parentNode}return!1}function Da(d,f,a){var b="";if(d&&d!==f&&(b=Da(d.parentNode,f,a),1===d.nodeType)){b+=(b?">":"")+d.nodeName;if(f=d.id)b+="#"+f;if(f=d.className.trim()){var c=f.split(/\s\s*/);c.sort();b=b+"."+c.join(".")}if(f=d.dir)b+="[dir="+f+"]";c&&(a=a.classNames,-1<z.call(c,a.highlight)&&(b+="[backgroundColor="+d.style.backgroundColor.replace(/ /g,"")+"]"),-1<z.call(c,a.colour)&&(b+="[color="+d.style.color.replace(/ /g,"")+"]"),-1<z.call(c,a.fontFamily)&&
(b+="[fontFamily="+d.style.fontFamily.replace(/ /g,"")+"]"),-1<z.call(c,a.fontSize)&&(b+="[fontSize="+d.style.fontSize+"]"))}return b}function M(d){var f=d.nodeType;return 1===f||11===f?d.childNodes.length:d.length||0}function A(d){var f=d.parentNode;f&&f.removeChild(d);return d}function H(d,f){var a=d.parentNode;a&&a.replaceChild(f,d)}function y(d){var f=d.ownerDocument.createDocumentFragment(),a=d.childNodes;for(a=a?a.length:0;a--;)f.appendChild(d.firstChild);return f}function B(d,f,a,b){d=d.createElement(f);
var c;a instanceof Array&&(b=a,a=null);if(a)for(c in a)f=a[c],f!==p&&d.setAttribute(c,a[c]);if(b)for(a=0,c=b.length;a<c;a+=1)d.appendChild(b[a]);return d}function C(d,f){var a=f.__squire__,b=d.ownerDocument,c=d,g;if(d===f&&(!(g=d.firstChild)||"BR"===g.nodeName)){var e=a.createDefaultBlock();g?d.replaceChild(e,g):d.appendChild(e);d=e;e=null}if(3===d.nodeType)return c;if(v(d)){for(g=d.firstChild;ua&&g&&3===g.nodeType&&!g.data;)d.removeChild(g),g=d.firstChild;g||(ua?(e=b.createTextNode("\u200b"),a._didAddZWS()):
e=b.createTextNode(""))}else if(va){for(;3!==d.nodeType&&!w(d);){g=d.firstChild;if(!g){e=b.createTextNode("");break}d=g}3===d.nodeType?/^ +$/.test(d.data)&&(d.data=""):w(d)&&d.parentNode.insertBefore(b.createTextNode(""),d)}else if(!d.querySelector("BR"))for(e=B(b,"BR");(g=d.lastElementChild)&&!v(g);)d=g;if(e)try{d.appendChild(e)}catch(k){a.didError({name:"Squire: fixCursor \u2013 "+k,message:"Parent: "+d.nodeName+"/"+d.innerHTML+" appendChild: "+e.nodeName})}return c}function N(d,f){var a=d.childNodes,
b=d.ownerDocument,c=null,g,e=f.__squire__._config;var k=0;for(g=a.length;k<g;k+=1){var n=a[k];var m="BR"===n.nodeName;if(!m&&v(n))c||(c=B(b,e.blockTag,e.blockAttributes)),c.appendChild(n),--k,--g;else if(m||c)c||(c=B(b,e.blockTag,e.blockAttributes)),C(c,f),m?d.replaceChild(c,n):(d.insertBefore(c,n),k+=1,g+=1),c=null;3===E(n)&&N(n,f)}c&&d.appendChild(C(c,f));return d}function J(d,f,a,b){var c=d.nodeType,g;if(3===c&&d!==a)return J(d.parentNode,d.splitText(f),a,b);if(1===c){"number"===typeof f&&(f=f<
d.childNodes.length?d.childNodes[f]:null);if(d===a)return f;c=d.parentNode;for(g=d.cloneNode(!1);f;){var e=f.nextSibling;g.appendChild(f);f=e}"OL"===d.nodeName&&x(d,b,"BLOCKQUOTE")&&(g.start=(+d.start||1)+d.childNodes.length-1);C(d,b);C(g,b);(e=d.nextSibling)?c.insertBefore(g,e):c.appendChild(g);return J(c,g,a,b)}return f}function Ea(d,f){for(var a=d.childNodes,b=a.length,c=[],g,e;b--;)if(g=a[b],e=b&&a[b-1],b&&v(g)&&Ca(g,e)&&!ta[g.nodeName])f.startContainer===g&&(f.startContainer=e,f.startOffset+=
M(e)),f.endContainer===g&&(f.endContainer=e,f.endOffset+=M(e)),f.startContainer===d&&(f.startOffset>b?--f.startOffset:f.startOffset===b&&(f.startContainer=e,f.startOffset=M(e))),f.endContainer===d&&(f.endOffset>b?--f.endOffset:f.endOffset===b&&(f.endContainer=e,f.endOffset=M(e))),A(g),3===g.nodeType?e.appendData(g.data):c.push(y(g));else if(1===g.nodeType){for(e=c.length;e--;)g.appendChild(c.pop());Ea(g,f)}}function ca(d,f){3===d.nodeType&&(d=d.parentNode);if(1===d.nodeType){var a={startContainer:f.startContainer,
startOffset:f.startOffset,endContainer:f.endContainer,endOffset:f.endOffset};Ea(d,a);f.setStart(a.startContainer,a.startOffset);f.setEnd(a.endContainer,a.endOffset)}}function ha(d,f,a,b){for(var c=f,g;(g=c.parentNode)&&g!==b&&1===g.nodeType&&1===g.childNodes.length;)c=g;A(c);c=d.childNodes.length;(b=d.lastChild)&&"BR"===b.nodeName&&(d.removeChild(b),--c);d.appendChild(y(f));a.setStart(d,c);a.collapse(!0);ca(d,a);ia&&(b=d.lastChild)&&"BR"===b.nodeName&&d.removeChild(b)}function Q(d,f){var a=d.previousSibling,
b=d.firstChild,c=d.ownerDocument,g="LI"===d.nodeName;if(!g||b&&/^[OU]L$/.test(b.nodeName))if(a&&Ca(a,d)){if(3!==E(a))if(g)c=B(c,"DIV"),c.appendChild(y(a)),a.appendChild(c);else return;A(d);c=3!==E(d);a.appendChild(y(d));c&&N(a,f);b&&Q(b,f)}else g&&(a=B(c,"DIV"),d.insertBefore(a,b),C(a,f))}function Fa(d){this.isShiftDown=d.shiftKey}function da(d,f,a){var b;d||(d={});if(f)for(b in f)if(a||!(b in d)){var c=f[b];d[b]=c&&c.constructor===Object?da(d[b],c,a):c}return d}function wa(d,f){9===d.nodeType&&(d=
d.body);var a=d.ownerDocument,b=a.defaultView;this._win=b;this._doc=a;this._root=d;this._events={};this._isFocused=!1;this._lastSelection=null;bb&&this.addEventListener("beforedeactivate",this.getSelection);this._hasZWS=!1;this._lastFocusNode=this._lastAnchorNode=null;this._path="";this._willUpdatePath=!1;"onselectionchange"in a?this.addEventListener("selectionchange",this._updatePathOnEvent):(this.addEventListener("keyup",this._updatePathOnEvent),this.addEventListener("mouseup",this._updatePathOnEvent));
this._undoIndex=-1;this._undoStack=[];this._undoStackLength=0;this._ignoreAllChanges=this._ignoreChange=this._isInUndoState=!1;if(R){var c=new MutationObserver(this._docWasChanged.bind(this));c.observe(d,{childList:!0,attributes:!0,characterData:!0,subtree:!0});this._mutation=c}else this.addEventListener("keyup",this._keyUpDetectChange);this._restoreSelection=!1;this.addEventListener("blur",cb);this.addEventListener("mousedown",Ga);this.addEventListener("touchstart",Ga);this.addEventListener("focus",
db);this._awaitingPaste=!1;this.addEventListener(ea?"beforecut":"cut",eb);this.addEventListener("copy",fb);this.addEventListener("keydown",Fa);this.addEventListener("keyup",Fa);this.addEventListener(ea?"beforepaste":"paste",gb);this.addEventListener("drop",hb);this.addEventListener(ia?"keypress":"keydown",ib);this._keyHandlers=Object.create(F);this.setConfig(f);ea&&(b.Text.prototype.splitText=function(a){var b=this.ownerDocument.createTextNode(this.data.slice(a)),c=this.nextSibling,d=this.parentNode,
g=this.length-a;c?d.insertBefore(b,c):d.appendChild(b);g&&this.deleteData(a,g);return b});d.setAttribute("contenteditable","true");try{a.execCommand("enableObjectResizing",!1,"false"),a.execCommand("enableInlineTableEditing",!1,"false")}catch(g){}d.__squire__=this;this.setHTML("")}function cb(){this._restoreSelection=!0}function Ga(){this._restoreSelection=!1}function db(){this._restoreSelection&&this.setSelection(this._lastSelection)}function xa(d,f,a){for(f=f.firstChild;f;f=b){var b=f.nextSibling;
if(v(f)){if(3===f.nodeType||"BR"===f.nodeName||"IMG"===f.nodeName){a.appendChild(f);continue}}else if(u(f)){a.appendChild(d.createDefaultBlock([xa(d,f,d._doc.createDocumentFragment())]));continue}xa(d,f,a)}return a}var U=l.defaultView,S=navigator.userAgent,jb=/Android/.test(S),Ha=/iP(?:ad|hone|od)/.test(S),Ia=/Mac OS X/.test(S),kb=/Windows NT/.test(S),lb=/Gecko\//.test(S),ea=/Trident\/[456]\./.test(S),ia=!!U.opera,ja=/Edge\//.test(S),mb=!ja&&/WebKit\//.test(S),Ja=/Trident\/[4567]\./.test(S),G=Ia?
"meta-":"ctrl-",va=ea||ia,ua=ea||mb,bb=ea,R="undefined"!==typeof MutationObserver,ma="undefined"!==typeof WeakMap,O=/[^ \t\r\n]/,z=Array.prototype.indexOf,ya={1:1,2:2,3:4,8:128,9:256,11:1024},$a=function(){return!0};r.prototype.nextNode=function(){for(var d=this.currentNode,f=this.root,a=this.nodeType,b=this.filter,c;;){for(c=d.firstChild;!c&&d&&d!==f;)c=d.nextSibling,c||(d=d.parentNode);if(!c)return null;if(ya[c.nodeType]&a&&b(c))return this.currentNode=c;d=c}};r.prototype.previousNode=function(){for(var d=
this.currentNode,f=this.root,a=this.nodeType,b=this.filter,c;;){if(d===f)return null;if(c=d.previousSibling)for(;d=c.lastChild;)c=d;else c=d.parentNode;if(!c)return null;if(ya[c.nodeType]&a&&b(c))return this.currentNode=c;d=c}};r.prototype.previousPONode=function(){for(var d=this.currentNode,f=this.root,a=this.nodeType,b=this.filter,c;;){for(c=d.lastChild;!c&&d&&d!==f;)c=d.previousSibling,c||(d=d.parentNode);if(!c)return null;if(ya[c.nodeType]&a&&b(c))return this.currentNode=c;d=c}};var ab=/^(?:#text|A(?:BBR|CRONYM)?|B(?:R|D[IO])?|C(?:ITE|ODE)|D(?:ATA|EL|FN)|EM|FONT|HR|I(?:FRAME|MG|NPUT|NS)?|KBD|Q|R(?:P|T|UBY)|S(?:AMP|MALL|PAN|TR(?:IKE|ONG)|U[BP])?|TIME|U|VAR|WBR)$/,
ta={BR:1,HR:1,IFRAME:1,IMG:1,INPUT:1},na=ma?new WeakMap:null,za=function(d,f){for(var a=d.childNodes;f&&1===d.nodeType;)d=a[f-1],a=d.childNodes,f=a.length;return d},Ka=function(d,f){if(1===d.nodeType){var a=d.childNodes;if(f<a.length)d=a[f];else{for(;d&&!d.nextSibling;)d=d.parentNode;d&&(d=d.nextSibling)}}return d},P=function(d,f){var a=d.startContainer,b=d.startOffset,c=d.endContainer,g=d.endOffset;if(3===a.nodeType){var e=a.parentNode;var k=e.childNodes;if(b===a.length)b=z.call(k,a)+1,d.collapsed&&
(c=e,g=b);else{if(b){var n=a.splitText(b);c===a?(g-=b,c=n):c===e&&(g+=1);a=n}b=z.call(k,a)}a=e}else k=a.childNodes;e=k.length;b===e?a.appendChild(f):a.insertBefore(f,k[b]);a===c&&(g+=k.length-e);d.setStart(a,b);d.setEnd(c,g)},La=function(d,f,a){var b=d.startContainer,c=d.startOffset,g=d.endContainer,e=d.endOffset;f||(f=d.commonAncestorContainer);3===f.nodeType&&(f=f.parentNode);e=J(g,e,f,a);b=J(b,c,f,a);g=f.ownerDocument.createDocumentFragment();for(var k,n,m;b!==e;)c=b.nextSibling,g.appendChild(b),
b=c;b=f;c=e?z.call(f.childNodes,e):f.childNodes.length;(e=(k=f.childNodes[c])&&k.previousSibling)&&3===e.nodeType&&3===k.nodeType&&(b=e,c=e.length,n=e.data,m=k.data," "===n.charAt(n.length-1)&&" "===m.charAt(0)&&(m=" "+m.slice(1)),e.appendData(m),A(k));d.setStart(b,c);d.collapse(!0);C(f,a);return g},Z=function(d,f){var a=K(d,f),b=V(d,f),c=a!==b;L(d);W(d,a,b,f);var g=La(d,null,f);L(d);c&&(b=V(d,f),a&&b&&a!==b&&ha(a,b,d,f));a&&C(a,f);(a=f.firstChild)&&"BR"!==a.nodeName?d.collapse(!0):(C(f,f),d.selectNodeContents(f.firstChild));
return g},nb=function(d,f,a){var b,c;N(f,a);for(b=f;b=t(b,a);)C(b,a);d.collapsed||Z(d,a);L(d);d.collapse(!1);var g=x(d.endContainer,a,"BLOCKQUOTE")||a;var e=K(d,a);var k=t(f,f);var n=!!e&&!e.textContent&&!e.querySelector("IMG");if(e&&k&&!n&&!x(k,f,"PRE")&&!x(k,f,"TABLE")){W(d,e,e,a);d.collapse(!0);var m=d.endContainer;var h=d.endOffset;pa(e,a,!1);v(m)&&(b=J(m,h,I(m,a),a),m=b.parentNode,h=z.call(m.childNodes,b));if(h!==M(m))for(c=a.ownerDocument.createDocumentFragment();b=m.childNodes[h];)c.appendChild(b);
ha(m,k,d,a);h=z.call(m.parentNode.childNodes,m)+1;m=m.parentNode;d.setEnd(m,h)}M(f)&&(n&&(d.setEndBefore(e),d.collapse(!1),A(e)),W(d,g,g,a),n=(b=J(d.endContainer,d.endOffset,g,a))?b.previousSibling:g.lastChild,g.insertBefore(f,b),b?d.setEndBefore(b):d.setEnd(g,M(g)),e=V(d,a),L(d),m=d.endContainer,h=d.endOffset,b&&3===E(b)&&Q(b,a),(b=n&&n.nextSibling)&&3===E(b)&&Q(b,a),d.setEnd(m,h));c&&(f=d.cloneRange(),ha(e,c,f,a),d.setEnd(f.endContainer,f.endOffset));L(d)},X=function(d,f,a){var b=f.ownerDocument.createRange();
b.selectNode(f);if(a)return f=-1<d.compareBoundaryPoints(3,b),d=1>d.compareBoundaryPoints(1,b),!f&&!d;f=1>d.compareBoundaryPoints(0,b);d=-1<d.compareBoundaryPoints(2,b);return f&&d},L=function(d){for(var f=d.startContainer,a=d.startOffset,b=d.endContainer,c=d.endOffset,g=!0,e;3!==f.nodeType;){e=f.childNodes[a];if(!e||w(e))break;f=e;a=0}if(c)for(;3!==b.nodeType;){e=b.childNodes[c-1];if(!e||w(e)){if(g&&e&&"BR"===e.nodeName){--c;g=!1;continue}break}b=e;c=M(b)}else for(;3!==b.nodeType;){e=b.firstChild;
if(!e||w(e))break;b=e}d.collapsed?(d.setStart(b,c),d.setEnd(f,a)):(d.setStart(f,a),d.setEnd(b,c))},W=function(d,f,a,b){var c=d.startContainer,g=d.startOffset,e=d.endContainer,k=d.endOffset,n=!0;f||(f=d.commonAncestorContainer);for(a||(a=f);!g&&c!==f&&c!==b;){var m=c.parentNode;g=z.call(m.childNodes,c);c=m}for(;;){n&&3!==e.nodeType&&e.childNodes[k]&&"BR"===e.childNodes[k].nodeName&&(k+=1,n=!1);if(e===a||e===b||k!==M(e))break;m=e.parentNode;k=z.call(m.childNodes,e)+1;e=m}d.setStart(c,g);d.setEnd(e,
k)},K=function(d,f){var a=d.startContainer;v(a)?a=I(a,f):a!==f&&u(a)||(a=za(a,d.startOffset),a=t(a,f));return a&&X(d,a,!0)?a:null},V=function(d,f){var a=d.endContainer,b;if(v(a))a=I(a,f);else if(a===f||!u(a)){a=Ka(a,d.endOffset);if(!a||!oa(f,a))for(a=f;b=a.lastChild;)a=b;a=I(a,f)}return a&&X(d,a,!0)?a:null},T=new r(null,5,function(d){return 3===d.nodeType?O.test(d.data):"IMG"===d.nodeName}),qa=function(d,f){var a=d.startContainer,b=d.startOffset;T.root=null;if(3===a.nodeType){if(b)return!1;var c=
a}else if((c=Ka(a,b))&&!oa(f,c)&&(c=null),!c&&(c=za(a,b),3===c.nodeType&&c.length))return!1;T.currentNode=c;T.root=K(d,f);return!T.previousNode()},Ma=function(d,f){var a=d.endContainer,b=d.endOffset,c;T.root=null;if(3===a.nodeType){if((c=a.data.length)&&b<c)return!1;T.currentNode=a}else T.currentNode=za(a,b);T.root=V(d,f);return!T.nextNode()},Na=function(d,f){var a=K(d,f);f=V(d,f);if(a&&f){var b=a.parentNode;d.setStart(b,z.call(b.childNodes,a));b=f.parentNode;d.setEnd(b,z.call(b.childNodes,f)+1)}},
ob={8:"backspace",9:"tab",13:"enter",32:"space",33:"pageup",34:"pagedown",37:"left",39:"right",46:"delete",219:"[",221:"]"},ib=function(d){var f=d.keyCode,a=ob[f],b="",c=this.getSelection();if(!d.defaultPrevented)if(a||(a=String.fromCharCode(f).toLowerCase(),/^[A-Za-z0-9]$/.test(a)||(a="")),ia&&46===d.which&&(a="."),111<f&&124>f&&(a="f"+(f-111)),"backspace"!==a&&"delete"!==a&&(d.altKey&&(b+="alt-"),d.ctrlKey&&(b+="ctrl-"),d.metaKey&&(b+="meta-")),d.shiftKey&&(b+="shift-"),a=b+a,this._keyHandlers[a])this._keyHandlers[a](this,
d,c);else c.collapsed||d.isComposing||d.ctrlKey||d.metaKey||1!==(d.key||a).length||(this.saveUndoState(c),Z(c,this._root),this._ensureBottomLine(),this.setSelection(c),this._updatePath(c,!0))},Y=function(d){return function(f,a){a.preventDefault();f[d]()}},fa=function(d,f){f=f||null;return function(a,b){b.preventDefault();b=a.getSelection();a.hasFormat(d,null,b)?a.changeFormat(null,{tag:d},b):a.changeFormat({tag:d},f,b)}},ka=function(d,f){try{f||(f=d.getSelection());var a=f.startContainer,b;3===a.nodeType&&
(a=a.parentNode);for(b=a;v(b)&&(!b.textContent||"\u200b"===b.textContent);)a=b,b=a.parentNode;a!==b&&(f.setStart(b,z.call(b.childNodes,a)),f.collapse(!0),b.removeChild(a),u(b)||(b=I(b,d._root)),C(b,d._root),L(f));a===d._root&&(a=a.firstChild)&&"BR"===a.nodeName&&A(a);d._ensureBottomLine();d.setSelection(f);d._updatePath(f,!0)}catch(c){d.didError(c)}},Pa=function(d,f,a){var b=d._root,c,g;d._recordUndoState(a);d._config.addLinks&&Aa(a.startContainer,b,d);d._removeZWS();d._getRangeAndRemoveBookmark(a);
a.collapsed||Z(a,b);if((c=K(a,b))&&(g=x(c,b,"PRE"))){L(a);c=a.startContainer;var e=a.startOffset;3!==c.nodeType&&(c=d._doc.createTextNode(""),g.insertBefore(c,g.firstChild));f||"\n"!==c.data.charAt(e-1)&&!qa(a,b)||"\n"!==c.data.charAt(e)&&!Ma(a,b)?(c.insertData(e,"\n"),C(g,b),c.length===e+1?a.setStartAfter(c):a.setStart(c,e+1)):(c.deleteData(e&&e-1,e?2:1),f=J(c,e&&e-1,b,b),c=f.previousSibling,c.textContent||A(c),c=d.createDefaultBlock(),f.parentNode.insertBefore(c,f),f.textContent||A(f),a.setStart(c,
0));a.collapse(!0);d.setSelection(a);d._updatePath(a,!0);d._docWasChanged()}else{if(!c||f||/^T[HD]$/.test(c.nodeName)){if(g=x(a.endContainer,b,"A"))g=g.parentNode,W(a,g,g,b),a.collapse(!1);P(a,d.createElement("BR"));a.collapse(!1)}else{if(g=x(c,b,"LI"))c=g;if(!c.textContent&&!c.querySelector("IMG")){if(x(c,b,"UL")||x(c,b,"OL"))return d.decreaseListLevel(a);if(x(c,b,"BLOCKQUOTE"))return d.modifyBlocks(pb,a)}e=c;f=qb[e.nodeName];g=null;a=J(a.startContainer,a.startOffset,e.parentNode,d._root);e=d._config;
f||(f=e.blockTag,g=e.blockAttributes);sa(a,f,g)||(e=B(a.ownerDocument,f,g),a.dir&&(e.dir=a.dir),H(a,e),e.appendChild(y(a)),a=e);f=a;Ba(c);Oa(c);for(C(c,b);1===f.nodeType;){b=f.firstChild;if("A"===f.nodeName&&(!f.textContent||"\u200b"===f.textContent)){b=d._doc.createTextNode("");H(f,b);f=b;break}for(;b&&3===b.nodeType&&!b.data;){a=b.nextSibling;if(!a||"BR"===a.nodeName)break;A(b);b=a}if(!b||"BR"===b.nodeName||3===b.nodeType&&!ia)break;f=b}a=d.createRange(f,0)}d.setSelection(a);d._updatePath(a,!0)}},
F={enter:Ha?function(d,f,a){d._saveRangeToBookmark(a);var b=d._getHTML(),c=function(){d.removeEventListener("keyup",c);d._setHTML(b);a=d._getRangeAndRemoveBookmark();Pa(d,!1,a)};d.addEventListener("keyup",c)}:function(d,f,a){f.preventDefault();Pa(d,f.shiftKey,a)},"shift-enter":function(d,f,a){return d._keyHandlers.enter(d,f,a)},backspace:function(d,f,a){var b=d._root;d._removeZWS();d.saveUndoState(a);if(a.collapsed)if(qa(a,b)){f.preventDefault();f=K(a,b);var c;if(f)if(N(f.parentNode,b),c=I(f,b))if(c.isContentEditable){ha(c,
f,a,b);for(f=c.parentNode;f!==b&&!f.nextSibling;)f=f.parentNode;f!==b&&(f=f.nextSibling)&&Q(f,b);d.setSelection(a)}else A(c);else if(f){if(x(f,b,"UL")||x(f,b,"OL"))return d.decreaseListLevel(a);if(x(f,b,"BLOCKQUOTE"))return d.modifyBlocks(Qa,a);d.setSelection(a);d._updatePath(a,!0)}}else d.setSelection(a),setTimeout(function(){ka(d)},0);else f.preventDefault(),Z(a,b),ka(d,a)},"delete":function(d,f,a){var b=d._root,c;d._removeZWS();d.saveUndoState(a);if(a.collapsed)if(Ma(a,b)){if(f.preventDefault(),
f=K(a,b))if(N(f.parentNode,b),c=t(f,b))if(c.isContentEditable){ha(f,c,a,b);for(c=f.parentNode;c!==b&&!c.nextSibling;)c=c.parentNode;c!==b&&(c=c.nextSibling)&&Q(c,b);d.setSelection(a);d._updatePath(a,!0)}else A(c)}else{c=a.cloneRange();W(a,b,b,b);b=a.endContainer;var g=a.endOffset;if(1===b.nodeType&&(b=b.childNodes[g])&&"IMG"===b.nodeName){f.preventDefault();A(b);L(a);ka(d,a);return}d.setSelection(c);setTimeout(function(){ka(d)},0)}else f.preventDefault(),Z(a,b),ka(d,a)},tab:function(d,f,a){var b=
d._root;d._removeZWS();if(a.collapsed)if(qa(a,b))for(b=K(a,b);b=b.parentNode;){if("UL"===b.nodeName||"OL"===b.nodeName){f.preventDefault();d.increaseListLevel(a);break}}else b=document.createElement("span"),b.appendChild(document.createTextNode("\t")),b.style.whiteSpace="pre",a.insertNode(b),a.setStartAfter(b),a.setEndAfter(b),d.setSelection(a),f.preventDefault()},"shift-tab":function(d,f,a){var b=d._root;d._removeZWS();if(a.collapsed&&qa(a,b)){var c=a.startContainer;if(x(c,b,"UL")||x(c,b,"OL"))f.preventDefault(),
d.decreaseListLevel(a)}},space:function(d,f,a){var b=d._root;d._recordUndoState(a);d._config.addLinks&&Aa(a.startContainer,b,d);d._getRangeAndRemoveBookmark(a);f=a.endContainer;if(a.collapsed&&a.endOffset===M(f)){do if("A"===f.nodeName){a.setStartAfter(f);break}while(!f.nextSibling&&(f=f.parentNode)&&f!==b)}a.collapsed||(Z(a,b),d._ensureBottomLine(),d.setSelection(a),d._updatePath(a,!0));d.setSelection(a)},left:function(d){d._removeZWS()},right:function(d){d._removeZWS()}};Ia||(F.pageup=function(d){d.moveCursorToStart()},
F.pagedown=function(d){d.moveCursorToEnd()});F[G+"b"]=fa("B");F[G+"i"]=fa("I");F[G+"u"]=fa("U");F[G+"shift-7"]=fa("S");F[G+"shift-5"]=fa("SUB",{tag:"SUP"});F[G+"shift-6"]=fa("SUP",{tag:"SUB"});F[G+"shift-8"]=Y("makeUnorderedList");F[G+"shift-9"]=Y("makeOrderedList");F[G+"["]=Y("decreaseQuoteLevel");F[G+"]"]=Y("increaseQuoteLevel");F[G+"d"]=Y("toggleCode");F[G+"y"]=Y("redo");F[G+"z"]=Y("undo");F[G+"shift-z"]=Y("redo");var rb={1:10,2:13,3:16,4:18,5:24,6:32,7:48},Ra={backgroundColor:{regexp:O,replace:function(d,
f,a){return B(d,"SPAN",{"class":f.highlight,style:"background-color:"+a})}},color:{regexp:O,replace:function(d,f,a){return B(d,"SPAN",{"class":f.colour,style:"color:"+a})}},fontWeight:{regexp:/^bold|^700/i,replace:function(d){return B(d,"B")}},fontStyle:{regexp:/^italic/i,replace:function(d){return B(d,"I")}},fontFamily:{regexp:O,replace:function(d,f,a){return B(d,"SPAN",{"class":f.fontFamily,style:"font-family:"+a})}},fontSize:{regexp:O,replace:function(d,f,a){return B(d,"SPAN",{"class":f.fontSize,
style:"font-size:"+a})}},textDecoration:{regexp:/^underline/i,replace:function(d){return B(d,"U")}}},ra=function(d){return function(f,a){var b=B(f.ownerDocument,d);a.replaceChild(b,f);b.appendChild(y(f));return b}},Sa=function(d,f,a){var b=d.style,c=d.ownerDocument,g,e,k;for(g in Ra){var n=Ra[g];if((e=b[g])&&n.regexp.test(e)){n=n.replace(c,a.classNames,e);k||(k=n);m&&m.appendChild(n);var m=n;d.style[g]=""}}k&&(m.appendChild(y(d)),"SPAN"===d.nodeName?f.replaceChild(k,d):d.appendChild(k));return m||
d},sb={P:Sa,SPAN:Sa,STRONG:ra("B"),EM:ra("I"),INS:ra("U"),STRIKE:ra("S"),FONT:function(d,f,a){var b=d.face,c=d.size,g=d.color,e=d.ownerDocument;a=a.classNames;var k;if(b)var n=k=B(e,"SPAN",{"class":a.fontFamily,style:"font-family:"+b});c&&(c=B(e,"SPAN",{"class":a.fontSize,style:"font-size:"+rb[c]+"px"}),n||(n=c),k&&k.appendChild(c),k=c);g&&/^#?([\dA-F]{3}){1,2}$/i.test(g)&&("#"!==g.charAt(0)&&(g="#"+g),g=B(e,"SPAN",{"class":a.colour,style:"color:"+g}),n||(n=g),k&&k.appendChild(g),k=g);n||(n=k=B(e,
"SPAN"));f.replaceChild(n,d);k.appendChild(y(d));return k},TT:function(d,f,a){a=B(d.ownerDocument,"SPAN",{"class":a.classNames.fontFamily,style:'font-family:menlo,consolas,"courier new",monospace'});f.replaceChild(a,d);a.appendChild(y(d));return a}},tb=/^(?:A(?:DDRESS|RTICLE|SIDE|UDIO)|BLOCKQUOTE|CAPTION|D(?:[DLT]|IV)|F(?:IGURE|IGCAPTION|OOTER)|H[1-6]|HEADER|L(?:ABEL|EGEND|I)|O(?:L|UTPUT)|P(?:RE)?|SECTION|T(?:ABLE|BODY|D|FOOT|H|HEAD|R)|COL(?:GROUP)?|UL)$/,ub=/^(?:HEAD|META|STYLE)/,la=new r(null,5),
Ta=function c(f,a,b){var g=f.childNodes,e,k;for(e=f;v(e);)e=e.parentNode;la.root=e;e=0;for(k=g.length;e<k;e+=1){var n=g[e];var m=n.nodeName;var h=n.nodeType;var l=sb[m];if(1===h){h=n.childNodes.length;if(l)n=l(n,f,a);else if(ub.test(m)){f.removeChild(n);--e;--k;continue}else if(!tb.test(m)&&!v(n)){--e;k+=h-1;f.replaceChild(y(n),n);continue}h&&c(n,a,b||"PRE"===m)}else{if(3===h){h=n.data;var q=!O.test(h.charAt(0));l=!O.test(h.charAt(h.length-1));if(b||!q&&!l)continue;if(q){for(la.currentNode=n;q=la.previousPONode();){m=
q.nodeName;if("IMG"===m||"#text"===m&&O.test(q.data))break;if(!v(q)){q=null;break}}h=h.replace(/^[ \t\r\n]+/g,q?" ":"")}if(l){for(la.currentNode=n;(q=la.nextNode())&&!("IMG"===m||"#text"===m&&O.test(q.data));)if(!v(q)){q=null;break}h=h.replace(/[ \t\r\n]+$/g,q?" ":"")}if(h){n.data=h;continue}}f.removeChild(n);--e;--k}}return f},Oa=function b(a){for(var c=a.childNodes,g=c.length,e;g--;)e=c[g],1!==e.nodeType||w(e)?3!==e.nodeType||e.data||a.removeChild(e):(b(e),v(e)&&!e.firstChild&&a.removeChild(e))},
wb=function(a){return 1===a.nodeType?"BR"===a.nodeName:O.test(a.data)},Ua=function(a,b){for(var c=a.parentNode;v(c);)c=c.parentNode;c=new r(c,5,wb);c.currentNode=a;return!!c.nextNode()||b&&!c.previousNode()},pa=function(a,b,c){a=a.querySelectorAll("BR");var g=[],e=a.length,k;for(k=0;k<e;k+=1)g[k]=Ua(a[k],c);for(;e--;)c=a[e],(k=c.parentNode)&&(g[e]?v(k)||N(k,b):A(c))},Va=function(a,b,c,g){var e=b.ownerDocument.body;g=g.willCutCopy;pa(b,c,!0);b.setAttribute("style","position:fixed;overflow:hidden;bottom:100%;right:100%;");
e.appendChild(b);c=b.innerHTML;var k=b.innerText||b.textContent;g&&(c=g(c));kb&&(k=k.replace(/\r?\n/g,"\r\n"));a.setData("text/html",c);a.setData("text/plain",k);e.removeChild(b)},eb=function(a){var b=a.clipboardData,c=this.getSelection(),g=this._root,e=this;if(c.collapsed)a.preventDefault();else{this.saveUndoState(c);if(!ja&&b){var k=K(c,g);var n=V(c,g);n=k===n&&k||g;k=Z(c,g);var m=c.commonAncestorContainer;3===m.nodeType&&(m=m.parentNode);for(;m&&m!==n;){var h=m.cloneNode(!1);h.appendChild(k);k=
h;m=m.parentNode}n=this.createElement("div");n.appendChild(k);Va(b,n,g,this._config);a.preventDefault()}else setTimeout(function(){try{e._ensureBottomLine()}catch(vb){e.didError(vb)}},0);this.setSelection(c)}},fb=function(a){var b=a.clipboardData,c=this.getSelection(),g=this._root;if(!ja&&b){var e=K(c,g);var k=V(c,g);k=e===k&&e||g;c=c.cloneRange();L(c);W(c,k,k,g);e=c.cloneContents();c=c.commonAncestorContainer;3===c.nodeType&&(c=c.parentNode);for(;c&&c!==k;){var n=c.cloneNode(!1);n.appendChild(e);
e=n;c=c.parentNode}c=this.createElement("div");c.appendChild(e);Va(b,c,g,this._config);a.preventDefault()}},gb=function(a){var b=a.clipboardData,c=b&&b.items,g=this.isShiftDown,e=!1,k=!1,n=!1,m=null,h=null,l=this,q;if(c){var p=c.length;for(var r={};p--;){var aa=c[p];var t=aa.type;"text/html"===t?h=aa:"text/plain"===t||"text/uri-list"===t?m=aa:"text/rtf"===t?k=!0:/^image\/.*/.test(t)&&(n=!0,aa.getAsFile&&window.FileReader&&(aa=aa.getAsFile()))&&(r.$jscomp$loop$prop$box$2=parent.$("hin"),parent.readBlobAsDataURL(aa).then(function(a){return function(b){return parent.postPromise("/sims/dataurlSave.jsp",
{a:parent.ap,d:b,cw:a.$jscomp$loop$prop$box$2.clientWidth,ch:a.$jscomp$loop$prop$box$2.clientHeight,RTE:"true"})}}(r)).then(function(a){return function(b){b&&3<b.length&&(b=b.replace("&amp;","&"),l.insertImage(b),parent.insertAtCursor(a.$jscomp$loop$prop$box$2,b))}}(r)));r={$jscomp$loop$prop$box$2:r.$jscomp$loop$prop$box$2}}if(n&&(!k||!h)){a.preventDefault();this.fireEvent("dragover",{dataTransfer:b,preventDefault:function(){e=!0}});e&&this.fireEvent("drop",{dataTransfer:b});return}if(!ja){a.preventDefault();
!h||g&&m?m&&m.getAsString(function(a){l.insertPlainText(a,!0)}):h.getAsString(function(a){l.insertHTML(a,!0)});return}}c=b&&b.types;if(!ja&&c&&(-1<z.call(c,"text/html")||!lb&&-1<z.call(c,"text/plain")&&0>z.call(c,"text/rtf")))a.preventDefault(),!g&&(q=b.getData("text/html"))?this.insertHTML(q,!0):((q=b.getData("text/plain"))||(q=b.getData("text/uri-list")))&&this.insertPlainText(q,!0);else{this._awaitingPaste=!0;a=this._doc.body;b=this.getSelection();var v=b.startContainer,w=b.startOffset,x=b.endContainer,
y=b.endOffset,u=this.createElement("DIV",{contenteditable:"true",style:"position:fixed; overflow:hidden; top:0; right:100%; width:1px; height:1px;"});a.appendChild(u);b.selectNodeContents(u);this.setSelection(b);setTimeout(function(){try{l._awaitingPaste=!1;for(var a="",b=u,c,e;u=b;)b=u.nextSibling,A(u),(c=u.firstChild)&&c===u.lastChild&&"DIV"===c.nodeName&&(u=c),a+=u.innerHTML;e=l.createRange(v,w,x,y);l.setSelection(e);a&&l.insertHTML(a,!0)}catch(xb){l.didError(xb)}},0)}},hb=function(a){a=a.dataTransfer.types;
for(var b=a.length,c=!1,g=!1;b--;)switch(a[b]){case "text/plain":c=!0;break;case "text/html":g=!0;break;default:return}(g||c)&&this.saveUndoState()},h=wa.prototype,yb=function(a,b,c){b=c._doc;return(a=a?DOMPurify.sanitize(a,{ALLOW_UNKNOWN_PROTOCOLS:!0,WHOLE_DOCUMENT:!1,RETURN_DOM:!0,RETURN_DOM_FRAGMENT:!0}):null)?b.importNode(a,!0):b.createDocumentFragment()};h.setConfig=function(a){a=da({blockTag:"DIV",blockAttributes:null,tagAttributes:{blockquote:null,ul:null,ol:null,li:null,a:null},classNames:{colour:"colour",
fontFamily:"font",fontSize:"size",highlight:"highlight"},leafNodeNames:ta,undo:{documentSizeThreshold:-1,undoLimit:-1},isInsertedHTMLSanitized:!0,isSetHTMLSanitized:!0,sanitizeToDOMFragment:"undefined"!==typeof DOMPurify&&DOMPurify.isSupported?yb:null,willCutCopy:null,addLinks:!0},a,!0);a.blockTag=a.blockTag.toUpperCase();this._config=a;return this};h.createElement=function(a,b,c){return B(this._doc,a,b,c)};h.createDefaultBlock=function(a){var b=this._config;return C(this.createElement(b.blockTag,
b.blockAttributes,a),this._root)};h.didError=function(a){console.log(a)};h.getDocument=function(){return this._doc};h.getRoot=function(){return this._root};h.modifyDocument=function(a){var b=this._mutation;b&&(b.takeRecords().length&&this._docWasChanged(),b.disconnect());this._ignoreAllChanges=!0;a();this._ignoreAllChanges=!1;b&&(b.observe(this._root,{childList:!0,attributes:!0,characterData:!0,subtree:!0}),this._ignoreChange=!1)};var Wa={pathChange:1,select:1,input:1,undoStateChange:1};h.fireEvent=
function(a,b){var c=this._events[a];if(/^(?:focus|blur)/.test(a)){var g=this._root===this._doc.activeElement;if("focus"===a){if(!g||this._isFocused)return this;this._isFocused=!0}else{if(g||!this._isFocused)return this;this._isFocused=!1}}if(c)for(b||(b={}),b.type!==a&&(b.type=a),c=c.slice(),g=c.length;g--;){var e=c[g];try{e.handleEvent?e.handleEvent(b):e.call(this,b)}catch(k){k.details="Squire: fireEvent error. Event type: "+a,this.didError(k)}}return this};h.destroy=function(){var a=this._events,
b;for(b in a)this.removeEventListener(b);this._mutation&&this._mutation.disconnect();delete this._root.__squire__;this._undoIndex=-1;this._undoStack=[];this._undoStackLength=0};h.handleEvent=function(a){this.fireEvent(a.type,a)};h.addEventListener=function(a,b){var c=this._events[a],g=this._root;if(!b)return this.didError({name:"Squire: addEventListener with null or undefined fn",message:"Event type: "+a}),this;c||(c=this._events[a]=[],Wa[a]||("selectionchange"===a&&(g=this._doc),g.addEventListener(a,
this,!0)));c.push(b);return this};h.removeEventListener=function(a,b){var c=this._events[a],g=this._root,e;if(c){if(b)for(e=c.length;e--;)c[e]===b&&c.splice(e,1);else c.length=0;c.length||(delete this._events[a],Wa[a]||("selectionchange"===a&&(g=this._doc),g.removeEventListener(a,this,!0)))}return this};h.createRange=function(a,b,c,g){if(a instanceof this._win.Range)return a.cloneRange();var e=this._doc.createRange();e.setStart(a,b);c?e.setEnd(c,g):e.setEnd(a,b);return e};h.getCursorPosition=function(a){if(!a&&
!(a=this.getSelection())||!a.getBoundingClientRect)return null;var b=a.getBoundingClientRect();if(b&&!b.top){this._ignoreChange=!0;var c=this._doc.createElement("SPAN");c.textContent="\u200b";P(a,c);b=c.getBoundingClientRect();var g=c.parentNode;g.removeChild(c);ca(g,a)}return b};h._moveCursorTo=function(a){var b=this._root;a=this.createRange(b,a?0:b.childNodes.length);L(a);this.setSelection(a);return this};h.moveCursorToStart=function(){return this._moveCursorTo(!0)};h.moveCursorToEnd=function(){return this._moveCursorTo(!1)};
h.setSelection=function(a){if(a)if(this._lastSelection=a,this._isFocused)if(jb&&!this._restoreSelection)this._restoreSelection=!0,this.blur(),this.focus();else{Ha&&this._win.focus();var b=this._win.getSelection()||null;b&&(b.removeAllRanges(),b.addRange(a))}else this._restoreSelection=!0;return this};h.getSelection=function(){var a=this._win.getSelection()||null,b=this._root;if(this._isFocused&&a&&a.rangeCount){var c=a.getRangeAt(0).cloneRange();a=c.startContainer;var g=c.endContainer;a&&w(a)&&c.setStartBefore(a);
g&&w(g)&&c.setEndBefore(g)}c&&oa(b,c.commonAncestorContainer)?this._lastSelection=c:(c=this._lastSelection,a=c.commonAncestorContainer,oa(a.ownerDocument,a)||(c=null));c||(c=this.createRange(b.firstChild,0));return c};h.getSelectedText=function(){var a=this.getSelection();if(!a||a.collapsed)return"";var b=new r(a.commonAncestorContainer,5,function(b){return X(a,b,!0)}),c=a.startContainer,g=a.endContainer,e=b.currentNode=c,k="",n=!1,m;for(b.filter(e)||(e=b.nextNode());e;){if(3===e.nodeType)(m=e.data)&&
/\S/.test(m)&&(e===g&&(m=m.slice(0,a.endOffset)),e===c&&(m=m.slice(a.startOffset)),k+=m,n=!0);else if("BR"===e.nodeName||n&&!v(e))k+="\n",n=!1;e=b.nextNode()}return k};h.getPath=function(){return this._path};var Ba=function(a,b){a=new r(a,4);for(var c,g;g=a.nextNode();)for(;-1<(c=g.data.indexOf("\u200b"))&&(!b||g.parentNode!==b);)if(1===g.length){do c=g.parentNode,c.removeChild(g),g=c,a.currentNode=c;while(v(g)&&!M(g));break}else g.deleteData(c,1)};h._didAddZWS=function(){this._hasZWS=!0};h._removeZWS=
function(){this._hasZWS&&(Ba(this._root),this._hasZWS=!1)};h._updatePath=function(a,b){if(a){var c=a.startContainer,g=a.endContainer;if(b||c!==this._lastAnchorNode||g!==this._lastFocusNode)this._lastAnchorNode=c,this._lastFocusNode=g,b=c&&g?c===g?Da(g,this._root,this._config):"(selection)":"",this._path!==b&&(this._path=b,this.fireEvent("pathChange",{path:b}));this.fireEvent(a.collapsed?"cursor":"select",{range:a})}};h._updatePathOnEvent=function(a){var b=this;b._isFocused&&!b._willUpdatePath&&(b._willUpdatePath=
!0,setTimeout(function(){b._willUpdatePath=!1;b._updatePath(b.getSelection())},0))};h.focus=function(){this._root.focus({preventScroll:!0});Ja&&this.fireEvent("focus");return this};h.blur=function(){this._root.blur();Ja&&this.fireEvent("blur");return this};h._saveRangeToBookmark=function(a){var b=this.createElement("INPUT",{id:"squire-selection-start",type:"hidden"}),c=this.createElement("INPUT",{id:"squire-selection-end",type:"hidden"});P(a,b);a.collapse(!1);P(a,c);if(b.compareDocumentPosition(c)&
2){b.id="squire-selection-end";c.id="squire-selection-start";var g=b;b=c;c=g}a.setStartAfter(b);a.setEndBefore(c)};h._getRangeAndRemoveBookmark=function(a){var b=this._root,c=b.querySelector("#squire-selection-start");b=b.querySelector("#squire-selection-end");if(c&&b){var g=c.parentNode,e=b.parentNode,k=z.call(g.childNodes,c),n=z.call(e.childNodes,b);g===e&&--n;A(c);A(b);a||(a=this._doc.createRange());a.setStart(g,k);a.setEnd(e,n);ca(g,a);g!==e&&ca(e,a);a.collapsed&&(g=a.startContainer,3===g.nodeType&&
((e=g.childNodes[a.startOffset])&&3===e.nodeType||(e=g.childNodes[a.startOffset-1]),e&&3===e.nodeType&&(a.setStart(e,0),a.collapse(!0))))}return a||null};h._keyUpDetectChange=function(a){var b=a.keyCode;a.ctrlKey||a.metaKey||a.altKey||!(16>b||20<b)||!(33>b||45<b)||this._docWasChanged()};h._docWasChanged=function(){ma&&(na=new WeakMap);this._ignoreAllChanges||(R&&this._ignoreChange?this._ignoreChange=!1:(this._isInUndoState&&(this._isInUndoState=!1,this.fireEvent("undoStateChange",{canUndo:!0,canRedo:!1})),
this.fireEvent("input")))};h._recordUndoState=function(a,b){if(!this._isInUndoState||b){var c=this._undoIndex,g=this._undoStack,e=this._config.undo,k=e.documentSizeThreshold;e=e.undoLimit;b||(c+=1);c<this._undoStackLength&&(g.length=this._undoStackLength=c);a&&this._saveRangeToBookmark(a);a=this._getHTML();-1<k&&2*a.length>k&&-1<e&&c>e&&(g.splice(0,c-e),this._undoStackLength=c=e);g[c]=a;this._undoIndex=c;this._undoStackLength+=1;this._isInUndoState=!0}};h.saveUndoState=function(a){a===p&&(a=this.getSelection());
this._recordUndoState(a,this._isInUndoState);this._getRangeAndRemoveBookmark(a);return this};h.undo=function(){if(0!==this._undoIndex||!this._isInUndoState){this._recordUndoState(this.getSelection(),!1);--this._undoIndex;this._setHTML(this._undoStack[this._undoIndex]);var a=this._getRangeAndRemoveBookmark();a&&this.setSelection(a);this._isInUndoState=!0;this.fireEvent("undoStateChange",{canUndo:0!==this._undoIndex,canRedo:!0});this.fireEvent("input")}return this};h.redo=function(){var a=this._undoIndex,
b=this._undoStackLength;if(a+1<b&&this._isInUndoState){this._undoIndex+=1;this._setHTML(this._undoStack[this._undoIndex]);var c=this._getRangeAndRemoveBookmark();c&&this.setSelection(c);this.fireEvent("undoStateChange",{canUndo:!0,canRedo:a+2<b});this.fireEvent("input")}return this};h.hasFormat=function(a,b,c){a=a.toUpperCase();b||(b={});if(!c&&!(c=this.getSelection()))return!1;!c.collapsed&&3===c.startContainer.nodeType&&c.startOffset===c.startContainer.length&&c.startContainer.nextSibling&&c.setStartBefore(c.startContainer.nextSibling);
!c.collapsed&&3===c.endContainer.nodeType&&0===c.endOffset&&c.endContainer.previousSibling&&c.setEndAfter(c.endContainer.previousSibling);var g=this._root,e=c.commonAncestorContainer,k;if(x(e,g,a,b))return!0;if(3===e.nodeType)return!1;e=new r(e,4,function(a){return X(c,a,!0)});for(var n=!1;k=e.nextNode();){if(!x(k,g,a,b))return!1;n=!0}return n};h.getFontInfo=function(a){var b={color:p,backgroundColor:p,family:p,size:p},c=0,g;if(!a&&!(a=this.getSelection()))return b;var e=a.commonAncestorContainer;
if(a.collapsed||3===e.nodeType)for(3===e.nodeType&&(e=e.parentNode);4>c&&e;){if(a=e.style)!b.color&&(g=a.color)&&(b.color=g,c+=1),!b.backgroundColor&&(g=a.backgroundColor)&&(b.backgroundColor=g,c+=1),!b.family&&(g=a.fontFamily)&&(b.family=g,c+=1),!b.size&&(g=a.fontSize)&&(b.size=g,c+=1);e=e.parentNode}return b};h._addFormat=function(a,b,c){var g=this._root;if(c.collapsed){var e=C(this.createElement(a,b),g);P(c,e);c.setStart(e.firstChild,e.firstChild.length);c.collapse(!0);for(a=e;v(a);)a=a.parentNode;
Ba(a,e)}else{var k=new r(c.commonAncestorContainer,5,function(a){return(3===a.nodeType||"BR"===a.nodeName||"IMG"===a.nodeName)&&X(c,a,!0)});var n=c.startContainer;var h=c.startOffset;var l=c.endContainer;var p=c.endOffset;k.currentNode=n;k.filter(n)||(n=k.nextNode(),h=0);if(!n)return c;do{var q=k.currentNode;if(e=!x(q,g,a,b))q===l&&q.length>p&&q.splitText(p),q===n&&h&&(q=q.splitText(h),l===n&&(l=q,p-=h),n=q,h=0),e=this.createElement(a,b),H(q,e),e.appendChild(q)}while(k.nextNode());3!==l.nodeType&&
(3===q.nodeType?(l=q,p=q.length):(l=q.parentNode,p=1));c=this.createRange(n,h,l,p)}return c};h._removeFormat=function(a,b,c,g){this._saveRangeToBookmark(c);var e=this._doc;if(c.collapsed){if(ua){var k=e.createTextNode("\u200b");this._didAddZWS()}else k=e.createTextNode("");P(c,k)}for(e=c.commonAncestorContainer;v(e);)e=e.parentNode;var h=c.startContainer,m=c.startOffset,l=c.endContainer,p=c.endOffset,q=[],r=function(a,b){if(!X(c,a,!1)){var e=3===a.nodeType;if(X(c,a,!0))if(e)a===l&&p!==a.length&&q.push([b,
a.splitText(p)]),a===h&&m&&(a.splitText(m),q.push([b,a]));else for(a=a.firstChild;a;a=e)e=a.nextSibling,r(a,b);else"INPUT"===a.nodeName||e&&!a.data||q.push([b,a])}},t=Array.prototype.filter.call(e.getElementsByTagName(a),function(e){return X(c,e,!0)&&sa(e,a,b)});g||t.forEach(function(a){r(a,a)});q.forEach(function(a){var b=a[0].cloneNode(!1);a=a[1];H(a,b);b.appendChild(a)});t.forEach(function(a){H(a,y(a))});this._getRangeAndRemoveBookmark(c);k&&c.collapse(!1);ca(e,c);return c};h.changeFormat=function(a,
b,c,g){if(!c&&!(c=this.getSelection()))return this;this.saveUndoState(c);b&&(c=this._removeFormat(b.tag.toUpperCase(),b.attributes||{},c,g));a&&(c=this._addFormat(a.tag.toUpperCase(),a.attributes||{},c));this.setSelection(c);this._updatePath(c,!0);R||this._docWasChanged();return this};var qb={DT:"DD",DD:"DT",LI:"LI",PRE:"PRE"};h.forEachBlock=function(a,b,c){if(!c&&!(c=this.getSelection()))return this;b&&this.saveUndoState(c);var g=this._root,e=K(c,g),k=V(c,g);if(e&&k){do if(a(e)||e===k)break;while(e=
t(e,g))}b&&(this.setSelection(c),this._updatePath(c,!0),R||this._docWasChanged());return this};h.modifyBlocks=function(a,b){if(!b&&!(b=this.getSelection()))return this;this._recordUndoState(b,this._isInUndoState);var c=this._root;Na(b,c);W(b,c,c,c);var g=La(b,c,c);P(b,a.call(this,g));b.endOffset<b.endContainer.childNodes.length&&Q(b.endContainer.childNodes[b.endOffset],c);Q(b.startContainer.childNodes[b.startOffset],c);this._getRangeAndRemoveBookmark(b);this.setSelection(b);this._updatePath(b,!0);
R||this._docWasChanged();return this};var Qa=function(a){var b=this._root,c=a.querySelectorAll("blockquote");Array.prototype.filter.call(c,function(a){return!x(a.parentNode,b,"BLOCKQUOTE")}).forEach(function(a){H(a,y(a))});return a},pb=function(){return this.createDefaultBlock([this.createElement("INPUT",{id:"squire-selection-start",type:"hidden"}),this.createElement("INPUT",{id:"squire-selection-end",type:"hidden"})])},Xa=function(a,b,c){b=ba(b,a._root);var g;var e=a._config.tagAttributes;for(var k=
e[c.toLowerCase()],h=e.li;e=b.nextNode();)if("LI"===e.parentNode.nodeName&&(e=e.parentNode,b.currentNode=e.lastChild),"LI"!==e.nodeName){var m=a.createElement("LI",h);e.dir&&(m.dir=e.dir);(g=e.previousSibling)&&g.nodeName===c?(g.appendChild(m),A(e)):H(e,a.createElement(c,k,[m]));m.appendChild(y(e));b.currentNode=m}else e=e.parentNode,m=e.nodeName,m!==c&&/^[OU]L$/.test(m)&&H(e,a.createElement(c,k,[y(e)]))},Ya=function(a,b){for(var c=a.commonAncestorContainer,g=a.startContainer,e=a.endContainer;c&&
c!==b&&!/^[OU]L$/.test(c.nodeName);)c=c.parentNode;if(!c||c===b)return null;g===c&&(g=g.childNodes[a.startOffset]);for(e===c&&(e=e.childNodes[a.endOffset]);g&&g.parentNode!==c;)g=g.parentNode;for(;e&&e.parentNode!==c;)e=e.parentNode;return[c,g,e]};h.increaseListLevel=function(a){if(!a&&!(a=this.getSelection()))return this.focus();var b=this._root,c=Ya(a,b);if(!c)return this.focus();var g=c[0],e=c[1];c=c[2];if(!e||e===g.firstChild)return this.focus();this._recordUndoState(a,this._isInUndoState);var k=
g.nodeName,h=e.previousSibling;h.nodeName!==k&&(h=this._config.tagAttributes[k.toLowerCase()],h=this.createElement(k,h),g.insertBefore(h,e));do g=e===c?null:e.nextSibling,h.appendChild(e);while(e=g);(g=h.nextSibling)&&Q(g,b);this._getRangeAndRemoveBookmark(a);this.setSelection(a);this._updatePath(a,!0);R||this._docWasChanged();return this.focus()};h.decreaseListLevel=function(a){if(!a&&!(a=this.getSelection()))return this.focus();var b=this._root,c=Ya(a,b);if(!c)return this.focus();var g=c[0],e=c[1];
c=c[2];e||(e=g.firstChild);c||(c=g.lastChild);this._recordUndoState(a,this._isInUndoState);if(e){var k=g.parentNode;var h=c.nextSibling?J(g,c.nextSibling,k,b):g.nextSibling;if(k!==b&&"LI"===k.nodeName){for(k=k.parentNode;h;){var m=h.nextSibling;c.appendChild(h);h=m}h=g.parentNode.nextSibling}var l=!/^[OU]L$/.test(k.nodeName);do m=e===c?null:e.nextSibling,g.removeChild(e),l&&"LI"===e.nodeName&&(e=this.createDefaultBlock([y(e)])),k.insertBefore(e,h);while(e=m)}g.firstChild||A(g);h&&Q(h,b);this._getRangeAndRemoveBookmark(a);
this.setSelection(a);this._updatePath(a,!0);R||this._docWasChanged();return this.focus()};h._ensureBottomLine=function(){var a=this._root,b=a.lastElementChild;b&&b.nodeName===this._config.blockTag&&u(b)||a.appendChild(this.createDefaultBlock())};h.setKeyHandler=function(a,b){this._keyHandlers[a]=b;return this};h._getHTML=function(){return this._root.innerHTML};h._setHTML=function(a){var b=this._root,c=b;c.innerHTML=a;do C(c,b);while(c=t(c,b));this._ignoreChange=!0};h.getHTML=function(a){var b=[],
c,g;a&&(g=this.getSelection())&&this._saveRangeToBookmark(g);if(va)for(c=a=this._root;c=t(c,a);)if(!c.textContent&&!c.querySelector("BR")){var e=this.createElement("BR");c.appendChild(e);b.push(e)}a=this._getHTML().replace(/\u200B/g,"");if(va)for(c=b.length;c--;)A(b[c]);g&&this._getRangeAndRemoveBookmark(g);return a};h.setHTML=function(a){var b=this._config,c=b.isSetHTMLSanitized?b.sanitizeToDOMFragment:null,g=this._root;"function"===typeof c?a=c(a,!1,this):(c=this.createElement("DIV"),c.innerHTML=
a,a=this._doc.createDocumentFragment(),a.appendChild(y(c)));Ta(a,b);pa(a,g,!1);N(a,g);for(b=a;b=t(b,g);)C(b,g);for(this._ignoreChange=!0;b=g.lastChild;)g.removeChild(b);g.appendChild(a);C(g,g);this._undoIndex=-1;this._undoStackLength=this._undoStack.length=0;this._isInUndoState=!1;g=this._getRangeAndRemoveBookmark()||this.createRange(g.firstChild,0);this.saveUndoState(g);this._lastSelection=g;this._restoreSelection=!0;this._updatePath(g,!0);return this};h.insertElement=function(a,b){b||(b=this.getSelection());
b.collapse(!0);if(v(a))P(b,a),b.setStartAfter(a);else{for(var c=this._root,g=K(b,c)||c,e;g!==c&&!g.nextSibling;)g=g.parentNode;g!==c&&(e=g.parentNode,e=J(e,g.nextSibling,c,c));e?c.insertBefore(a,e):(c.appendChild(a),e=this.createDefaultBlock(),c.appendChild(e));b.setStart(e,0);b.setEnd(e,0);L(b)}this.focus();this.setSelection(b);this._updatePath(b);R||this._docWasChanged();return this};h.insertImage=function(a,b){a=this.createElement("IMG",da({src:a},b,!0));this.insertElement(a);return a};h.linkRegExp=
/\b((?:(?:ht|f)tps?:\/\/|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,}\/)(?:[^\s()<>]+|\([^\s()<>]+\))+(?:\((?:[^\s()<>]+|(?:\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'".,<>?\u00ab\u00bb\u201c\u201d\u2018\u2019]))|([\w\-.%+]+@(?:[\w\-]+\.)+[A-Z]{2,}\b)(?:\?[^&?\s]+=[^&?\s]+(?:&[^&?\s]+=[^&?\s]+)*)?/i;h.bbcodeRegExp=/\[(img|url|embed|email|\*)([ =][^>]*?)?\]((?:.|[\r\n])*?)/;var Aa=function(a,b,c){var g=a.ownerDocument;a=new r(a,4,function(a){return!x(a,b,"A")});var e=c.linkRegExp,k=c.bbcodeRegExp,h=c._config.tagAttributes.a,
m,l;if(e)for(;m=a.nextNode();){var p=m.data;var q=m.parentNode;if(!k.test(p))for(;l=e.exec(p);){var t=l.index;var u=t+l[0].length;if(t){var v=g.createTextNode(p.slice(0,t));q.insertBefore(v,m)}v=c.createElement("A",da({href:l[1]?/^(?:ht|f)tps?:/i.test(l[1])?l[1]:"http://"+l[1]:"mailto:"+l[0]},h,!1));v.textContent=p.slice(t,u);q.insertBefore(v,m);m.data=p=p.slice(u)}}};h.insertHTML=function(a,b){var c=this._config,g=c.isInsertedHTMLSanitized?c.sanitizeToDOMFragment:null,e=this.getSelection(),k=this._doc;
if("function"===typeof g)a=g(a,b,this);else{if(b){g=a.indexOf("\x3c!--StartFragment--\x3e");var h=a.lastIndexOf("\x3c!--EndFragment--\x3e");-1<g&&-1<h&&(a=a.slice(g+20,h))}/<\/td>((?!<\/tr>)[\s\S])*$/i.test(a)&&(a="<TR>"+a+"</TR>");/<\/tr>((?!<\/table>)[\s\S])*$/i.test(a)&&(a="<TABLE>"+a+"</TABLE>");g=this.createElement("DIV");g.innerHTML=a;a=k.createDocumentFragment();a.appendChild(y(g))}this.saveUndoState(e);try{var m=this._root;var l=a;var p={fragment:a,preventDefault:function(){this.defaultPrevented=
!0},defaultPrevented:!1};Aa(a,a,this);Ta(a,c);pa(a,m,!1);Oa(a);for(a.normalize();l=t(l,a);)C(l,m);b&&this.fireEvent("willPaste",p);p.defaultPrevented||(nb(e,p.fragment,m),R||this._docWasChanged(),e.collapse(!1),this._ensureBottomLine());this.setSelection(e);this._updatePath(e,!0);b&&this.focus()}catch(q){this.didError(q)}return this};var Za=function(a){return a.split("&").join("&amp;").split("<").join("&lt;").split(">").join("&gt;").split('"').join("&quot;")};h.insertPlainText=function(a,b){var c=
this.getSelection();if(c.collapsed&&x(c.startContainer,this._root,"PRE")){var g=c.startContainer,e=c.startOffset;if(!g||3!==g.nodeType){var k=this._doc.createTextNode("");g.insertBefore(k,g.childNodes[e]);g=k;e=0}a={text:a,preventDefault:function(){this.defaultPrevented=!0},defaultPrevented:!1};b&&this.fireEvent("willPaste",a);a.defaultPrevented||(a=a.text,g.insertData(e,a),c.setStart(g,e+a.length),c.collapse(!0));this.setSelection(c);return this}c=a.split("\n");a=this._config;e=a.blockTag;k=a.blockAttributes;
a="</"+e+">";e="<"+e;for(g in k)e+=" "+g+'="'+Za(k[g])+'"';e+=">";g=0;for(k=c.length;g<k;g+=1){var h=c[g];h=Za(h).replace(/ (?= )/g,"&nbsp;");c[g]=e+(h||"<BR>")+a}return this.insertHTML(c.join(""),b)};var D=function(a,b,c){return function(){this[a](b,c);return this.focus()}};h.addStyles=function(a){if(a){var b=this._doc.documentElement.firstChild,c=this.createElement("STYLE",{type:"text/css"});c.appendChild(this._doc.createTextNode(a));b.appendChild(c)}return this};h.bold=D("changeFormat",{tag:"B"});
h.italic=D("changeFormat",{tag:"I"});h.underline=D("changeFormat",{tag:"U"});h.strikethrough=D("changeFormat",{tag:"S"});h.subscript=D("changeFormat",{tag:"SUB"},{tag:"SUP"});h.superscript=D("changeFormat",{tag:"SUP"},{tag:"SUB"});h.removeBold=D("changeFormat",null,{tag:"B"});h.removeItalic=D("changeFormat",null,{tag:"I"});h.removeUnderline=D("changeFormat",null,{tag:"U"});h.removeStrikethrough=D("changeFormat",null,{tag:"S"});h.removeSubscript=D("changeFormat",null,{tag:"SUB"});h.removeSuperscript=
D("changeFormat",null,{tag:"SUP"});h.makeLink=function(a,b){var c=this.getSelection();if(c.collapsed){var g=a.indexOf(":")+1;if(g)for(;"/"===a[g];)g+=1;P(c,this._doc.createTextNode(a.slice(g)))}b=da(da({href:a},b,!0),this._config.tagAttributes.a,!1);this.changeFormat({tag:"A",attributes:b},{tag:"A"},c);return this.focus()};h.removeLink=function(){this.changeFormat(null,{tag:"A"},this.getSelection(),!0);return this.focus()};h.makeTable=function(a,b){for(var c=this._doc.createElement("table"),g=this._doc.createElement("tbody"),
e=0;e<b;e++){for(var k=this._doc.createElement("tr"),h=0;h<a;h++){var m=this._doc.createElement("td");m.appendChild(document.createTextNode("\u00a0"));k.appendChild(m)}g.appendChild(k)}c.appendChild(g);P(this.getSelection(),c)};h.setFontFace=function(a){var b=this._config.classNames.fontFamily;this.changeFormat(a?{tag:"SPAN",attributes:{"class":b,style:"font-family: "+a+", sans-serif;"}}:null,{tag:"SPAN",attributes:{"class":b}});return this.focus()};h.setFontSize=function(a){var b=this._config.classNames.fontSize;
this.changeFormat(a?{tag:"SPAN",attributes:{"class":b,style:"font-size: "+("number"===typeof a?a+"px":a)}}:null,{tag:"SPAN",attributes:{"class":b}});return this.focus()};h.setTextColour=function(a){var b=this._config.classNames.colour;this.changeFormat(a?{tag:"SPAN",attributes:{"class":b,style:"color:"+a}}:null,{tag:"SPAN",attributes:{"class":b}});return this.focus()};h.setHighlightColour=function(a){var b=this._config.classNames.highlight;this.changeFormat(a?{tag:"SPAN",attributes:{"class":b,style:"background-color:"+
a}}:a,{tag:"SPAN",attributes:{"class":b}});return this.focus()};h.setTextAlignment=function(a){this.forEachBlock(function(b){var c=b.className.split(/\s+/).filter(function(a){return!!a&&!/^align/.test(a)}).join(" ");a?(b.className=c+" align-"+a,b.style.textAlign=a):(b.className=c,b.style.textAlign="")},!0);return this.focus()};h.alignRight=function(){this.setTextAlignment("right")};h.alignCenter=function(){this.setTextAlignment("center")};h.alignLeft=function(){this.setTextAlignment("left")};h.alignJustify=
function(){this.setTextAlignment("justify")};h.setTextDirection=function(a){this.forEachBlock(function(b){a?b.dir=a:b.removeAttribute("dir")},!0);return this.focus()};var zb=function(a){var b=this._root,c=this._doc,g=c.createDocumentFragment();a=ba(a,b);for(var e;e=a.nextNode();){var k=e.querySelectorAll("BR"),h=[],m=k.length,l;for(l=0;l<m;l+=1)h[l]=Ua(k[l],!1);for(;m--;)l=k[m],h[m]?H(l,c.createTextNode("\n")):A(l);k=e.querySelectorAll("CODE");for(m=k.length;m--;)A(k[m]);g.childNodes.length&&g.appendChild(c.createTextNode("\n"));
g.appendChild(y(e))}for(a=new r(g,4);e=a.nextNode();)e.data=e.data.replace(/ /g," ");g.normalize();return C(this.createElement("PRE",this._config.tagAttributes.pre,[g]),b)},Ab=function(a){for(var b=this._doc,c=this._root,g=a.querySelectorAll("PRE"),e=g.length,k,h,l,p,t,q;e--;){k=g[e];for(h=new r(k,4);l=h.nextNode();){p=l.data;p=p.replace(/ (?= )/g," ");for(t=b.createDocumentFragment();-1<(q=p.indexOf("\n"));)t.appendChild(b.createTextNode(p.slice(0,q))),t.appendChild(b.createElement("BR")),p=p.slice(q+
1);l.parentNode.insertBefore(t,l);l.data=p}N(k,c);H(k,y(k))}return a};h.code=function(){var a=this.getSelection();a.collapsed||3===E(a.commonAncestorContainer)?this.modifyBlocks(zb,a):this.changeFormat({tag:"CODE",attributes:this._config.tagAttributes.code},null,a);return this.focus()};h.removeCode=function(){var a=this.getSelection();x(a.commonAncestorContainer,this._root,"PRE")?this.modifyBlocks(Ab,a):this.changeFormat(null,{tag:"CODE"},a);return this.focus()};h.toggleCode=function(){this.hasFormat("PRE")||
this.hasFormat("CODE")?this.removeCode():this.code();return this};h.removeAllFormatting=function(a){if(!a&&!(a=this.getSelection())||a.collapsed)return this;for(var b=this._root,c=a.commonAncestorContainer;c&&!u(c);)c=c.parentNode;c||(Na(a,b),c=b);if(3===c.nodeType)return this;this.saveUndoState(a);W(a,c,c,b);var g=c.ownerDocument,e=a.startContainer,k=a.startOffset,h=a.endContainer,l=a.endOffset,p=g.createDocumentFragment();g=g.createDocumentFragment();h=J(h,l,c,b);for(k=J(e,k,c,b);k!==h;)b=k.nextSibling,
p.appendChild(k),k=b;xa(this,p,g);g.normalize();k=g.firstChild;b=g.lastChild;p=c.childNodes;k?(c.insertBefore(g,h),k=z.call(p,k),l=z.call(p,b)+1):l=k=z.call(p,h);a.setStart(c,k);a.setEnd(c,l);ca(c,a);L(a);this.setSelection(a);this._updatePath(a,!0);return this.focus()};h.increaseQuoteLevel=D("modifyBlocks",function(a){return this.createElement("BLOCKQUOTE",this._config.tagAttributes.blockquote,[a])});h.decreaseQuoteLevel=D("modifyBlocks",Qa);h.increaseIndent=D("modifyBlocks",function(a){if(1===a.children.length&&
"P"===a.firstChild.tagName){var b=a.firstChild;b.style.marginLeft=b.style&&b.style.marginLeft?parseInt(b.style.marginLeft)+25+"px":"25px";return a}return this.createElement("P",{style:"margin-left:25px;"},[a])});h.decreaseIndent=D("modifyBlocks",function(a){if(1===a.children.length&&"P"===a.firstChild.tagName){var b=a.firstChild;b.style.marginLeft=b.style&&b.style.marginLeft?parseInt(b.style.marginLeft)-25+"px":"-25px";return a}return this.createElement("P",{style:"margin-left:-25px;"},[a])});h.makeUnorderedList=
D("modifyBlocks",function(a){Xa(this,a,"UL");return a});h.makeOrderedList=D("modifyBlocks",function(a){Xa(this,a,"OL");return a});h.removeList=D("modifyBlocks",function(a){var b=a.querySelectorAll("UL, OL"),c=a.querySelectorAll("LI"),g=this._root,e;var h=0;for(e=b.length;h<e;h+=1){var l=b[h];var m=y(l);N(m,g);H(l,m)}h=0;for(e=c.length;h<e;h+=1)b=c[h],u(b)?H(b,this.createDefaultBlock([y(b)])):(N(b,g),H(b,y(b)));return a});U.Squire=wa;top!==U&&"true"===l.documentElement.getAttribute("data-squireinit")&&
(U.editor=new wa(l),U.onEditorLoad&&(U.onEditorLoad(U.editor),U.onEditorLoad=null));h.testPresenceinSelection=function(a,b,c,g){var e=this.getPath();c=g.test(e)|this.hasFormat(c);return!(a!==b||!c)}})(document);
