/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2022-11-10 01:41:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sims;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.oreilly.servlet.multipart.DefaultFileRenamePolicy;
import com.oreilly.servlet.multipart.FileRenamePolicy;
import com.ragic.s3.nui.comment.Comment;
import com.ragic.s3.nui.comment.CommentEngine;
import com.ragic.s3.nui.helper.AppManager;
import com.ragic.s3.nui.helper.Encoder;
import com.ragic.s3.nui.helper.Util;
import com.ragic.s3.sdb.data.bdb.BDBMgr;
import com.ragic.s3.util.Const;
import com.ragic.s3.util.SIMSMultipartRequest;
import com.ragic.s3.util.UploadedFile;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import java.net.URLEncoder;
import java.text.SimpleDateFormat;
import java.util.Collection;
import java.util.Date;
import java.util.Set;
import com.ragic.s3.nui.*;
import com.ragic.s3.util.RagicFileRenameTruncateMultiDotsToOnePolicy;
import com.ragic.s3.service.notification.Notification;
import com.ragic.s3.nui.helper.ExceptionManager;
import com.ragic.s3.util.ChronologyDate.RagicDateFormatter;

public final class comment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.ragic.s3.nui");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ragic.s3.nui.comment.Comment");
    _jspx_imports_classes.add("com.ragic.s3.service.notification.Notification");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.AppManager");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.util.Collection");
    _jspx_imports_classes.add("com.ragic.s3.nui.comment.CommentEngine");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.util.Set");
    _jspx_imports_classes.add("com.ragic.s3.util.Const");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.ExceptionManager");
    _jspx_imports_classes.add("com.oreilly.servlet.multipart.FileRenamePolicy");
    _jspx_imports_classes.add("com.ragic.s3.sdb.data.bdb.BDBMgr");
    _jspx_imports_classes.add("org.json.JSONException");
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("com.ragic.s3.util.RagicFileRenameTruncateMultiDotsToOnePolicy");
    _jspx_imports_classes.add("org.json.JSONObject");
    _jspx_imports_classes.add("com.oreilly.servlet.multipart.DefaultFileRenamePolicy");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.Util");
    _jspx_imports_classes.add("com.ragic.s3.util.ChronologyDate.RagicDateFormatter");
    _jspx_imports_classes.add("com.ragic.s3.util.UploadedFile");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.Encoder");
    _jspx_imports_classes.add("com.ragic.s3.util.SIMSMultipartRequest");
    _jspx_imports_classes.add("org.json.JSONArray");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


    boolean multipart = request.getParameter("multipart") != null;
    boolean delete = request.getParameter("delete") != null;
    boolean getCellLocationComments = request.getParameter("gclc") != null;
    String apname = request.getParameter("a");
    String path = request.getParameter("p");
    String sheet = request.getParameter("fn");
    int domainId = Encoder.parseInt(request.getParameter("f"), -1);
    int nodeId = Encoder.parseInt(request.getParameter("n"), -1);

    NUIForm form = AppManager.getFormPage(apname, path, sheet);
    if (domainId == Const.NODOMAIN && form != null) {
        domainId = form.getRootDomainId();
    }

    if (domainId == -1 || nodeId == -1) return;

    User user = (User) session.getAttribute("USER");
    if (user == null) user = new User();
    RagicBundle bundle = (RagicBundle) session.getAttribute("RAGIC_BUNDLE");
    if (bundle == null) return;
    RagicDateFormatter rdf = com.ragic.s3.util.Util.getDisplayDateTimeFormat(apname, true, bundle);

    //determine user access right
    //get user right of this sheet
    int userRight = AppManager.getSheetRightByFormName(apname, path, sheet, user);
    //check if user is create user
    String entryManager = Util.getCreateUser(apname, domainId, nodeId);
    boolean ifEntryManager = user.getUserId().equals(entryManager);
    boolean ifRead = userRight >= Const.USER || ifEntryManager;
    boolean ifCanDelete = userRight > Const.MANAGER || ifEntryManager;
    if (!ifRead) {
        out.println("No rights.");
        return;
    }

    //deleting comment
    if (delete) {
        String commentDate = request.getParameter("t");
        boolean ifCellComment = request.getParameter("cellComment") != null;
        Set<Comment> commentSet = CommentEngine.loadComment(apname, domainId, nodeId, ifCellComment);
        for(Comment c : commentSet){
            if(c.getCommentDate() == Encoder.parseLong(commentDate)){
                if (ifCanDelete || c.getUserId().equals(user.getUserId())){
                    CommentEngine.deleteComment(apname, path, sheet, domainId, nodeId, commentDate, ifCellComment);
                    return;
                }
            }
        }
        return;
    }

    //saving comment
    if (multipart) {
        FileRenamePolicy policy = new RagicFileRenameTruncateMultiDotsToOnePolicy();
        SIMSMultipartRequest mReq = new SIMSMultipartRequest(request, "cust/data/" + apname + "/upload", 1024 * 1024 * 1024, "UTF-8", policy);
        String content = mReq.getParameter("c");
        String cellLoc = mReq.getParameter("cellLoc");
        Collection attachments = mReq.getFile("at");
        String attachment = null;
        for (Object o : attachments) {
            UploadedFile uf = (UploadedFile) o;
            attachment = uf.getFilesystemName();
        }

        //try writing the comment to DB
        try {
            CommentEngine.saveComment(user.getUserId(), user.getUserName(apname), bundle, apname, path, sheet, domainId, nodeId, content, attachment, null, cellLoc);

            //process mentions
            Set<String> mentionedNames=Encoder.getMentionedNames(content);
            if(mentionedNames.size()>0){
                for(String mentionedName:mentionedNames){
                    Notification.notifyMentionedName(apname,mentionedName,user,bundle,form,nodeId,bundle.getString("comment"),content);
                }
            }

        } catch (Exception e) {
            ExceptionManager.getInstance().processException(e,null,user);
            Account.removeInstance(apname);
            BDBMgr.removeInstance(apname);
        }

        if (cellLoc != null) {

      out.write("<script>\r\n    parent.loadAllCellComments(true);\r\n    parent.loadCellComment();\r\n</script>\r\n");

} else {

      out.write("<script>\r\n    parent.document.getElementById('magic').value = \"");
      out.print("loadComments();biffdata.commentSize++;$('commentCount').textContent='('+biffdata.commentSize+')';$('nuiiframe').src='';");
      out.write("\";\r\n    parent.document.getElementById('magic').click();\r\n</script>\r\n");

        }

        return;
    }

    if (getCellLocationComments) {
        Set<Comment> cl = CommentEngine.loadComment(apname, domainId, nodeId, true);
        JSONArray ja = new JSONArray();
        for (Comment c : cl) {
            String cellLoc = c.getCellLoc();
            String[] cellLocSplit = cellLoc.split("_");
            if(cellLocSplit.length<2) continue;

            JSONObject jo = new JSONObject();
            try {
                jo.put("id", c.getKey());
                jo.put("domainId", cellLocSplit[0]);
                jo.put("nodeId", cellLocSplit[1]);
                jo.put("userName", c.getUserName());
                jo.put("content", Encoder.processBBCode(Encoder.textToHTML(c.getContent(), false)));
                jo.put("ts", c.getCommentDate());
                jo.put("date", rdf.format(bundle.convertTime(new Date(c.getCommentDate()))));
            } catch (JSONException e) {
                e.printStackTrace();
            }
            ja.put(jo);
        }
        out.print(ja.toString());
        return;
    }


    //new comment
    out.println("<form id=\"newCommentForm\" action=\"/sims/comment.jsp?multipart&a=" + apname + "&p=" + path + "&fn=" + sheet + "&f=" + domainId + "&n=" + nodeId + "\" target=\"nuiiframe\" method=\"POST\" enctype=\"multipart/form-data\">");
    out.println("<textarea onpaste=\"clipboardUploadImage(this,event);\" id='commentTextarea' rows=1 class='textareaDisabled' name=c onfocus='focusComment()' onblur='blurComment()' onkeyup='mentionACKey(event)' onkeydown='mentionACKey(event)' placeholder=\"" + bundle.getString("writeCommentHere") + "\"></textarea>");
    out.println("<div id='commentSubmitDiv' style='display:none;margin:5px 0 0 0;'><div class=\"topButtonWhole\" id='commentSubmit' onclick=\"submitComment(this);\"><i class=\"fad fa-spinner-third fa-spin\"></i>" + bundle.getString("comment") + "</div>");
    out.println("<a href='javascript:void(0);' id='commentAttachLink' onclick='$(\"commentAttach\").click();'><i class=\"fa fa-paperclip\" style=\"margin:0 5px;color:#888;\"></i><span id='commentAttachLinkText'>" + bundle.getString("attachFile") + "</span></a>");
    out.println("<input type=file id='commentAttach' name=at style='display:none' onchange='$(\"commentAttachLinkText\").textContent=getFilenameFromInputFile(this.value);' /></div>");
    out.println("</form>");

    //loading comment
    Set<Comment> cl = CommentEngine.loadComment(apname, domainId, nodeId);
    int count = cl.size();
    if(count > 0) out.println("<div class='commentsEnlargeIcon' onclick='enlargeComment(\""+apname+"\",\""+domainId+"\",\""+nodeId+"\")'><i class='fas fa-external-link-alt'></i></div>");
    for (Comment c : cl) {
        String userName = c.getUserName();
        if (userName == null || userName.length() == 0) {
            if (user.isValid()) userName = c.getUserId();
            else userName = bundle.getString("guestUser");
        }
        userName = Encoder.encjs(userName); //Prevent XSS
        boolean ifMe=user.getUserId().equals(c.getUserId());
        String userImageUrl=Account.getInstance(apname).getUserImage(c.getUserId());
        out.println("<div class='commentItem'>");
      if(userImageUrl==null){
        out.println("<div class='avatar jsavatar'"+(ifMe?" onclick='getPrefSetting();' style='cursor:pointer;'":"")+" email='"+c.getUserId()+"' userName='"+userName+"'></div>");
      }
      else{
        out.println("<div class='avatar jsavatar'"+(ifMe?" onclick='getPrefSetting();' style='cursor:pointer;'":"")+" email='"+c.getUserId()+"' userName='"+userName+"'></div>");
      }
      out.println("<div class='commentBubbleWrap'>");
      out.println("<div class='commentBubble'>");
//        out.println("<span class='commentSeq'>" + count);
        if (ifCanDelete || c.getUserId().equals(user.getUserId())){
          out.println("<div class='commentDelete'><a href='javascript:void(0);' onclick='deleteComment(" + domainId + "," + nodeId + "," + c.getCommentDate() + ");'><i class='fa fa-times' style='color:#555;'></i></a></div>");
        }

        out.println("<div class='commentText' id='commentText" + count + "'>"
                +"<span class='commentUser'>" + userName + "</span>"
                + Encoder.processBBCode(Encoder.textToHTML(c.getContent(), true))
                + "</div>");

        if (c.getImages() != null) {
            for (String image : c.getImages()) {
                bundle.addFileToken(image);
                out.println("<a href='/sims/file.jsp?a=" + apname + "&f=" + image + "' target='_blank'><img style='max-width:100%;' src='/sims/file.jsp?a=" + apname + "&f=" + URLEncoder.encode(image, "UTF-8") + "' /></a>");
            }
        }
        if (c.getAttachment() != null && c.getAttachment().length() > 0) {
            String attachmentFileName = c.getAttachment();
            bundle.addFileToken(attachmentFileName);
            if (attachmentFileName.length() > 11 && attachmentFileName.charAt(10) == '@')
                attachmentFileName = attachmentFileName.substring(11);
            if (attachmentFileName.length() > 9 && attachmentFileName.charAt(8) == '@')
                attachmentFileName = attachmentFileName.substring(9);  // S3

            String lowercaseFilename=attachmentFileName.toLowerCase();
            boolean ifImg=lowercaseFilename.endsWith(".png") || lowercaseFilename.endsWith(".gif") || lowercaseFilename.endsWith(".jpg") || lowercaseFilename.endsWith(".jpeg") || lowercaseFilename.endsWith(".bmp");
            out.println("<div class='commentAttachment'>" + bundle.getString("attachment") + ": " +
                    "<a href='/sims/file.jsp?"+(ifImg?"":"force&")+"a=" + apname + "&f=" + URLEncoder.encode(c.getAttachment(), "UTF-8") + "' target='_blank'>" +
                    "<img style='margin:0 3px -3px 5px' src='" + Encoder.getIcon(c.getAttachment()) + "' />" +
                    attachmentFileName + "</a>" +
                    "</div>");
        }
      out.println("</div>");
      String defaultDateTimeFormat = Account.getInstance(apname).getAppSetting().getDefaultDateTimeFormat();
      Date convertedDate = bundle.convertTime(new Date(c.getCommentDate()));
      String commentDateTime = Encoder.formatDate(convertedDate, defaultDateTimeFormat, bundle);
      out.println("<div class='commentDate' title='" + commentDateTime + "'>" + Encoder.timeAgo(new Date(c.getCommentDate()),bundle) + "</div>");
      out.println("</div>");


      out.println("</div>");
        count--;
    }

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
