/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2022-11-10 01:41:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sims;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ragic.s3.service.notification.MagicRecordLink;
import com.ragic.s3.nui.helper.Encoder;
import com.ragic.s3.util.Util;
import com.ragic.s3.nui.*;
import com.ragic.s3.util.Const;
import com.ragic.s3.service.api.APIQuery;
import com.ragic.s3.service.api.APIResults;

public final class createMagicRecordLink_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.ragic.s3.nui");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ragic.s3.service.notification.MagicRecordLink");
    _jspx_imports_classes.add("com.ragic.s3.service.api.APIQuery");
    _jspx_imports_classes.add("com.ragic.s3.util.Util");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.Encoder");
    _jspx_imports_classes.add("com.ragic.s3.util.Const");
    _jspx_imports_classes.add("com.ragic.s3.service.api.APIResults");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


  User user = (User) session.getAttribute("USER");
  String apname = request.getParameter("a");
  String path = request.getParameter("p");
  boolean approval = request.getParameter("approval") != null;
  int sheetIndex = Encoder.parseInt(request.getParameter("si"));
  int nodeId;
  String rw = request.getParameter("rw");
  int expireDate = Encoder.parseInt(request.getParameter("expireDate"),0);
  String host = Util.getServerUrl(RagicConfig.getInstance());
  boolean ifApi = request.getParameter("api")!=null;
  if(user == null || apname == null || path == null || expireDate <= 0) return;
  if(!rw.equalsIgnoreCase("r") && !rw.equalsIgnoreCase("w")) return;

  //get node ID
  if(ifApi) nodeId = Encoder.parseInt(request.getParameter("n"), Const.NODOMAIN);
  else {
    NUIFormSet set = NUIFormSetInfo.loadBrowsingFormSet(session, apname, path, sheetIndex+"_Sheet"+sheetIndex);
    nodeId = set.loadData(false).getRootNodeId();
  }
  if(nodeId < 0) return;

  APIQuery aq=new APIQuery(apname,path,sheetIndex);
  NUIForm form = aq.getForm();
  // check FeatureAccessModule Right
  UserFeatureAccessModule modules=UserFeatureAccessModule.configureUserAccessModule(session,apname,user);
//  boolean ifExternalUser = user.getIfExternalv2(apname);
  if((!modules.ifAllow(Const.FUNC_MAGIC_RECORD,form,user) || !user.isValid() /*|| ifExternalUser*/) && !approval) return; //need have right to share and need valid user
  // Check this user whether have the right to access this node or not
  aq.setWhoami("Create Magic Record Link");
  aq.setRootNodeId(nodeId);
  if(approval) user = new UserSuper("system@ragic.com");
  aq.setUser(user);
  APIResults result = aq.getAPIResults();
  if(result.getData().size() == 0) return;

  if(rw.equalsIgnoreCase("w")) {
    String rightStr = form.getRightsString(user,nodeId);
    String[] rightArray = rightStr.split(",");
    if(!"w".equalsIgnoreCase(rightArray[1]) || form.ifUserNoEdit(user)) return;
  }

  // debug
//  out.print(user.getUserId() +" Success!!");

  // output
  MagicRecordLink mrl = new MagicRecordLink(apname,path,sheetIndex,nodeId);
  mrl.setExpiresIn(expireDate);
  String token = mrl.createMagicLink(rw);

  out.print(host+"/"+apname+path+"/"+sheetIndex+"/"+nodeId+"?embed&hidetop&embedEntry&rmlc="+Encoder.encodeURIComponent(token));

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
