/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2022-11-10 01:41:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sims;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ragic.s3.nui.RagicBundle;
import com.ragic.s3.nui.helper.*;

public final class excel_002dto_002ddb_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.ragic.s3.nui.helper");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ragic.s3.nui.RagicBundle");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


  String apname=request.getParameter("a");
  if(apname != null) apname = Encoder.encjs(apname);
  RagicBundle bundle=(RagicBundle) session.getAttribute("RAGIC_BUNDLE");
  //User user=(User)session.getAttribute("USER");

      out.write("<div style=\"margin:25px;position:relative;\">\r\n\r\n");
      out.write("<div id=\"rtpstep1\">\r\n<ol id=\"rtpinstructions\">\r\n");
      out.print(bundle.getString("rtpinstructions1"));
      out.write("</ol>\r\n\r\n<textarea id=\"conversionReceiver\"></textarea>\r\n</div>\r\n\r\n");
      out.write("<form id=\"rtpform\" action=\"/sims/sheetExcelSmartCreate.jsp\" method=\"POST\" target=\"nuiiframe\">\r\n<div id=\"rtpstep2\" style=\"display:none;\" class=\"clearfix\">\r\n  <div id=\"conversionTableDiv\" style='float:left;overflow:auto;'>\r\n    <table id=\"conversionTable\"></table>\r\n  </div>\r\n  <div style=\"float:left;width:20%;margin:0 0 0 25px;\">\r\n    <ol id=\"rtpinstructions2\" style=\"float:left;\">\r\n      ");
      out.print(bundle.getString("rtpinstructions2"));
      out.write("</ol>\r\n    <div id=\"rtpactions\" style='float:left;clear:left;'>\r\n      <div class=\"rtpbutton\" onclick=\"rtpSave();\">");
      out.print(bundle.getString("save"));
      out.write("</div>\r\n    </div>\r\n  </div>\r\n</div>\r\n\r\n\r\n\r\n");
      out.write("<div id=\"rtpSavePanel\" style=\"display:none;position:absolute;top:80px;left:80px;border:8px solid #888;background:#ffffff;border-radius:8px;width:650px;height:300px;\">\r\n  <div style=\"border:1px solid #000;height:100%;width:100%;\">\r\n    <div class=\"closeButton\" onclick=\"$('rtpSavePanel').style.display='none';\">x</div>\r\n    <div style=\"margin:25px;\">\r\n      <div style=\"font-size:12px;color:#888888;margin:0 0 5px 0;\">");
      out.print(bundle.getString("applicationName"));
      out.write(":</div>\r\n      <input id=\"appName\" type=\"text\" name=\"appName\" value=\"Imported\" style=\"border:1px solid #cccccc;width:300px;\" MAXLENGTH=\"50\" />\r\n      <div style=\"font-size:12px;color:#888888;margin:25px 0 5px 0;\">");
      out.print(bundle.getString("applicationSetting"));
      out.write(":</div>\r\n      <select id=\"rtpac\" name=\"ac\" style=\"font-size:12px;height:30px;\">\r\n        ");
      out.print(bundle.getString("rtpAccessOptions"));
      out.write("</select>\r\n      <div class=\"rtpbutton\" style=\"margin:25px 0 0 0;\" onclick=\"if(edition=='COMM' && $('rtpac').selectedIndex<3){alert('Your access right cannot be set to internal when you are using community version.');return;}else{ragictp.exportSheet();}\">");
      out.print(bundle.getString("createDatabase"));
      out.write("</div>\r\n    </div>\r\n  </div>\r\n</div>\r\n\r\n");
      out.write("<div id=\"rtpstep3\" style=\"display:none;\" class=\"clearfix\">\r\n  \r\n</div>\r\n\r\n\r\n");
      out.write("<input type=\"hidden\" name=\"a\" value=\"");
      out.print(apname);
      out.write("\" />\r\n<input id=\"appPath\" type=\"hidden\" name=\"p\" value=\"\" />\r\n<textarea id=\"rtpcontent\" name=\"c\" style=\"display:none\"></textarea>\r\n<textarea id=\"rtpimport\" name=\"i\" style=\"display:none\"></textarea>\r\n</form>\r\n\r\n</div>\r\n\r\n\r\n\r\n\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
