/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2022-11-10 01:41:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sims;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ragic.s3.nui.RagicBundle;
import com.ragic.s3.nui.NUIForm;
import com.ragic.s3.nui.helper.Encoder;
import com.ragic.s3.nui.helper.AppManager;
import com.ragic.s3.nui.CellLocation;
import com.ragic.s3.nui.CellInfo;
import java.util.Map;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

public final class preFillValue_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.json.JSONException");
    _jspx_imports_classes.add("org.json.JSONObject");
    _jspx_imports_classes.add("com.ragic.s3.nui.RagicBundle");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.AppManager");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("com.ragic.s3.nui.CellLocation");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.Encoder");
    _jspx_imports_classes.add("com.ragic.s3.nui.NUIForm");
    _jspx_imports_classes.add("com.ragic.s3.nui.CellInfo");
    _jspx_imports_classes.add("org.json.JSONArray");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


    RagicBundle bundle = (RagicBundle) session.getAttribute("RAGIC_BUNDLE");
    String apName = request.getParameter("a");
    String path = request.getParameter("p");
    int sheetIndex = Encoder.parseInt(request.getParameter("si"), -1);
    NUIForm form = AppManager.getFormPage(apName, path, sheetIndex);
    if (form == null) return;
    String action = request.getParameter("action");
    Map<CellLocation, CellInfo> fields = form.getFields();
    StringBuilder options = new StringBuilder();
    for (Map.Entry<CellLocation, CellInfo> m : fields.entrySet()) {
        CellInfo info = m.getValue();
        options.append("<option value=\"").append(info.getDomainId()).append("\">").append(info.getValue()).append("</option>");
    }
    if ("load".equals(action)) {
        JSONArray pfvTemplates = form.getEmbedPreFillValue();

      out.write("<form class=\"pfv-container\" onsubmit=\"event.preventDefault();\">\r\n    <nav class=\"pfv-btn-wrapper\">\r\n        <button class=\"pfv-btn addTemplate\">");
      out.print(bundle.getString("pfvAddTemplate"));
      out.write("</button>\r\n        <button class=\"pfv-btn saveTemplate\">");
      out.print(bundle.getString("pfvSaveTemplate"));
      out.write("</button>\r\n    </nav>\r\n    <main class=\"pfv-template-container\">");

        try {
            if (pfvTemplates != null) {
                int templateCount = pfvTemplates.length();
                for (int i = 0; i < templateCount; ++i) {
                    JSONObject pfvTemplate = pfvTemplates.getJSONObject(i);
                    String title = pfvTemplate.getString("title");
                    boolean apply = pfvTemplate.getBoolean("apply");
    
      out.write("<fieldset class=\"pfv-template-content");
      out.print(apply ? " apply-template" : "");
      out.write("\">\r\n            <div class=\"pfv-template-title-wrapper\">\r\n                <span class=\"pfv-template-title\">");
      out.print(title);
      out.write("</span>\r\n                <i class=\"fas fa-pencil-alt pfv-btn pfv-template-title-edit\" onclick=\"editTitle(this);\"></i>\r\n                <i class=\"fa fa-times pfv-btn pfv-template-delete\" onclick=\"removeTemplate(this);\"></i>\r\n            </div>\r\n            <article class=\"pfv-template-instruction-container\">\r\n                ");

                    JSONArray instructions = pfvTemplate.getJSONArray("instructions");
                    int instructionCount = instructions.length();
                    for (int j = 0; j < instructionCount; ++j) {
                        JSONObject instruction = instructions.getJSONObject(j);
                        String fieldId = instruction.getString("fieldId");
                        String fieldValue = instruction.getString("fieldValue");
                        StringBuilder optionString = new StringBuilder(options.toString());
                        int pos = optionString.indexOf(fieldId);
                        if (pos > 8) {
                            optionString.insert(pos - 8, " selected");
                        }
                
      out.write("<section class=\"pfv-template-instruction-content\">\r\n                    <label>\r\n                        <span style=\"margin-right: 5px;\">");
      out.print(bundle.getString("pfvField"));
      out.write("</span>\r\n                        <select>");
      out.print(optionString);
      out.write("</select>\r\n                    </label>\r\n                    <label>\r\n                        <span style=\"margin: 0 5px;\">");
      out.print(bundle.getString("pfvFillIn"));
      out.write("</span>\r\n                        <input type=\"text\" value=\"");
      out.print(fieldValue);
      out.write("\">\r\n                    </label>\r\n                    <i class=\"fa fa-times pfv-btn pfv-instruction-delete\" onclick=\"deleteInstruction(this)\"></i>\r\n                </section>\r\n                ");

                    }
                
      out.write("</article>\r\n            <i class=\"fa fa-plus-circle pfv-btn pfv-instruction-add\" onclick=\"addInstruction(this);\"></i>\r\n        </fieldset>\r\n        ");

                }
            }
        
      out.write("</main>\r\n</form>\r\n<template id=\"template\">\r\n    <fieldset class=\"pfv-template-content\">\r\n        <div class=\"pfv-template-title-wrapper\">\r\n            <span class=\"pfv-template-title\">");
      out.print(bundle.getString("pfvTemplate"));
      out.write("</span>\r\n            <i class=\"fas fa-pencil-alt pfv-btn pfv-template-title-edit\" onclick=\"editTitle(this)\"></i>\r\n            <i class=\"fa fa-times pfv-btn pfv-template-delete\" onclick=\"removeTemplate(this)\"></i>\r\n        </div>\r\n        <article class=\"pfv-template-instruction-container\">\r\n            <section class=\"pfv-template-instruction-content\">\r\n                <label>\r\n                    <span style=\"margin-right: 5px;\">");
      out.print(bundle.getString("pfvField"));
      out.write("</span>\r\n                    <select>");
      out.print(options);
      out.write("</select>\r\n                </label>\r\n                <label>\r\n                    <span style=\"margin: 0 5px;\">");
      out.print(bundle.getString("pfvFillIn"));
      out.write("</span>\r\n                    <input type=\"text\">\r\n                </label>\r\n                <i class=\"fa fa-times pfv-btn pfv-instruction-delete\" onclick=\"deleteInstruction(this)\"></i>\r\n            </section>\r\n        </article>\r\n        <i class=\"fa fa-plus-circle pfv-btn pfv-instruction-add\" onclick=\"addInstruction(this);\"></i>\r\n    </fieldset>\r\n</template>\r\n<template id=\"instruction\">\r\n    <section class=\"pfv-template-instruction-content\">\r\n        <label>\r\n            <span style=\"margin-right: 5px;\">");
      out.print(bundle.getString("pfvField"));
      out.write("</span>\r\n            <select>");
      out.print(options);
      out.write("</select>\r\n        </label>\r\n        <label>\r\n            <span style=\"margin: 0 5px;\">");
      out.print(bundle.getString("pfvFillIn"));
      out.write("</span>\r\n            <input type=\"text\">\r\n        </label>\r\n        <i class=\"fa fa-times pfv-btn pfv-instruction-delete\" onclick=\"deleteInstruction(this)\"></i>\r\n    </section>\r\n</template>\r\n");

        } catch (JSONException e) {
            e.printStackTrace();
        }
    } else {
        String embedPreFillValue = request.getParameter("embedPreFillValue");
        try {
            form.saveEmbedPreFillValue(new JSONArray(Encoder.decodeURIComponent(embedPreFillValue)));
        } catch (JSONException e) {
            e.printStackTrace();
        }
    }

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
