/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2022-11-10 01:41:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sims;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ragic.s3.nui.NUIFilterSet;
import com.ragic.s3.nui.NUIForm;
import com.ragic.s3.nui.NUIFormSetInfo;
import com.ragic.s3.nui.RagicBundle;
import com.ragic.s3.nui.User;
import com.ragic.s3.nui.helper.AppManager;
import com.ragic.s3.nui.helper.Encoder;
import com.ragic.s3.nui.helper.RemoteAccountManager;
import java.util.Map;

public final class publishURLs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


    private String getSharedViewInterface(NUIForm listingPage, RagicBundle bundle) {
        String htmlStr = "";
        if (listingPage != null) {
            for (Map.Entry<Integer, NUIFilterSet> e : listingPage.getDesignerFilterSet().entrySet()) {
                NUIFilterSet fs = e.getValue();
                htmlStr += "<option value='" + fs.getSequence() + "'>" + fs.getName() + "</option>";
            }
        }
        if (htmlStr.length() > 0) {
            htmlStr = "<tr><td style='font-weight:bold;padding:5px;'> " + bundle.getString("applyView") + ":</td>"
                    + "<td><select id='plViewSel'><option></option>"
                    + htmlStr + "</select></td></tr>";
        }
        return htmlStr;
    }


  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ragic.s3.nui.NUIFilterSet");
    _jspx_imports_classes.add("com.ragic.s3.nui.RagicBundle");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.AppManager");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.RemoteAccountManager");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.Encoder");
    _jspx_imports_classes.add("com.ragic.s3.nui.NUIFormSetInfo");
    _jspx_imports_classes.add("com.ragic.s3.nui.User");
    _jspx_imports_classes.add("com.ragic.s3.nui.NUIForm");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


    RagicBundle bundle = (RagicBundle) session.getAttribute("RAGIC_BUNDLE");
    User user = (User) session.getAttribute("USER");
    String apname = request.getParameter("a");
    String path = request.getParameter("p");
    int sheetIndex = Encoder.parseInt(request.getParameter("si"));
    String url = request.getParameter("url");
    int newRight = Encoder.parseInt(request.getParameter("r"), -100);
    NUIForm form = AppManager.getFormPage(apname, path, sheetIndex);
    if (form == null) return;
    NUIForm listingPage = AppManager.getListingPage(apname, path, sheetIndex);
    boolean useAPIKey = Encoder.parseInt(request.getParameter("ak")) == 1 ? true : false;
    boolean isPublic = false;

    if (newRight == 2) {
        //make the sheet to public
        //set access right for Everyone to Viewer
        form.setRight("EVERYONE", 2);
        form.setUser(user);
        form.saveFile(apname, path);
        form.copyAccessInfo();
        NUIFormSetInfo.resetForms(apname, path, session);//reset the cache person who saves this, the session registry save does not help if the person is in multiple accounts
        isPublic = true;
    }
    else if (newRight == 0 || newRight == 1) {
        //set access right for Everyone to No Rights or Survey User
        form.setRight("EVERYONE", newRight);
        form.setUser(user);
        form.saveFile(apname, path);
        form.copyAccessInfo();
        NUIFormSetInfo.resetForms(apname, path, session);
    }
    else if (useAPIKey) {}
    else {
        int right = form.getRight("EVERYONE");
        if (right != 0 && right != 1) {
            isPublic = true;
        }
    }
    
    if (isPublic) {
        out.print("<table style='font-size:12px;' onchange='changePublishType(false);'><tr>"
                + "<td style='font-weight:bold;padding:5px;'>" + bundle.getString("downloadField") + ":</td>"
                + "<td><input type='radio' name='plField' id='plListing' style='margin:0 5px 0 0; padding:5px;' checked><label for='plListing'>" + bundle.getString("downloadField2") + "</label></td>"
                + "<td><input type='radio' name='plField' id='plAll' style='margin:0 5px 0 0;padding:5px;'><label for='plAll'>" + bundle.getString("downloadField1") + "</label></td></tr>"
                + getSharedViewInterface(listingPage, bundle)
                + "</table>"
                + "<table style='font-size:inherit;width:90%;margin:10px 0'><col width='20%'/><col width='80%'/>"
                + "<tr><td>Web page:</td><td style='padding:3px 0'><input id='plWebPage' value='" + url
                + "' style='width:100%' readonly='readonly' onclick='this.select()'/></td></tr>"
                + "<tr><td>CSV:</td><td style='padding:3px 0'><input id='plCSV' value='" + url
                + ".csv' style='width:100%' readonly='readonly' onclick='this.select()'/></td></tr>"
                + "<tr><td>Excel:</td><td style='padding:3px 0'><input id='plExcel' value='" + url
                + ".xlsx' style='width:100%' readonly='readonly' onclick='this.select()'/></td></tr>"
                + "<tr><td>JSON:</td><td style='padding:3px 0'><input id='plJSON' value='" + url
                + "?api&listing' style='width:100%' readonly='readonly' onclick='this.select()'/></td></tr>"
                + "</table><div style='padding:15px'><hr style='border-top-color:#cccccc'></div>"
                + "<div><div style='margin:12px 5px 12px 8px;border:1px solid rgb(219, 219, 219);background-position: 0px 0px;float:none;display:inline-block;' class='topButtonWhole' onclick='stopPublishing();' onmouseover='buttover(this);' onmouseout='buttout(this);' onmousedown=\"this.style.backgroundPosition='0 21px';\" onmouseup=\"this.style.backgroundPosition='0 0';\">"
                + bundle.getString("stopPublishing") + "</div></div>"
                + "<div style='line-height:22px;padding-left:10px'><div><input type='radio' id='setRight1' name='setRight' checked><label for='setRight1' style='padding-left:5px;'>"
                + bundle.getString("setEveryoneNoRights") + "</label></div>"
                + "<div><input type='radio' id='setRight2' name='setRight'><label for='setRight2' style='padding-left:5px;'>"
                + bundle.getString("setEveryoneSurveyUser") + "</label></div></div>");
    }
    else if (useAPIKey) {
        String apikey = RemoteAccountManager.main_getAPIKey(user.getUserId(),user.isPassivelyAddedUser());
        out.print("<div>" + bundle.getString("getLinkByApiKeyHint2") + "</div>"
                + "<table style='margin-top:12px; font-size:12px;' onchange='changePublishType(true)'><tr>"
                + "<td style='font-weight:bold; padding:5px;'>" + bundle.getString("downloadField") + ":</td>"
                + "<td><input type='radio' name='plField' id='plListing' style='margin:0 5px 0 0; padding:5px;' checked><label for='plListing'>" + bundle.getString("downloadField2") + "</label></td>"
                + "<td><input type='radio' name='plField' id='plAll' style='margin:0 5px 0 0;padding:5px;'><label for='plAll'>" + bundle.getString("downloadField1") + "</label></td></tr>"
                + getSharedViewInterface(listingPage, bundle)
                + "</table>"
                + "<table style='font-size:inherit;width:90%;margin:10px 0'><col width='20%'/><col width='80%'/>"
                + "<tr><td>CSV:</td><td style='padding:3px 0'><input id='plCSV' value='" + url + ".csv?APIKey="
                + apikey
                + "' style='width:100%' readonly='readonly' onclick='this.select()'/></td></tr>"
                + "<tr><td>Excel:</td><td style='padding:3px 0'><input id='plExcel' value='" + url + ".xlsx?APIKey="
                + apikey
                + "' style='width:100%' readonly='readonly' onclick='this.select()'/></td></tr>"
                + "<tr><td>JSON:</td><td style='padding:3px 0'><input id='plJSON' value='" + url + "?api&APIKey="
                + apikey + "&listing"
                + "' style='width:100%' readonly='readonly' onclick='this.select()'/></td></tr>"
                + "</table>"
                + "<input type='hidden' id='apikey' value='" + apikey + "'>"
                + "<div><div style='margin: 12px 5px 12px 8px; border: 1px solid rgb(219, 219, 219); background-position: 0px 0px; float: none; display: inline-block;' class='topButtonWhole' onclick='publishURLs();' onmouseover='buttover(this);' onmouseout='buttout(this);' onmousedown='this.style.backgroundPosition=\"0 21px\";' onmouseup='this.style.backgroundPosition=\"0 0\";'>"
                + bundle.getString("back") + "</div></div>");
    }
    else {  // no rights
        out.print("<div style='max-width:750px;line-height:1.5;'><p>" + bundle.getString("sheetNotPublic1") + "</p>"
                + "<ul><li style='margin:15px 0 15px 0;'><span style='cursor:pointer;color:#08c;text-decoration:underline;' onclick='publishURLs(2,null)'>"
                + bundle.getString("sheetNotPublic2") + "</span>"
                + bundle.getString("sheetNotPublic3") + "</li>"
                + "<li style='margin:15px 0 15px 0;'><span style='cursor:pointer;color:#08c;text-decoration:underline;' onclick='publishURLs(null,true)'>"
                + bundle.getString("getLinkByApiKey") + "</span>"
                + bundle.getString("getLinkByApiKeyHint1") + "</li>"
                + "</ul></div>");
    }

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
