/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2022-11-10 01:41:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sims;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ragic.s3.nui.*;
import java.text.SimpleDateFormat;
import java.util.Set;
import com.ragic.s3.service.report.ReportHistory;
import org.json.JSONObject;
import org.json.JSONArray;
import com.ragic.s3.nui.helper.Encoder;
import com.ragic.s3.nui.helper.Util;
import java.io.File;
import com.ragic.s3.service.report.ReportConfig;
import com.ragic.s3.util.Const;
import com.ragic.s3.service.report.Report;
import com.ragic.s3.nui.menu.MenuReport;
import com.ragic.s3.nui.menu.MenuSet;
import com.ragic.s3.nui.menu.MenuTab;

public final class reportHistory_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.ragic.s3.nui");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ragic.s3.nui.menu.MenuReport");
    _jspx_imports_classes.add("com.ragic.s3.service.report.ReportConfig");
    _jspx_imports_classes.add("com.ragic.s3.nui.menu.MenuTab");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.util.Set");
    _jspx_imports_classes.add("com.ragic.s3.util.Const");
    _jspx_imports_classes.add("java.io.File");
    _jspx_imports_classes.add("com.ragic.s3.service.report.Report");
    _jspx_imports_classes.add("org.json.JSONObject");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.Util");
    _jspx_imports_classes.add("com.ragic.s3.service.report.ReportHistory");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.Encoder");
    _jspx_imports_classes.add("org.json.JSONArray");
    _jspx_imports_classes.add("com.ragic.s3.nui.menu.MenuSet");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


    RagicBundle bundle=(RagicBundle) session.getAttribute("RAGIC_BUNDLE");
    String apname=request.getParameter("ap");
    User user = (User)session.getAttribute("USER");

    if(apname==null) return;

    String action = request.getParameter("action");
    int menuSetIndex=Encoder.parseInt(request.getParameter("msi"),MenuSet.DEFAULT_MENUSET);

    if("loadVersion".equals(action)) {
        int version = Encoder.parseInt(request.getParameter("version"), -1);
        if(version != -1) {
            String rhFileName = Util.getReportHistoryFileName(apname, version);
            if(!rhFileName.isEmpty()) {
                File configFile = new File("cust/def/app/"+apname+"/report.json");
                File rhFile = new File("cust/def/app/"+apname+"/ragic-setup/reportHistory/" + rhFileName);
                if(configFile.exists() && rhFile.exists()) {
                    ReportConfig rc = Account.getInstance(apname).getReportConfig();
                    rc.readConfigFromFile(rhFile);
                    rc.save(user);
                }
                MenuSet ms = Account.getInstance(apname).getMenuSet(menuSetIndex);
                ReportConfig reportConfig=Account.getInstance(apname).getReportConfig();
                MenuTab reportTab=ms.getTab("Report");
                if(reportTab==null){
                    reportTab=new MenuTab(Const.HOME_VAR_REPORT, "Report", ms.getConfig());
                    reportTab.setReportTab(true);
                    ms.addTab(reportTab);
                } else {
                    ms.removeTab(reportTab);
                    reportTab=new MenuTab(Const.HOME_VAR_REPORT, "Report", ms.getConfig());
                    reportTab.setReportTab(true);

                    ms.addTab(reportTab);
                }

                for(Report r:reportConfig.listReports()){
                    if(reportTab.getReport(r.getId()) == null){
                        reportTab.addReport(new MenuReport(r.getName(),r.getId(),ms.getConfig()));
                    }
                }
            }
        }
    } else {
        Set<ReportHistory> reportHistories = ReportHistory.getReportHistories(bundle, apname);

        JSONObject result = new JSONObject();
        JSONArray historiesJa = new JSONArray();

        Account account = Account.getInstance(apname);
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        for(ReportHistory rh : reportHistories) {
            String userName = account.getUserName(rh.getEmail());
            if(userName == null) userName = "";
            JSONObject rhJo = new JSONObject();
            String dateTime = sdf.format(rh.getDate());
            rhJo.put("userName", userName);
            rhJo.put("version", rh.getVersion());
            rhJo.put("dateTime", dateTime);

            historiesJa.put(rhJo);
        }
        result.put("reportHistories", historiesJa);

        out.print(result.toString(2));
    }

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
