/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2022-11-10 01:41:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sims;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ragic.s3.nui.helper.Encoder;
import com.ragic.s3.nui.User;
import com.ragic.s3.nui.RagicBundle;
import com.ragic.s3.util.Util;
import com.ragic.s3.nui.helper.AppManager;
import com.ragic.s3.nui.NUIForm;

public final class shareThisSheet_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ragic.s3.util.Util");
    _jspx_imports_classes.add("com.ragic.s3.nui.RagicBundle");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.AppManager");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.Encoder");
    _jspx_imports_classes.add("com.ragic.s3.nui.User");
    _jspx_imports_classes.add("com.ragic.s3.nui.NUIForm");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;



    RagicBundle bundle = (RagicBundle) session.getAttribute("RAGIC_BUNDLE");
    User user = (User) session.getAttribute("USER");
    String apname = request.getParameter("a");
    String path = request.getParameter("p");
    int sheetIndex = Encoder.parseInt(request.getParameter("si"));
    NUIForm form = AppManager.getFormPage(apname, path, sheetIndex);
    if(form==null) return;
    String realName=form.getRealname();
    String type=request.getParameter("type");

    //  https://localhost/clone2/forms/1?webview&webaction=form&ver=new&dfCheckbox
    String url=Util.getServerProtocol()+"://"+Util.getServerNameWithPort()+"/"+apname+path+"/"+sheetIndex;

    if(type==null) type="webform";

    if("webform".equals(type)){
        url+="?webview&webaction=form&ver=new&dfCheckbox";
    }
    else if("raw".equals(type)){}
    else {
        url+="?webview&webaction=form&ver=new&dfCheckbox";
    }

    String bcType="QR Code";


      out.write("<div style=\"float:left;font-size:16px;margin:0 0 30px 0;\">\r\n    <div>");
      out.print(bundle.getString("shareThisSheetOptions"));
      out.write(":</div>\r\n    <div style=\"margin:15px 8px 0 0;float:left;clear:left;\">\r\n        <input onclick=\"shareThisSheet('webform');\" style=\"margin:0 8px 0 0;\" id=\"shareSheetWebForm\" name=\"shareSheetOption\" type=\"radio\" ");
      out.print(("webform".equals(type)?"checked":""));
      out.write(">\r\n        <label for=\"shareSheetWebForm\">\r\n        ");
      out.print(bundle.getString("shareThisSheetWebform"));
      out.write("&nbsp;&nbsp;<a onclick=\"configWebEmbedForm();\" href=\"javascript:void(0);\">(");
      out.print(bundle.getString("configure"));
      out.write(")</a>\r\n        <a href=\"javascript:void(0);\" style=\"font-weight:700;margin:0 0 0 8px;\" onclick=\"showSingleTooltip(this,'HELP_SHARESHEET_WEBFORM',false,true,false,true);\">?</a>\r\n    </label></div>\r\n    <div style=\"margin:15px 8px 0 0;float:left;clear:left;\">\r\n        <input onclick=\"shareThisSheet('raw');\" style=\"margin:0 8px 0 0;\" id=\"shareSheetBasic\" name=\"shareSheetOption\" type=\"radio\" ");
      out.print(("raw".equals(type)?"checked":""));
      out.write(">\r\n        <label for=\"shareSheetBasic\">\r\n        ");
      out.print(bundle.getString("shareThisSheetRaw"));
      out.write("<a href=\"javascript:void(0);\" style=\"font-weight:700;margin:0 0 0 8px;\" onclick=\"showSingleTooltip(this,'HELP_SHARESHEET_RAW',false,true,false,true);\">?</a>\r\n    </label></div>\r\n</div>\r\n<div>\r\n    <div style=\"float:left;clear:left;margin:0 0 12px 0;font-size:18px;\">");
      out.print(bundle.getString("url"));
      out.write(":</div>\r\n    <div style=\"float:left;clear:left;margin:0 0 12px 0;\">\r\n        <input style=\"width:500px;\" onclick=\"this.select();\" type=\"text\" value=\"");
      out.print(url);
      out.write("\" />\r\n    </div>\r\n    <div style=\"float:left;clear:left;\">\r\n        <div style=\"float:left;clear:left;margin:12px 0 12px 0;font-size:18px;\">QR Code:</div>\r\n        <img style=\"float:left;clear:left;\" src=\"/sims/barcode.jsp?content=");
      out.print(Encoder.encodeURIComponent(url));
      out.write("&bc_type=");
      out.print(Encoder.encodeURIComponent(bcType));
      out.write("&width=200&height=200&ifAppendText=false\" />\r\n    </div>\r\n    <div style=\"float:left;\">\r\n        <div style=\"float:left;clear:left;font-size:16px;margin:226px 0 0 30px;\">\r\n            <a href=\"/sims/barcode.jsp?content=");
      out.print(Encoder.encodeURIComponent(url));
      out.write("&bc_type=");
      out.print(Encoder.encodeURIComponent(bcType));
      out.write("&width=200&height=200&ifAppendText=false&force&filename=");
      out.print(Encoder.encodeURIComponent(realName+"QRCode.png"));
      out.write("\">\r\n                ");
      out.print(bundle.getString("downloadQRCode"));
      out.write("</a>\r\n        </div>\r\n    </div>\r\n</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
