/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2022-11-10 01:41:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sims;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ragic.s3.nui.helper.AppManager;
import com.ragic.s3.util.Const;
import com.ragic.s3.nui.*;
import java.util.*;

public final class t_005fapproval_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


    private final List<String> validActionButtonAfterApproval =
            Collections.unmodifiableList(Arrays.asList("B","F", "T_lockThisEntry", "T_unlockThisEntry",
                    "T_loadAllListenFields", "T_recalThisEntry"));

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.ragic.s3.nui");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.AppManager");
    _jspx_imports_classes.add("com.ragic.s3.util.Const");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


    RagicBundle bundle = (RagicBundle) session.getAttribute("RAGIC_BUNDLE");

    User user = (User) session.getAttribute("USER");
    String apname = request.getParameter("a"),
            path = request.getParameter("p"),
            sheet = request.getParameter("fn");
    if (apname == null || path == null || sheet == null ||
            AppManager.getSheetRightByFormName(apname, path, sheet, user) == Const.NORIGHT) return;

    Account account = Account.getInstance(apname);
    NUIForm form = AppManager.getFormPage(apname, path, sheet);

    if(form == null) return;
    Map<String, ActionButton> actionButtons = form.getActionButtons();

    //create selection info
    StringBuilder selection = new StringBuilder(64);
    selection.append("<select onchange='changeApprovalItem(this);' onclick='checkApprovalOption(this);' style='width:100%;margin:3px 0;' class='wfDesignate'>");
    selection.append("<option selected='selected' value='all'>" + bundle.getString("approvalDefaultAll") + "</option>");

    selection.append("<optgroup data-designate='S' label='" + bundle.getString("approval_company_organize_tree") + "'>")
            .append("<option value=\"" + Const.APPROVAL_COMPANY_ORGANIZE_TREE_DIRECT_SUPERVISOR + "\">" + bundle.getString("approval_direct_supervisor") + "</option>")
            .append("<option value=\"" + Const.APPROVAL_COMPANY_ORGANIZE_TREE_SUPERVISOR_OF_SUPERVISOR + "\">" + bundle.getString("approval_supervisor_of_supervisor") + "</option>")
            .append("<option value=\"" + Const.APPROVAL_COMPANY_ORGANIZE_TREE_DIRECT_SUPERVISOR_OF_LAST_STEP + "\">" + bundle.getString("approval_direct_supervisor_of_last_step") + "</option>")
            .append("</optgroup>");

    Set<String> groups = account.getGroups();
    groups.add(Const.G_ADMIN);
    selection.append("<optgroup data-designate='G' label='" + bundle.getString("groups") + "'>");
    for (String group : groups) {
        selection.append("<option value=\"" + group + "\">" + group + "</option>");
    }
    selection.append("</optgroup>");

    selection.append("<optgroup data-designate='U' label='" + bundle.getString("users") + "'>");
    Map<String, String> activeUsers = account.getSortedActiveUsers();
    for (Map.Entry<String, String> entry : activeUsers.entrySet()) {
        String email = entry.getKey();
        String userName = entry.getValue();
        selection.append("<option value=\"" + email + "\">" + (userName.length() > 0 ? userName : email) + "</option>");
    }
    selection.append("</optgroup>");

    selection.append("<optgroup data-designate='P' label='" + bundle.getString("approvalCell") + "'>");
    List<CellInfo> fields = form.getAllFields(false);
    for (CellInfo field : fields) {
        Map<String, String> attrs = field.getAttributes();
        if((field.isSelection() && (attrs.containsKey("usrref") || attrs.containsKey("grpref"))) || attrs.containsKey("email")) {
            selection.append("<option value=\"" + field.getDomainId() + "\">" + field.getValue() + "</option>");
        }
    }
    selection.append("</optgroup>");


    selection.append("</select>");



      out.write("<table class=\"panelGrid\" id=\"approvalTable\">\r\n    <thead>\r\n    <tr>\r\n        <th style=\"width:5%\"> ID </th>\r\n        <th style=\"width:42%;\">\r\n            ");
      out.print(bundle.getString("approvalProcess"));
      out.write("<span style=\"color:#ff0000;\">*</span>\r\n        </th>\r\n        <th style=\"width:40%;\">\r\n            ");
      out.print(bundle.getString("approvalTransactor"));
      out.write("</th>\r\n        <th style=\"width:8%;\"></th>\r\n        <th style=\"width:5%\"></th>\r\n    </tr>\r\n    </thead>\r\n    <tbody></tbody>\r\n    <tfoot>\r\n    <tr>\r\n        <td style=\"border:0;padding:6px 12px;\" colspan=\"4\">\r\n            <a style=\"display:inline-block;padding-top:5px;\" onclick=\"createApprovalItem();\"\r\n               href=\"javascript:void(0);\">");
      out.print(bundle.getString("addApprovalProcess"));
      out.write("</a>\r\n            <br/>\r\n\r\n            <a id=\"approvalAdvanceAnchor\" style=\"display:none;padding-top:5px;\"\r\n               onclick=\"this.style.display='none';$('approvalAdvanceSetting').style.display='';$('approvalCCSetting').style.display='';\r\n               $('actionButtonAfterApprovalSetting').style.display='';\"\r\n               ");
      out.write("\r\n               href=\"javascript:void(0);\">");
      out.print(bundle.getString("advancedSetting"));
      out.write("</a>\r\n\r\n            <div id=\"approvalAdvanceSetting\" style=\"display:none;margin: 0 auto\">\r\n\r\n                <div id=\"approvalPolicyOuter\" style=\"display: inline-block\">\r\n                    <div class=\"approvalPolicyDiv\">\r\n                        <input type=\"checkbox\" name=\"approvalPolicyStrict\" id=\"approvalPolicyStrict\"\r\n                               onchange=\"changeApprovalPolicy(this, 0);\">\r\n                        <label for=\"approvalPolicyStrict\">");
      out.print(bundle.getString("approvalStrictVerify"));
      out.write("</label>\r\n                        <a href=\"javascript:void(0);\"\r\n                           onclick=\"showSingleTooltip(this,'HELP_STRICT_APPROVAL',false,true,false,true,true);\"\r\n                           class=\"tooltipQ\"><i class=\"fas fa-question\"></i></a>\r\n                    </div>\r\n\r\n                    <div class=\"approvalPolicyDiv\">\r\n                        <input type=\"checkbox\" name=\"approvalPolicyReject\" id=\"approvalPolicyReject\"\r\n                               onchange=\"changeApprovalPolicy(this, 1);\">\r\n                        <label for=\"approvalPolicyReject\">");
      out.print(bundle.getString("approvalRejectionAllow"));
      out.write("</label>\r\n                    </div>\r\n\r\n                    <div class=\"approvalPolicyDiv\">\r\n                        <input type=\"checkbox\" name=\"approvalPolicyLock\" id=\"approvalPolicyLock\"\r\n                               onchange=\"changeApprovalPolicy(this, 2);\">\r\n                        <label for=\"approvalPolicyLock\">");
      out.print(bundle.getString("approvalAutoLockEntry"));
      out.write("</label>\r\n                    </div>\r\n\r\n                    <div class=\"approvalPolicyDiv\">\r\n                        <input type=\"checkbox\" name=\"autoApproval\" id=\"autoApproval\"\r\n                               onchange=\"changeApprovalPolicy(this, 3);\">\r\n                        <label for=\"autoApproval\">");
      out.print(bundle.getString("autoApproval"));
      out.write("</label>\r\n                        <a href=\"javascript:void(0);\" onclick=\"showSingleTooltip(this,'HELP_AUTOAPPROVAL',false,true,false,true, true);\"\r\n                           class=\"tooltipQ\"><i class=\"fas fa-question\"></i></a>\r\n                    </div>\r\n\r\n                    <div class=\"approvalPolicyDiv\">\r\n                        <input type=\"checkbox\" name=\"approvalManuallySign\" id=\"approvalManuallySign\"\r\n                               onchange=\"changeApprovalPolicy(this, 4);\">\r\n                        <label for=\"approvalManuallySign\">");
      out.print(bundle.getString("approvalManuallySign"));
      out.write("</label>\r\n                    </div>\r\n\r\n                    <div class=\"approvalPolicyDiv\">\r\n                        <input type=\"checkbox\" name=\"approvalOnlyNofitySubmitter\" id=\"approvalOnlyNofitySubmitter\"\r\n                               onchange=\"changeApprovalPolicy(this, 5);\">\r\n                        <label for=\"approvalOnlyNofitySubmitter\">");
      out.print(bundle.getString("approvalOnlyNofitySubmitter"));
      out.write("<a href=\"javascript:void(0);\" onclick=\"showSingleTooltip(this,'HELP_ONLY_NOTIFY_SUBMITTER',false,true,false,true, true);\" class=\"tooltipQ\">\r\n                                <i class=\"fas fa-question\"></i></a>\r\n                        </label>\r\n                    </div>\r\n\r\n                    <div class=\"approvalPolicyDiv\">\r\n                        <input type=\"checkbox\" name=\"cancelProhibited\" id=\"cancelProhibited\"\r\n                               onchange=\"changeApprovalPolicy(this, 6);\">\r\n                        <label for=\"cancelProhibited\">");
      out.print(bundle.getString("cancelProhibited"));
      out.write("<a href=\"javascript:void(0);\" onclick=\"showSingleTooltip(this,'HELP_CANCELPROHIBITED',false,true,false,true, true);\" class=\"tooltipQ\">\r\n                                <i class=\"fas fa-question\"></i></a>\r\n                        </label>\r\n                    </div>\r\n\r\n                    <div class=\"approvalPolicyDiv\">\r\n                        <input type=\"checkbox\" name=\"dontShowCommentBlock\" id=\"dontShowCommentBlock\"\r\n                               onchange=\"changeApprovalPolicy(this, 7);\">\r\n                        <label for=\"dontShowCommentBlock\">");
      out.print(bundle.getString("dontShowCommentBlock"));
      out.write("</label>\r\n                    </div>\r\n\r\n                    <div id=\"approvalCCSetting\" style=\"display:none;margin: 5px 0 0 0;text-align: left;\">\r\n                        <div style=\"display:inline-block\"><i class=\"fa-fw far fa-envelope\"></i><span>");
      out.print(bundle.getString("approvalCC"));
      out.write(":</span></div>\r\n                        <select id=\"approvalCCSelect\">\r\n                            <option value='' ></option>\r\n                            ");

                                for (Map.Entry<String, String> entry : activeUsers.entrySet()) {
                                    String email = entry.getKey();
                                    String userName = entry.getValue();
                            
      out.write("<option value='");
      out.print(email);
      out.write('\'');
      out.write('>');
      out.print((userName.length() > 0? userName : email));
      out.write("</option>\r\n                            ");

                                }
                            

                                groups = account.getGroups();
                                for(String group : groups) {
                            
      out.write("<option data-icon=\"fa-users\" value='");
      out.print(group);
      out.write('\'');
      out.write('>');
      out.print(group);
      out.write("</option>\r\n                            ");

                                }
                            

                                for (CellInfo field : fields) {
                                    Map<String, String> attrs = field.getAttributes();
                                    if((field.isSelection() && (attrs.containsKey("usrref") || attrs.containsKey("grpref")))) {
                                        
      out.write("<option data-icon='' value='");
      out.print(Const.APPROVAL_CC_PREFIX);
      out.print(field.getDomainId());
      out.write('\'');
      out.write('>');
      out.print(field.getValue());
      out.write("</option>\r\n                            ");

                                    }
                                }
                            
      out.write("</select>\r\n                    </div>\r\n                    <div id=\"actionButtonAfterApprovalSetting\" style=\"display:none;margin: 5px 0 0 0;text-align: left;\">\r\n                        <div style=\"display:inline-block\"><i class=\"fa-fw far fa-caret-square-right\"></i><span>");
      out.print(bundle.getString("actionButtonAfterApproval"));
      out.write(":</span></div>\r\n                        <select id=\"actionButtonSelect\">\r\n                            <option value='' ></option>\r\n                            ");

                                for(Map.Entry<String, ActionButton> ab:actionButtons.entrySet()) {
                                    String actionButtionId = ab.getKey();
                                    ActionButton actionButton = ab.getValue();
                                    String actionButtonName = actionButton.getName();
                                    String buttonType = actionButton.getType();
                                    if(!validActionButtonAfterApproval.contains(buttonType)) continue;
                            
      out.write("<option value='");
      out.print(actionButtionId);
      out.write('\'');
      out.write('>');
      out.print(actionButtonName);
      out.write("</option>\r\n                            ");

                                }
                            
      out.write("</select>\r\n                        <a href=\"javascript:void(0);\" style=\"left: 20px\" onclick=\"showSingleTooltip(this,'HELP_EXECUTE_ACTION_BUTTON_AFTER_APPROVED',false,true,true,true,true);\" class=\"tooltipQ\">\r\n                            <i class=\"fas fa-question\"></i>\r\n                        </a>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n        </td>\r\n    </tr>\r\n    </tfoot>\r\n</table>\r\n\r\n");
      out.write("<div style=\"display:none;\">\r\n    ");
      out.print(selection);
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
