/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2022-11-10 01:41:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sims;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ragic.s3.nui.NUIForm;
import com.ragic.s3.nui.RagicBundle;
import com.ragic.s3.nui.User;
import com.ragic.s3.nui.helper.AppManager;
import com.ragic.s3.nui.helper.Encoder;
import com.ragic.s3.nui.helper.RemoteAccountManager;
import com.ragic.s3.service.workflow.Workflow;
import com.ragic.s3.util.Const;
import com.ragic.s3.util.DES;
import com.ragic.s3.util.Util;
import java.util.Set;
import com.ragic.s3.service.api.APIQuery;
import com.ragic.s3.service.api.APIEntry;

public final class wf_005fmailResult_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ragic.s3.util.Util");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.AppManager");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.RemoteAccountManager");
    _jspx_imports_classes.add("com.ragic.s3.service.workflow.Workflow");
    _jspx_imports_classes.add("java.util.Set");
    _jspx_imports_classes.add("com.ragic.s3.nui.User");
    _jspx_imports_classes.add("com.ragic.s3.nui.NUIForm");
    _jspx_imports_classes.add("com.ragic.s3.util.Const");
    _jspx_imports_classes.add("com.ragic.s3.service.api.APIEntry");
    _jspx_imports_classes.add("com.ragic.s3.service.api.APIQuery");
    _jspx_imports_classes.add("com.ragic.s3.nui.RagicBundle");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.Encoder");
    _jspx_imports_classes.add("com.ragic.s3.util.DES");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


    RagicBundle bundle = (RagicBundle) session.getAttribute("RAGIC_BUNDLE");
    boolean hasLoggedIn = true;
    String apname = request.getParameter("a"),
           path = request.getParameter("p"),
           sheet = request.getParameter("fn"),
           sheetIndex = "1",
           wfId = request.getParameter("wfId"),
           encryptEmail = request.getParameter("cmail"),
           comment = request.getParameter("comment"),
           wfResp = request.getParameter("response"),
           apr_pwd = request.getParameter("apr_pwd"),
           sigData = request.getParameter("dig_sig");
    if (sheet != null) sheetIndex = sheet.split("_")[0];
    int nodeId = Encoder.parseInt(request.getParameter("n"), Const.NONODE);
    String entryUrl = Util.getServerUrl() + "/" + apname + path + "/" + sheetIndex + "/" + nodeId;

    NUIForm form = AppManager.getFormPage(apname, path, sheet);
    if (form == null || !form.isUsable()) return;

    APIQuery aq = new APIQuery(apname, path, sheet);
    APIEntry ae = aq.getAPIEntry(nodeId);

    if(ae == null) {
        out.println("<div style='text-align: center;" +
                "margin: 30px 0 0 0;" +
                "font-size: 18px;'>"+ bundle.getString("invalidApprovalEntry")+"</div>");
    } else {

    Workflow wf = Workflow.load(apname, wfId);
    if (wf == null) return;



    String rawDecrypt = new DES().decrypt(encryptEmail);
    if (rawDecrypt == null) return;
    String email = rawDecrypt.substring((path + sheet + form.getRootDomainId()).length());

    Set<String> emails = wf.getNextDeputyChain();

    boolean NotReply = Workflow.PROCESSING.equals(wf.getStatus()) && !emails.add(email),
            doPWDCheck = form.isStrictApproval(),
            digitalSigning = form.isApprovalDigitalSigning(),
            passPWDCheck = false,
            canceled = Workflow.NEW.equals(wf.getStatus()) || Workflow.CANCEL.equalsIgnoreCase(wf.getStatus());

    String pwdHint = bundle.getString("approval_pwd_req"),
           commentHint = bundle.getString("approval_comment_req"),
           pwSuggest = "";

    if (doPWDCheck && apr_pwd != null) {
        if (RemoteAccountManager.main_authenticateUser(email, apr_pwd, "PWD") != null) {
            passPWDCheck = true;
        } else {
            pwSuggest = bundle.getString("ApprovalConfirmWrongPassword");
        }
    }

  /*Common HTML code below*/

      out.write("<!DOCTYPE html>\r\n<html style=\"margin-top: 30px\">\r\n<head>\r\n    <meta http-equiv=\"Content-Type\" content=\"text/html;charset=utf-8\"/>\r\n    <link rel=\"stylesheet\" type=\"text/css\" href=\"/intl/common/fa5/css/fontawesome-all.min.css\" />\r\n    <style>\r\n        * {\r\n            box-sizing: border-box;\r\n        }\r\n\r\n        body {\r\n            font-family: \"Open Sans\", \"Noto Sans CJK TC\", \"Noto Sans CJK SC\", \"Noto Sans CJK JP\", \"Noto Sans CJK KR\", \"Lucida Grande\", Tahoma, arial, sans-serif;\r\n        }\r\n\r\n        #msgBox {\r\n            max-width: 640px;\r\n            border-radius: 4px;\r\n            border: #bbb 1px solid;\r\n            box-shadow: inset 0 0 5px #efefef;\r\n            margin: 0 auto;\r\n        }\r\n\r\n        #msg {\r\n            margin: 20px 20px 20px 20px;\r\n            text-align: center;\r\n        }\r\n\r\n        input[type=\"submit\"] {\r\n            border: #bbb 1px solid;\r\n            padding: 2px;\r\n        }\r\n\r\n        .signatureBlock {\r\n            position: relative;\r\n        }\r\n\r\n        .clearSignatureIcon {\r\n");
      out.write("            position: absolute;\r\n            top: 0px;\r\n            right: 0px;\r\n            margin: 10px;\r\n            cursor: pointer;\r\n        }\r\n\r\n        .topButtonWhole {\r\n            width: 100px;\r\n            height: 40px;\r\n            cursor: pointer;\r\n            color: #ffffff;\r\n            border: 0;\r\n            border-radius: 3px;\r\n            -webkit-border-radius: 3px;\r\n            -moz-border-radius: 3px;\r\n            padding: 5px 10px;\r\n            margin: 5px 10px;\r\n            appearance: none;\r\n            -webkit-appearance: none;\r\n            -moz-appearance: none;\r\n            display: flex;\r\n            flex-direction: column;\r\n            justify-content: center;\r\n        }\r\n\r\n        .btn-red {\r\n            background-color: #f27079;\r\n        }\r\n    </style>\r\n</head>\r\n<body>\r\n<div id=\"msgBox\">\r\n    <div id=\"msg\">\r\n        ");

            if(canceled) {
              out.println(bundle.getString("ApprovalCancelled"));
            } else if (!NotReply) {
                out.println(bundle.getString("ApprovalStepExpired"));
            } else if ((!doPWDCheck || passPWDCheck) && comment != null) {
                //if user had replied this mail approval, show complete message.
                User user = (User) session.getAttribute("USER");
                if (user == null || !user.getUserId().equals(email)) {
                    user = new User();
                    user.setUserId(email);
                    user.setIp(request.getRemoteAddr());
                    session.setAttribute("USER", user);//real user object should come from logging in
                    hasLoggedIn = false;
                }
                RequestDispatcher dispatcher = request.getRequestDispatcher("wf_index.jsp?act=sign&fromMail");
                dispatcher.include(request, response);
                if (!hasLoggedIn) session.removeAttribute("USER");  //removev user object after submit response
                if (Workflow.ACCEPT.equals(wfResp)) {
                    out.print(String.format(bundle.getString("ApprovalSelectApproveMessage"), entryUrl));
                } else if (Workflow.REJECT.equals(wfResp)) {
                    out.print(String.format(bundle.getString("ApprovalSelectRejectMessage"), entryUrl));
                }
            } else { 
      out.write("<form id=\"approvalForm\" action=\"\" method=\"post\">\r\n            <input name=\"a\" type=\"hidden\" value=\"");
      out.print(apname);
      out.write("\">\r\n            <input name=\"p\" type=\"hidden\" value=\"");
      out.print(path);
      out.write("\">\r\n            <input name=\"fn\" type=\"hidden\" value=\"");
      out.print(sheet);
      out.write("\">\r\n            <input name=\"n\" type=\"hidden\" value=\"");
      out.print(nodeId);
      out.write("\">\r\n            <input name=\"response\" type=\"hidden\" value=\"");
      out.print(wfResp!=null?wfResp:"A");
      out.write("\">\r\n            <input name=\"cmail\" type=\"hidden\" value=\"");
      out.print(encryptEmail);
      out.write("\">\r\n            <input name=\"wfId\" type=\"hidden\" value=\"");
      out.print(wfId);
      out.write("\">\r\n            <input name=\"dig_sig\" type=\"hidden\" value=\"\">\r\n            ");
if (doPWDCheck) {
      out.write("<h3>");
      out.print(pwdHint );
      out.write("</h3>\r\n            ");
if (pwSuggest.length() > 0) { 
      out.write("<label>");
      out.print(pwSuggest);
      out.write("</label><br/>");
} 
      out.write("<input name=\"apr_pwd\" type=\"password\">\r\n            ");
}
if(digitalSigning && Workflow.ACCEPT.equals(wfResp)) { 
      out.write("<h3 style=\"margin-bottom: 10px\">");
      out.print(bundle.getString("signature"));
      out.write("</h3>\r\n              <div style=\"display: flex;justify-content: center;\">\r\n                  <div id=\"approvalCanvasContainer\" class=\"signatureBlock\" style=\"margin:0 0 5px 0;\">\r\n                      <canvas id=\"approvalSigcanvas\" width=\"500\" height=\"250\" style=\"background:#f8f8f8;border:1px solid #ccc;border-radius:5px;margin:0 0 8px 0;\"></canvas>\r\n                      <div class=\"clearSignatureIcon\" onclick=\"clearSig();\"><i class=\"fas fa-redo-alt\"></i></div>\r\n                  </div>\r\n              </div>\r\n              <div id=\"approvalSigBackgroundDiv\"></div>\r\n            ");
 } 
      out.write("<h3 style=\"margin-bottom: 10px\">");
      out.print(commentHint );
      out.write("</h3>\r\n            <textarea style=\"width:500px;height:80px;\" name=\"comment\">");
      out.print(comment != null ? comment : "");
      out.write("</textarea>\r\n\r\n            <div style=\"display:flex;justify-content:center;padding:10px 0 10px 0;\">\r\n                <div class=\"topButtonWhole btn-red\" type=\"submit\" onclick=\"approvalSubmit()\" value=\"\"><div>OK</div></div>\r\n            </div>\r\n        </form>\r\n        ");
 } 
      out.write("</div>\r\n</div>\r\n</body>\r\n</html>\r\n<script>\r\n    let sigPad;\r\n    function clearSig() {\r\n        sigPad.clear();\r\n        sigPad._isBackGroundEmpty = true;\r\n    }\r\n\r\n    function approvalSubmit() {\r\n        if (sigPad) {\r\n            let data = sigPad.toDataURL();\r\n            document.getElementById(\"approvalForm\").elements.namedItem('dig_sig').value = data;\r\n        }\r\n        document.getElementById(\"approvalForm\").submit();\r\n    }\r\n\r\n    function loadSigScript(canvas,data){\r\n        if(window['SignaturePad']){\r\n            sigPad = new SignaturePad(canvas);\r\n            if(data) sigPad.fromDataURL(data);\r\n            return;\r\n        }\r\n        var script = document.createElement('script');\r\n        script.src = '/sims/js/signature.js';\r\n        script.onload = function () {\r\n            sigPad = new SignaturePad(canvas);\r\n            if(data) sigPad.fromDataURL(data);\r\n        };\r\n        document.head.appendChild(script);\r\n    }\r\n    var canvas = document.getElementById(\"approvalSigcanvas\");\r\n    if(canvas)\r\n");
      out.write("    loadSigScript(canvas);\r\n\r\n    // if (!ctrl.isIE || !ctrl.isObsoleteIE) {\r\n    //     setSignatureBackgroundBox($('approvalSigBackgroundDiv'), true);\r\n    // }\r\n</script>\r\n");

    }

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
