/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2022-11-10 01:41:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sims.dev;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ragic.s3.nui.User;
import com.ragic.s3.nui.helper.UserManager;
import com.ragic.s3.nui.helper.Encoder;
import com.ragic.s3.nui.helper.AppManager;
import com.ragic.s3.nui.NUIForm;
import com.ragic.s3.sdb.data.bdb.BDBWorker;
import com.ragic.s3.nui.CellInfo;
import com.ragic.s3.sdb.query.SDBQuery;
import com.ragic.s3.sdb.query.SDBQueryFull;
import com.ragic.s3.sdb.query.SDBNode;
import java.util.List;
import com.ragic.s3.util.Const;
import com.ragic.s3.sdb.data.bdb.BDBWorkerCommand;
import java.util.ArrayList;
import com.ragic.s3.sdb.data.bdb.BDBWorkerCommandUnlink;
import com.ragic.s3.nui.CellLocation;
import java.util.Map;

public final class dbconsole2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ragic.s3.sdb.data.bdb.BDBWorkerCommand");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.AppManager");
    _jspx_imports_classes.add("com.ragic.s3.sdb.query.SDBQuery");
    _jspx_imports_classes.add("com.ragic.s3.nui.User");
    _jspx_imports_classes.add("com.ragic.s3.nui.NUIForm");
    _jspx_imports_classes.add("com.ragic.s3.util.Const");
    _jspx_imports_classes.add("com.ragic.s3.nui.CellInfo");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("com.ragic.s3.sdb.data.bdb.BDBWorkerCommandUnlink");
    _jspx_imports_classes.add("com.ragic.s3.sdb.data.bdb.BDBWorker");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("com.ragic.s3.nui.CellLocation");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.Encoder");
    _jspx_imports_classes.add("com.ragic.s3.sdb.query.SDBNode");
    _jspx_imports_classes.add("com.ragic.s3.sdb.query.SDBQueryFull");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.UserManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


  //access right check
  User access=(User)session.getAttribute("USER");
  if(access==null || !UserManager.ifRagicSupport(access.getUserId())) {
    if(access!=null) out.println("No access for "+access.getUserId());
    else out.println("Not Logged In.");
    return;
  }

  String recordURL=request.getParameter("record");//   /support/nobug/1/123
  if(recordURL==null) {
    out.println("Input Record URL (ex:/support/nobug/1/123) : <form method=GET action='dbconsole2.jsp'><input type='text' name='record' /><input type='submit' /></form>");
    return;
  }
  String[] sec=recordURL.split("/");
  if(sec.length<5){
    out.println("<span style=color:red>Invalid Record URL</span> (ex:/support/nobug/1/123) : <form method=GET action='dbconsole2.jsp'><input type='text' name='record' /><input type='submit' /></form>");
    return;
  }
  String apname=sec[1];
  String path="/"+sec[2];
  int sheetIndex= Encoder.parseInt(sec[3]);
  int recordId=Encoder.parseInt(sec[4]);
  NUIForm form= AppManager.getFormPage(apname, path, sheetIndex);
  boolean useLastNode="true".equals(request.getParameter("uln"));

  String action=request.getParameter("action");
  if("unlink".equals(action)){
    BDBWorker worker=new BDBWorker(apname);
    try{
      int domainId=Encoder.parseInt(request.getParameter("d"), Const.NONODE);
      int nodeId=Encoder.parseInt(request.getParameter("ni"), Const.NONODE);
      worker.unlinkNode(form.getRootDomainId(),recordId,domainId,nodeId);
    }
    finally{
      worker.commit();
    }
    return;
  }
  else if("dedup".equals(action)){
    BDBWorker worker=new BDBWorker(apname);
    List<BDBWorkerCommand> dedups=new ArrayList<>();
    try{
      int key=form.getKeyField();
      SDBQuery q=new SDBQueryFull(worker);
      q.go(key);
      SDBNode keyNode;
      while((keyNode=q.next())!=null){
        for(CellInfo info:form.getAllFields(false)){
          if(Const.MSELECT.equals(info.getType()) || info.isMultiFilesUpload()) continue;

          List<SDBNode> list=q.dipAllNodes(info.getDomainId());
          for(int i=0;i<list.size();i++){
            int keepIndex=useLastNode?list.size()-1:0;
            if(i!=keepIndex) {
              System.out.println("Dedup for keyNodeId: "+keyNode.getId());
              dedups.add(new BDBWorkerCommandUnlink(key,keyNode.getId(),info.getDomainId(),list.get(i).getId()));
            }
          }
        }
        //do subtables
        Map<CellLocation,Integer> subtableKeys=form.getSubtableKey();
        for(Map.Entry<CellLocation,Integer> e:subtableKeys.entrySet()){
          Integer subtableKey=e.getValue();
          List<CellInfo> subtableCellInfoList =form.getSubtableFields(subtableKey);
          Integer parentAlias=form.getSubtableParentAlias(e.getKey());
          q.go(e.getValue());
          if(parentAlias!=null){
            q.setAliasParent(parentAlias);
          }
          SDBNode subtableKeyNode=null;
          while((subtableKeyNode=q.next())!=null){
            for(CellInfo info: subtableCellInfoList){
              if(Const.MSELECT.equals(info.getType()) || info.isMultiFilesUpload()) continue;
              List<SDBNode> list=q.dipAllNodes(info.getDomainId());
              for(int i=0;i<list.size();i++){
                int keepIndex=useLastNode?list.size()-1:0;
                if(i!=keepIndex) {
                  dedups.add(new BDBWorkerCommandUnlink(subtableKey,subtableKeyNode.getId(),info.getDomainId(),list.get(i).getId()));
                }
              }
              out.println("</div>");
            }
          }
          out.println("</div>");
          q.goback();
        }
      }
    }
    finally{
      worker.commit();
    }
    worker=new BDBWorker(apname);
    try{
      System.out.println("Dedup removing "+dedups.size()+" links for "+apname+path+"/"+sheetIndex);
      for(BDBWorkerCommand c:dedups){
        c.execute(worker);
      }
      System.out.println("Dedup removed "+dedups.size()+" links for "+apname+path+"/"+sheetIndex);
    }
    finally{
      worker.commit();
    }
  }

      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/intl/common/fa5/css/fontawesome-all.min.css\" />\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"/intl/common/sims.css?v=3776\"/>\r\n<style>\r\ndiv{font-size:10px;}\r\n</style>\r\n");


  //to add:
  //  1. Delete Node
  //  2. Unlink Node
  //  3. List all nodes under a field id


  BDBWorker worker=new BDBWorker(apname);
  try{
    int key=form.getRootDomainId();
    SDBQuery q=new SDBQueryFull(worker);
    q.go(key);
    q.filter(recordId);
    SDBNode keyNode =q.next();
    if(keyNode==null){
      out.println("record not found<br>");
      out.println("Input Record URL (ex:/support/nobug/1/123) : <form method=GET action='dbconsole2.jsp'><input type='text' name='record' /><input type='submit' /></form>");
      return;
    }
    out.println("<div style='background:#ccc;margin:10px 5px 10px 0;padding:3px;'>"+ keyNode.getId()+"|"+Encoder.textToHTML(keyNode.getValue())+"</div>");
    for(CellInfo info:form.getAllFields(false)){
      List<SDBNode> list=q.dipAllNodes(info.getDomainId());
      boolean first=true;
      out.println("<div style='background:#efefef;margin:10px 5px 10px 25px;padding:3px;'>");
      out.println(info.getValue());
      for(SDBNode node:list){
        out.println("<div style='display:inline-block;border:1px #ccc solid;border-radius:3px;padding:2px;margin:3px;"+(!first?"color:#08c;font-weight:800;":"")+"'>"+node.getId()+"|"+Encoder.textToHTML(node.getValue())+"</div>");
        out.println("<div style='display:inline-block;cursor:pointer;' onclick='unlinkNode("+info.getDomainId()+","+node.getId()+")'>x</div>");
        first=false;
      }
      out.println("</div>");
    }

    Map<CellLocation,Integer> subtableKeys=form.getSubtableKey();
    for(Map.Entry<CellLocation,Integer> e:subtableKeys.entrySet()){
      List<CellInfo> subtableCellInfoList =form.getSubtableFields(e.getValue());
      out.println("<div style='background:#cde;margin:10px 5px 10px 10px;padding:3px;'>");
      Integer parentAlias=form.getSubtableParentAlias(e.getKey());
      q.go(e.getValue());
      if(parentAlias!=null){
        q.setAliasParent(parentAlias);
      }
      while(q.next()!=null){
        for(CellInfo info: subtableCellInfoList){
          List<SDBNode> list=q.dipAllNodes(info.getDomainId());
          boolean first=true;
          out.println("<div style='background:#efefef;margin:10px 5px 10px 25px;padding:3px;'>");
          out.println(info.getValue());
          for(SDBNode node:list){
            out.println("<div style='display:inline-block;border:1px #ccc solid;border-radius:3px;padding:2px;margin:3px;"+(!first?"color:#08c;font-weight:800;":"")+"'>"+node.getId()+"|"+Encoder.textToHTML(node.getValue())+"</div>");
            //if(!first) out.println("<div style='display:inline-block;cursor:pointer;' onclick='unlinkSubtableNode("+info.getDomainId()+","+node.getId()+")'>x</div>");
            first=false;
          }
          out.println("</div>");
        }
      }
      out.println("</div>");
      q.goback();
    }
  }
  finally{
    worker.commit();
  }

      out.write("<input type=\"button\" onclick=\"dedup()\" value=\"Remove Duplicated Nodes for all records on this sheet\" style=\"margin:20px;\"/>\r\n<input type=\"button\" onclick=\"dedup(true)\" value=\"Use last node to remove Duplicated Nodes for all records on this sheet\" style=\"margin:20px;\"/>\r\n<script>\r\n  function ajaxget(url,obj,callback,sync){\r\n    var qs='?';\r\n    var first=true;\r\n    for(var key in obj){\r\n      if(!first) qs+='&';\r\n      else first=false;\r\n      qs+=encodeURIComponent(key)+'='+encodeURIComponent(obj[key]);\r\n    }\r\n\r\n    var _reader=new XMLHttpRequest();\r\n    _reader.open('GET',url+qs,!sync);\r\n    if(!sync){\r\n      _reader.onreadystatechange = function(){\r\n        if(_reader.readyState==4){\r\n          if(_reader.status!=200){\r\n            return false;\r\n          }\r\n          if(callback) callback(_reader.responseText);\r\n          return true;\r\n        }\r\n      }\r\n    }\r\n    _reader.send(null);\r\n    if(sync) {\r\n      if(_reader.status!=200){\r\n        return false;\r\n      }\r\n      if(callback) callback(_reader.responseText);\r\n");
      out.write("    }\r\n    return true;\r\n  }\r\nfunction dedup(useLastNode){\r\n  ajaxget('/sims/dev/dbconsole2.jsp',{'record':'");
      out.print(recordURL);
      out.write("','action':'dedup','uln':(useLastNode?'true':'false')},function(){\r\n    location.reload();\r\n  },true);\r\n}\r\nfunction unlinkNode(domainId,id){\r\n  ajaxget('/sims/dev/dbconsole2.jsp',{'record':'");
      out.print(recordURL);
      out.write("','action':'unlink','d':domainId,'ni':id},function(){\r\n    location.reload();\r\n  });\r\n}\r\n</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
