/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2022-11-10 01:41:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sims.dev;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ragic.s3.nui.helper.Encoder;
import com.ragic.s3.sdb.data.bdb.BDBWorker;
import com.ragic.s3.nui.helper.DataHelper;
import com.ragic.s3.nui.Selection;
import com.ragic.s3.sdb.query.SDBNode;
import com.ragic.s3.sdb.query.SDBQuery;
import com.ragic.s3.sdb.query.SDBQueryFull;
import com.ragic.s3.nui.helper.UserManager;
import com.ragic.s3.nui.User;
import java.util.*;

public final class fixSelection2Free_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ragic.s3.sdb.data.bdb.BDBWorker");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.DataHelper");
    _jspx_imports_classes.add("com.ragic.s3.sdb.query.SDBQuery");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.Encoder");
    _jspx_imports_classes.add("com.ragic.s3.sdb.query.SDBNode");
    _jspx_imports_classes.add("com.ragic.s3.nui.Selection");
    _jspx_imports_classes.add("com.ragic.s3.sdb.query.SDBQueryFull");
    _jspx_imports_classes.add("com.ragic.s3.nui.User");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.UserManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;



  String apname=request.getParameter("a");
  int keyDomainId= Encoder.parseInt(request.getParameter("key"));
  int freeDomainId=Encoder.parseInt(request.getParameter("free"));
  boolean detect=request.getParameter("detect")!=null;
  if(apname==null || keyDomainId==0 || freeDomainId==0) return;

  //access right check
  User access=(User)session.getAttribute("USER");
  if(access==null || !access.ifApManager(apname)) {
    if(access!=null) out.println("This function is only for user group SYSAdmin. No access for "+access.getUserId());
    else out.println("Not Logged In.");
    return;
  }

  BDBWorker worker=new BDBWorker(apname);
  if(detect){
    Set<Integer> listOfLinkedNodeIds= new HashSet<>();
    Set<String> parentInfo=new LinkedHashSet<>();
    int duplicateLinkCount=0;
    SDBQuery q=new SDBQueryFull(worker);
    q.go(keyDomainId);
    SDBNode keyNode;
    while((keyNode =q.next())!=null){
      SDBNode nodeFree=q.dipNode(freeDomainId);
      if(nodeFree==null) continue;
      if(listOfLinkedNodeIds.contains(nodeFree.getId())) {
        parentInfo.add(keyNode.getId()+":"+ keyNode.getValue());
        duplicateLinkCount++;
      }
      listOfLinkedNodeIds.add(nodeFree.getId());
    }
    worker.commit();
    out.print("Selection duplicated links:"+duplicateLinkCount+"<br>");
    for(String s:parentInfo) out.println(s+"<br>");
    return;
  }



  Map<Integer,String> newLink= new HashMap<>();
  try{
    //go through each node and get where they should link to
    SDBQuery q=new SDBQueryFull(worker);
    q.go(keyDomainId);
    SDBNode node;
    while((node=q.next())!=null){
      int keyNodeId=node.getId();
      node=q.dipNode(freeDomainId);
      if(node==null) continue;
      newLink.put(keyNodeId,node.getValue());
    }
  }
  finally{
    worker.commit();
  }

  //do the re-linking
  for(Map.Entry<Integer,String> e:newLink.entrySet()){
    int keyNodeId=e.getKey();
    String value=e.getValue();
    BDBWorker worker2=new BDBWorker(apname);
    try{
      worker2.unlinkAllNodes(keyDomainId,keyNodeId,freeDomainId);
      int newNodeId=worker2.addNode(freeDomainId,value);
      worker2.linkNode(keyDomainId,keyNodeId,freeDomainId,newNodeId);
    }
    finally{
      worker2.commit();
    }
  }



      out.write("DONE!\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
