/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2022-11-10 01:41:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sims.dev;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ragic.s3.nui.User;
import org.json.JSONObject;
import com.ragic.s3.util.SystemData;
import com.ragic.s3.service.schedule2.RagicAccountJobs;
import java.util.Map;
import java.util.List;
import java.util.ArrayList;
import com.ragic.s3.nui.helper.*;
import com.ragic.s3.nui.RagicConfig;
import java.io.File;
import java.util.Date;

public final class moveap_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.ragic.s3.nui.helper");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("org.json.JSONObject");
    _jspx_imports_classes.add("com.ragic.s3.service.schedule2.RagicAccountJobs");
    _jspx_imports_classes.add("com.ragic.s3.nui.RagicConfig");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("com.ragic.s3.nui.User");
    _jspx_imports_classes.add("com.ragic.s3.util.SystemData");
    _jspx_imports_classes.add("java.io.File");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;



  final String apname=request.getParameter("a");
  final String targetServer=request.getParameter("to");
  User access=(User)session.getAttribute("USER");
  if(access==null || (!UserManager.ifRagicAdmin(access.getUserId()))) {
    if(access!=null) out.println("No access for "+access.getUserId());
    else out.println("Not Logged In.");
    return;
  }
  if(apname==null || targetServer==null) {
    out.println("invalid request");
    return;
  }

  if(!Util.apnameExistsLocally(apname)) {
    out.println(apname+" not on this server");
    return;
  }

  //check if started
  String moveStatus =SystemData.getInstance().getProperty("MOVEAP_" + apname);
  boolean ifStarted= moveStatus !=null;
  if(!ifStarted){
    //mark progress
    SystemData.getInstance().setProperty("MOVEAP_" + apname, "backing up");
    //do the migration in a thread
    new Thread(
            new Runnable(){
              public void run(){
                //make a snap shot of the ap
                BackupDB.s3BackupManual(apname, "snapshot");

                //mark progress
                SystemData.getInstance().setProperty("MOVEAP_" + apname, "restoring");


                String fromServerName = RagicConfig.getInstance().getProperty("SERVER_NAME");
                //restore the ap in target ap
                URLCaller.get("https://"+targetServer+"/sims/dev/_moveap.jsp?a="+apname + "&fromServer=" + fromServerName);

                //mark the redirection
                if(RemoteAccountManager.ifProcessLocally()) {
                  RedirectManager.getInstance().setServerIfNeeded(apname,targetServer);
                  RedirectManager.getInstance().saveChanges();
                } else {
                  URLCaller.get("https://www.ragic.com/api/internal/main_setServer.jsp?a=" + apname + "&targetServer="
                  + targetServer);
                }

                //remove local jobs
                RagicAccountJobs.getInstance().removeAllJobs(apname);

                //rename local folders
                String timestamp=Encoder.formatDate(new Date(),"yyyyMMddHHmmss");
                File dir=new File("cust/data/"+apname);
                dir.renameTo(new File("cust/data/_moved_"+apname+"_"+timestamp));
                dir=new File("cust/def/app/"+apname);
                dir.renameTo(new File("cust/def/app/_moved_"+apname+"_"+timestamp));

                Util.apnameNowNotExist(apname);

              }

            }
    ).start();
  }
  else{//already started
    //check current status, if restoring, status will need to be updated from target ap
    if("restoring".equals(moveStatus)){
      //check status
      JSONObject result=URLCaller.get("https://"+targetServer+"/sims/dev/_moveap.jsp?a="+apname);
      if(result!=null && "done".equals(result.optString("status"))){
        SystemData.getInstance().setProperty("MOVEAP_"+apname,"done");
      }
    }
  }

      out.write("Migration for <b>");
      out.print(apname);
      out.write("</b> to server <b>");
      out.print(targetServer);
      out.write("</b> is <b>");
      out.print(moveStatus==null?"initializing":moveStatus);
      out.write("</b>.\r\n\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
