/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2022-11-10 01:41:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sims.dev;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ragic.s3.util.SIMSMultipartRequest;
import java.util.Collection;
import com.ragic.s3.util.UploadedFile;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import com.ragic.s3.nui.RagicBundle;
import com.ragic.s3.nui.helper.Encoder;
import com.ragic.s3.nui.helper.UserManager;
import com.ragic.s3.nui.User;

public final class test2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ragic.s3.nui.RagicBundle");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.util.Collection");
    _jspx_imports_classes.add("com.ragic.s3.util.UploadedFile");
    _jspx_imports_classes.add("com.ragic.s3.util.SIMSMultipartRequest");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.Encoder");
    _jspx_imports_classes.add("com.ragic.s3.nui.User");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.UserManager");
    _jspx_imports_classes.add("java.io.File");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;



  User access=(User)session.getAttribute("USER");
  if(access==null || (!UserManager.ifRagicSupport(access.getUserId()))) {
    if(access!=null) out.println("No access for "+access.getUserId());
    else out.println("Not Logged In.");
    return;
  }

  RagicBundle bundle=(RagicBundle) session.getAttribute("RAGIC_BUNDLE");
  String path=request.getParameter("p");
  if(path==null) path=".";


  //get uploaded file
  try{
    SIMSMultipartRequest mreq=new SIMSMultipartRequest(request, path, Integer.MAX_VALUE ,"UTF-8");
    Collection files=mreq.getFile("backup");
    final String[] value=new String[files.size()];
    int count=0;
    for (Object file1 : files) {
      UploadedFile file=(UploadedFile) file1;
      if (file==null) continue;
      value[count]=new String(file.getFilesystemName().getBytes("UTF-8"), "ISO-8859-1");
      count++;
    }
    out.println("<script>location.href='?p="+path+"';</script>");
  }
  catch (Exception e){
    e.printStackTrace();
  }


  File dir=new File(path);
  out.println("<table>");
  SimpleDateFormat sdf=new SimpleDateFormat("yyyyMMdd HH:mm");
  for(File f:dir.listFiles()){
    out.println("<tr>");
    if(f.isDirectory()) {
      out.println("<td><a href='?p="+f.getPath()+"'>"+f.getName()+"</a></td>");
      out.println("<td>"+ Encoder.timeAgo(new Date(f.lastModified()),bundle)+"</td>");
    }
    else {
      out.println("<td>"+f.getName()+"</td>");
      out.println("<td><a href=''>"+ Encoder.timeAgo(new Date(f.lastModified()),bundle)+"</a></td>");
    }
    out.println("<td>"+f.length()+"</td>");
    out.println("</tr>");
  }
  out.println("</table>");




      out.write("<form action=\"\" method=\"POST\" enctype=\"multipart/form-data\" style=\"margin:25px 0;\">\r\n  <input type=\"text\" name=\"p\" value=\"");
      out.print(path);
      out.write("\" /><br/>\r\n  <input type=\"file\" name=\"update\" />\r\n  <input type=\"submit\" />\r\n</form>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
