/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2022-11-10 01:41:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sims.dev;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ragic.s3.nui.User;
import com.ragic.s3.nui.helper.UserManager;
import java.util.Map;
import com.ragic.s3.nui.helper.Encoder;
import com.ragic.s3.util.SystemCache;
import com.ragic.s3.util.License;
import com.ragic.s3.nui.RagicConfig;
import java.util.Date;
import com.ragic.s3.nui.RagicBundle;
import com.ragic.s3.util.Util;

public final class threads_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ragic.s3.util.Util");
    _jspx_imports_classes.add("com.ragic.s3.nui.RagicConfig");
    _jspx_imports_classes.add("com.ragic.s3.nui.RagicBundle");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.Encoder");
    _jspx_imports_classes.add("com.ragic.s3.util.License");
    _jspx_imports_classes.add("com.ragic.s3.nui.User");
    _jspx_imports_classes.add("com.ragic.s3.nui.helper.UserManager");
    _jspx_imports_classes.add("com.ragic.s3.util.SystemCache");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n<head>\r\n  <title>Threads - ");
      out.print(RagicConfig.getInstance().getProperty("SERVER_NAME"));
      out.write("</title>\r\n</head>\r\n<body>\r\n");

  //access right check
  User user =(User)session.getAttribute("USER");
  boolean allThreads=request.getParameter("all")!=null;
  boolean allallThreads=request.getParameter("allall")!=null;
  boolean nostack=request.getParameter("nostack")!=null;

  //prod, only allow Ragic support
  if(License.isProd() && (user==null || (!UserManager.ifRagicSupport(user.getUserId())))) {
    if(user!=null) out.println("No access for "+ user.getUserId());
    else out.println("Not Logged In.");
    return;
  }

  //distr, only allow SYSAdmin
  if(License.isDistr() && (user==null || !user.ifApManager("default"))){
    if(user!=null) out.println("No access for "+ user.getUserId());
    else out.println("Not Logged In.");
    return;
  }

  RagicBundle bundle=(RagicBundle)session.getAttribute("RAGIC_BUNDLE");
  Date date=bundle.convertTime(new Date());
  out.println(Encoder.formatAsStandardDate(date,true)+"<br><br>");

  int stop=Encoder.parseInt(request.getParameter("stop"),-1);
  String stopAp=request.getParameter("stopAp");
  if(stop!=-1 && stopAp!=null){
    Map<Thread,StackTraceElement[]> dump=Thread.getAllStackTraces();
    for(Map.Entry<Thread,StackTraceElement[]> e:dump.entrySet()) {
      Thread t = e.getKey();
      if(t.getId()==stop) t.interrupt();
    }
    Util.resetDB(stopAp,user.getUserId(),false);
  }

  String filterThreadName=request.getParameter("filter");
  boolean hasFilter=filterThreadName!=null;

  if(hasFilter){
    Map<Thread,StackTraceElement[]> dump=Thread.getAllStackTraces();
    for(Map.Entry<Thread,StackTraceElement[]> e:dump.entrySet()){
      Thread t=e.getKey();
      StackTraceElement[] sta=e.getValue();
      if(t.getName().contains(filterThreadName) && !t.getName().startsWith("/sims/dev/threads.jsp")){
        out.println("<p>");
        out.println("<b>"+t.getName()+"</b><br/>");
        out.println("<b>STATE:"+t.getState().name()+"</b> ");
        out.println("<a href='/sims/dev/threads.jsp?stop="+t.getId()+"'>Stop</a><br/>");
        for(StackTraceElement st:sta){
          String ststring=st.toString();
          if(ststring.contains("com.ragic") || ststring.contains("org.apache.jsp")) out.println(ststring+"<br/>");
          else out.println("<span style='color:#ccc;'>"+ststring+"</span><br/>");
        }
        out.println("</p>");
      }
    }
    return;
  }

  long stopThreadId = Encoder.parseLong(request.getParameter("stop"),-1);
  if(stopThreadId !=-1){
    SystemCache.getInstance().stopThread(stopThreadId);
    out.println("<script>location.href='/sims/dev/threads.jsp';</script>");
    return;
  }

  Map<Thread,StackTraceElement[]> dump=Thread.getAllStackTraces();
  int count=0,runnableCount=0,blockedCount=0;
  for(Map.Entry<Thread,StackTraceElement[]> e:dump.entrySet()){
    Thread t=e.getKey();
    count++;
    boolean blocked=t.getState().compareTo(Thread.State.BLOCKED)==0;
    boolean runnable=t.getState().compareTo(Thread.State.RUNNABLE)==0;
    if(blocked || runnable || allThreads){//list only threads in state RUNNABLE by default
      if(runnable) runnableCount++;
      if(blocked) blockedCount++;
      StackTraceElement[] sta=e.getValue();

      //analyze stack first
      boolean specialThread=false,ragicThread=false;
      for(StackTraceElement st:sta){
        String ststring=st.toString();
        if(ststring.contains("com.amazonaws.services.s3.AmazonS3Client.uploadPart")){
          out.println("<p><b>Backup Upload Thread</b></p>");
          specialThread=true;
          break;
        }
        if(ststring.contains("com.ragic.s3.nui.helper.BackupDB.s3BackupAll")){
          out.println("<p><b>Backup Create Thread</b></p>");
          specialThread=true;
          break;
        }
//        if(ststring.contains("sun.nio.ch.EPollArrayWrapper.poll")){
//          out.println("<p><b>Jetty Selector Thread</b></p>");
//          specialThread=true;
//          break;
//        }
        if(ststring.contains("org.eclipse.jetty.util.thread.QueuedThreadPool$3.run")){
          //out.println("<p><b>Jetty SSL Selector Thread</b></p>");
          specialThread=true;
          break;
        }
        if(ststring.contains("com.ragic.s3.service.health.HealthChecker.checkServer")){
          out.println("<p><b>Health Check Thread</b></p>");
          specialThread=true;
          break;
        }
//        if("Email / URLCallerAsync / Dropbox".equals(t.getName())){
//          out.println("<p><b>Email / URLCallerAsync / Dropbox</b></p>");
//          specialThread=true;
//          break;
//        }
        if("/sims/dev/threads.jsp".equals(t.getName())){
//          out.println("<p><b>/sims/dev/threads.jsp</b></p>");
          specialThread=true;
          break;
        }
        if("JEEvictor".equals(t.getName())){
          out.println("<p><b>JEEvictor (BDB)</b></p>");
          specialThread=true;
          break;
        }
        if(ststring.contains("com.ragic.s3")){
          ragicThread=true;
          break;
        }
        if(ststring.contains("org.eclipse.jetty.io.ManagedSelector$SelectorProducer.select")){
            specialThread=true;
            break;
        }
        if(ststring.contains("sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)")){
          specialThread=true;
          break;
        }
        if(ststring.contains("sun.misc.Unsafe.park(Native Method)")){
          specialThread=true;
          break;
        }
        if(ststring.contains("sun.nio.fs.LinuxWatchService.poll(Native Method)")){
          specialThread=true;
          runnableCount--;//this runnable does not affect performance
          break;
        }

      }
      if(specialThread && !ragicThread && !allallThreads) continue;

      out.println("<p>");
      out.println("<b>"+t.getName()+"</b><br/>");
      out.println("<b>STATE:"+t.getState().name()+"</b> ");
      out.println("<a href='/sims/dev/threads.jsp?stop="+t.getId()+"'>Stop</a><br/>");
      if(!nostack){
        for(StackTraceElement st:sta){
          String ststring=st.toString();
          if(ststring.contains("com.ragic") || ststring.contains("org.apache.jsp")) out.println(ststring+"<br/>");
          else out.println("<span style='color:#ccc;'>"+ststring+"</span><br/>");
        }
      }
      out.println("</p>");
    }
  }



      out.write("\r\nTotal threads:");
      out.print(count);
      out.write(", runnable:");
      out.print(runnableCount);
      out.write(", blocked:");
      out.print(blockedCount);
      out.write("</body>\r\n</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
