/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2022-11-10 01:41:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.intl.en;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ragic.s3.util.License;
import com.ragic.s3.nui.RagicBundle;
import com.ragic.s3.nui.RagicConfig;

public final class init_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ragic.s3.nui.RagicBundle");
    _jspx_imports_classes.add("com.ragic.s3.nui.RagicConfig");
    _jspx_imports_classes.add("com.ragic.s3.util.License");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


    //if(!RagicConfig.getInstance().ifProperty("NEED_INIT")) return;
    //RagicBundle bundle =new RagicBundle()
    RagicBundle bundle = (RagicBundle) session.getAttribute("RAGIC_BUNDLE");

      out.write("<script>\r\n    \r\n    function checkPwd() {\r\n        let pwdInput = document.getElementById(\"pwd\");\r\n        let rPwdInput = document.getElementById(\"rPwd\");\r\n        if(!pwdInput.value || pwdInput.value !== rPwdInput.value ) {\r\n          let errorMsgDiv = document.getElementById(\"errorMsg\");\r\n          errorMsgDiv.style.display = '';\r\n          errorMsgDiv.textContent = \"");
      out.print(bundle.getString("passwordNotEqual"));
      out.write("\";\r\n          return false;\r\n        }\r\n        return true;\r\n    }\r\n\r\n    \r\n</script>\r\n\r\n\r\n<div  id=\"featureMain\" class=\"clearfix\">\r\n  <form onsubmit=\"return checkPwd();\" action=\"/intl/en/initExec\" method=\"POST\" style=\"padding-top:20px\">\r\n    <div id=\"errorMsg\" style=\"display: none;color: #ff0000;\"></div>\r\n    <table  style=\"width:100%\">\r\n      <tr><td colspan=2 style=\"vertical-align:top;\">\r\n        <h1 style=\"font-size:26px;color:#333333;margin:12px 0 12px 0;font-weight:bold;\">\r\n          ");
      out.print(bundle.getString("ragicCloudDB"));
      out.write("</h1>\r\n      </td></tr>\r\n\r\n      ");

        if("qnap".equals(License.getLicensee())){
      
      out.write("<tr><td colspan=2 style=\"font-size:14px;color:#333;\">\r\n        ");
      out.print(bundle.getString("QNAPFreeVersion"));
      out.write("</td></tr>\r\n      ");

        }
      
      out.write("<tr style=\"height: 90px\"></tr>\r\n\r\n  <tr class=\"subTitleLine\"><td ><span style=\"font-size: 20px;font-weight:700 \">");
      out.print(bundle.getString("Admin_Config"));
      out.write("</span></td></tr>\r\n\r\n        <tr class=\"blank1Line\"></tr>\r\n\r\n      <tr class=\"inputLine\"><td class=\"inputText\" ><span class=\"initLable\">");
      out.print(bundle.getString("setAdmin"));
      out.write("</span></td>\r\n        <td><input type=\"text\" id=\"e\" name=\"e\" title=\"");
      out.print(bundle.getString("setAdmin"));
      out.write("\" value=\"\" size=\"50\"/>\r\n        </td></tr>\r\n\r\n      <tr class=\"inputLine\"><td class=\"inputText\"><span class=\"initLable\">");
      out.print(bundle.getString("setPassword"));
      out.write("</span></td>\r\n        <td><input type=\"password\" id=\"pwd\" name=\"p\" title=\"");
      out.print(bundle.getString("setPassword"));
      out.write("\" size=\"20\"/>\r\n        </td></tr>\r\n\r\n      <tr class=\"inputLine\"><td class=\"inputText\"><span class=\"initLable\">");
      out.print(bundle.getString("confirmPasswordn"));
      out.write("</span></td>\r\n        <td><input type=\"password\" id=\"rPwd\" name=\"rp\" title=\"");
      out.print(bundle.getString("confirmPasswordn"));
      out.write("\" size=\"20\"/>\r\n        </td></tr>\r\n\r\n        <tr class=\"blank2Line\"></tr>\r\n\r\n  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../en/SMTPConfig.jsp", out, false);
      out.write("<tr>\r\n            <td style=\" text-align: center; vertical-align: middle;\" colspan=\"2\"><input type=\"submit\" title=\"");
      out.print(bundle.getString("save_config"));
      out.write("\" value=\"");
      out.print(bundle.getString("save_config"));
      out.write("\" /></td>\r\n        </tr>\r\n\r\n\r\n        <tr class=\"blankLine\"></tr>\r\n\r\n    </table>\r\n\r\n</form>\r\n</div>\r\n<style>\r\n.initLable{\r\n    margin:0 30px 0 0;\r\n    font-size:15px;\r\n    font-weight:550;\r\n    color:#333;\r\n}\r\n.blankLine{\r\n    height: 40px;\r\n}\r\n.blank1Line{\r\n    height: 15px;\r\n}\r\n.blank2Line{\r\n    height: 30px;\r\n}\r\n.defaultCheckbox{\r\n    vertical-align:middle;\r\n    width: 15px;\r\n    height: 15px;\r\n    margin: 0 2px 0 20px;\r\n}\r\n.defaultLabel{\r\n    vertical-align:middle;\r\n    font-size: 15px;\r\n}\r\n.subTitleLine{\r\n   margin-bottom: 4rem;\r\n    padding-bottom: 1rem;\r\n    border-bottom: 1px solid #d0d0d0;\r\n}\r\n.inputLine{\r\n    height: 60px\r\n}\r\n.inputText{\r\n    text-align: right;\r\n    width: 40%;\r\n}\r\n\r\n</style>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
